### PR TITLE
Try parallel tests

### PR DESCRIPTION
**Pull request by koppor**
This PR applies https://docs.gradle.org/8.1/userguide/performance.html#execute_tests_in_parallel to our project.

NOT using the JUNIT parallelism (where we failed a few months ago), but trying gradle :)

More background: https://aahlenst.dev/blog/comparing-parallel-test-execution-in-junit5-gradle-maven/

```[tasklist]
### Compulsory checks
- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.
```

### CODE REVIEW

**Comment by koppor** [comment]
Other PR (https://github.com/JabRef/jabref/pull/9703) without parallel:

image

Thus, parallelism doesn't bring anything. Don't know why. Let's investigate if we have more time for this.

**Comment by koppor** [comment]
image

**Comment by koppor** [comment]
image

**Comment by koppor** [comment]
No speed gain on GitHub, but locally huge performance improvement

**Review by Siedlerchr — APPROVED** [review]

**Pull request merged**
