### PR TITLE
Fixed add group button changing color after adding 10 groups

### LINKED ISSUE #8051: UI: Dark theme: "Add group" button seems inactivated
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

JabRef 5.4--2021-09-01--69550d3 Linux 4.19.0-17-amd64 amd64  Java 16.0.2  JavaFX 16+8

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behavior

In dark theme:

- At the bottom of the group interface, the button `Add group` is, at first, very visible (too much I would say):
ksnip_20210902-093301

- Then (after some time, or after creating a subgroup?), the appearance of this button is modified, and it looks like it is inactivated (black characters on grey background):
ksnip_20210902-093559

I would expect the `Add group` button to look like the `Search` button.

### Appendix

...
<details>
<summary>Log File</summary>
```
Paste an excerpt of your log file here
```
</details>

### PR DESCRIPTION
**Pull request by dimitrisdimos00**
Moreover changed the text color from white to background color. Changed the method setNewGroupButtonStyle of class GroupTreeView. Also changed the GroupTree.css file. Deleted the inactive pseudoclass as it will not be used.

fixes #8051

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

In these pictures we see the new button not changing after having 10+ groups:

new group button 2
new group button

### CODE REVIEW

**Comment by dimitrisdimos00** [comment]
I made some commits. Please check if the color of the button is better now. Thanks!

**Comment by mlep** [comment]
Thank you @dimitrisdimos00 for tackling this issue.
I do not have the tools at hand to build JabRef, so, I cannot check directly :disappointed: .
Maybe another developer can check on this, or maybe you can provide the screenshots, as you did before?
Cheers.

**Comment by dimitrisdimos00** [comment]
Here:
Στιγμιότυπο οθόνης 2022-01-06 124222
Στιγμιότυπο οθόνης 2022-01-06 124355

**Comment by mlep** [comment]
@dimitrisdimos00 This looks great!
Thank you for making JabRef a better software!

**Comment by dimitrisdimos00** [comment]
@mlep Your welcome! Glad to help!

**Comment by ThiloteE** [comment]
In my opinion, in light mode, the darkish blue colour (or at least some kind of different colour) is needed as a contrast to `web search`, which is right underneath. This might not be a problem, if #8398 is implemented.

**Comment by calixtus** [comment]
I don't really know how to proceed with this PR.
We had some discussion a while ago about this feature (https://github.com/JabRef/jabref/issues/8051#issuecomment-1006030482) and decided to include it. Removing this feature should not happen without a proper discussion. Ill put this on for next dev call.
Maybe you could write down some pros and cons here.

We also probably could use something like our ADRs we have for decisions about code architecture but for our UI design decisions?

**Comment by Siedlerchr** [comment]
I never really got the idea of those after 10 groups it's showing in a different color

**Comment by dimitrisdimos00** [comment]
Well personally I find it kind of strange as a functionality. If we want the user to learn this button maybe we could do it through a tutorial rather than this.

**Comment by tobiasdiez** [comment]
I remember I got the idea from feedly (In http://blog.feedly.com/wp-content/uploads/2017/10/discover.gif the "Add content" button has a green background until you added a few sources). Given that their interface is quite usable, I trusted that they have competent ui experts and did their research whether this feature is helpful or not (we sadly don't have the resources for a proper A/B testing etc). But I do agree that it's not very standard behavior to change the background color like this.

**Comment by dimitrisdimos00** [comment]
I guess it's not such a bad feature. If we keep it though it would be better to change it to a different, more visible and more matching color than before...

**Comment by koppor** [comment]
DIN 66234, Teil 8: "Erwartungskonformität". - I would translate it to "expectation conformance" - An application should behave as expected by the user. The difficult thing is to guess the expectations. Since this is the only place in JabRef with that functionality - and that functionality does not seem to be common.

However, if this functionality is used consistently within JabRef, it is maybe cool. Maybe, this is also a call for an "basic" and "advanced" mode of JabRef. #futurework

Thus, we remove this functionality for now.

**Review by koppor — APPROVED** [review]

**Pull request merged**
