### PR TITLE
[WIP] Fix for issue #7771: Lighten Jabref Icon 32

### PR DESCRIPTION
**Pull request by gdrosos**
I lightened the color of the Jabref icon 32 image (40% lighrer ) in order to make  it more visible in the Windows  Taskbar and address the #7771 issue.
Now, the icon from this color:
JabRef-icon-32 Screenshot_427Screenshot_428
results in this more visible one:
JabRef-icon-32 Screenshot_420 Screenshot_419 Screenshot_421

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by Siedlerchr** [comment]
Thanks for the work! Looks better now. I also attached the original svg logo file, so we don't loose any quality
[without-bg.svg.zip](https://github.com/JabRef/jabref/files/6661505/without-bg.svg.zip)

**Comment by gdrosos** [comment]
> Thanks for the work! Looks better now. I also attached the original svg logo file, so we don't loose any quality
> [without-bg.svg.zip](https://github.com/JabRef/jabref/files/6661505/without-bg.svg.zip)

Thank you, should I change all the Jabref Icons accordingly or the change of the Icon 32 is enough? Also, the lightened original PNG looks like this (on png format): 
image (1)

**Comment by tobiasdiez** [comment]
I think for consistency we should then use the new icon everywhere, and change the primary color as well. This amounts more or less to a slight rebranding. 

I'm absolutely in favor of choosing a better primary color, i.e. a slightly different purple. The current purple is too dark to be displayed on a dark background (which was motivating concern for this PR) and at the same time is too bland to stand out, especially when used as a font color:
image
Compare this to say using `#0071BC` (VS Code brand color for font highlights):
image

My proposal would be to generate two lighter versions of the current purple (or a slightly more vibrant version thereof). The darkest one can be used as background for buttons (for buttons), the middle one (maybe a bit more grayish) as font and icon color, and the lightest one as font color on black. There shouldn't be however too much variation in the color. 
That's also roughly how VS Code is doing this:
image

Speaking of VS Code, they also moved from a one-colored icon to one with slightly different colors because this enhances contrast, see discussion here https://github.com/microsoft/vscode/issues/71827. Maybe we can do something similar as well, with one side of the book in a slightly different color.

Tagging @JabRef/developers and especially our branding master @stefan-kolb. That's probably something we should discuss on the next devcall.

**Comment by Siedlerchr** [comment]
I like the idea of adjusting the program icons, but I would not change the logo color on our flyers etc

**Comment by koppor** [comment]
Summary of vscode: single color to multiple colors in the colors: . They have multiple colors on their homepage.

We want to be consistent in our color scheme (UI colors, flyer, homepage, ...). Thus, we cannot just change the color of the icon. Brandig discussions are hard things to do.

We need to talk to our design consultants. We will come back to this issue when having more insights.

Nevertheless, thank you for bringing up that issue and thinking of a quick and easy solution.

**Comment by stefan-kolb** [comment]
Quite a big change. I'm not against it, but if we move forward here, we should adjust everything consistently. It's probably not easy to find the "right" color here. For dark backgrounds we should have an inverted (white) logo anyway I guess. There's probably no color that works well on light and dark colors or at least this color might not be our favorite one...

**Comment by tobiasdiez** [comment]
@stefan-kolb Do you remember which color you used for the flyers?

**Comment by stefan-kolb** [comment]
`#4f5f8f`. Also see the flyer PDF inside the admin repo.

**Comment by koppor** [comment]
Thank you for the discussions here. We did not find a designer really thinking of the issue. We are going to discuss this on JabCon this year. We will reopen the PR (or open a new one) in case we make progress.

**Comment by Siedlerchr** [comment]
DevCal decision: We just make the color a bit lighter, even if it does not fit with the overall color scheme.
 This benefits also mac users with a dark theme

**Pull request closed without merging**
