### PR TITLE
Fix NPE when executing CrawlerTest

### PR DESCRIPTION
**Pull request by koppor**
```[tasklist]
### Compulsory checks
- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.
```

### CODE REVIEW

**Comment by Siedlerchr** [comment]
But fetcher test did not execute?

**Comment by calixtus** [comment]
I mentioned this in other prs too. Sometimes they are run, sometimes not. I thought always this is some black gradle magic to know, when fetcher tests are affected by the code changes. Is the crawler test marked as a fetchertest in the code?

**Review by calixtus — APPROVED** [review]

**Comment by koppor** [comment]
Fetcher test execution is specified in https://github.com/JabRef/jabref/blob/main/.github/workflows/tests-fetchers.yml. The condition at https://github.com/JabRef/jabref/blob/f1664552b235479bc368c8af0cff8c21238224f0/.github/workflows/tests-fetchers.yml#L8 needs to be updated to include the crawler, too.

Marked as fetcher test: https://github.com/JabRef/jabref/blob/f1664552b235479bc368c8af0cff8c21238224f0/src/test/java/org/jabref/logic/crawler/CrawlerTest.java#L37

**Comment by koppor** [comment]
Manually triggered execution for the commit - checkmark is green: https://github.com/JabRef/jabref/actions/runs/4988652064

**Review by Siedlerchr — APPROVED** [review]

**Pull request merged**
