### PR TITLE
Reusable method create to get last focused tab preferences

### PR DESCRIPTION
**Pull request by Shehanka**
----

- [x] Change in CHANGELOG.md described
- [x] Tests created for changes
- [x] Manually tested changed features in running JabRef
- [ ] Screenshots added in PR description (for bigger UI changes)
- [x] Ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)
- [x] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)

### CODE REVIEW

**Comment by Shehanka** [comment]
@tobiasdiez

**Comment by tobiasdiez** [comment]
What are the changes in this PR? Except the refactoring of the `getWriter` method (which was already merged), I don't see any significant changes.

Please also refrain from purely refactoring PRs. If you notice a small problem that can be simply fixed, then it is of course ok to propose such a PR (as e.g. your last one). In general, we strive however to improve the quality of the code while solving some "real-world" problems but not for the sake of improving the code quality.

**Comment by Shehanka** [comment]
I have changed package access level of LastFocusedTabPreferencesTest and optimized some methods

**Comment by matthiasgeiger** [comment]
Yes. However, this is not a functional improvement of actual application code but just minor adjustments (marked by intelliJ as warning?!) In an unit test.

So please try to work on topics marked with the 'good-first-issue' label to actually contribute to JabRef. Thank you!

**Pull request closed without merging**
