### PR TITLE
Create chocolatey package for dev version

### LINKED ISSUE #5031: Make development version/snapshots available in choco community repository
There should be a package for development/beta builds at chocolatey community repository

### PR DESCRIPTION
**Pull request by tobiasdiez**
Fixes #5031.

Things to do:

- [ ] Check that the correct version of JabRef gets uninstalled (if both the stable and the dev version are installed) -> specify unique software name in nuspec
- [ ] Create github action
- [ ] Calculate and add checksum as part of the github action
- [ ] Replace version in jabref-dev.nuspec
- [ ] Specify correct packageSourceUrl

https://chocolatey.org/docs/create-packages

### CODE REVIEW

**Comment by koppor** [comment]
Refs https://github.com/JabRef/jabref/issues/5399

**Comment by koppor** [comment]
We are working at https://github.com/OlafHaag/chocolatey-packages/issues/6#issuecomment-608111851 to get this done. Thus, this PR is obsolete.

**Comment by tobiasdiez** [comment]
Don't you think it is easier if we publish the dev build with the help of a github action as we have the complete build information using gitversion which is not available from https://builds.jabref.org/master/ ?

**Comment by tobiasdiez** [comment]
Reopen based on https://github.com/OlafHaag/chocolatey-packages/issues/6#issuecomment-609831278

**Comment by koppor** [comment]
Note that our stable versions are available in winpkg: https://github.com/microsoft/winget-pkgs/pull/505

**Comment by koppor** [comment]
@koppor: See also https://github.com/tunisiano187/Chocolatey-packages/tree/master/automatic/freeplane

**Pull request closed without merging**
