### PR TITLE
[WIP] Use snapshot version of testfx-core 4.0.x

### PR DESCRIPTION
**Pull request by koppor**
This reverts commit 012d9b056b25b79edddbdcefb27a5c0dd70d3480.

According to https://github.com/TestFX/TestFX/issues/682#issuecomment-531458652, Java 11 compilation issues with TestFX should be solved

### CODE REVIEW

**Comment by koppor** [comment]
Now, we have

```
/home/travis/build/JabRef/jabref/src/test/java/org/jabref/gui/entryeditor/SourceTabTest.java:69: error: cannot access Matcher

        robot.clickOn(1200, 500);
             ^
  class file for org.hamcrest.Matcher not found
```

**Comment by koppor** [comment]
When I include hamcrast "modern" (`testCompile 'org.hamcrest:hamcrest:2.1'`), I get

    module java.xml.bind reads package org.hamcrest from both org.hamcrest and hamcrest.core

With the depcreated hamcrest dependencies (`testCompile 'org.hamcrest:hamcrest-all:1.3'), I get:

    module java.xml.bind reads package org.hamcrest from both hamcrest.core and hamcrest.all

**Comment by Siedlerchr** [comment]
There is a release candidate of hamcarest 2.2 which should fix it:
https://github.com/hamcrest/JavaHamcrest/releases/tag/v2.2-rc1

**Comment by koppor** [comment]
Did you test it? I remember testing it also with the -rc1 and had the same
bad results. - It would be good if you tested it, too.


Am Mo., 7. Okt. 2019 um 07:57 Uhr schrieb Christoph <
notifications@github.com>:

**Comment by Siedlerchr** [comment]
Nope, still does not work. I guess it's because the alpha does not yet contain the recent changes in the module system https://github.com/TestFX/TestFX/commit/08c26976c524e6d29b806da7a1d0d591bd540ad8

**Comment by koppor** [comment]
With the +, it should use the snapshot version. Doesn't it?

Christoph <notifications@github.com> schrieb am Mo., 7. Okt. 2019, 18:14:

**Comment by tobiasdiez** [comment]
Let's wait until hamcrest and testfx release proper stable versions until we upgrade. It was necessary at some point to use snapshots when upgrading to java 11 but we should go back to our old convention of using stable releases where possible. Added to https://github.com/JabRef/jabref/issues/5226

**Pull request closed without merging**
