### PR TITLE
[WIP] Remove @Ignore labels from JabRef test cases

### PR DESCRIPTION
**Pull request by mairdl**
Some test cases that are marked with `@Ignore` work just fine, this PR removes those labels. Other test cases are ignored because they try to access JabRef UI elements, which aren't initialized the right way.
- [ ] Test cases work on Travis
- [ ] internal qs

### CODE REVIEW

**Comment by Siedlerchr** [comment]
Good work!  Ready for merge? It looks like all tests are passing on travis

**Comment by mairdl** [comment]
At the moment I am not 100% sure if the changes of b994030 are right.

**Comment by Siedlerchr** [comment]
@mairdl  What does the documentation/help say? 
All layout related stuff is documented here: https://help.jabref.org/en/CustomExports

**Comment by mairdl** [comment]
@Siedlerchr thanks that cleared it up.

**Comment by mairdl** [comment]
Regarding the DialogTest: I tried out several thingst to make the DialogTest work, but nothing seems to make it work. As a solution I could split the 2 cases in a diffrent class.

**Comment by Siedlerchr** [comment]
If the split works locally and on travis, it's okay.

**Comment by mairdl** [comment]
Ok the split work 👍

**Comment by Siedlerchr** [comment]
Good work! Seems to work on travis, so I will merge it in for now.

**Comment by koppor** [comment]
...and now Travis fails...

**Comment by Siedlerchr** [comment]
Before I merged it in, travis was green

**Comment by Siedlerchr** [comment]
Is not related to this one is the Springer Link test which fails

net.sf.jabref.logic.importer.fetcher.SpringerLinkTest > findByDOI FAILED

java.lang.AssertionError: expected:<Optional[
http://link.springer.com/content/pdf/10.1186/s13677-015-0042-8.pdf]> but
was:<Optional.empty>

at org.junit.Assert.fail(Assert.java:88)

at org.junit.Assert.failNotEquals(Assert.java:834)

at org.junit.Assert.assertEquals(Assert.java:118)

at org.junit.Assert.assertEquals(Assert.java:144)

at
net.sf.jabref.logic.importer.fetcher.SpringerLinkTest.findByDOI(SpringerLinkTest.java:41)




2016-09-27 14:42 GMT+02:00 Oliver Kopp <notifications@github.com>:

**Pull request merged**
