### PR TITLE
Move L&F configuration from advanced to appearance tab in preferences

### PR DESCRIPTION
**Pull request by stefan-kolb**
- [ ] Why don't we display LAF selection on OSX?

__Appearance__

image

__Advanced__

image

### CODE REVIEW

**Comment by simonharrer** [comment]
@chochreiner any idea why the L&F selection is hidden on Mac OS X?

**Comment by simonharrer** [comment]
LGTM :+1:

**Comment by chochreiner** [comment]
I've only had a quick look at it, but i guess it is because only the default L&F shows the the OSX specific first dropdownmenu

at a first glance, there is no reason why this menu should be disabled - apart from the fact that IMHO only the default L&F looks good

**Comment by stefan-kolb** [comment]
Seems reasonable to me :+1: So we keep it this way.

**Pull request merged**
