### PR TITLE
[WIP] Enable PDF fulltext search

### PR DESCRIPTION
**Pull request by koppor**
This PR enables a fulltext search of all linked PDFs.

It is an initial implementation skeleton, where work can be started from.

### CODE REVIEW

**Comment by Braunch** [comment]
Some TODOs I thought about:
- [ ] include index initialization in JabRef
  - [ ] evaluate when to create/update index
  - [ ] evaluate if update method needs to be written (that doesn't create the whole index from scratch)
- [ ] sort search results
- [ ] use pdf importer from #1883 
- [ ] validate the extracted fields in the search result
- [ ] include in UI
- [ ] Qs stuff, unit/integration tests

**Comment by koppor** [comment]
There is no person working on it. 
We are currently trying to focus on other things. :fire:
We will come back later to this topic, therefore closing adding [on-hold label](https://github.com/JabRef/jabref/issues?utf8=%E2%9C%93&q=label%3Aon-hold+) and closing the issue for now.

**Comment by tobiasdiez** [comment]
Some links that are maybe helpful:
- We want: Extended/fulltext search: index pdfs, reviews ect. (related issue: https://github.com/JabRef/jabref/issues/2263)
- Lucene project: https://github.com/schoenm1/lucene
- http://tockit.sourceforge.net/docco/screenshots.html
- Lucene + pdfbox http://www.programming-free.com/2012/11/simple-word-search-in-pdf-files-using.html 
- real-live example using javafx http://blog.mirkosertic.de/javastuff/fxdesktopsearch
- Extract references from pdf: https://initiative.eudml.org/EuDmlAnalysisDemo/ or https://github.com/CrossRef/pdfextract

**Comment by koppor** [comment]
superseded by https://github.com/JabRef/jabref/pull/2838

**Pull request closed without merging**
