### PR TITLE
Multiple messages in the SnackBar

### LINKED ISSUE #7340: Multiple messages in the SnackBar
If JabRef has do display several messages very shortly after each other, the messages are stacked and played one after each other. This is confusing, since the SnackBar is still displaying a message, which is already obsolete. E.g. if you cycle quickly through the preview styles.

A simple solution would be to stack the messages inside an already showing SnackBar, separated by a new line and to lengthen the display time of the SnackBar for the time only the last message should show.

### PR DESCRIPTION
**Pull request by EduRibeiro00**
Previously, the SnackBar component could only display one message at a time, and messages that were created quickly were displayed in sequence and became obsolete because there was a more recent message waiting to be displayed.
The changes made allow for the SnackBar to display multiple messages in the same component, each in a different line.

Image

Changes that are still to be made in this PR:
- [ ] Increase/Reset SnackBar timeout when a new message is added
- [x] Add a maximum limit for the number of messages displayed at the same time in the SnackBar
- [ ] Gradually remove old messages from the SnackBar as they timeout

Fixes #7340.

---

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by EduRibeiro00** [comment]
I'm having difficulties in finding a way to increase or reset the toast display timeout, so the new messages added to the SnackBar can be displayed the right amount of time. There seems to be no way of modifying the timeout of an already displaying event... I've tried closing the SnackBar and firing another event with the new messages, but that leads to weird closing and opening animations.

**Comment by tobiasdiez** [comment]
A quick and dirty way would be to resubmit the previous event before submitting the combined event. According to
https://github.com/sshahine/JFoenix/blob/2dbb8515da236140c41eabe22eb549b458f1e867/jfoenix/src/main/java/com/jfoenix/controls/JFXSnackbar.java#L312-L317
this should reset the timer. Another approach would be to use reflection to get the `pauseTransition` and call `playFromStart` on it.

**Comment by Siedlerchr** [comment]
What's the status here? Would be nice if you could continue working on this!

**Comment by EduRibeiro00** [comment]
> What's the status here? Would be nice if you could continue working on this!

Sorry for being inactive! I have been a little busy but I will be able to continue this issue in a few days.

**Comment by koppor** [comment]
@EduRibeiro00 I found this PR while cleaning up the mass of opened tabs in my Firefox. May I ask whether you could find some time these days? We are having [JabCon](https://jabcon.jabref.org/) and could provide fast feedback.

**Comment by EduRibeiro00** [comment]
> @EduRibeiro00 I found this PR while cleaning up the mass of opened tabs in my Firefox. May I ask whether you could find some time these days? We are having [JabCon](https://jabcon.jabref.org/) and could provide fast feedback.

Hello. In the next week or so I will have some time to contribute 👍

**Comment by koppor** [comment]
Closing this issue due to inactivity :zzz: 

Please ping us if you intend to resume work on this one.

**Pull request closed without merging**
