### PR TITLE
[WIP] RISImporterTest

### PR DESCRIPTION
**Pull request by obraliar**

### CODE REVIEW

**Comment by koppor** [comment]
[Not fully covered](https://codecov.io/github/JabRef/jabref/src/main/java/net/sf/jabref/importer/fileformat/RisImporter.java?ref=b89d758f48d1e461ded1dcea997b1d08f71b428b). Is it possible to get this for line 95, too?

RIS is a very widely used import format. The tests should be really good here.

@obraliar and @mairdl Could you please check https://github.com/JabRef/jabref/issues/296

Could you also check https://github.com/JabRef/jabref/issues/399#issuecomment-160138158 and check whether Mendeley exports the `file` field somehow in the RIS format? Please answer at #399. If Mendeley does export the field, at a test case for it!

**Comment by koppor** [comment]
@obraliar This test fails, please fix. Please also work together with @zellerdev @mairdl and @ayanai1 to answer https://github.com/JabRef/jabref/pull/310#issuecomment-168193536

**Comment by obraliar** [comment]
This test fails due to the bug (see https://github.com/JabRef/jabref/issues/296). So it shouldn't be up on the test method.

**Comment by tobiasdiez** [comment]
@obraliar Could you try to fix the bug? You are probably the only person since ages which looked at the RIS importer code. So you are the perfect candidate to fix this bug :)

It is usually a good idea to write a test replicating a bug (which you have already done). Then fix the bug. Here the test verifies that the bug is indeed fixed. Finally, leave the test as a regression test to prevent that the same bug is reintroduced later.

**Comment by koppor** [comment]
Could you please add a test for the RIS given at http://bibtexml.sourceforge.net/examples.html#ris, too? You can reuse the `bib` files @zellerdev will use from there for #511.

**Comment by koppor** [comment]
@obraliar Please also address http://tex.stackexchange.com/questions/288511/failing-to-import-into-jabref-3-0 and resolve the conflicts.

**Comment by lenhard** [comment]
@obraliar Please build and integrate a test case for the RIS file available in #742

**Comment by koppor** [comment]
New pull request at #817

**Pull request closed without merging**
