### PR TITLE
Added Hayagriva YAML export

### LINKED ISSUE #10382: Typst-flavored (Hayagriva) YAML export
The Typst typesetting system has it's own YAML format, described here:
https://github.com/typst/hayagriva/blob/main/docs/file-format.md
Note that this is _not_ the same as CSL YAML (which Jabref can target already)

It would be useful if Jabref could export to this format.

### PR DESCRIPTION
**Pull request by JawadTUE**
Fixes #10382 

I added Hayagrive YAML export based on their  [documentation](https://github.com/typst/hayagriva/blob/main/docs/file-format.md). 

The following fields are not included, because I did not find a relevant field for them in Jabref: parent, affiliated, issue, volume-total, page-total, time-range, runtime, serial-number, language, archive, archive-location.

`HayagrivaType.java` contains the mapping from Jabref type to Hayagriva Entry Type.

I confirmed that the exported `.yaml` file works with the typst system by using `hayagriva literature.yml reference` as stated in their [documentation](https://github.com/typst/hayagriva/tree/main).

screenshot

### Mandatory checks
- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [x] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by Siedlerchr** [comment]
I think this looks already good. However, I think it's not necessary to have the own author formatter as they say they can be specified either in square brackets or in verbose mode with multiple authors under each other:
 
https://github.com/JabRef/jabref/blob/3f53201dea6640bd2b0f903a257b8f772ba206a8/src/main/resources/resource/layout/yaml.layout#L3-L6 
could be reused here as well? (except the "literal")

**Comment by Siedlerchr** [comment]
Can you also please add a test for this? See the YamlExporterTest as an example

**Comment by Siedlerchr** [comment]
@JawadTUE  How is the status here? Codewise it looked already good. Just unit tests missing

**Comment by JawadTUE** [comment]
I will finish this by tomorrow.

**Comment by JawadTUE** [comment]
I added the unit tests. These are basically the same as the tests in `YamlExporterTest.java`, with one extra test `exportsCorrectMultipleAuthors` to test that multiple authors are correctly exported.

**Review by Siedlerchr — APPROVED** [review]

**Pull request merged**
