### PR TITLE
Major OpenOffice changes

### PR DESCRIPTION
**Pull request by oscargus**
Assuming that the current state of the OpenOffice/LibreOffice connection is good enough (and that no one will improve it significantly in the near future), this PR removes currently unused code.

The major removed thing (from some perspective) is the .bst-support. However, as far as I can tell, it wasn't finished (and therefore not enabled) and while I really think it is a nice feature, I cannot really imagine someone finishing it.

As a second change, the push-to-application button support is removed and only the side panel can be used (which is much more advanced anyway). There are probably further things that can be removed, such as a few preferences related to push-to-application, but that will require further analysis.

This PR builds on #601, so merging that first is probably the best (and this may require some thinking).

### CODE REVIEW

**Comment by oscargus** [comment]
Also "solves" #534.

**Comment by koppor** [comment]
I need to investigate further. In #110 I identified the bibtex VM (`net.sf.jabref.bst.VM`), which can handle bsts. Seems to be very complete. I am aware that citastionstyles (see #119) is the successor of `bst` files. I am currently unsure, whether citation styles really cover all cases and if users can easily switch.

In the case of biblatex vs. citationstyles, I am pretty sure that biblatex is more powerful. When reading the documentation of [biblatex-apa](https://www.ctan.org/pkg/biblatex-apa), I don't think that a [621 line XML](https://www.zotero.org/styles/apa) can have the same functionality. But you can convince me of the opposite. - I know that this doesn't help in the bst vs. citation styles case though.

**Comment by oscargus** [comment]
The BST engine is intact (and should probably be used more, e.g. in
generating  author formats). It was just the OO connection  (method
insertBST in OpenOfficePanel (?)) that was removed.

**Comment by koppor** [comment]
Could you say a few words about the expected funtionality behind insertBST or is it a mystery? :innocent:

**Comment by oscargus** [comment]
Well, it's got a hard coded .bst file in it:

``` java
wrapper.loadBstFile(new File("/home/usr/share/texmf-tetex/bibtex/bst/ams/amsalpha.bst"));
```

The other indication of incompleteness is `BstWrapper.java` with the following method:

``` java
public Map<String, String> processEntries(Collection<BibEntry> entries, BibDatabase database) {
        // TODO: how to handle uniquefiers?

        // TODO: need handling of crossrefs?
        String result = vm.run(entries);
        return parseResult(result);
    }
```

In addition, IEEEtran.bst introduces lots of additional LaTeX-commands, so the cleaning provided in `parseResult` will not take you that far. While the idea of using .bst is excellent, in this case I think it is still better to define reference style through the other definition files.

(I've been thinking about generating previews using .bst, but cleaning up the .bbl is a mess in the general, or at least the IEEEtran.bst, case and the same thing is bound to happen here. For previews, I think a feasible way is to generate a PNG/PDF and display it, but that won't really be of any use here.)

**Comment by oscargus** [comment]
Also, there's not even commented out menu items etc or any configuration.

An option would also be to keep the .bst-stuff but get rid of the push-to-application-button (and other commented out things, there are three potential buttons which are not used). Will also simplify things a bit.

**Comment by oscargus** [comment]
Seems like the final commit solves #607 if nothing else.

**Comment by koppor** [comment]
Should we open an issue then which reads "Add bst support for OpenOffice" referencing this PR?

Regarding the previews: I assume, you mean the preview panel? I thought, the BibtexVM can be used as is for that?

**Comment by oscargus** [comment]
Yes, I think it makes sense to open an issue.

Yes, the VM can be used, but for some .bst-files (e.g. IEEEtran.bst) there will be quite a bit of non-trivial latex code to parse...

**Pull request merged**
