### PR TITLE
Apply JUnit5BestPractices (and fix some issues manually)

### PR DESCRIPTION
**Pull request by koppor**
Follow-up to https://github.com/JabRef/jabref/pull/10797

99% of the rewrite worked. I just had to manually exclude some files and make some adaptions (copy three test files, make JavaDoc links full links)

Opened upstream issues:

- https://github.com/openrewrite/rewrite-testing-frameworks/issues/458
- https://github.com/openrewrite/rewrite-testing-frameworks/issues/459

Existing upstream issue: https://github.com/openrewrite/rewrite-testing-frameworks/issues/258

### Mandatory checks

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by Siedlerchr** [comment]
> Task :test
org.jabref.gui.mergeentries.ThreeWayMergeCellViewModelTest

  oddEvenLogic(boolean, boolean, boolean, boolean)

    Test initializationError FAILED

    org.junit.platform.commons.PreconditionViolationException: Could not find factory method [oddEvenLogic] in class [org.jabref.gui.mergeentries.ThreeWayMergeCellViewModelTest]


org.jabref.logic.citationkeypattern.CitationKeyGeneratorTest

  authorsAlpha(String, BibEntry, String)

    Test initializationError FAILED

    org.junit.platform.commons.PreconditionViolationException: Could not find factory method [authorsAlpha] in class [org.jabref.logic.citationkeypattern.CitationKeyGeneratorTest]


org.jabref.logic.citationstyle.CitationStyleGeneratorTest

  cslMapping(String, BibDatabaseMode, BibEntry, String)

    Test initializationError FAILED

    org.junit.platform.commons.PreconditionViolationException: Could not find factory method [cslMapping] in class [org.jabref.logic.citationstyle.CitationStyleGeneratorTest]


org.jabref.logic.importer.fileformat.BibtexImporterTest

  parsingOfEncodedFileWithHeader(Charset, String)

    Test initializationError FAILED

    org.junit.platform.commons.PreconditionViolationException: Could not find factory method [parsingOfEncodedFileWithHeader] in class [org.jabref.logic.importer.fileformat.BibtexImporterTest]

**Comment by Siedlerchr** [comment]
As this does not work I would not merge it and close it for the moment to reduce noise

**Comment by koppor** [comment]
Note that I marked it as "draft" :)

**Comment by koppor** [comment]
For reference the reported issues:

- https://github.com/openrewrite/rewrite-testing-frameworks/issues/459
- https://github.com/openrewrite/rewrite-testing-frameworks/issues/458#issuecomment-1892845540
- https://github.com/openrewrite/rewrite-testing-frameworks/issues/258

And an old one:

https://github.com/openrewrite/rewrite-testing-frameworks/issues/404

**Comment by koppor** [comment]
I will focus on "RemoveTestPrefix", because this is already a huge change. I fixed the issues mentioned at https://github.com/JabRef/jabref/pull/10799#issuecomment-1899102088.

**Comment by koppor** [comment]
GitHub does not like my pushes. Thus keeping the PR closed and re-opening a clean PR.

**Pull request closed without merging**
