### PR TITLE
[WIP] Add External Application Selection to Preferences

### PR DESCRIPTION
**Pull request by slyr91**
WIP - Add External Application Selection to Preferences

This pull request is in regards to #674. 
This initial commit adds a button to the settings panel for each external application which allows the user to select an application to make default. There is currently a problem with this build where the application will not update the pushToApplicationButton. I believe the issue has something to do with the interaction between javafx and swing components. Also I plan on adding keybinding options as well in the future, it's just taking me a bit of time to familiarize myself with the program between life events. Let me know what you think so far and on the direction I am taking.

### CODE REVIEW

**Comment by tobiasdiez** [comment]
This looks like a good start. Nice work!

The button is not updated because such an update mechanism is not yet implemented. The icon is generated from an action (which itself is created in `PushToApplicationButton.getMenuAction`). However, the [Action class](https://github.com/JabRef/jabref/blob/maintable-beta/src/main/java/org/jabref/gui/actions/Action.java) only has static return values. I would propose to follow the example of [controlsfx Action](https://controlsfx.bitbucket.io/org/controlsfx/control/action/Action.html) and replace the getters in the action interface by javafx properties. Then you can use bindings in the adapter class [JabRefAction](https://github.com/JabRef/jabref/blob/maintable-beta/src/main/java/org/jabref/gui/actions/JabRefAction.java) and in this way update the UI if the underlying property is changed. 

@slyr91 do you want to implement these changes or prefer if somebody from the team does it? (I would volunteer but it may take some time).

**Comment by slyr91** [comment]
I will definitely give this a solid try. @tobiasdiez I am still learning about the proper procedures on GitHub but if I can implement those changes should I add them to this pull request or to a separate one?

**Comment by tobiasdiez** [comment]
Good question. In general, it is better to create a few smaller PRs because that makes reviewing and understanding the code changes easier. Having said this, in this particular case, I think however that the changes are small and localized enough so that you can simply push them to this PR.

**Comment by stefan-kolb** [comment]
@slyr91 Will you work on this in the future?

**Comment by slyr91** [comment]
@stefan-kolb I definitely will give it a shot soon. I have just been too busy to dive into this. I had finals to deal with and now I am trying to study for a certification so all my free time goes to that. As soon as I am done with that I will be returning to this.

**Comment by slyr91** [comment]
I'm getting back into this now and I noticed that the branch this was originally built on, maintainable-beta, is closed. Which branch should I apply these changes and proposed improvements to?

**Comment by stefan-kolb** [comment]
Hi, on the `master` branch please 😄

**Comment by Siedlerchr** [comment]
You probably have to rework your code a bit as recently the preferences dialog was transformed to javaFX as well.

**Comment by tobiasdiez** [comment]
Surpassed by #5024.

**Pull request closed without merging**
