### PR TITLE
Datepicker fix

### PR DESCRIPTION
**Pull request by matthiasgeiger**
Fix for #2403 - and as I was just touching this stuff again: I replaced our custom `EasyDateFormat` class with a standard `DateTimeFormatter`

- [ ] Change in CHANGELOG.md described
- [ ] Tests created for changes
- ~~[ ] Screenshots added (for bigger UI changes)~~
- [x] Manually tested changed features in running JabRef
- ~~[ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)~~
- ~~[ ] If you changed the localization: Did you run `gradle localizationUpdate`?~~

### CODE REVIEW

**Comment by koppor** [comment]
Documentation at http://help.jabref.org/en/TimeStamp

Does not work with master and v3.8 on my side. v3.7 does not compile any more ("Could not find de.undercouch:citeproc-java:1.0.0-SNAPSHOT"). Does also not work with v3.6. 

The solution is to reset the preferences.

Solution works for me. @matthiasgeiger Thank you for the fix.

**Comment by mlep** [comment]
Does not work for me even after resetting the preferences... (JabRef-3.8.1-dev--snapshot--2016-12-20--master--b655bfd.jar)

**Comment by lenhard** [comment]
@mlep: After resetting the preferences, the timestamp field appears for me and the datepicker works as desired. 

The dev version you mention in your comment is not the most recent one, maybe it did not yet include the fix. Can you try again with JabRef-3.8.1-dev--snapshot--2016-12-20--master--62d55e1.jar

**Comment by mlep** [comment]
Indeed, the calendar is displayed now.
HOWEVER, the `Clear` function does not work as expected: the timestamp field is not cleared. If I click on `Today`, then `Clear` works.

**Comment by lenhard** [comment]
@mlep Indeed! Clear only works if a proper date is already in the field. If you insert something else, such as `abc`, then clear does not work.

@matthiasgeiger Can you please address this? Since this PR is already merged, I guess we need a follow-up PR.

**Comment by mlep** [comment]
Note: for me, it does not clear even if the field content looks good, like:
 ` timestamp     = {2016-10-26},`

**Pull request merged**
