### PR TITLE
Fix drag and drop into empty library

### LINKED ISSUE #6851: Drag & drop of PDF: not on empty library
JabRef 5.2--2020-09-02--5c9edc9
Linux 4.9.0-13-amd64 amd64 
Java 14.0.2

- [X] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

Drag & drop of a PDF file (to create a new entry) does not work if the library file has no entry.

1. Menu File --> New library (the table entry space displays "No content in table")
2. Drag & drop a pdf file in the entry table space.
Nothing happens

### PR DESCRIPTION
**Pull request by tp-1000**
fixes #6851
Drag & Drop into empty library

	Fixes issue preventing files from being "dragged & dropped" into an
	empty library

	Added a drag/drop handlers on the table-view to allow for files
	to be drag & drop into an empty library

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

**Review by tobiasdiez — APPROVED** [review]
Code wise this looks good to me. Thanks! Have you tested that dropping on entries still works and takes precedence over the general table view drop handler (e.g. directly dropping on an entry adds a link to this entry)?

Also you have checkstyle errors, may I ask you to please fix them.

**Comment by tp-1000** [comment]
The short answer, no I cannot drop a file on an entry and get it to add the file to that entry. But it never did. I checked all the the positions top+bottom and center, and only top and bottom add files but only as new entries. I was a little confused as to the intended behavior. I would be happy to investigate further. How is it intended to work?

**Comment by Siedlerchr** [comment]
Dropping a file on an entry depends on the modifier key you pressed (alt, shift or ctrl).
There's a description in the help somehow at the linked files topic

**Comment by tp-1000** [comment]
I'll check it out and give you an update

**Comment by tp-1000** [comment]
So I'm guessing my issue is a Mac OS transfer mode key thing or possibly a system security setting, but I'm unable to get "move" to trigger and "copy" does nothing. Only "link" adds a file to the entry (control + drag). To answer your original question the entries still take precedence, and work exactly the way they did without my fix.

With my fix:
Drag and drop on an entry does not create a new entry. It works exactly as it did before.


Let me know if you want me to investigate more, or require further changes.

**Review by tobiasdiez — APPROVED** [review]
Ok, thanks for testing!

@Siedlerchr didn't we fix these drag & drop issues on Mac as well?

**Comment by Siedlerchr** [comment]
@tp-1000  On mac you need to use the option key.
However, I can only get modus copy to work. 
https://developer.apple.com/documentation/appkit/nsdragginginfo/1415966-draggingsourceoperationmask?language=objc

See the switch method in handleOnDragDropped

**Comment by Siedlerchr** [comment]
I checked this with a minimal demo app and it seems like it's a bug again

**Comment by tp-1000** [comment]
That's no good. Well, thanks for follow up.

**Comment by calixtus** [comment]
> I checked this with a minimal demo app and it seems like it's a bug again in javafx

Is there a related open issue in the javafx bugtracker?

**Comment by Siedlerchr** [comment]
I couldn't find one, so I submitted one yesterday evening. TL;DR: On Mac only Copy mode works

**Comment by Siedlerchr** [comment]
As this issue on mac is not related to your changes, https://bugs.openjdk.java.net/browse/JDK-8227371 
I am merging this

**Review by Siedlerchr — APPROVED** [review]

**Pull request merged**
