### PR TITLE
[WIP/Testing] Test Module Issue

### PR DESCRIPTION
**Pull request by DominikVoigt**
This PR is used to test whether the module issue is caused by jackson directly

For reference, java bug: https://bugs.openjdk.java.net/browse/JDK-8246197

- [ ] Change in CHANGELOG.md described (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by tobiasdiez** [comment]
This is really terrible... it essentially means that we cannot add any (sufficiently) large dependency. Shit...

Can you please try remove jgit and load add some random other library, just to exclude that jgit is not the source.

Then we should also think about how to proceed from here. Two obvious ways would be to remove some old libraries (antlr e.g.) and some less-used features (vm), maybe even to the extend to provide them as plugins (libreoffice) although I really don't wanna go this way.

**Comment by Siedlerchr** [comment]
Now we get a different exception for some modules:


```
Error: java.lang.RuntimeException: Module com.google.gson's descriptor indicates the set of packages is : [com.google.gson.annotations, com.google.gson, com.google.gson.stream, com.google.gson.reflect], 

but module contains packages: [com.google.gson.internal, com.google.gson.internal.bind, com.google.gson.stream, com.google.gson.internal.reflect, com.google.gson, com.google.gson.internal.bind.util, com.google.gson.annotations, com.google.gson.reflect]
```

**Comment by Siedlerchr** [comment]
@DominikVoigt  seems to work again

**Comment by koppor** [comment]
For reference:

- Listed at #5226 (which is a list on which external bugs we depend)
- There is a repository demonstrating the issue, too: https://github.com/GedMarc/JDK_Jlink_Bug

**Comment by tobiasdiez** [comment]
Did you already experimented with removing jgit again? Hopefully (maybe) this dependency explodes the module tree?!

**Comment by Siedlerchr** [comment]
Even with gradle 6.7 this fails:
`Error: jdk.internal.org.objectweb.asm.MethodTooLargeException: Method too large: jdk/internal/module/SystemModules$all.moduleDescriptors ()[Ljava/lang/module/ModuleDescriptor;`

**Comment by tobiasdiez** [comment]
Can you please post the content of that file? (I don't have a working jdk available at the moment)

**Comment by Siedlerchr** [comment]
Possible workaround: https://github.com/beryx/badass-jlink-plugin/issues/168#issuecomment-753478623
It's a problem of the jdk. I will try to test it locally and check the module class.

**Comment by koppor** [comment]
Closing, because we work at https://github.com/JabRef/jabref/pull/7126.

**Pull request closed without merging**
