### PR TITLE
Hide the side pane after closing all panels within it

### PR DESCRIPTION
**Pull request by LoayGhreeb**
Follow-up #11180.

Hide the side pane after closing all panels within it. 
@calixtus can you confirm if the removal of that listener was intentional or not?

Additionally, why is it important to update the side pane after the width changes?

### Mandatory checks

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by calixtus** [comment]
grafik

**Comment by calixtus** [comment]
An now you are also removing the width listener...
This must have slipped through. I'll clean it up.

**Review by calixtus — APPROVED** [review]

**Comment by LoayGhreeb** [comment]
Why is the width listener important? I think it will have no effect.
- If the side pane is shown, both conditions in `updateSidePane()` will be false `if (sidePane.getChildren().isEmpty())`, `if (!splitPane.getItems().contains(sidePane))`, because it will be shown only if it has children.
- If the side pane is hidden, the width can't be changed.

**Comment by calixtus** [comment]
For storing the width of the side pane in the prefs for persistence between sessions.

**Comment by calixtus** [comment]
Maybe there was a misunderstanding. The widthlistener is important for storing the divider position and calling the method is neccessary for initialization here, since the default behaviour of the splitpane is to show, even if it shouldn't.

**Comment by calixtus** [comment]
To move forward here, I will merge this simple Bugfix. Let's see if someone complains... 😄

**Pull request merged**
