### PR TITLE
Installer Code Signing #1879

### PR DESCRIPTION
**Pull request by stefan-kolb**
- [ ] Change in CHANGELOG.md described
- [ ] Win
- [ ] OSX

### CODE REVIEW

**Comment by koppor** [comment]
LGTM

[LGTM](https://lgtm.in/i/Mur1n32nq)

**Comment by stefan-kolb** [comment]
Can someone please try this on OSX @chochreiner. I also signed the dmg but I'm not sure that this works with the current certificate (even quite sure that it doesn't).

**Comment by behrinml** [comment]
Standard response (double click):
screen shot 2016-11-29 at 16 53 18

By right click -> open:
screen shot 2016-11-29 at 16 53 31

With the signed version:
screen shot 2016-11-29 at 16 59 42

So it seems to work but gives of course the standard warning for Applications from outside the App Store.

**Comment by chochreiner** [comment]
hmm
for me, there is no difference between the app from the master and the cert branch
Which certificate are you currently using?

**Comment by behrinml** [comment]
Which settings do you have for installing applications? For me it is set to "Allow apps downloaded from Mac App Store and identified developers".

I think if you use one of the other two settings there will be no differences between the builds...

**Comment by chochreiner** [comment]
For me its: "App Store and identified developers" (on MacOS Sierra)

**Comment by behrinml** [comment]
Ok.. Now I am confused. Just checked on MacOS Sierra from a colleague and there is no difference between the builds. Maybe it is something about the OS (I am using OS X El Capitan) or I have changed something else which interferes, f.e. disabled SIP to get Spaces back, but this shouldn't make a difference. I can check next week on OS X Mavericks or later today on Mac OS X Snow Leopard.. but I think the latter has no signing...

**Comment by stefan-kolb** [comment]
Maybe we need an extra certificate issued or registered with the App Store for MacOSX? Needs to be investigated later. For now it works for Windows at least.

**Pull request merged**
