### PR TITLE
PDFs are not stored next to .bib file if file directory is configured

### PR DESCRIPTION
**Pull request by koppor**
We had following issue:

- database file directory is configured outside the .bib directory
- .bib file is versioned
- .bib file is shared among a research group
- a user constantly adds PDFs into the git repository

Inspecting the code, the reason probably is that the database file directory is accessible on Windows only, but not on Mac OS X. Thus, during download, JabRef did a fallback on the directory of the .bib file.

This PR fixes it:

- In case a directory is set for a database, the fallback is NOT the directory of the .bib file, but the globally configured directory
- The globally configured directory is empty per default. The new default is the user's home + `JabRef` sub directory:
  Snipaste_2022-09-01_23-49-52

---

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by Siedlerchr** [comment]
How does this correlate with the Checkbox ticked "Search and store files relative to the bib library directory?"
=> If all direcroties are empty and this is checked then the file should be stored next to the bib file

**Comment by koppor** [comment]
> How does this correlate with the Checkbox ticked "Search and store files relative to the bib library directory?" => If all direcroties are empty and this is checked then the file should be stored next to the bib file

This is the long description of following new (!) code:

```java
   if (fileDirs.isEmpty() && preferences.shouldStoreFilesRelativeToBibFile()) {
```

Should I add this as text or would it be clear from the code itself?

**Comment by calixtus** [comment]
Major problem: swing reintroduced in JabRefPreferences, architecture tests are failing and future modularization is at risk

**Comment by Siedlerchr** [comment]
Deciscions: Move to OS or Desktop class

**Comment by Siedlerchr** [comment]
CleanupWorker fails cleanupRenamePdfRenamesRelativeFile and cleanupRelativePathsConvertAbsoluteToRelativePath

**Pull request merged**
