### PR TITLE
[WIP] Try with jaxb 3.0 and xjc

### PR DESCRIPTION
**Pull request by Siedlerchr**
Fixes #7137 

Finally I  was able to fix this jaxb jakarta dependeny update. Hellish complicated with all those implementaitons and version numbers and different namespaces ☺️ 

TODO:
- [ ] Depends on xmpbox/pdfbox

- [ ] Change in CHANGELOG.md described (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by Siedlerchr** [comment]
Hm:
>Error: Two versions of module jakarta.activation found in /Users/runner/work/***/***/build/jlinkbase/jlinkjars (jakarta.activation-api-2.0.0.jar and jakarta.activation-2.0.0.jar)

**Comment by Siedlerchr** [comment]
The failing xmp test seems to come from:

`java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter`

**Comment by Siedlerchr** [comment]
The problem is https://github.com/apache/pdfbox/blob/5f6c8b4e1fd32396889206f2222dce26480d2a95/xmpbox/src/main/java/org/apache/xmpbox/DateConverter.java

xmpbox/pdfbox still depends on javax.xml.bind that is obviously no longer present.

**Comment by tobiasdiez** [comment]
@Siedlerchr have you reported the issues upstream with xmpbox?

**Comment by Siedlerchr** [comment]
@koppor  wanted to do this because he already has an account at the apache

**Comment by koppor** [comment]
Issue submitted: https://issues.apache.org/jira/browse/PDFBOX-5061

Pull request fixing the issue submitted: https://github.com/apache/pdfbox/pull/101

**Comment by tobiasdiez** [comment]
Application insights uses a fat jar that contains all dependencies https://github.com/microsoft/ApplicationInsights-Java/issues/1060, so this shouldn't actually be a problem.

**Comment by Siedlerchr** [comment]
Well, the original error was.
```
aused by: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
        at com.microsoft.applicationinsights.internal.config.TelemetryConfigurationFactory.<init>(TelemetryConfigurationFactory.java:90) ~[applicationinsights-core-2.4.1.jar:?]
        at com.microsoft.applicationinsights.internal.config.TelemetryConfigurationFactory.<clinit>(TelemetryConfigurationFactory.java:66) ~[applicationinsights-core-2.4.1.jar:?]
        at com.microsoft.applicationinsights.TelemetryConfiguration.getActive(TelemetryConfiguration.java:70) ~[applicationinsights-core-2.4.1.jar:?]
    at org.jabref.gui.Globals.startTelemetryClient(Globals.java:122) ~[JabRef-100.0.0.jar:?]
```    

With version 3.x they also changed the approach.  Apparently they now use an java agent. Not exactly sure. 
https://docs.microsoft.com/de-de/azure/azure-monitor/app/java-get-started?tabs=maven

**Pull request closed without merging**
