### PR TITLE
Fix for bug #919: Accents don't export to RTF

### PR DESCRIPTION
**Pull request by ruytakata**
Tests with various accented characters were made. The result was: 
Ç ü é ã á ä à å ç ê ë è ï í ì î Ä Å É æ Æ ô ö ò û ù ÿ Ö Ü ó ú ñ Ñ Ã Á Â À Ð Ê Ë È Í Î Ï Ì Ó Ô Ò õ Õ Ú Û Ù ý Ý ø Ø ï

### CODE REVIEW

**Comment by koppor** [comment]
GitHub has the disadvantage that it continues updating the pull request when new commits flow into a branch. Therefore, the "Cleanup entries error 3" commit went into this PR. Should be OK for now, but for the next PRs, please make a separate branch for each fix :)

**Comment by ruytakata** [comment]
About the commit, very sorry. I did a commit with the first modification, and I dont know how I should do the second. I'm learning to use the github yet.

**Comment by ruytakata** [comment]
About the "`A", in my environment I tested all the characters listed (Ç ü é ã á ä à å ç ê ë è ï í ì î Ä Å É æ Æ ô ö ò û ù ÿ Ö Ü ó ú ñ Ñ Ã Á Â À Ð Ê Ë È Í Î Ï Ì Ó Ô Ò õ Õ Ú Û Ù ý Ý ø Ø ï). Those who had problems I changed. (Print of a example attached before the change)

jabref
rtf

My enviroment is a Archlinux with Java 1.8.0_45. I will try to find a Windows enviroment to test before send more commits in the future.

**Comment by oscargus** [comment]
The fix in HTMLConverter is incorrect for the accented i:s. With the modification the accent is added to a normal i, while in the old version it was added to a dot-less i (\i).

**Comment by ruytakata** [comment]
I did not understand. Can you explain in more detail? I tested all "i" characters and seem correct to me.

**Comment by oscargus** [comment]
See, e.g., https://en.wikibooks.org/wiki/LaTeX/Special_Characters especially

"To place a diacritic on top of an i or a j, its dot has to be removed. The dotless version of these letters is accomplished by typing \i and \j."

**Pull request merged**
