### PR TITLE
Fix regression from adding tests.

### PR DESCRIPTION
**Pull request by ror3d**
I just noticed that using the "Redownload file" funcionality from linked files copied the current path to the sourceURL, which made it so that the actual source URL was lost upon the second download of a file. To reproduce:

1. Create an entry
2. Download a file to the entry with the Download button on the right of the Files section in the General tab
3. Right-click on the file, choose Edit, and observe that the "Link" points to the local file's path, and sourceURL points to the url used for the download
4. Delete the downloaded file from the download directory
5. Right-click again on the file and choose "Redownload file"
6. When the download is finished, right-click the linked file, choose Edit, and notice that both Link and sourceURL point to the local path

Through git blame, the changes were introduced by @calixtus when adding tests in commit 8f3f55b. I do have a question about those changes that I would like to understand better:
In my original implementation, I had made it so that the LinkedFile in the BibEntry wasn't changed, just updated with the new information. The changes introduced in that commit reverted that change to what was done previously, which is call BibEntry.replaceDownloadedFile. What is the reason for that? i.e. why is that better?

### Mandatory checks

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [x] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by koppor** [comment]
Looks good. Is there a test case possible? 😅

**Comment by ror3d** [comment]
Okay I added the test for this, I verified that the previous code doesn't pass the test and the new code does.

**Comment by koppor** [comment]
I removed the CHANGELOG entry, because the "fix" was introduced after the last release.

**Comment by calixtus** [comment]
uhh, I think I remember there was sthg about avoiding code duplication...
Code lgtm.

**Pull request merged**
