### PR TITLE
Build snap from java package

### PR DESCRIPTION
**Pull request by LyzardKing**
This is the snap of the java package.
I tested it during my normal workload and it seems to work.
It needs more testing though.
I used the app/JabRef.cfg to set the version, is it correct?
at the moment it's set at version 1.0

----

- [ ] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [ ] Manually tested changed features in running JabRef
- [ ] Screenshots added in PR description (for bigger UI changes)
- [ ] Ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)

### CODE REVIEW

**Comment by Siedlerchr** [comment]
lgtm so far. @tobiasdiez  Where is the jabref version string stored?

**Comment by LyzardKing** [comment]
I can get the version by reading the output of ./JabRef --version, but do you intend to keep a variable somewhere updated?
If not I'll add that Let me know :)

**Comment by tobiasdiez** [comment]
I had the same problem with the chocolatey package. Not sure what's the best way to automatize it. We could use gradle to set the correct version similar to here
https://github.com/JabRef/jabref/blob/631cec58beda06e182dc6d85ac676f4073a9bbea/build.gradle#L291-L293
This has the advantage that we only need to set the version in gradle. However, then the snap (and chocolatey) package needs to processed every time before you can test it locally...
@koppor any ideas?

Moreover, I was wondering if the snap stuff should be moved to `buildres/snap`

**Comment by LyzardKing** [comment]
I believe that the snapcraft.io build system expects to find the snap in the root of the repo, but since you are doing things "manually" it shouldn't be an issue. If gradle could set the version it would be good, to avid having to parse the cli --version, that might change in the future.
If the app/JabRef.cfg file is supposed to hold the app data it could be the right one to use..it already has a version line.
Then the ci can build/publish the snap..
I'll test the github actions though, since I never tried that integration..

**Comment by tobiasdiez** [comment]
Is this (and https://github.com/JabRef/jabref/pull/5322) now obsolete?

**Comment by LyzardKing** [comment]
Yes, you can go ahead and close them both...

**Pull request closed without merging**
