### PR TITLE
Add vector module

### LINKED ISSUE #11502: Enhance indexing speed with java vector api
JabRef complains on startup with a warning:

`
WARN: Java vector incubator module is not readable. For optimal vector performance, pass '--add-modules jdk.incubator.vector' to enable Vector API.
`

The Vector API is a feature on hold (incubator) https://openjdk.org/jeps/460 since JDK 16 waiting for project Valhalla https://openjdk.org/projects/valhalla/ to be finished eventually and be finally integrated. It should already be stable and there should be no problem for us to enable that feature.

### PR DESCRIPTION
**Pull request by calixtus**
Fixed #11502 

Tradeoff: Displays a warning now "Using incubator modules: jdk.incubator.vector"

### Mandatory checks

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by Siedlerchr** [comment]
Needs to be adjusted on the mac pipelines as well

**Comment by Siedlerchr** [comment]
Have you tested the build?

**Comment by calixtus** [comment]
Windows portable, yes. Works fine.

**Comment by Siedlerchr** [comment]
Needs to be added here with --add modules https://github.com/JabRef/jabref/blob/d8ebffc51cff2f48c68155f6851ff263dba19244/.github/workflows/deployment-arm64.yml#L139-L140
and in other deployment pipeline as well

**Comment by calixtus** [comment]
Ok I see, will look into it. Thought gradle pipeline was used for GitHub actions.

**Comment by Siedlerchr** [comment]
> Ok I see, will look into it. Thought gradle pipeline was used for GitHub actions.

Yes but not for mac

**Comment by calixtus** [comment]
@Siedlerchr please test if this works on Mac.

**Comment by stephanlukasczyk** [comment]
Just installed https://builds.jabref.org/pull/11532/merge/JabRef-5.16-arm64.dmg on an MBP with M3 Pro CPU (macOS 14.5).  Starting causes macOS to complain that the program is not signed (probably expected) but then nothing happens.  JabRef does not show any reactions, it's not starting up.  Unfortunately, I do not have the time to dig deeper into it today, sorry.

**Comment by Siedlerchr** [comment]
@stephanlukasczyk  you have to allow it under settings->  data protection and  security or alternatively xattr -r -d com.apple.quarantine /path/to/MyApp.app

**Comment by stephanlukasczyk** [comment]
@Siedlerchr No, setting `xattr -r -d com.apple.quarantine /Applications/JabRef.app` does not change anything, still no reaction.

**Comment by Siedlerchr** [comment]
Yeah, starting it manually I get java.lang.module.FindException: Module jdk.incubator.vector not found
 /Applications/JabRef.app/Contents/MacOS/JabRef
if I remove it from app.cfg it starts again

**Review by Siedlerchr — APPROVED** [review]

**Comment by Siedlerchr** [comment]
Fixed it, we need it as jpackage option and as start option

**Comment by calixtus** [comment]
Thanks

**Pull request merged**
