### PR TITLE
Update to MADR 4.0.0

### LINKED ISSUE #11912: Update to MADR 4.0.0
(This is a non-coding issue)

[MADR 4.0.0 was released](https://github.com/adr/madr/releases/tag/4.0.0).

The decisiosn in https://github.com/JabRef/jabref/tree/main/docs/decisions should be updated to that format.

### PR DESCRIPTION
**Pull request by RabidGhost**
Closes #11912

Updates ADRs to [MADR 4.0.0 format](https://github.com/adr/madr/releases/tag/4.0.0) and fixes some small typos in existing ADRs.

Some markdown lint disables have been removed. Please confirm if this is intended.

### Mandatory checks
Items unchecked are not applicable.

- [x] I own the copyright of the code submitted and I licence it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by koppor** [comment]
Follow-up is https://github.com/JabRef/jabref/pull/12016

@RabidGhost Please LEAVE OPEN the pull reuqest (DO NOT close the PR) - see [After submission of a pull request](https://github.com/JabRef/jabref/blob/main/CONTRIBUTING.md#after-submission-of-a-pull-request) - If the text there is not clear, please propose a new text to guide contributors. (There were multiple others closing the PR after any comment)

**Comment by RabidGhost** [comment]
> After submission of a pull request

Sorry about this. I was failing as some checks as this request was from my forks main branch. I couldnt find any way to change this in the pull request. 

> If the text there is not clear, please propose a new text to guide contributors.

I may do this, i think this point could be better highlighted in the text. Thanks for the feedback

**Comment by RabidGhost** [comment]
> If the text there is not clear, please propose a new text to guide contributors. (There were multiple others closing the PR after any comment)

If I want to clarify the text in the guide, should I create an issue for it before begining work?

**Comment by koppor** [comment]
> If I want to clarify the text in the guide, should I create an issue for it before begining work?

You can just open a pull request. Explain in the PR that the text was unclear.

**Comment by koppor** [comment]
> Sorry about this. I was failing as some checks as this request was from my forks main branch. 

Yes, it is caused by your changes. Because your changes are checked. It is not a bad thing if checkers find something. They guide you where to look at.

> I couldnt find any way to change this in the pull request.

Maybe the information that you should "just" fix the issue, commit and push (in the branch) is missing?

**Pull request closed without merging**
