### PR TITLE
Rename formatters

### PR DESCRIPTION
**Pull request by tobiasdiez**
The aim of this PR is to rename all formatters as discussed in https://github.com/JabRef/jabref/issues/920.

Changes:
- Remove Converter class which is superfluous with the improved formatter interface
- Enable LatexToUnicode as formatter (previously it was only a LayoutFormatter)
- Rename formatters (the key is always the class name without the `Formatter` suffix, a value in brackets indicates that I deviated from the last version in #920):

(I will add the necessary changes to the language files as soon as the names are accepted)

Format:
 * Basis is https://github.com/JabRef/jabref/issues/920#issuecomment-195779352
 * Plus later comments
 * name: chosen name, brackets show non chosen alternatives.

--

### Authors related
- [ ] AuthorsFormatter
  - classname: NormalizePersonNamesFormatter (NormalizeAuthorsFormatter)
  - name: normalize names of persons (normalize authors)
- [ ] AuthorsMinifier
  - classname: MinifyPersonNamesFormatter (MinifyAuthorsFormatter)
  - name: Minify authors

### Date related
- [ ] MonthFormatter
  - classname: NormalizeMonthFormatter
  - name: normalize month
- [ ] DateFormatter
  - classname: NormalizeDateFormatter
  - name: normalize date

### Page related
- [ ] PageNumbersFormatter
  - classname: NormalizePagesFormatter
  - name: normalize page numbers (normalize pages)

### Casing related
- [ ] TitleCaseChanger
  - classname: TitleCaseFormatter
  - name: title case (Titelize, EnforceTitleCaseFormatter)
- [ ] UpperEachFirstCaseChanger
  - classname: CapitalizeFormatter
  - name: capitalize
- [ ] UpperCaseChanger
  - classname: UpperCaseFormatter (UpcaseFormatter)
  - name: upper case (to upper case)
- [ ] UpperFirstCaseChanger
  - classname: SentenceCaseFormatter (CapitalizeFirstDowncaseOthersFormatter)
  - name: sentence case (capitalize first, downcase others)
- [ ] LowerCaseChanger
  - classname: LowerCaseFormatter (DowncaseFormatter)
  - name: lower case (to down case)
- [ ] CaseKeeper
  - classname: ProtectCapitalsFormatter (FreezeTermsFormatter)
  - name: protect capitals (freeze terms)
- [ ] RemoveBracesFormatter
  - key: RemoveBracesFormatter (UnfreezeWords)
  - name: remove enclosing braces (unfreeze words)
  - Note that this formatter only removes braces which enclose the whole field (e.g. "{test}" to "test"), but not "In {CDMA}" to "In CDMA")

### LaTeX conversion
- [ ] LatexFormatter
  - classname: LatexCleanupFormatter 
  - name: LaTeX cleanup (remove LaTeX)
  - Note that this formatter does not remove all latex code, but just does some basic cleanup like combinding adjacent math environments)
- [ ] HTMLToLatexFormatter
  - name: HTML to LaTeX
  - classname: HtmlToLatexFormatter
- [ ] UnicodeToLatexFormatter
  - name: Unicode to LaTeX
  - classname: UnicodeToLatexFormatter
- [ ] LatexToUnicodeFormatter 
  - name: LaTeX to Unicode
  - classname: LatexToUnicodeFormatter 
- [ ] SuperscriptFormatter
  - classname: OrdinalsToLatexSuperscriptFormatter (OrdinalsToLatexFormatter)
  - name: ordinals to LaTeX superscript (ordinals to LaTeX)
- [ ] UnitFormatter
  - classname: UnitsToLatexFormatter
  - name: units to LaTeX

### Radical formatters
- [ ] EraseFormatter
  - name: Clear
  - classname: ClearFormatter

--

- [ ] Change in CHANGELOG.md described?
- [ ] Tests created for changes?

### CODE REVIEW

**Comment by tobiasdiez** [comment]
By the way, I would prefer to capitalize the first word in the name of the Formatters, i.e.  ̀Normalize month`

**Comment by oscargus** [comment]
I can only second starting the names with capital letters.

**Comment by koppor** [comment]
- [ ] Examples have to be separated from the description, to prevent translations of them.
- [ ] Examples should be stored as `from` and `to`.

**Comment by matthiasgeiger** [comment]
... or examples should be in the form " *from* **>** *to*" - storing them independently is not neceessary.

**Comment by tobiasdiez** [comment]
I merge this now in. Hopefully I got every name and description right...

**Comment by mlep** [comment]
Among the added localization strings, what does "Completely_the_field." means?

**Comment by tobiasdiez** [comment]
@mlep Thanks for pointing out the strange description string. I fixed it in #1087.

**Comment by mlep** [comment]
@tobiasdiez Great. Thank you for tidying up JabRef Localizations.

**Pull request merged**
