### PR TITLE
Implement #1904: filter groups

### PR DESCRIPTION
**Pull request by tobiasdiez**
Add textbox add the bottom of the groups panel which allows for filtering the groups by name. Implements #1904.

snipimage 002

- [x] Change in CHANGELOG.md described
- [x] Tests created for changes
- [x] Screenshots added (for bigger UI changes)
- [x] Manually tested changed features in running JabRef
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)
- [ ] If you changed the localization: Did you run `gradle localizationUpdate`?

### CODE REVIEW

**Comment by Siedlerchr** [comment]
Great idea. However, I would place the search bar on top of the screen and not at the bottom, or alternatively is there a way to reuse the existing search bar and add an option to search for groups?

**Comment by tobiasdiez** [comment]
Maybe it's indeed a good idea to move the search bar and button to the top...as this is an easy change I would postpone it for the moment and see what kind of further user controls are necessary in the group pane.

**Comment by stefan-kolb** [comment]
On the bottom looks good to me.

**Comment by lenhard** [comment]
I think having the search box at the bottom is fine for now, since we can also change it easily.

The feature works nicely with normal-size bib files, but I just checked it with the large bib file and there the feature scales very badly. If I enter something into the search field, it freezes and nothing happens for one or two minutes until the rearrangement of the groups appears (as desired). 

Do you see a chance to speed this up? Maybe some parallelism, using `parallel()` in streams, could help?

**Comment by lenhard** [comment]
Looks like other people see a group-related performance degradation: https://github.com/JabRef/jabref/issues/2561#issuecomment-283417338 So, this is most likely not specific to this PR and you could go for a merge.

However, we really need to follow up with a performance improvement PR.

**Comment by lenhard** [comment]
Since, as indicated in https://github.com/JabRef/jabref/issues/2561#issuecomment-283494292 the degraded performance for large bibs is expected at the moment and will be tackled separately, I think this is ready for merge (which I am doing right away).

**Comment by matthiasgeiger** [comment]
One suggestion as I just stumbled over it: I think the searching should be case insensitive (although this might further slow down the searching ;-))

**Comment by AEgit** [comment]
Should the performance issue with the groups filtering (which is still massive) also be added to the 4.0 milestone?

**Comment by lenhard** [comment]
@AEgit I am not exactly sure which issue you are referring to, but yes: We should try to improve performance before a final release. So if there is an open issue that should be in 4.0, please point me to it!

**Comment by AEgit** [comment]
@lenhard The performance issue I'm referring to happens with large databases (>10k entries, ~1k static groups) in conjunction with the groups filtering. When you try to find a group using the newly implemented groups search/filter, you have to wait for several minutes for the search to complete. During that time JabRef behaves as if it had crashed. You mentioned this problem yourself in this comment:
https://github.com/JabRef/jabref/pull/2588#issuecomment-283042778

Should I open a new ticket for this?

**Comment by lenhard** [comment]
@AEgit Yes, please open a new ticket for this, so that we do not forget it.

**Comment by AEgit** [comment]
Done ;)
https://github.com/JabRef/jabref/issues/2852

**Pull request merged**
