### PR TITLE
Allow - in citaton keys

### PR DESCRIPTION
**Pull request by koppor**
Doesn't fully work, needs some more polishing.

Follow-up to https://github.com/JabRef/jabref/pull/9703

### Mandatory checks

- [x] I own the copyright of the code submitted and I licence it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if change is visible to the user)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by ThiloteE** [comment]
The most credible source for allowed / unallowed characters does not list `-` and `:`: https://tex.stackexchange.com/questions/408530/what-characters-are-allowed-to-use-as-delimiters-for-bibtex-keys

But there are some mentions of possible complications here:

- https://tex.stackexchange.com/questions/388500/what-is-valid-as-a-biblatex-entry-key?noredirect=1&lq=1
- https://de.wikibooks.org/wiki/LaTeX-Kompendium:_Sonderzeichen
- https://en.wikibooks.org/wiki/LaTeX/Special_Characters

For example:

`<html><body>

Bezeichnung | Ausgabe | LaTeX-Code
:-- | -- | --
Bindestrich (auch Viertelgeviertstrich) | - | -



</body>
</html>`

`<html><body>


Command | Sample | Character
-- | -- | --
\textendash | n/a | –
\\_ | _ | _


</body>
</html>`

But I don't know, if this still holds in the current bibtex, biblatex, biber, ecosystem.
We could test random applications and packages and if we find no complications, then updating those wiki/stackoverflow pages could be good. Or we merge and let users report issues...

**Comment by ThiloteE** [comment]
Ah and if you use your citationkey to name your linked files, then `:` is not good on Windows Operating system ...

**Comment by koppor** [comment]
Note that we remove characters not allowed on a file system while generating a file name. Moreover, I saw `:` only when JabRef issued `Problem:` somewhere in the code.

---

We distinguish between un-wanted and forbitten characters:

unwanted: perfeclty legal, but disturbing:

    public static final String DEFAULT_UNWANTED_CHARACTERS = "`ʹ!;?^";

forbidden - not working with BibTeX:

     /// Source of disallowed characters: <https://tex.stackexchange.com/a/408548/9075>
     /// These characters are disallowed in BibTeX keys.
     private static final List<Character> DISALLOWED_CHARACTERS = Arrays.asList('{', '}', '(', ')', ',', '=', '\\', '"', '#', '%', '~', '\'');

Public sources use `:` and `/` in the key:

Example:

```bibtex
@phdthesis{DBLP:phd/de/Kopp16,
  author       = {Oliver Kopp},
  title        = {Partner{\"{u}}bergreifende Gesch{\"{a}}ftsprozesse und ihre
                  Realisierung in {BPEL}},
  school       = {University of Stuttgart},
  year         = {2016},
  url          = {https://nbn-resolving.org/urn:nbn:de:bsz:93-opus-105304},
  urn          = {urn:nbn:de:bsz:93-opus-105304},
  timestamp    = {Sat, 17 Jul 2021 09:07:39 +0200},
  biburl       = {https://dblp.org/rec/phd/de/Kopp16.bib},
  bibsource    = {dblp computer science bibliography, https://dblp.org}
}
```

Fun fact: We allow forward-slash. Thus, the discussion on `:` seems to be odd to be.

---

I am aiming to make JabRef "knobless" so that it works well in a default-configuration without WTFs. - And I found removing dashes (and somehow also colons) a WTF. I saw these characters often when working with LaTeX and BibTeX.

**Comment by koppor** [comment]
@mlep Thank you for the pointer. I refined the documentation at https://github.com/JabRef/user-documentation/pull/538.

Since we are working towards an alpha and can IMHO experiment, we should give this a "go". @Siedlerchr

**Pull request merged**
