### PR TITLE
Fix destination for jabref mozilla json

### LINKED ISSUE #5502: Error installing jabref deb package in ubuntu: native messaging host is not a dir
Latest version of JabRef:`  sudo dpkg -i jabref_5.0.0-1_amd64\(1\).deb `

```
install: target '/usr/lib/mozilla/native-messaging-hosts/' is not a directory: No such file or directory
dpkg: error processing package jabref (--install):
 installed jabref package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 jabref
```

I manually checked it, the dir is not existing. /usr/lib/mozilla only has a subfolder plugins

Linux osboxes 4.15.0-62-generic #69-Ubuntu SMP Wed Sep 4 20:55:53 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
Ubuntu 18.04
Firefox 69

### PR DESCRIPTION
**Pull request by LyzardKing**
Fixes #5502 
I'd keep the branch open, to enable test  builds of deb/rpm packages while we fix the last jpackage options.

### CODE REVIEW

**Comment by Siedlerchr** [comment]
Ah shit, oss.sonatype maven repo once again is down...

**Comment by LyzardKing** [comment]
It managed to build locally and went down just as I pushed the change upstream...

**Comment by LyzardKing** [comment]
@Siedlerchr I forced the build to run again, since the repo is up now.
Once it's built let me know if you can test it!

**Comment by koppor** [comment]
@LyzardKing What testing do you mean? None of us has Linux machines :(

If you say, it's good to go, we can merge!

**Comment by LyzardKing** [comment]
It should be fine.
Just to be on the safe side I'll try rebasing on master so I can test the deb first

**Comment by koppor** [comment]
Seeing https://github.com/JabRef/jabref/issues/5502, @Siedlerchr is our linux tester. 🎉

**Comment by Siedlerchr** [comment]
> Seeing #5502, @Siedlerchr is our linux tester. 🎉

You wish. Nope, I have only a slow Ubuntu VM (running on my hdd cause my ssd is too small) for testing stuff.

**Comment by LyzardKing** [comment]
> > Seeing #5502, @Siedlerchr is our linux tester. tada
> 
> You wish. Nope, I have only a slow Ubuntu VM (running on my hdd cause my ssd is too small) for testing stuff.

:smile: 

I tested on a live image with no jabref version, with the version in the ubuntu repo and reinstalling the deb.
The install seems to never fail and copies the proper json file.
@Siedlerchr if you want to test it to be sure, then you're free to merge

**Comment by LyzardKing** [comment]
That was fast.. 
@tobiasdiez I would have kept the branch, to test the deb, since the licence/copyright stuff is still missing..
Regarding that, I have never had a reply on the mailing list..

**Comment by tobiasdiez** [comment]
Yeah, you are not alone. I've also send a few mails to the jdk mailing list and didn't get a single response yet.
The license stuff is not super important so I guess it is fine to wait until jpackage is released and properly documented.

(the branches are deleted automatically btw)

**Comment by LyzardKing** [comment]
Ah ok..
The rest of the deb should work..and the license in the rpm should (in theory) work
since it's set in a separate command..
But I'll test that tomorrow in a vm ;)

**Comment by Siedlerchr** [comment]
Works fine now.

**Comment by LyzardKing** [comment]
:tada:

**Pull request merged**
