### PR TITLE
Snapcraft

### PR DESCRIPTION
**Pull request by koppor**
Our beta snapcraft image does not start. Reason: No Java 14 available.

I updated the gnome base image. We need to stay "core18". - Gnome 3.34 is not available for core20 --> https://forum.snapcraft.io/t/gnome-3-34-extension-for-core20/18590/3?u=koppor

@LyzardKing Can you take over?

- [ ] Change in CHANGELOG.md described (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by LyzardKing** [comment]
I'll look at it and see what I can do! :)

**Comment by LyzardKing** [comment]
@koppor If I try and build from this branch it works, sithout any changes.

**Comment by LyzardKing** [comment]
A while back I added a shell laucher for the snap (it can be found in the snap in bin/JabRef)
If I explicitly run that command in the snap --shell environment it works.
There must have been an issue somewhere with that.

**Comment by Siedlerchr** [comment]
@LyzardKing  thanks for helping. @calixtus tried the beta (before that branch) with Arch Unit and had the problems with the missing jre

**Comment by LyzardKing** [comment]
Ah ok. 
The script uses `#! /bin/sh`
I thought that was generic enough

**Comment by koppor** [comment]
I think, there shouldn't be a space between `#!` and `/bin/sh` - or is this a hidden feature?

**Comment by LyzardKing** [comment]
The white space is simply optional, so that shouldn't be an issue

**Pull request merged**
