### PR TITLE
Added UpdateFieldPreferences

### PR DESCRIPTION
**Pull request by oscargus**
Less dependency on JabRefPreferences in a small part of logic...

### CODE REVIEW

**Comment by tobiasdiez** [comment]
LGTM :+1:

**Comment by stefan-kolb** [comment]
Hm what is the big difference here? The only thing that changed is that some prefs are now stored in another class that still need JabRefPreferences?!

**Comment by oscargus** [comment]
Correct. But it is very simple to move the `fromPreferences` method to
`JabRefPreferences` and eventually the whole logic will not access
`JabRefPreferences` at all. I think we are soon reaching the point where
that can happen as there are no Globals calls left (once one of my other
PRs is merged) and most classes and methods have this type of specialised
preferences. (Simon and Tobias convinced me of this as I had similar
doubts.)

**Comment by oscargus** [comment]
I thought I'd add a method to `JabRefPreferences` as we actually are closing in on this now.

**Pull request merged**
