### PR TITLE
Update JabRef_it.properties

### PR DESCRIPTION
**Pull request by Doc73**
Modified translation of line 1854

----

- [ ] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [ ] Manually tested changed features in running JabRef
- [ ] Screenshots added in PR description (for bigger UI changes)
- [ ] Ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)

### CODE REVIEW

**Comment by calixtus** [comment]
Hi Doc73, please note that translations in JabRef are handled via crowdin.com. So changing the language files here would probably have no effect in the long run.

**Comment by Doc73** [comment]
Ah, sorry! I didn't know....

**Comment by Siedlerchr** [comment]
The translations should be synced both ways . But for future translations, crowdin is favorable.
Should also be easier as you get suggestions from previous translations or automatic machine translations.
If you are native Italian, I could add you as Translation manager. So you can automatically accept your and other translations

**Comment by Doc73** [comment]
@Siedlerchr 
I'm Italian! You could add me, but I cannot assure you that I can commit myself to this job, for reasons of time. :-(

**Comment by Siedlerchr** [comment]
Gracie! No problem if you don't have that much time. Just if you could look over it from time to time. Most is already translated I think thx to @frithnath

**Comment by Siedlerchr** [comment]
@Doc73  Just join via this link (you can use github for login) and I can add you as proofreader (means you can accept/approve yours and other translations) http://translate.jabref.org/project/jabref/invite

**Comment by Doc73** [comment]
@Siedlerchr 
Done! I am not very acquainted with these things, but if I can, I will try to make my contribution.

**Pull request merged**
