### PR TITLE
Fix exception in localization tests

### PR DESCRIPTION
**Pull request by tobiasdiez**
Hopefully....

- [ ] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [ ] Screenshots added (for bigger UI changes)
- [ ] Manually tested changed features in running JabRef
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)

### CODE REVIEW

**Comment by koppor** [comment]
`2235 tests completed, 3 failed, 33 skipped`

**Comment by tobiasdiez** [comment]
Yes, but the integration tests fail without any warning 
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

Any idea why? no javafx installed?

**Comment by Siedlerchr** [comment]
There are duplicates in the lang file de and missing keys, too:
`    java.lang.AssertionError: Duplicate keys inside bundle JabRef_de expected:<[]> but was:<[Audio_CD, British_patent, British_patent_request, Candidate_thesis, Collaborator, Column, Compiler, Continuator, Data_CD, Editor, European_patent, European_patent_request, Founder, French_patent, French_patent_request, German_patent, German_patent_request, Line, Master's_thesis, Page, Paragraph, Patent, Patent_request, PhD_thesis, Redactor, Research_report, Reviser, Section, Software, Technical_report, U.S._patent, U.S._patent_request, Verse, change_entries_of_group, odd_number_of_unescaped_'#', Plain_text, Show_diff, character, word, Show_symmetric_diff, HTML_encoded_character_found, booktitle_ends_with_'conference_on', All_external_files, OpenOffice/LibreOffice_integration, incorrect_control_digit, incorrect_format, Expected_"%0"_to_contain_whitespace, Syntax_error_in_regular-expression_pattern, Copied_version_to_clipboard, BibTeX_key, Message, Merge_entry_with_%0_information, Updated_entry_with_info_from_%0]>`

**Comment by koppor** [comment]
Could you merge `javafx`? This is an addition to #1972? With that fix, we do not need to start the X server on TravisCI, do we?

**Comment by tobiasdiez** [comment]
Yes with this fix no X server is need for TravisCI, thus the change in #1972 (below https://github.com/JabRef/jabref/pull/1972/commits/a6ff713b5fc9415d72965a1506690f949908bbdd) is not needed. However, this change is just 2 lines while my fix is 1000 😢 
So if you could live with starting the Xserver for the tests, then my PR is pointless and can be closed.

**Comment by koppor** [comment]
+1 for fewer LOC for getting tests running.

**Pull request closed without merging**
