### PR TITLE
Menu: Update of Japanese localization (by Marisa)

### PR DESCRIPTION
**Pull request by mlep**
<describe the changes you have made here: what, why, ...>

- [ ] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [ ] Screenshots added (for bigger UI changes)

### CODE REVIEW

**Comment by mlep** [comment]
Any idea why Tracis gives the message " allFilesMustHaveSameKeys FAILED"?
I cannot find the key that is wrong or missing...
Please, help!

**Comment by stefan-kolb** [comment]
There are missing keys in language files. Please merge with most recent master.

**Comment by stefan-kolb** [comment]
I merged it manually.

**Comment by mlep** [comment]
The initial file is still 13 days old on Master. Doing the changes online, I used the most recent (no interaction with a recently merged pull request).
Using gradlew, both the original and my modified version give the same results:
> ----> No missing keys.
> ----> No possible obsolete keys (not in English language file).

I am stymied...

**Pull request closed without merging**
