### PR TITLE
Fixed #6601: Right click menu for main table header

### LINKED ISSUE #6601: Add right click menu for main table header
It would be nice if right-clicking on the main table header (where the column names are), provided a menu which either allowed to edit the viewed columns/fields directly or provided a link to the preferences. 

Maybe a list of the currently and most commonly used fields would show up to be activated/deactivated in the right click menu and for more detailed adjustments a reference to the settings would be displayed.

### PR DESCRIPTION
**Pull request by sj30001**
Fixes #6601 

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

We've added right-click menu in JabRef main table header to achieved a show and hide function for different table columns. The right-click menu also gives the user a link to the preferences entry table.

_**Right Click menu:**_
right click menu

 _**Hide and show table columns:**_
show and hide

_**Jump to preferences entry table:**_
link to preference

_**Multi-language support:**_
mulri language support

Bug Fixed:
1.Fix right-click not working properly on Mac OS
2.Fix show and hide status being refreshed after preference saved

### CODE REVIEW

**Comment by Siedlerchr** [comment]
Thanks, overall this looks already good! I'm just not that happy with the approach for the visible status. I need to think about a better approach.
Meanwhile, please have a look at the reviewdog/checkstyle

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
Perhaps use a `BooleanProperty` and bind it to the `MainTableColumn` `visibilityProperty()` and the `selectedProperty` of the radio menu item?

**Comment by sj30001** [comment]
Thanks, we'll take a look at reviewdog

**Comment by calixtus** [comment]
Right click menu is a good thing, but the visible property in this case not...
This creates a huge wtf moment for the users, who can now independently add/remove columns to the main table in the preferences dialog as well as in the right click menu with completely different methods.

Please remove the visible property handling here and try add/remove columns (maybe with a standard set of columns) in the list of main table columns. See TableTabViewModel.

**Comment by Siedlerchr** [comment]
@sj30001  It would be really nice if you could add the required changes

**Comment by sj30001** [comment]
> @sj30001 It would be really nice if you could add the required changes

Thanks, I'll discuss with our team and apply changes as required

**Comment by sj30001** [comment]
> can now independently add/remove columns to the main table in the preferences dialog as well as in the right-click menu wit
Hi Calixtus,
Our team just had a meeting, and we are a little bit confused about the changes we need to do. The right-click menu will only set the columns visibility it won't add or remove any columns like what we can do in the preference window. If we use our right-click menu to hide a column it won't remove it completely (ie. no column will be deleted in the preference window), it can be shown again by using the right-click menu again.  The visible property is there to make this show and hide function works. If we remove it I think we'll lose the functionality that issue 6601 wants us to solve. 

Another confusion we have is with the auto check, we've managed to fix the style check problem reported by auto-check, but there is a MacOS installer fail check we don't know why it didn't pass. We've used a Mac machine to build the run the project with no problem. Do we need to worry about that? Thanks a lot for reading this, it will be great if you could give us a little hint on what we should do. Thanks again.
Steve

**Comment by Siedlerchr** [comment]
You can ignore the mac installer. It's not working  on forks because it requires access to secrets for notarization.

**Comment by calixtus** [comment]
About the visibility property. Yes what you describe is from the user perspective the main problem: With your changes there are now two different ways to show/hide columns: By changing the columns in the preferences AND also by showing/hiding them in the right-click menu. This is confusing for the user, as the user expects only one place / one way to show and hide columns in the main table. So I would ask you, to show/hide the columns by adding or removing them from the columns list instead of changing the visibility property. Note that this is also in my probably a question of performance, since hidden by visibility property columns are still computed. In a database with only about 100 entries, this may not make much difference, but in database of 10000 it does.

In the right-click-menu there should only be a list with commonly used columns, that can be added or removed, maybe also the recently used columns. If you have questions I'm happy to help.

Thank you for your efforts to make JabRef a better library management tool!

**Comment by sj30001** [comment]
> About the visibility property. Yes what you describe is from the user perspective the main problem: With your changes there are now two different ways to show/hide columns: By changing the columns in the preferences AND also by showing/hiding them in the right-click menu. This is confusing for the user, as the user expects only one place / one way to show and hide columns in the main table. So I would ask you, to show/hide the columns by adding or removing them from the columns list instead of changing the visibility property. Note that this is also in my opinion a question of performance, since hidden by visibility property columns are still computed. In a database with only about 100 entries, this may not make much difference, but in database of 10000 it does.
> 
> In the right-click-menu there should only be a list with commonly used columns, that can be added or removed, maybe also the recently used columns. If you have questions I'm happy to help.
> 
> Thank you for your efforts to make JabRef a better library management tool!

Thanks, this clarifies our confusion. We'll make the necessary changes ASAP. Thanks again

**Comment by Qiming-Liu** [comment]
Hi, Thanks for the guidance.
We have encountered two problems in the implementation process and I would greatly appreciate it if you would help us with the same :
1. How to get the standard columns list from maintable?
2. How to create one standard column and refresh the header after the creation?

**Comment by calixtus** [comment]
A standard column list can be made up, yet we only have the default values in JabRefPreferences. But these are probably only too few.
For creating columns and refreshing the table see the class TableTab in preferences/table package and JabRefFram::setUpAllTables for details.

**Comment by koppor** [comment]
Closing this PR due to inactivity :zzz: 

Please comment on the PR if you intend to continue to work on the PR.

**Pull request closed without merging**
