### PR TITLE
Fix style of highlighted checkboxes while searching in preferences

### LINKED ISSUE #7226: Style of checkboxes while searching in preferences
JabRef 5.2--2020-12-22--d83ef74
Mac OS X 10.15.7 x86_64 
Java 15.0.1

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

When searching for an option in JabRef preferences, the checkbox has incorrect styling. The "unchecked" behaviour, while distinct from the "checked", is confusing since it still has a checkmark in it. This is a visual bug, the behaviour is still correct.

1. Open Preferences
2. Search for an option that uses checkbox (e.g. autosave)
3. Observe a checkbox highlighted in red, check/uncheck it

**Highlighted unchecked box**
Highlighted unchecked box
**Highlighted checked box**
Highlighted checked box

### PR DESCRIPTION
**Pull request by faeludire**
What:
- Fix style of checkboxes while searching in preferences

Why:
- The "unchecked" behaviour, while distinct from the "checked", is confusing since it still has a checkmark in it. This is a visual bug, the behaviour is still correct.

Fixes #7226 

Screenshot 2020-12-28 at 12 24 14

- [x] Change in CHANGELOG.md described (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

**Review by calixtus — APPROVED** [review]
Looks good to me.

**Review by Siedlerchr — APPROVED** [review]

**Comment by Siedlerchr** [comment]
Thanks for the fix! Can you please test if this works also in the Dark Theme?

**Comment by faeludire** [comment]
> Thanks for the fix! Can you please test if this works also in the Dark Theme?

Works fine in Dark mode as well. 

Screenshot 2020-12-28 at 14 13 56

**Comment by Siedlerchr** [comment]
Thanks again for the fix!

**Pull request merged**
