### PR TITLE
Default ID type in the ID-based entry generator

### PR DESCRIPTION
**Pull request by cerrisantos**
I have added a new preference that stores that last used id fetcher.

### CODE REVIEW

**Comment by cerrisantos** [comment]
Fix for #2796

**Comment by Siedlerchr** [comment]
Thanks for your contribution, codewise looks good. Please have a look at the checkstyle issues (just click on the failing Travis test to see details)

**Comment by cerrisantos** [comment]
I am confused about why the test is failing. I don't I think I have touched any of that functionality.

**Comment by tobiasdiez** [comment]
Yes, the test is completely unrelated to this PR. I'll merge now. Thanks again for your contribution.

**Comment by koppor** [comment]
@cerrisantos Thank you for your contribution. We would be happy to see more contributions from your side. We use the label good-first-issue, where more issues will be tagged. You can also have a look at https://github.com/koppor/jabref/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22. Or hop by at my office in V38 in Stuttgart. 😇

**Pull request merged**
