### PR TITLE
Fix missing external changes resolver dialog scrollbar 

### PR DESCRIPTION
**Pull request by alexandre-cremieux**
Closes [issue 1120](https://github.com/JabRef/jabref/issues/11220)

See screenshots bellow.

And refactor some code from the **org.jabref.gui.collab** package:

- Make the anchor pane offset configuration common for all subclasses of  **org.jabref.gui.collab.DatabaseChangeDetailsView**
- Replace the pattern mathing for if statement by a pattern matching for switch statement in **org.jabref.gui.collab.DatabaseChangeDetailsViewFactory** and remove the related TODO

Please read commits one by one to make PR easier to understand.

### Mandatory checks

- [X] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [X] Manually tested changed features in running JabRef (always required)
- [X] Screenshots added in PR description (for UI changes)
- [X] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [X] [Checked documentation](https://docs.jabref.org/): Is the iorg.jabref.gui.collab.DatabaseChangeDetailsViewFactorynformation available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

scrollable-metada-changes-review
boxed-group-tree-modification-message

### CODE REVIEW

**Comment by Siedlerchr** [comment]
Tested it, looks good. Please have a look at the checkstyle error

**Comment by alexandre-cremieux** [comment]
Hello @Siedlerchr ,

Thanks for the test. I corrected the checkstyle error.

**Review by Siedlerchr — DISMISSED** [review]

**Comment by Siedlerchr** [comment]
I just saw the open rewrite error, can you execute ./gradlew rewriteRun  and commit your changes?

**Comment by alexandre-cremieux** [comment]
@Siedlerchr done.

I didn't know that tool. Very interesting, especially for contributions. The lossless semantic tree seems to be a powerful model. Have you seen interesting improvements in the code base since you started to use it ?

**Comment by Siedlerchr** [comment]
It's great for doing migrations or automatic refactoring e.g with more modern Java methods 
Does not always work 100%, we had some quirks where it did not work but we reported the bugs and they got fixed. 
It depends a bit on the recipes

**Review by Siedlerchr — APPROVED** [review]

**Comment by alexandre-cremieux** [comment]
Going to take a look. For now, it seems quite fresh but I like the approach. At least, automatic migrations can save days of development time, not saying it is a low value added work.

Thanks. Will look soon for another contribution to JabRef.

**Comment by koppor** [comment]
@alexandre-cremieux There is a whole company doing business with this rewrite. See https://docs.openrewrite.org/ for more information. -- Looking forward to more contributions!

**Pull request merged**
