### PR TITLE
Use JUnit5 conditions to disable some tests on CI server

### PR DESCRIPTION
**Pull request by tobiasdiez**
Instead of assumptions, we can now disable tests on the CI server using a new `@DisabledOnCIServer` annotation. I converted the fetcher tests affected to junit 5.
Moreover, I extracted some common tests (null / empty) to a new parametrized fulltextfetcher class.

----

- [ ] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [ ] Screenshots added (for bigger UI changes)
- [ ] Manually tested changed features in running JabRef
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)
- [ ] If you changed the localization: Did you run `gradle localizationUpdate`?

### CODE REVIEW

**Comment by tobiasdiez** [comment]
Good question! IntelliJ warned about it and this is why I changed it. If you look that the examples from the JUnit team, they also always use the default visibility (e.g. [here](http://junit.org/junit5/docs/current/user-guide/#writing-tests-standard)). 
With junit 4 all tests had to be public and this restriction was removed in the new version.

I have no strong opinion about this.

**Comment by lenhard** [comment]
In that case, I'd say we go for default visibility in all JUnit5 tests, regardless of whether they're new or migrated from a JUnit4 tests.

**Comment by tobiasdiez** [comment]
Ok, I now used the default visibility everywhere.

**Comment by Siedlerchr** [comment]
Default Visibility is normally considered an anti pattern and is marked by coday:
DefaultPackage

Since: PMD 3.4

Use explicit scoping instead of the default package private level.

**Pull request merged**
