### PR TITLE
Fixed columns shrink in width when enlarging the JabRef window

### LINKED ISSUE #6818: When enlarging JabRef window, columns shrink in width
JabRef 5.1--2020-08-30--e023aa0
Linux 5.4.0-42-generic amd64 
Java 14.0.2

1. Resizing JabRef window works fine on opening, scaling column width with window size.
2. Have more than 2 files/tabs open.
3. Change the width of a column (e.g., Year).
4. **Enlarge** the JabRef window width.
5. JabRef responsively **shrinks** all the columns, except the rightmost (as if you were reducing window width).

### PR DESCRIPTION
**Pull request by yinpeiqi**
In method 'resize', in order to make sure that we are staying under the total table width, the program used to reduce the newSize by two for every column. Cause the method will be call for many times, that will occur the problem which shown in the video in issue 6818. I do a little bit modify for this implement of controlling width, which is reduce the width only if the current width exceed the total width and only reduce for the surplus part.
Fixes #6818 

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

Before:

https://user-images.githubusercontent.com/60515999/110437190-12273d80-80f0-11eb-966c-4797901d20a9.mp4

After:

https://user-images.githubusercontent.com/60515999/110437211-19e6e200-80f0-11eb-830e-922142c4a7f3.mp4

### CODE REVIEW

**Review by tobiasdiez — APPROVED** [review]
Very nice that you found this mistake. It was hunting us for a very long time now.

There is a proposal to completely rewrite the resize policy in https://github.com/JabRef/jabref/pull/7181. But since this still needs some work until this is finished, I propose to merge this PR nonetheless. Maybe this makes #7181 actually obsolete - I'll let @koppor  and @DominikVoigt decide this.

**Comment by yinpeiqi** [comment]
@tobiasdiez Thanks for your acknowledgment

**Comment by koppor** [comment]
@tobiasdiez No, it does not make it obsolete. Even though, I am for +1 for this quick fix.

**Review by calixtus — APPROVED** [review]
Thanks for this fix. I should work with the current implementation of the SmartConstrainedResizePolicy and I'm going to merge it (after two approvals).
However, it's no substitute for the long term solution @koppor and @DominikVoigt proposed, because this PR still depends on reflection. So please don't be too sad, if sooner or later this SmartConstrainedResizePolicy will be removed.

**Pull request merged**
