### PR TITLE
Clean-up of StringUtil and some added tests

### PR DESCRIPTION
**Pull request by oscargus**
Replaced/removed/unified some methods in StringUtil and added some tests in StringUtilTest.

### CODE REVIEW

**Comment by simonharrer** [comment]
Can you please rebase on current master so that I can merge this in?

**Comment by simonharrer** [comment]
I will merge this in. But you missed a few tests as the code coverage shows for the StringUtil class.

**Comment by oscargus** [comment]
Yes, but they will show later (I moved the tests twice in different PRs...).

**Comment by oscargus** [comment]
The missing test (makeBibtexExtension) is because I removed that function and made use of getCorrectFileName instead (where ever that change is...).

**Comment by oscargus** [comment]
Oh, yeah. You mean that it is not fully tested? Correct! I only added tests for those methods I played with (and I don't know how to get that coverage information without pushing and creating a PR...).

**Comment by koppor** [comment]
[EclEmma](http://eclemma.org/) seems to be the tool of choice for code coverage.

**Pull request merged**
