### PR TITLE
Convert the Swing Dialog to JavaFX

### PR DESCRIPTION
**Pull request by 1160300311**
----

- [ ] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [ ] Manually tested changed features in running JabRef
- [ ] Screenshots added in PR description (for bigger UI changes)
- [ ] Ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)

### CODE REVIEW

**Comment by 1160300311** [comment]
We convert part of the swing dialog to javafx. The dialog we are trying to change is Options->Preferences.

**Comment by tobiasdiez** [comment]
Oh wow, with the preferences you actually took the most complex of all dialogs ;-). From what I can see, you already made good progress. Nice! 
I would suggest you try to merge with the current master so that some of the code changes in master are no longer shown as differences and then I'll have a look and give you feedback.

**Comment by Siedlerchr** [comment]
In addition to what Tobias says, in future please create a new branch for a feature or issue to work on and to commit to. This make it easier for you and us to review the changes.

**Comment by tobiasdiez** [comment]
What's the relation of this PR with https://github.com/JabRef/jabref/pull/4253?

**Comment by 1160300311** [comment]
They are the same. I just created a new branch, and pushed my changes to the branch. I will close this PR at once. @tobiasdiez

**Pull request closed without merging**
