### PR TITLE
Fix latex2unicode and unicode2latex

### LINKED ISSUE #5547: LaTeX to Unicode and vice versa has stopped working
JabRef 5.0.0-dev--2019-10-29----3b6c355ae
Linux 5.0.0-32-generic amd64 
Java 12.0.2

- [X ] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. In editor, right click when in a text field.
2. unicode <-> LaTeX conversion doesn't work at all or not properly.

This is a regression: it was working properly in recent versions of 5beta.

### PR DESCRIPTION
**Pull request by koppor**
Begin to fix https://github.com/JabRef/jabref/issues/5547

Together with @calixtus 

Still work in progess. Early draft - just to save our work if my machine crashes.

- [ ] Change in CHANGELOG.md described (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for bigger UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not: Issue created at <https://github.com/JabRef/user-documentation/issues>.

### CODE REVIEW

**Review by tobiasdiez — COMMENTED** [review]
Uiii, replacing the latex2unicode library may turn out to be a big project (especially to get the more advanced parsing to work). Anyway, please also add the test from https://github.com/tomtung/latex2unicode/blob/master/src/test/scala/com/github/tomtung/latex2unicode/Latex2UnicodeTest.scala as our tests are not as extensive.

**Comment by Siedlerchr** [comment]
Why not port the Scala stuff to plain Java?

**Comment by koppor** [comment]
This is a very early PR and we are in the middle of discussing. We did not finish it. We (especially me) thought, it would be a good idea to push the changes here in the case of data loss.

We are currently in the process of understanding @oscargus's code. We aim for latex -> unicode and unicode -> latex working. They do not cover the same set of functionality. In the case of plain symbols, the unicode -> latex converter seems to cover more.

We really look into the latex2unicode code, but had not the time to port everything. We're just at the beginning.

Sorry for not explaining in the description. The time was up and I wanted to persist the work we achieved so far.

**Comment by koppor** [comment]
For the ADR:

- Why not latextounicode (or why latextounicode)
- Roundtrip should work
- latex2unicode has a parser
- what about biber? --> works directly with latex
- maintable can embed a variant of html or something like that --> https://docs.oracle.com/javase/8/javafx/api/javafx/scene/text/TextFlow.html

**Comment by calixtus** [comment]
Since this PR was not moving forward and we didn't ha a good idea yet how to move on, were closing this for now.

**Comment by koppor** [comment]
This could maybe solve https://github.com/JabRef/jabref/issues/7291.

**Comment by koppor** [comment]
Tests should also include https://github.com/JabRef/jabref/issues/2500#issuecomment-276589778

**Comment by koppor** [comment]
This could have fixed #3644.

**Comment by calixtus** [comment]
Possible solution strategy: create a simple parser for simple latex text formatting and use a hashmap (sadly we were not able to see a clear systematic in the unicode char tables)

**Comment by koppor** [comment]
Missing `\mkbibquote{}`, `\enquote{}`, `\mkbibemph{}`, and `\emph{}`. See https://discourse.jabref.org/t/recognize-quotation-commands/3296/3 for a discussion.

**Comment by calixtus** [comment]
https://github.com/koppor/jabref/issues/354

https://github.com/plk/biber/blob/dev/lib/Biber/LaTeX/recode_data.xml

**Comment by koppor** [comment]
See also https://tex.stackexchange.com/a/9793/9075

**Comment by koppor** [comment]
Related work: https://www.ctan.org/pkg/texaccents

**Comment by koppor** [comment]
- [ ] Maybe readd https://github.com/JabRef/jabref/pull/9427/files#diff-8649f9004139f540ebcd8e96f03f979adc4c67bcfe447f7f841b4ba478442411

**Comment by koppor** [comment]
- [ ] Should support `$\backslash$`. See https://discourse.jabref.org/t/mendeley-bib-import-with-linked-files/3470/5 and https://github.com/JabRef/jabref/pull/9906

**Comment by koppor** [comment]
Readings on Unicode https://tonsky.me/blog/unicode/ (via @Siedlerchr)

**Comment by koppor** [comment]
Related work: https://github.com/zepinglee/citeproc-lua/blob/ab3ce712cc92073f12be26ff0b22b30eb906092d/citeproc/citeproc-latex-data.lua#L517

**Comment by koppor** [comment]
Main reason of this PR:

image

**Pull request closed without merging**
