### PR TITLE
Fix failing test on windows due to line ending

### PR DESCRIPTION
**Pull request by tobiasdiez**
Some test were failing in RisMonthTest since they expected a string in LF but got something with CRLF

### CODE REVIEW

**Comment by koppor** [comment]
LGTM :+1:. As usual, I would love to see only one commit. You know the usual `git reset upstream/master` stuff?

**Comment by oscargus** [comment]
Ahh, thanks! I usually develop on Windows but now I used a Linux machine...

**Comment by tobiasdiez** [comment]
@koppor it was one commit and then I tried to use the github for desktop application to create a pull-request. This added for some reason the second commit. I will go back to the command line....

**Comment by simonharrer** [comment]
Please rebase on master as one commit, so it can be merged.

**Comment by tobiasdiez** [comment]
It is already fixed in your PR #715.

**Pull request closed without merging**
