### PR TITLE
Fixed wrong data display

### LINKED ISSUE #6388: Brackets added to surname display after slash
JabRef version  on 
JabRef 5.1--2020-05-01--a123eb1
Linux 5.3.0-51-generic amd64 
Java 14.0.1

- [x ] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Open editor
2. If the author's surname is preceded by a slash, it get curly brackets round it in the table display.  This is odd behaviour and probably a small bug.

image

### PR DESCRIPTION
**Pull request by Gena928**
Fixes #6388 

Description will be a bit later )))

- [X] Change in CHANGELOG.md described (if applicable)
- [ ] Tests created for changes (if applicable)
- [X] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by Siedlerchr** [comment]
You seem to only have commited the changelog entry...

**Comment by Gena928** [comment]
Sorry, 
I thought I can put draft commit as my intension to do the issue. And a bit later do the work. No?

**Comment by Siedlerchr** [comment]
Okay. go ahead. I thought you already had a fix or some code. Otehrwise it's fine if you just put a comment under the issue

**Comment by Gena928** [comment]
OK, next time I'll put a line of code in the issue.

**Pull request closed without merging**
