### PR TITLE
Adding text formatting for hits

### LINKED ISSUE #8797: Groups only show 4 digit number of entries
### JabRef version

Other (please describe below)

### Operating system

GNU / Linux

### Details on version and operating system

JabRef 5.7--2022-05-15--a90ee23 Linux 5.17.6-300.fc36.x86_64 amd64  Java 18.0.1  JavaFX 18+12

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

open a library with more than 9999 entries; the first digit is not shown on my system.

### Appendix

Screenshot from 2022-05-15 15-56-15

### PR DESCRIPTION
**Pull request by vigneshdurairaj**
```[tasklist]
### Compulsory checks
- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.
```

Fixes #8797

As first-time contributors, we would like to ensure that our submission adheres to the community guidelines. Consequently, we have submitted this Pull Request as part of our university project. Our team member, @sambhav97, has been assigned to the issue.

We believe that displaying numbers such as 1000 as 1k is a design choice. To provide a visual representation, we have included a screenshot displaying how the entries appear with this change. If there are any oversights or areas for improvement, please do not hesitate to inform us.

**When the entries are 1000**
Screenshot 2023-03-19 at 10 21 43 AM
**When the entries are 1500**
Screenshot 2023-03-19 at 10 22 03 AM
**When the entries are 100,000**
Screenshot 2023-03-19 at 10 22 35 AM

### CODE REVIEW

**Comment by Siedlerchr** [comment]
I like the idea,  just a question for the last screenshot? Does that mean 100,000 entries? or just 1000?
I would assume 100k= 100,000

**Comment by calixtus** [comment]
looks just like a typo to me, since he had 1000 entries = 1k in his first screenshot...

**Comment by calixtus** [comment]
grafik

**Comment by vigneshdurairaj** [comment]
It is a typo, it is suppose to be 100,000

**Comment by vigneshdurairaj** [comment]
> I like the idea, just a question for the last screenshot? Does that mean 100,000 entries? or just 1000?
> I would assume 100k= 100,000

Yes it is 100,000. Changed the description now accordingly.

**Comment by Siedlerchr** [comment]
I tested it, it's a nice idea.  However, it does not resolve the original issue:
Set font size to 14 in Appearance.

There is still something not right with the padding regarding the font size. You might need to check with https://github.com/JonathanGiles/scenic-view to see what's going on. 

grafik

**Comment by calixtus** [comment]
About the size of the controls, labels and stuff: Controls should be sized in relation to the base font size of the main application window. See the documentation on jfx css measure units: [docs.oracle.com/javafx/2/api/javafx/scene/doc-files/cssref.html#typelength](https://docs.oracle.com/javafx/2/api/javafx/scene/doc-files/cssref.html#typelength)

**Comment by vigneshdurairaj** [comment]
We analyzed the code, and wanted to look into padding at first. The padding in css accommodates the arrow and the icon. Since, the text formatting was applied, we were able to see where the UI breaks and able to accomdate the fonts at that points. We changed the fonts from % to em. and applied logic in java to reduce the font size 0.20 em after the font size reaches 17 on every steps of 4. 

**With font size  default**
default
**With font size  14**
size_14
**With font size  18**
size_17
**With font size  22**
size_21
**With font size  >  26**
size_22

**Comment by Siedlerchr** [comment]
Yeah! Really great work, tested it, works fine! Thanks for digging into this :) 
Codewise looks also good to me. 
Please add a changelog entry, then you can set it to ready for review.

**Review by calixtus — APPROVED** [review]
😍 
Took the liberty tho shorten the changelog a bit.

**Pull request merged**
