### PR TITLE
Add Hint for checking master version

### PR DESCRIPTION
**Pull request by Siedlerchr**
I added a tasklist checkbox with the hint to verify the problem with the latest master

- [ ] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [ ] Screenshots added (for bigger UI changes)
- [ ] Manually tested changed features in running JabRef
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)
- [ ] If you changed the localization: Did you run `gradle localizationUpdate`?

### CODE REVIEW

**Comment by halirutan** [comment]
Good idea. We have too many issue reports that still use 4.0 and report things that are already fixed. I think at the current pace of changes that are made, working towards a big 4.1 release is not the best course of action. We have reworked so many things. Shouldn't we push an update soon?

**Comment by LinusDietz** [comment]
Actually, I'm against this.
The underlying problem is, that we have introduced too many bugs in our major releases lately which were, of course, reported quite often.

As @halirutan said, we should release more often and the problem should go away again.

**Comment by Siedlerchr** [comment]
Even when the release is stable, the dev Version could already contain a bug fix for an issue present in release. Therefore it makes sense to check the latest dev before

**Comment by halirutan** [comment]
I'm definitely in favor of this as well. It is a good thing to ask users "hey, have you checked our latest dev release?" Especially, since some of them might not even be aware of that there is an active develop-version that they can try.

**Pull request merged**
