### PR TITLE
Change DOI importer to use application/x-bibtex

### PR DESCRIPTION
**Pull request by sheffien**
Changes the CrossRef content negotiation method to yield more complete bibtex entries. This fixes an issue with DOI import from papers with many authors, which previously yielded truncated results.

### CODE REVIEW

**Comment by sheffien** [comment]
Please see [CrossRef content negotiation documentation](http://crosscite.org/cn/) for information about why I propose this change

**Comment by koppor** [comment]
Thank you for the update. Could you also adapt the CHANGELOG and the About.html as described at https://github.com/JabRef/jabref/blob/master/CONTRIBUTING.md?

**Comment by sheffien** [comment]
I can -- but it was just a single line change so I wasn't sure it was worth adding myself as a contributor, or updating the CHANGELOG. Do you still want those updates for such a simple change?

**Comment by koppor** [comment]
Yeah, sure.

**Comment by sheffien** [comment]
Done.

**Pull request merged**
