### PR TITLE
Refactor different Entry types

### PR DESCRIPTION
**Pull request by stefan-kolb**
e.g. IEEETRANBSTCTL belongs to IEEE types not standard BibTeX types

### CODE REVIEW

**Comment by stefan-kolb** [comment]
@tobiasdiez Sorry if we break anything, but we cannot go on if we dont merge now...

**Comment by tobiasdiez** [comment]
Sure, go ahead. I didn't find the time to properly work on the entry type stuff so all my changes in this direction where a bit half hearted. Good to see further progress!

The changes look mostly good to me. The only thing I don't really like is the duplication of biblatex and bibtex entry types. My reasoning was that for the parser there is no way to decide whether an "article" is bibtex or biblatex. Thus, there should be an interim generic type (which was the StandardEntryType). Only later one can decide on the specific nature with more information (ie the type definitions - a name which I really like by the way). But I only glanced at the code changes, so I probably missed the reason for the change. You have more eyes that look at the code, so just merge. I trust you guys 😀

**Comment by stefan-kolb** [comment]
Hm, we could only extract the IEEETypes then. Actually, this was the intial reason for our refactoring. And merge the Bibtex/Biblatex types again if this makes no difference in any other code fragments...

**Comment by tobiasdiez** [comment]
That should work. What's actually the reason to treat the ieee stuff separately? Maybe one can use an approach via IeeeTypeDefinition, ie only differentiate later. (Some strange user might actually define a custom type which by accident has the same name as the ieee one - this might or might not lead to some confusion in the code).

**Comment by stefan-kolb** [comment]
Uhm, we saw that we had the IEEEControl type included inside the standard Bibtex types. Also, the IEEE types are only usable when relying on the IEEETran.bst file so it's a pretty special use case, I guess.

**Comment by tobiasdiez** [comment]
Sounds reasonable!

**Pull request merged**
