### PR TITLE
Don't abort build when there are checkstyle violations

### PR DESCRIPTION
**Pull request by lynyus**
Upon wish of @lenhard, nothing more to say here

### CODE REVIEW

**Comment by koppor** [comment]
Why?

This improves our code quality. If not the author, who else will clean up the code?

Which checkstyle rules are annoying?

We all know  (do we?) that JabRef's code was (and still is) a mess (at some places). I strongly believe that checkstyle rules are one solution to the problem.

**Comment by koppor** [comment]
I give it a go. If the active developers don't see any value in checkstyle checks, I give it a go.

Refs https://github.com/JabRef/jabref/issues/2996

**Comment by Siedlerchr** [comment]
Well, also I think checkstyle warnings are annoying, they necessary. And it's not much work when you just have to press ctrl+f in eclipse to do it.
The only thing I am not happy about is that sort order of declarations. That could create problems when initializing fields.

**Comment by lynyus** [comment]
Hey @koppor, the intention is not to abolish checkstyle, but to improve the coding experience.

When working on a PR, the most important thing are the unit tests to pass. When executing gradle check it takes 59 secs to only compile the java code and run the checkstyle tests. If there is ANY problem because I didn't hit the code formatter the build will abort at this point. That's why suggested to make them optional. Of course they should be adhered.

In an ideal case they SHOULD fail on travis, but not locally. Does anybody know if that's possible in an elegant way?

**Comment by lenhard** [comment]
If I recall the discussion correctly, then we agreed on the following: This build should execute even if their are checkstyle warnings (so that you get feedback on the tests), but it should still fail. Is this what this PR achieves?

I hate checkstyle and complain all the time, but I concede that the rules improve code quality.

**Pull request merged**
