### PR TITLE
Unified translations strings

### PR DESCRIPTION
**Pull request by oscargus**
Removed:
 * 10 translations strings where a very similar one was already available
 * 3 unused keybindnings
 * 14 names which cannot be translated

### CODE REVIEW

**Comment by oscargus** [comment]
Fixes #989

**Comment by Siedlerchr** [comment]
Good work. When this is done I will add the missing German strings.

**Comment by matthiasgeiger** [comment]
@Siedlerchr You should wait with translating as a) we'll discuss #1013 and 920 today in a DevCall which is highly affecting the l10n files as there will be a whole bunch of new/changed translations and b) we should ask our longstanding German translator @domwass if he has time to translate. (As I learned that he's more experienced than me producing better and more consistent translations :wink:)

**Comment by domwass** [comment]
Regarding my time: there is none left at the moment (I’m writing a book which is due in two weeks). So go ahead, I will look into it as soon as I will have some time left.

**Comment by matthiasgeiger** [comment]
Thanks for the feedback! And good luck with your book!

**Pull request merged**
