### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by Siedlerchr**
Enjoy!

### CODE REVIEW

**Comment by tobiasdiez** [comment]
Is it possible to set the synchronization schedule to once per week? I think this should be more than sufficient.

**Comment by Siedlerchr** [comment]
I can only pause the integration as we normally do. I think there aren't any other options. Otherwise it gets synced whenever someone translates stuff

**Comment by tobiasdiez** [comment]
There should be: https://support.crowdin.com/github-integration/#synchronization-schedule

**Comment by Siedlerchr** [comment]
Ah thanks for the hint. Will change it tomorrow

**Pull request merged**
