### PR TITLE
Backported bug fix in #193

### PR DESCRIPTION
**Pull request by oscargus**
Fixed a small bug that sometimes stalled the fetching.

### CODE REVIEW

**Comment by oscargus** [comment]
Made a quick fix directly in GitHub (same bug fix as in master, but there some other things were changed as well, such as logging). Apparently a conflict in the CHANGELOG was caused by not having an up to date version of the branch...

**Comment by oscargus** [comment]
Tried to make a "manual merge" but apparently not a good idea...

**Comment by simonharrer** [comment]
If you like I can help you with the merge through a screen sharing session via skype. Just write me your skype name to simon.harrer@gmail.com

**Comment by oscargus** [comment]
Thanks @simonharrer ! I'll make an effort over the weekend to use the "correct" local computer approach and provide a new PR. If I can't solve it, you'll hear from me.

**Comment by oscargus** [comment]
I sort of messed up my local copy of this branch (didn't really get that to work properly to start with, plus that I do not have the build system set up).

However, it would be much appreciated if someone could add the bug fix to the final 2.11 (noticed that beta 5 was just released), as this bug too often stalls the search. There are some more fixes in the master branch, but this is the most crucial one.

**Comment by simonharrer** [comment]
I backported this to the dev_2.11 by hand.

**Comment by oscargus** [comment]
Thanks! I appreciate it.

**Pull request closed without merging**
