### PR TITLE
Fix jakarta annotation missing

### PR DESCRIPTION
**Pull request by Siedlerchr**
- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by calixtus** [comment]
grafik

**Comment by Siedlerchr** [comment]
It works now. The deps are only cached here. So the latest snapshot is not getting pulled

**Comment by Siedlerchr** [comment]
Tested it locally with jpackage and it works. We need to have a proper release of the afterburner stuff soon 
Currently we are only using jitpack snapshot https://github.com/JabRef/afterburner.fx/pull/5

**Review by calixtus — APPROVED** [review]
lgtm

**Review by koppor — COMMENTED** [review]
We can then delete https://github.com/JabRef/jabref/blob/main/lib/afterburner.fx.jar, can't we?

**Comment by Siedlerchr** [comment]
> We can then delete https://github.com/JabRef/jabref/blob/main/lib/afterburner.fx.jar, can't we?

That should already bee part of this pr

**Pull request merged**
