### PR TITLE
Fixed saving radio button choice under specified keywords

### LINKED ISSUE #10248: group properties (specified keywords) not saving radiobutton choice
### JabRef version

5.9 (latest release)

### Operating system

Windows

### Details on version and operating system

Windows 10 22H2

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Create new group, by specified keywords
2. Choose 1 of the 2 radiobuttons and enter a value in the textbox
3. Click "OK"
4. Go back the to group's properties and see that the radiobutton selected was not saved (the textbox content is saved according to which radiobutton you have chosen)

afbeelding

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

### PR DESCRIPTION
**Pull request by DohaRamadan**
Fixed that checked-out radio buttons under specified keywords were not displayed as checked after closing and reopening the edit group window
Fixes #10248 

before: 
before2

after:
after2

### Mandatory checks
- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by ThiloteE** [comment]
wow, you are fast! Awesome :D

**Comment by the-dino-girl** [comment]
Thanks so much!!!

**Comment by HoussemNasri** [comment]
Thanks for the contribution! I tested the changes locally and couldn't replicate the bug anymore.

However, one thing that still bugs me, is when you select the "Specified keywords" option while creating a new group, none of the generation options are selected. That doesn't seem right...

@DohaRamadan do you think you can get it fixed? Maybe by selecting the first option as a default. 

image

**Review by HoussemNasri — APPROVED** [review]
LGTM! Just the minor issue described above. Can be handled in a later pull request if it's too much trouble.

**Comment by DohaRamadan** [comment]
Sure, i will do it no problem. 
Should i add it to this pull request or to a new one?

**Comment by HoussemNasri** [comment]
It's relevant to the pull request purpose, so I would put it here, but if it's gonna take time, you can always create a follow up PR.

**Comment by calixtus** [comment]
Should be a followup PR. Since we want to release tonight, I would like to ask you to create a new issue from your comment and we merge this one now.

**Comment by HoussemNasri** [comment]
@DohaRamadan Please comment on https://github.com/JabRef/jabref/issues/10269 so I can assign you.

**Pull request merged**
