### PR TITLE
Fix libre office connection and other progress dialogs

### LINKED ISSUE #6477: Libreoffice connection broken in 5.1
JabRef version 5.1--2020-05-13--98b62ba on Ubuntu 18.04.4 Linux 4.15.0-99-generic amd64 (Java 14.0.1)

- [X] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

I installed the latest dev version because it fixed another bug I was having (see https://discourse.jabref.org/t/scrolling-by-typing-a-name-does-not-work-in-5-x/1989). This bug is fixed but I noticed I cannot connect to LibreOffice anymore, while it was working just fine with my previous version (5.0–2020-03-06–2e6f433). 

1. Open a LibreOffice document, and the LibreOffice/OpenOffice connection panel in JabRef.
2. Click "connect" (clicking on "manual connect" gives the same thing, and the path is correct).
3. While the connection was almost immediate on the previous version, now it gets stuck on a window "Autodetecting paths..." until I hit cancel. I have not managed to get a libreoffice connection working.

<details>
  <summary>Log File</summary>
  
  ```
(log file was empty)
  ```
</details>

### PR DESCRIPTION
**Pull request by Siedlerchr**
Fixes #6477

Error was introduced in #6443 with the ProgressDialog showAndWait 
I had to revert that. @btut 
The showAndWait broke all dialogs which used the dialog.  (E.g). also copy linked files)

- [ ] Change in CHANGELOG.md described (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by btut** [comment]
Uh I forgot to roll that back. The ProgressDialog is not actually used by the background-task functionality because I could not get it to work.
I think it would be better to change the name of the method to showProgressDialog. The old name, showProgressDialogAndWait, suggests that the dialog is waited for.

**Comment by Siedlerchr** [comment]
Indeed, good idea. I renamed it now

**Comment by calixtus** [comment]
Do I get that right, that most of the progress dialogs can probably be converted to be displayed in the new progress popup?

**Comment by btut** [comment]
I don't know which other features use the progress dialogue.
I had three problems with the progress dialogue:

- It displays the progress of an actual task. I wanted to show a list of tasks
- It is not waited for
- There is no way to close it when the progress reached 100%

In the dialogue that I implemented as a solution for this, I used the list of tasks stored in StateManager. It would be easy to pass a list of tasks instead. Then we could add an option to the dialogue to only show and it could replace the other dialogues.

But as the original dialogue is not waited for, I guess it is only used as information to the user. How about registering the relevant task in the background-task list in StateManager? Then you could just pop up the new dialogue. You could even pop up the pop-over of the task-progress-indicator in the toolbar. This would be very similar to a show-only dialog (no wait). The user can hide it and check the status later by clicking on the progress-indicator again.

IMO this would be a good way to go. I think the new dialogue and pop-over are more informative as they show the actual progress of tasks if available. AFAICT from the code the old dialogue just showed an indeterminate progress bar.

**Comment by btut** [comment]
... I just checked and it is just the WaitForSaveFinished dialog that creates a task for this purpose. The other times the dialogue is shown it is shown with actual worker tasks, so progress should be shown.

**Comment by tobiasdiez** [comment]
I agree these progress dialogs can be replaced by using the new progress popup. None of them actually has a reason to block the UI and can safely be run in the background in my opinion.

**Comment by Siedlerchr** [comment]
The only critical application is indeed the connection to LibreOffie, but that could also be done in a background task because it's usually finished very fast. However, we have to be careful of tasks throwing exceptions. 
The copy linked files to folder displays a progress dialog and afterwards the result dialog.
Indeed it doesn't make sense to block the UI with a progress dialog here

**Pull request merged**
