### PR TITLE
Open office refactor finalization (formerly OObranch J cleanup)

### LINKED ISSUE #8540: Cannot generate bibliography in LO
### JabRef version

Latest development branch build (please note build date below)

### Operating system

macOS

### Details on version and operating system

mac os BigSur 
### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1.  Create a new empty LO Writer document
2. Write asdfasd 
3. Cite an entry
4. Exception is logged

Version is 
Version: 7.3.1.3 / LibreOffice Community
Build ID: a69ca51ded25f3eefd52d7bf9a5fad8c90b87951
CPU threads: 12; OS: Mac OS X 10.16; UI render: default; VCL: osx
Locale: de-DE (de_DE.UTF-8); UI: en-US
Calc: threaded

Debugging shows that it's looking for a section JR_BIB and tries to access it

```

2022-03-03 20:04:25 [JavaFX Application Thread] org.jabref.gui.openoffice.OpenOfficePanel.pushEntries()
WARN: Could not insert entry: com.sun.star.container.NoSuchElementException: 
	at org.libreoffice.uno/com.sun.star.lib.uno.environments.remote.Job.remoteUnoRequestRaisedException(Job.java:158)
	at org.libreoffice.uno/com.sun.star.lib.uno.environments.remote.Job.execute(Job.java:122)
	at org.libreoffice.uno/com.sun.star.lib.uno.environments.remote.JobQueue.enter(JobQueue.java:312)
	at org.libreoffice.uno/com.sun.star.lib.uno.environments.remote.JobQueue.enter(JobQueue.java:281)
	at org.libreoffice.uno/com.sun.star.lib.uno.environments.remote.JavaThreadPool.enter(JavaThreadPool.java:81)
	at org.libreoffice.uno/com.sun.star.lib.uno.bridges.java_remote.java_remote_bridge.sendRequest(java_remote_bridge.java:619)
	at org.libreoffice.uno/com.sun.star.lib.uno.bridges.java_remote.ProxyFactory$Handler.request(ProxyFactory.java:145)
	at org.libreoffice.uno/com.sun.star.lib.uno.bridges.java_remote.ProxyFactory$Handler.invoke(ProxyFactory.java:129)
	at jdk.proxy2/jdk.proxy2.$Proxy32.getByName(Unknown Source)
	at org.jabref/org.jabref.gui.openoffice.OOBibBase.clearBibTextSectionContent2(OOBibBase.java:1032)
	at org.jabref/org.jabref.gui.openoffice.OOBibBase.rebuildBibTextSection(OOBibBase.java:802)
	at org.jabref/org.jabref.gui.openoffice.OOBibBase.insertEntry(OOBibBase.java:370)
	at org.jabref/org.jabref.gui.openoffice.OpenOfficePanel.pushEntries(OpenOfficePanel.java:514)
	at org.jabref/org.jabref.gui.openoffice.OpenOfficePanel.lambda$5(OpenOfficePanel.java:188)
```

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

### PR DESCRIPTION
**Pull request by antalk2**
Cleanup unused stuff after integration. Adjust tests.

Fixes #8540  for me

### CODE REVIEW

**Comment by koppor** [comment]
This PR is the final PR for the OO improvement. I will collect some final checks for me here:

- [ ] User documentation updated? Screenshots, ...
- [ ] Is https://github.com/koppor/jabref/blob/69f7be4215bdbb21789a7946c08bc8a9db4c8719/docs/openoffice/ooresult-ooerror.md contained in `docs/openoffice`?
- [ ] Is https://github.com/koppor/jabref/blob/69f7be4215bdbb21789a7946c08bc8a9db4c8719/docs/openoffice/ooresult-alternatives.md contained in `docs/openoffice`?

**Comment by antalk2** [comment]
> This PR is the final PR for the OO improvement. I will collect some final checks for me here:
> 
>     * [ ]  User documentation updated? Screenshots, ...
> 
>     * [ ]  Is https://github.com/koppor/jabref/blob/69f7be4215bdbb21789a7946c08bc8a9db4c8719/docs/openoffice/ooresult-ooerror.md contained in `docs/openoffice`?
>     * [ ]  Is https://github.com/koppor/jabref/blob/69f7be4215bdbb21789a7946c08bc8a9db4c8719/docs/openoffice/ooresult-alternatives.md contained in `docs/openoffice`?

Now I copied them (docs/openoffice/*.md) into J.

1. After concluding that probably "[using PreconditionException, dialog in catch]" with OOError for PreconditionException
is better than what we have, started to move in that direction. 

2. Also reimplemented OOResult, which
  now can handle OOResult<Void,E> which sometimes allows more uniform handling and is used instead of OOVoidResult<E>

3. from OOError removed the title field 

These can be put aside, and need testing (they were made on a non-integrated branch). 
So maybe they should be somewhere after "J".

**Comment by antalk2** [comment]
I may have misunderstood/overinterpreted the above message being in oobranch-J.

* Should I copy them (docs/openoffice/*.md) to oobranch-C?
* Should I change something in oobranch-C? Maybe I forgot something and you are waiting for me to do it.

**Comment by Siedlerchr** [comment]
Hi, OObranch C looks good so far. 
We are planning a release of 5.3 soon and therefore we will wait with merging the c branch,

**Comment by antalk2** [comment]
Ok, thanks, then I leave it as is.

**Comment by calixtus** [comment]
As @tobiasdiez suggested, I did not do an in deep code review, but only made changes to code style an tested it on my windows machine a bit.
If bugs appear, they should be filed as issues and be fixed in follow-up prs.

**Comment by koppor** [comment]
@antalk2 Thank you so much for your contribution - and writing up documentation. I think, your text at https://github.com/JabRef/jabref/tree/main/docs/openoffice is a good start for new developers in case they want to work on this further (e.g., by adding CSL support; refs https://github.com/JabRef/jabref/issues/2146).

Your code will be part of the next release 🎉

**Comment by antalk2** [comment]
> @antalk2 Thank you so much for your contribution - and writing up documentation.

Thank you guys for taking over the integration.

Concerning https://github.com/JabRef/jabref/issues/7861 and https://github.com/JabRef/jabref/issues/7805 : I did not address these in the code, as far as I know they are not resolved.

https://github.com/JabRef/jabref/issues/7615 might work. It did at the time, but I was worried about the check taking too much time  (https://github.com/JabRef/jabref/issues/7615#issuecomment-850666391) and I am not sure if I turned it off (probably did not).

**Pull request merged**
