### PR TITLE
Update open OpenOfficePanel to show buttons in three rows of three.

### PR DESCRIPTION
**Pull request by ddunig2**
Changed open office panel to show buttons in rows of three instead of going straight down to save space as the button expanded out to take up unnecessary horizontal space.

### CODE REVIEW

**Comment by ddunig2** [comment]
I am not familiar with a change log entry, would you help me accomplish that please?

**Comment by tobiasdiez** [comment]
We have a `Changelog.md` file listing all the relevant changes. Just add a sentence there and commit these changes: https://github.com/JabRef/jabref/blob/master/CHANGELOG.md#changed

**Comment by ddunig2** [comment]
Should I create a pull request for that too or no?

**Comment by tobiasdiez** [comment]
You can make the changes locally and then push them to your branch `ddunig2:fix-for-issue-5479`, which updates this PR automatically. No separate PR is necessary.

**Comment by koppor** [comment]
@ddunig2 You can just work on your branch - a pull request collects all commits belonging to a branch. As soon as you pushed something, it will appear hear.

**Comment by tobiasdiez** [comment]
@ddunig2 Did you already had the chance to add the changelog entry? It would be nice if you could do this so that we can merge your first pull request to JabRef. Thanks!

**Comment by ddunig2** [comment]
I thought I did. I will double check.

**Comment by ddunig2** [comment]
I remember doing this, although I'm not sure if I did it correctly. I redid it and these are the steps I took this time. I went on my fork and went on the branch I did my work on. Looked for the changelog file and add the change to the ##change section. I hope this is the right approach.

**Comment by tobiasdiez** [comment]
Thanks! You did it perfectly and everything is well now, so I'm going to merge. Looking forward to your next contribution. 😄

**Pull request merged**
