### PR TITLE
Update citeproc dependency to 1.0.1

### PR DESCRIPTION
**Pull request by matthiasgeiger**
see https://github.com/michel-kraemer/citeproc-java/releases

### CODE REVIEW

**Comment by matthiasgeiger** [comment]
Test is failing: 
```
net.sf.jabref.logic.citationstyle.CitationStyleGeneratorTest > testCarriageReturn FAILED

    org.junit.ComparisonFailure: expected:<...ight-inline">J. Doe [and J. ]Doe, .</div>

      </div...> but was:<...ight-inline">J. Doe [John and]Doe, .</div>

      </div...>

        at org.junit.Assert.assertEquals(Assert.java:115)

        at org.junit.Assert.assertEquals(Assert.java:144)

        at net.sf.jabref.logic.citationstyle.CitationStyleGeneratorTest.testCarriageReturn(CitationStyleGeneratorTest.java:24)
```

As I'm not an expert for the CSL styles... is this an issue or just an irrelevant change? @bartsch-dev @koppor

**Comment by Siedlerchr** [comment]
We should update asap, because version 1.0.0 is no longer avaiable at jcenter/maven repo:
https://bintray.com/bintray/jcenter/de.undercouch%3Aciteproc-java

**Comment by koppor** [comment]
I have no clue. Just @Ignore

**Comment by bartsch-dev** [comment]
The new version just removes the carriage return (`\r`) which is bad as this possibly connects two lines.

**Comment by matthiasgeiger** [comment]
Thanks for the explanation. I already adapted the test to be no longer failing. 
Let's keep an eye on the discussion -  but I'll merge this anyway as currently all builds are failing due to a missing citeproc dependency.

**Comment by koppor** [comment]
Side note: Maven Central still offers version 1.0.0 - https://mvnrepository.com/artifact/de.undercouch/citeproc-java/1.0.0

I don't get, why it is removed on bintray (https://bintray.com/bintray/jcenter/de.undercouch%3Aciteproc-java)

@michel-kraemer Could you give us a hint why version 1.0.0 was removed on bintray?

**Comment by matthiasgeiger** [comment]
It was the '-SNAPSHOT' Version we used and which has been removed after the official 1.0.0 version

**Comment by michel-kraemer** [comment]
Hey guys. I see two problems here.

a) Version 1.0.0 is not available on Bintray. That's very strange. I only upload to Maven Central and Bintray should sync automatically. It must be a problem with Bintray actually, but if you like I can try to publish 1.0.0 to Bintray too.

b)`\r` is replaced by nothing and not a space. I'm sorry if this causes problems. It seems there are files out there containing only a `\r` without a `\n`? If you can confirm this in the other thread I can release a fix.

**Comment by michel-kraemer** [comment]
Regarding b): I fixed it here https://github.com/michel-kraemer/citeproc-java/commit/dc800d17d8bdab0817e5ef624843a40fb6d1a116

If you wish I can release 1.0.2 shortly.

**Comment by koppor** [comment]
Thank you for your feedback. I think, an update is not necessary: See https://github.com/JabRef/jabref/pull/2306

**Pull request merged**
