### PR TITLE
Add Checkstyle settings for newline after catch brace

### PR DESCRIPTION
**Pull request by subhramit**
Since this has been troubling for a while now...
IntelliJ:
image

This PR should test for github actions and reviewdog before merge.

### Mandatory checks

- [x] I own the copyright of the code submitted and I licence it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
- [ ] ~Change in `CHANGELOG.md` described in a way that is understandable for the average user (if change is visible to the user)~
- [ ] ~Tests created for changes (if applicable)~
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [x] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by subhramit** [comment]
> Your code currently does not meet [JabRef's code guidelines](https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace/intellij-13-code-style.html). We use [Checkstyle](https://checkstyle.sourceforge.io/) to identify issues. Please carefully follow [the setup guide for the codestyle](https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace/intellij-13-code-style.html). Afterwards, please [run checkstyle locally](https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace/intellij-13-code-style.html#run-checkstyle) and fix the issues.

Ah, perfect.

**Comment by Siedlerchr** [comment]
Seems to work, but would be even better if we could get this fixed in IJ

**Review by Siedlerchr — APPROVED** [review]

**Comment by subhramit** [comment]
> Seems to work, but would be even better if we could get this fixed in IJ

Do you mean the warning:
image

Or the auto-formatting that sometimes causes this?

**Comment by koppor** [comment]
> Or the auto-formatting that sometimes causes this?

Yes, the auto formatting. Takes some "minutes" to experiment / google / check intellij issues / report intellij issue / ...

**Comment by koppor** [comment]
For completeness, I would like to see a link to an stackoverflow question having this as question - and posting this as answer maybe?

**Comment by subhramit** [comment]
> For completeness, I would like to see a link to an stackoverflow question having this as question - and posting this as answer maybe?

Clarifying - 
This as a question - by "this" do you mean the issue framed as a question? Like "how to configure intellij not to add a newline after..."

This as answer - you mean the checkstyle properties in this PR as the answer?

**Review by calixtus — DISMISSED** [review]

**Comment by subhramit** [comment]
Fixed the violations in the rest of the codebase. Tests will be green now. Can do a final review and merge.

**Comment by koppor** [comment]
> > For completeness, I would like to see a link to an stackoverflow question having this as question - and posting this as answer maybe?
> 
> Clarifying - This as a question - by "this" do you mean the issue framed as a question? Like "how to configure intellij not to add a newline after..."


Question: Title: "How can checkstyle be configured to throw an error if a line break is after the opening brace"

Example:

I have

```java
try {
    // ...
} catch (
  Exception e) {
    // ...
}
```

Then you can also do "answer your own question". - Or wait for 48h if someone else answers

**Review by koppor — APPROVED** [review]

**Pull request merged**
