### PR TITLE
Grobid config panel without checkbox

### PR DESCRIPTION
**Pull request by hanachaari**
This fixes a koppor issue [#566](https://github.com/koppor/jabref/issues/566) related to Grobid preferences.The link: 
Fixes https://github.com/koppor/jabref/issues/566 .
I have changed Grobid preferences from a checkbox to a Radio-Button-Group (disable, enable, always ask). 

This is the new configuration panel
image
image
image

The dialog below appears as long as the user does not check "do not ask again" or change preferences .
image

Despite the decision as mentioned here https://github.com/koppor/jabref/issues/566#issuecomment-1370332527 was to remove the "do not ask checkbox", I think it is not recommended from a UX perspective. So, I provided two versions: the branch: "gorbidConfigPanel" without a checkbox and the branch"gorbidConfigPanelWithCheckBox" with a checkbox. 
The checkbox in the later branch is synchronized so when it is checked Grobid preferences will be "disabled" or "enabled" according to the user's answer(yes/no).

```[tasklist]
### Compulsory checks
- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [x] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.
```

### CODE REVIEW

**Comment by koppor** [comment]
The PR currently worked on is https://github.com/JabRef/jabref/pull/9801

**Comment by hanachaari** [comment]
I have continued working on this branch since it does not have the checkbox. I agree with Tobias' s comment https://github.com/JabRef/jabref/pull/9291#issuecomment-1309516155. So I have changed the behavior this way: 
Upon the first use no preference is selected 
image

With the first import this dialog is displayed 
image

Depending on the answer, set the preference to "enable" or "disabled".(yes in the case)
image

Thereafter, the user will not be asked again unless he resets preferences.

**Comment by koppor** [comment]
I double checked the casing of `Grobid`.

They say, "Grobid" is also OK. 

image

(Source: https://github.com/kermitt2/grobid#grobid-documentation)  Sorry for my wrong demand for "GROBID"

I noticed the inconsistency here:

image

**Comment by koppor** [comment]
Please address the comments by @calixtus from the PR https://github.com/JabRef/jabref/pull/9801#issuecomment-1527330492

After our discussions here, issue refinements, the task is different:

1. Keep preference appearance as is:

image

There is already the boolean setting.

2. Modify the logic when the dialog appears:

grafik

Instead of "Do not ask again", the dialog should only appear upon first start ever in JabRef. This should be recorded in the preferences. I think, we need a new preference key (internal storage) for that. In that way, no migration is necessary. (Adressing the comment https://github.com/JabRef/jabref/pull/9801#issuecomment-1524231761)

**Comment by hanachaari** [comment]
I am implementing the preferences in the tab directly now. However, I faced a problem when I was running the tests. Some tests(Tests/Unit tests) failed because I am working on Windows so paths are not recognized which caused the failure of the test.

**Comment by calixtus** [comment]
If you push your changes to GitHub, we can see your changes and maybe help. Please also merge the current main branch into your brach, since we just recently hat a major change in the preferences UI. The Importexport tab has been dissolved and it's content moved to other panels.

**Comment by calixtus** [comment]
Closing this PR due to inactivity :zzz: 
Please reopen a PR if you intend to continue on this issue.

**Pull request closed without merging**
