### PR TITLE
Native compile [GraalVM]

### PR DESCRIPTION
**Pull request by calixtus**
## Howto

- Run gradle task `nativeCompile`.

## TODOs

- [x] ArchitectureTest: Never use `.class.getResource` (because of https://github.com/oracle/graal/issues/7682#issuecomment-1786704111) (see https://github.com/JabRef/jabref/pull/11479/commits/cad404cd28759a61c8e77cb1b6dc9942c769de3b)

### Mandatory checks

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by calixtus** [comment]
image
image

**Comment by Siedlerchr** [comment]
Caused by: java.lang.module.InvalidModuleDescriptorException: Unsupported major.minor version 66.0

**Comment by koppor** [comment]
> Caused by: java.lang.module.InvalidModuleDescriptorException: Unsupported major.minor version 66.0

Uhoh. I went back to Java 21 in [`d39fb35` (#11298)](https://github.com/JabRef/jabref/pull/11298/commits/d39fb3563ac285b0a21cf25fd9614a5804ff1052), because I didn't know why Java 22 should be important at this point in time.

**Comment by koppor** [comment]
With Java 21, the image compiles fine, but cannot be started:

```bash
koppor@DESKTOP-KAK953S MINGW64 /c/git-repositories/jabref/build/native/nativeCompile (nativecompile)
$ ./JAbRef.exe
Messages are not initialized before accessing key: Display help on command line options
LOGGER ERROR: Service implementation 'org.tinylog.writers.ConsoleWriter' has no matching constructor
Exception in thread "main" java.lang.NullPointerException
        at org.jabref.logic.l10n.Localization.lookup(Localization.java:146)
        at org.jabref.logic.l10n.Localization.lang(Localization.java:58)
        at org.jabref.cli.JabRefCLI.getOptions(JabRefCLI.java:184)
        at org.jabref.cli.JabRefCLI.<init>(JabRefCLI.java:33)
        at org.jabref.Launcher.main(Launcher.java:59)
        at java.base@21.0.2/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
```

**Comment by koppor** [comment]
Current hint:

```groovy
// Source: https://github.com/tinylog-org/tinylog/issues/145#issuecomment-603430594
task generateConfiguration(type: Exec) {
    group = "graal"
    description = "Run application to generate the configuration for native image"
    dependsOn build
    commandLine project.gradle.gradleUserHomeDir.toPath().resolve("caches/com.palantir.graal/$graalVmVersion/graalvm-ce-$graalVmVersion/bin/java"), "-agentlib:native-image-agent=config-output-dir=" + project.buildDir.toPath().resolve("resources/main/META-INF/native-image"), "-cp", sourceSets.main.runtimeClasspath.getAsPath(), javaMainClass

    doFirst {
        mkdir project.buildDir.toPath().resolve("resources/main/META-INF/native-image")
    }
}
```

**Comment by calixtus** [comment]
> Current hint

Requires palantir graal plugin for gradle

**Comment by koppor** [comment]
> > Current hint
> 
> Requires palantir graal plugin for gradle
> 

I don't think so. The path starts with plantir, but the content seems to be the real GraalVM. Thus, the paths "just" need to ne adapted to recent GraalVM.

**Comment by koppor** [comment]
MWE project to try out a fix: https://github.com/shoneslab/graal-logging (referenced from https://github.com/tinylog-org/tinylog/issues/145#issuecomment-602885335)

**Comment by koppor** [comment]
This needs to be adressed: https://github.com/oracle/graal/issues/7682

**Comment by calixtus** [comment]
https://thenewstack.io/how-to-build-with-graalvm-inside-github-actions/

**Comment by koppor** [comment]
> https://thenewstack.io/how-to-build-with-graalvm-inside-github-actions/

Doesn't use Toolchain. Think, we already managed to compile using GraalVM, but have issues with our file access

**Comment by koppor** [comment]
Tinylog "official" "guide": https://github.com/tinylog-org/tinylog-graal-example

**Comment by koppor** [comment]
Current error:

```
Error: Error loading a referenced type: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported method jdk.internal.loader.NativeLibrary.findEntry0(long, String) is reachable
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Error encountered while parsing org.apache.lucene.store.PosixNativeAccess.lookupMadvise(PosixNativeAccess.java:87) 
Parsing context:
      141 types,   103 fields, and   138 methods registered for JNI access
        5 native libraries: crypt32, ncrypt, psapi, version, winhttp

------------------------------------------------------------------------------------------------------------------------
   at org.apache.lucene.store.PosixNativeAccess.<clinit>(PosixNativeAccess.java:67)
   at static root method.(Unknown Source)
```

**Comment by Siedlerchr** [comment]
Might be related https://github.com/oracle/graal/issues/673

**Comment by calixtus** [comment]
https://www.graalvm.org/22.0/reference-manual/native-image/JNI/

**Comment by koppor** [comment]
At https://github.com/JabRef/jabref/pull/11510, we even introduced more reflection.

Closing and re-opening at koppor, because it will take more time.

**Pull request closed without merging**
