### PR TITLE
Get notarization running on GitHub

### PR DESCRIPTION
**Pull request by koppor**
Fixes https://github.com/JabRef/jabref-issue-melting-pot/issues/24

Refs: https://docs.oracle.com/en/java/javase/20/jpackage/support-application-features.html#GUID-8D9F0607-91F4-4070-8823-02FCAB12238D

### Mandatory checks
- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by Siedlerchr** [comment]
To test the notarization workflow we need to create a tag

**Comment by Siedlerchr** [comment]
Notarization works now. just something with uploading/downloading to builds.jabref.org

**Comment by Siedlerchr** [comment]
Only piece missing is to copy the work flow parts now to the mac arm

**Comment by Siedlerchr** [comment]
https://github.com/JabRef/jabref/actions/runs/5400189417/jobs/9808895171?pr=10041
download artifact still goes with unsigned

**Comment by Siedlerchr** [comment]
Run actions/download-artifact@master
Starting download for JabRef-macOS-unsigned
Error: Unable to find an artifact with the name: JabRef-macOS-unsigned

**Comment by Siedlerchr** [comment]
for arm64 I think we should rename the files before uploading etc, I am not sure if we otherwise overwrite the existing ones

**Comment by koppor** [comment]
The patched macos AARM64 workflow (https://github.com/JabRef/jabref/actions/workflows/deployment-arm64.yml) needs to run on this branch (`fix-notary-tool`) with notarization `true`.

The .pkg and .dmg at https://builds.jabref.org/pull/10041/merge/ should be notarized (as of now), ,because I activated notarization.

**Comment by koppor** [comment]
We are continuing tweaking the build workflows (e.g., https://github.com/JabRef/jabref/pull/10049). Therefore, we merge. We can add fixes if needed later.

**Pull request merged**
