### PR TITLE
Better layout of DatabasePropertiesDialog

### PR DESCRIPTION
**Pull request by oscargus**
Does not fully solve #958 but at least better...

I do not fully understand why the formatter part doesn't scale horizontally.

### CODE REVIEW

**Comment by matthiasgeiger** [comment]
Uh... isn't @Siedlerchr currently working on this dialog (see #958 and #957)?

**Comment by Siedlerchr** [comment]
Öhm, you didn't need to do that, as I am already working at this ;)
See assigned label.

**Comment by oscargus** [comment]
I know. However, since I've struggled with JGoodies earlier I thought you
could use some input (regarding your question in that issue). Use it as
inspiration. :-)

**Comment by Siedlerchr** [comment]
Yeah, it was the scaling of the Icons to the buttons. I will try later, I think the solution is to putt the Icon Button and the other Buttons in a button bar.

**Comment by oscargus** [comment]
I think I solved that part (only tested on Linux where it looked OK to
start with though).

The key thing I did was to use "fill".

**Comment by matthiasgeiger** [comment]
@Siedlerchr Shall we merge this in and you work with @oscargus' improvements as a basis or do you prefer to create another PR beginning from scratch?

**Comment by Siedlerchr** [comment]
I will manually try to apply the fixes because I changed some more in the
layout (removed  Textfields etc)


2016-03-18 9:59 GMT+01:00 Matthias Geiger <notifications@github.com>:

**Pull request closed without merging**
