### PR TITLE
Show an informative progress indicator when dragging and dropping PDF files to JabRef 

### PR DESCRIPTION
**Pull request by BaronMac08**
Closes [#8738 ](https://github.com/JabRef/jabref/issues/8738)

Builds upon: the branch `fix-melting-630` merged at [#12001](https://github.com/JabRef/jabref/pull/12001)

Modifications:
- Dragging and dropping several PDF files into JabRef will be one large import rather than one small import for every file

Additions:
- Added informative messages about the ongoing progress of the big import by building upon the BackgroundTask progress indicator
- Added shortenFileName(fileName, maxLength) in StringUtil to shorten and prominently display the files being imported
- Added one new unit test for validating StringUtil.shortenFileName()

UI Screenshots after modifications and additions:

Screenshot 2024-10-23 at 16 46 06
Screenshot 2024-10-23 at 16 46 31
Screenshot 2024-10-23 at 16 47 49
Screenshot 2024-10-23 at 16 49 40

### Mandatory checks

- [x] I own the copyright of the code submitted and I licence it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [x] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by koppor** [comment]
This PR is a follow-up to https://github.com/JabRef/jabref/pull/12035. We need the magic of https://blog.flupp.de/posts/git-and-squashed-prs/. I will try.

**Comment by koppor** [comment]
@BaronMac08 Seeing the diff at https://github.com/JabRef/jabref/pull/12035/files, I would propose:

1. Close this pull request
2. Fetch `upstream/main`
3. Create a new branch `fiix-8738` based on `upstream/main`
4. Apply the changes listed at ttps://github.com/JabRef/jabref/pull/12035/files manually using your IDE
5. Commit and push
6. Create pull request.

**Comment by koppor** [comment]
Internal note:

I could not do "git magic", because following command hangs:

    git commit-tree 9dc82bc2931d1474ea656835bbe192dc1e54cea4 -p 650d4a248a49c08ca1a51278 -p fix-melting-630

**Comment by BaronMac08** [comment]
> @BaronMac08 Seeing the diff at https://github.com/JabRef/jabref/pull/12035/files, I would propose:
> 
> 1. Close this pull request
> 2. Fetch `upstream/main`
> 3. Create a new branch `fiix-8738` based on `upstream/main`
> 4. Apply the changes listed at ttps://github.com/[Show a progress indicator when dragging and dropping PDF files to JabRef #12035](https://github.com/JabRef/jabref/pull/12035)/files manually using your IDE
> 5. Commit and push
> 6. Create pull request.

Thank you @koppor. I will follow the suggested solution and open a new pull request.

**Pull request closed without merging**
