### PR TITLE
Small changes to default preferences

### PR DESCRIPTION
**Pull request by tobiasdiez**
- Fields in table are not colored (required/optional)
 - Owner column is not shown
 - Slightly increasing row padding in table

### CODE REVIEW

**Comment by simonharrer** [comment]
As timestamp and owner are both not on by default anymore, we should also not show both columns. Hence, I vote for removing support for the timestamp column in the defaults as well.

**Comment by simonharrer** [comment]
Why not colored for required/optional anymore by default? Any rationale behind your PR?

**Comment by tobiasdiez** [comment]
One reason is that these colors are not self-explanatory. It is hard for the user to recognize that blue fields are optional. Moreover, I don't see any value by coloring the fields by required/optional (except in some special cases maybe). Also then the complete layout is more homogeneous and clearer. But I have no strong opinion about this...

I will disable the timestamp column later.

**Comment by simonharrer** [comment]
Thanks for the detailed answer. I give my OK for this PR.
Am 12.09.2015 7:41 nachm. schrieb "Tobias Diez" <notifications@github.com>:

**Pull request merged**
