### PR TITLE
GVKParser handle publication year correctly

### PR DESCRIPTION
**Pull request by teertinker**
exchanged the field "date" with "year" to import GVK entries correctly.

Publication year was previously put to date when fetching entry-> now to year

* Sorry if I broke any conventions of changing code/testing...

### CODE REVIEW

**Comment by koppor** [comment]
GVK's `date` is always 4 digits?

**Comment by teertinker** [comment]
I use it a lot, and never got other "dates" than 4-digits.

**Comment by matthiasgeiger** [comment]
@koppor You changed this in b2c8db5458fb46b5581b7018897f67c8cf010bcc from year to date. 

The reason seems to be related to #1018: GVK returns Biblatex entries (regardless of the chosen mode)...

**Comment by koppor** [comment]
OK for revert. Current JabRef displays "year" in the "Required fields", which it IMHO did not back in 2015.

**Comment by simonharrer** [comment]
Reverted in 93fdb02ee5889d0e0cf9b41a2af763cc306fbe49

Thanks for the help, especially @teertinker :smile:

**Pull request closed without merging**
