### PR TITLE
French localization: translation of 2 empty strings

### PR DESCRIPTION
**Pull request by mlep**
<describe the changes you have made here: what, why, ...>

- [ ] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [ ] Screenshots added (for bigger UI changes)

### CODE REVIEW

**Comment by matthiasgeiger** [comment]
github marks the whole file as changed - have you accidentally changed the encoding of the file?

**Comment by mlep** [comment]
Strange: I have simply edited the 2 strings in my usual browser. I do not think I could have changed the encoding even if I wanted...

**Comment by matthiasgeiger** [comment]
Strange... if you don't mind I'll add the two strings manually.

**Comment by mlep** [comment]
Sure about strange, And sure you can add them manually

**Comment by matthiasgeiger** [comment]
Done in dad863b8ceae804a4dd9268bb2df1a05ea4b3718.

**Pull request closed without merging**
