### PR TITLE
Add purple background in Windows 8.1+ start menu

### PR DESCRIPTION
**Pull request by tobiasdiez**
Add a gray background in JabRef's start menu tile (for Windows 8.1 and 10) by implementing the [VisualElementsManifest](https://msdn.microsoft.com/en-us/library/windows/apps/dn393983.aspx).
screen

Note: I couldn't test the install procedure since `gradlew releaseWindows` gives an error:
```
[ERROR] [org.gradle.BuildExceptionReporter] > A problem occurred starting process 'command 'launch4j''
```

### CODE REVIEW

**Comment by koppor** [comment]
Regarding the test with installer. Please consult https://github.com/JabRef/jabref#release-process

**Comment by simonharrer** [comment]
:+1: we are currently in the process of moving to install4j installers. This should be integrated there as well.

**Comment by stefan-kolb** [comment]
Why make it gray? The picture is purple, should it be purple?!

**Comment by tobiasdiez** [comment]
Strange... on my system it is more gray than purple but on the screenshot it is more purple. Anyway, I took the main color in the jabref icon and made it a little bit lighter.

**Comment by stefan-kolb** [comment]
What about taking the exact same color, to free the 'R' as Windows does with their icons?

**Comment by tobiasdiez** [comment]
I oriented myself on MS Office.
untitled

**Comment by stefan-kolb** [comment]
So what about this one? image

**Comment by stefan-kolb** [comment]
You were faster :smile: 
Good work :+1:

**Comment by simonharrer** [comment]
:+1:

**Comment by stefan-kolb** [comment]
@JabRef/developers Does this work for any of you? Not working for me in the current setup.

**Comment by koppor** [comment]
What does "not working" mean? Here, there is a difference with and without `JabRef.VisualElementsManifest.xml` in `C:\Program Files\jabref`. I do the following command to let Windows know that I played around with the manifest file:

    (ls "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\JabRef\JabRef.lnk").lastwritetime = get-date

System: Windows 8.1 Pro, JabRef 64bit.

What I don't see is a background with one color, I see a background with some shading. However, the color changes depended of the presence or absence of `JabRef.VisualElementsManifest.xml`.

**Comment by stefan-kolb** [comment]
I don't see a custom background at all. I'm on Windows 10.

**Comment by matthiasgeiger** [comment]
So it is currently a manual step, which should be integrated in the new install4j process (if possible)?

**Comment by koppor** [comment]
No, no manual Step, install4j works perfectly. Only for debugging issues there are manual steps required.

**Comment by matthiasgeiger** [comment]
Okay... does not work for me. After installing and selecting "Pin to 'Start'" i only see the an uncolored background on Win10 (but I'm not sure whether if have changed some Windows prefs regarding this feature as I do not use the start tiles for other "Apps")

**Comment by simonharrer** [comment]
Hm, install4j should put the file in the folder with the exe file.

**Comment by stefan-kolb** [comment]
It is placed inside the jabref folder but has no effect for me. Maybe Matthias and I have overidden anything in Windows? Does it work for you Simon?

**Comment by koppor** [comment]
Windows 10 Pro Version 1511 Build 10586.11 displays purple background.

grabbed_20151125-114228

Steps taken: Download 64 bit installer from http://builds.jabref.org/master/. Install. Open Windows Startmenu (additional step since I use [Classic Shell](http://www.classicshell.net/)). Right click on JabRef (should be there), "Pin to Start menu" (or similar). At the right side: Scroll down and see all apps. The last app is "JabRef" and displayed as shown above.

**Comment by tobiasdiez** [comment]
I think the problem happens if you already had Jabref installed on the computer and/or installed the new version in the same folder. The problem is then that the shortcut pointing to the executable (usually `C:\ProgramData\Microsoft\Windows\Start Menu\Programs\JabRef\JabRef.lnk`)
is not updated. But Windows just reads the manifest file if this shortcut changes. Does it work if you invoke the command posted by @koppor in https://github.com/JabRef/jabref/pull/355#issuecomment-159449481?

**Comment by stefan-kolb** [comment]
The command does not work for me.
```
(ls "C:\Users\Stefan\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\JabRef\JabRef.lnk").lastwritetime = get-date
".lastwritetime" kann syntaktisch an dieser Stelle nicht verarbeitet werden.
```

I'll try to update Windows to the latest Patch release and see if it works, at least it does for Simon.

**Comment by simonharrer** [comment]
Works on my machine (tm) ;-)

I uninstalled all JabRef versions before.

**Comment by matthiasgeiger** [comment]
(not working after removing all jabref versions and a new clean install in another for win10 build 10240)

**Comment by tobiasdiez** [comment]
@stefan-kolb did you tried it in a powershell or usual command shell? should work as powershell.
@matthiasgeiger uninstalling Jabref might not work because the lnk file is not removed during uninstall?

**Comment by matthiasgeiger** [comment]
I've installed in a new start menu "folder" so this should not be the problem.

**Comment by matthiasgeiger** [comment]
Works now after update to Win10 1511 Build 10586 :+1:

**Comment by koppor** [comment]
@stefan-kolb Tooltip: [ConEmu](https://conemu.github.io/). Dropdown right of the "+": "Shells" -> "PowerShell"

**Comment by stefan-kolb** [comment]
Ok, so it is probably the update that fixes the problem. The other solutions do not work for me.

**Comment by simonharrer** [comment]
Maybe related: https://github.com/koppor/jabref/issues/57

**Pull request merged**
