### PR TITLE
Disable Write XMP Button in General tab of Entry-Editor when action is in progress

### LINKED ISSUE #8691: Write XMP Button should be disabled when action is in progress
We offer the functionality to write XMP to a PDF:

grafik

We tried to fix it at https://github.com/JabRef/jabref/pull/8658

However, the fix does not work:

<details>
<code>
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: 1-based index not found: 8
	at org.jabref.merged.module@5.6.160/com.google.common.cache.LocalCache$Segment.get(Unknown Source)
	at org.jabref.merged.module@5.6.160/com.google.common.cache.LocalCache.get(Unknown Source)
	at org.jabref.merged.module@5.6.160/com.google.common.cache.LocalCache.getOrLoad(Unknown Source)
	at org.jabref.merged.module@5.6.160/com.google.common.cache.LocalCache$LocalLoadingCache.get(Unknown Source)
	at org.jabref.merged.module@5.6.160/com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(Unknown Source)
	at org.jabref@5.6.160/org.jabref.logic.pdf.FileAnnotationCache.getFromCache(Unknown Source)
	at org.jabref@5.6.160/org.jabref.gui.entryeditor.fileannotationtab.FileAnnotationTabViewModel.lambda$reloadAnnotations$1(Unknown Source)
	at org.jabref.merged.module@5.6.160/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.6.160/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at org.jabref.merged.module@5.6.160/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at org.jabref.merged.module@5.6.160/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.6.160/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: 1-based index not found: 8
	at org.jabref.merged.module@5.6.160/org.apache.pdfbox.pdmodel.PDPageTree.get(Unknown Source)
	at org.jabref.merged.module@5.6.160/org.apache.pdfbox.pdmodel.PDPageTree.get(Unknown Source)
	at org.jabref.merged.module@5.6.160/org.apache.pdfbox.pdmodel.PDPageTree.get(Unknown Source)
	at org.jabref.merged.module@5.6.160/org.apache.pdfbox.pdmodel.PDPageTree.get(Unknown Source)
	at org.jabref@5.6.160/org.jabref.logic.pdf.PdfAnnotationImporter.importAnnotations(Unknown Source)
	at org.jabref@5.6.160/org.jabref.logic.pdf.EntryAnnotationImporter.lambda$importAnnotationsFromFiles$2(Unknown Source)
	at java.base/java.util.Optional.ifPresent(Unknown Source)
	at org.jabref@5.6.160/org.jabref.logic.pdf.EntryAnnotationImporter.importAnnotationsFromFiles(Unknown Source)
	at org.jabref@5.6.160/org.jabref.logic.pdf.FileAnnotationCache$1.load(Unknown Source)
	at org.jabref@5.6.160/org.jabref.logic.pdf.FileAnnotationCache$1.load(Unknown Source)
	at org.jabref.merged.module@5.6.160/com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(Unknown Source)
	at org.jabref.merged.module@5.6.160/com.google.common.cache.LocalCache$Segment.loadSync(Unknown Source)
	at org.jabref.merged.module@5.6.160/com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(Unknown Source)
	... 14 more

</code>
</details>

Proposal: When clicking on the button

1. JabRef disalbes the button
2. JabRef does its work
3. JabRef enabled the button

This a) provides the user a feedback that JabRef is working and b) removes `synchronized` statements from the code.

### PR DESCRIPTION
**Pull request by melmorsy**
Fixes #8691 

Disable the button before starting the 'write' task then re-enables the button after the task is complete

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Review by calixtus — COMMENTED** [review]
Could you maybe refactor the write xmp logic and implement it as a SimpleCommand? That way we can bind the disabled state in the view to the executable property of the SimpleCommand and benefit from the infrastructure the existing implementation of the command pattern provides.

**Comment by calixtus** [comment]
Don't be overwhelmed. By refactoring the "write xmp logic" i just meant *copy'n'paste* the existing logic into a new class implementing SimpleCommand and bind the disabled-property of the button to the executable-property of the SimpleCommand.

**Comment by melmorsy** [comment]
Thanks @calixtus for you suggestion and apologies for the delayed reply. Using SimpleCommand and binding the properties looks certainly to be an interesting approach. I had a look at the code to understand SimpleCommand a bit more, however it wasn't clear to me how would it fit with BackgroundTask? Currently, writeMetadataToPdf creates a BackgroundTask and passes it to the taskExecutor, if we implement a SimpleCommand that does the same, then couldn't SimpleCommand's "execute" method return before the writing to PDF is actually complete, since writing to PDF is done as a BackgroundTask which could be on a different thread? i.e. the button might get enabled before writing to PDF is actually complete?
Unfortunately I don't seem to find a documentation for SimpleCommand so my understanding is be based on going through the code usages for SimpleCommand, which may mean that I missed something, let me know please what do you think.

**Comment by calixtus** [comment]
SimpleCommand is basically a wrapper for every ui action you can imagine.
Just put the backgroundTask into the execute method of a SimpleCommand and use the onRunning or onSuccess methods to update the executable property and bin the property to the disable-property of the button.

**Review by calixtus — APPROVED** [review]
Looks good to me! Thanks for your contribution.

If you got time and want to go the extra mile you could also in a follow-up PR make the menu action use the new Command.

**Review by Siedlerchr — APPROVED** [review]

**Pull request merged**
