### PR TITLE
[WIP] Fix latex field formatter

### PR DESCRIPTION
**Pull request by lenhard**
Another attempt to fix the line wrapping. As far as I can see, some of the current behavior is due to the formatting implemented in `LatexFieldFormatter`. This PR tries to rectify some of this behavior by explicitly excluding the "review" and "abstract" fields from line wrapping.

Related: #114 #186 #185

### CODE REVIEW

**Comment by stefan-kolb** [comment]
@lenhard See the https://github.com/JabRef/jabref/tree/fix-linebreaking branch if you haven't done already. From my first tests there are some more problems with this class.

**Comment by lenhard** [comment]
@stefan-kolb The branches have different targets. You works aims at *parsing*, while this PR aims at *writing*.

**Comment by stefan-kolb** [comment]
Oups sorry ;)

**Comment by koppor** [comment]
Does this make #123 obsolete? :innocent:

**Comment by lenhard** [comment]
@koppor: No it does not. It just addresses `LatexFieldFormatter` which does formatting of bibtex field text. `BibtexWriter` still does field sorting and `BibtexParser` is a completely different "construction site" ;)

**Pull request merged**
