### PR TITLE
Rename cleanup actions: "Prepare for LaTeX" and "Prepare for BibTeX"

### LINKED ISSUE #8672: Rename cleanup actions: "Prepare for LaTeX" and "Prepare for BibTeX"
When this first came up: https://github.com/JabRef/jabref/issues/8490#issuecomment-1091209909

**My Problem:**

Cleanup actions are not well described and contrary to users intuitive thought.

I always thought the "LaTeX cleanup" action would remove **LaTeX code** so that the entries will be rendered well via CSL entry preview or alternatively that the entries will be rendered well when using them with OpenOffice/LibreOffice, but instead this action mostly removes characters (via RegEx) that **hinder** the bibliographic data to be used with LaTeX. Therefore, this cleanup-action does not convert from LaTeX to *"something else"*, but rather it goes the opposite direction.

**Solution:**

Make it more transparent to the user, which of the clenaup actions are advised to be used when trying to use the entries with LaTeX and Bibtex.

~Make ready for LaTeX:~

~- [ ] Rename "LaTeX cleanup" action to `Make ready for LaTeX: Cleanup`~
~- [ ] Rename "Unicode to LaTeX" to `Make ready for LaTeX: Unicode to LaTeX`~
~- [ ] Rename "HTML to LaTeX" to `Make ready for LaTeX: HTML to LaTeX`~
~- [ ] Rename "Ordinals to LaTeX superscript" to `Make ready for LaTeX: Ordinals to LaTeX superscript`~
~- [ ] Rename "Units to LaTeX" to `Make ready for LaTeX: Units to LaTeX`~

Prepare for LaTeX:

- [ ] Rename "LaTeX cleanup" action to `Prepare for LaTeX: Cleanup`
- [ ] Rename "Unicode to LaTeX" to `Prepare for LaTeX: Unicode to LaTeX`
- [ ] Rename "HTML to LaTeX" to `Prepare for LaTeX: HTML to LaTeX`
- [ ] Rename "Ordinals to LaTeX superscript" to `Prepare for LaTeX: Ordinals to LaTeX superscript`
- [ ] Rename "Units to LaTeX" to `Prepare for LaTeX: Units to LaTeX`

~Make ready for BibTeX:~
~- [ ] Rename "Normalize month" to `Make ready for BibTeX: Normalize month`~
~- [ ] Rename "Normalize names of persons" to `Make ready for BibTeX: Normalize names of persons`~
~- [ ] Rename "Normalize pagenumbers" to `Make ready for BibTeX: Normalize pagenumbers`~

Prepare for BibTeX:
- [ ] Rename "Normalize month" to `Prepare for BibTeX: Normalize month`
- [ ] Rename "Normalize names of persons" to `Prepare for BibTeX: Normalize names of persons`
- [ ] Rename "Normalize pagenumbers" to `Prepare for BibTeX: Normalize pagenumbers`

### PR DESCRIPTION
**Pull request by zkl-ai**
Fixes #8672

Result:
image

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Review by zkl-ai — COMMENTED** [review]
Rename cleanup actions: "Make LaTeX ready" and "Make BibTeX ready"

**Comment by ThiloteE** [comment]
Documentation needs to be changed here also: https://docs.jabref.org/finding-sorting-and-cleaning-entries/saveactions#latex-cleanup

**Comment by ThiloteE** [comment]
Also: Add to documentation of `Prepare for LaTeX: Cleanup` ([see here](https://docs.jabref.org/finding-sorting-and-cleaning-entries/saveactions#latex-cleanup)): Single `$` characters will not be removed from the entry. This allows users to denote the start and end of LaTeX math-mode in their bibliography. One enters math mode by typing a dollar sign `$`, and one leaves math mode by typing another dollar sign `$`

**Comment by zkl-ai** [comment]
> Also: Add to documentation of `Prepare for LaTeX: Cleanup` ([see here](https://docs.jabref.org/finding-sorting-and-cleaning-entries/saveactions#latex-cleanup)): Single `$` characters will not be removed from the entry. This allows users to denote the start and end of LaTeX math-mode in their bibliography. One enters math mode by typing a dollar sign `$`, and one leaves math mode by typing another dollar sign `$`

Ok. I will change it later!

**Comment by Siedlerchr** [comment]
Please have a look at the failing unit tests. You need to adjust the l10n https://devdocs.jabref.org/getting-into-the-code/code-howtos.html#using-localization-correctly

**Comment by zkl-ai** [comment]
> Please have a look at the failing unit tests. You need to adjust the l10n https://devdocs.jabref.org/getting-into-the-code/code-howtos.html#using-localization-correctly



> Please have a look at the failing unit tests. You need to adjust the l10n https://devdocs.jabref.org/getting-into-the-code/code-howtos.html#using-localization-correctly

Ok, I'm looking for it. Thank you for your warning.

**Comment by Siedlerchr** [comment]
It seems like you didn't read through it correctly. You actually need to change it in the Code and in the L10n file. And you cannot just rename the values. The keys and the values in the l10n have to be the same.
Sorry, but this PR makes no sense.

**Pull request closed without merging**
