### PR TITLE
Reordered items in main table right-click menu

### LINKED ISSUE #6099: UI: maintable: right-click menu: reorder items
In JabRef 5.0, when you right-click on an entry of the main table, you get the following menu:
RightClick

**Is your suggestion for improvement related to a problem? Please describe.**
Some items are not consistently located: the nearby items are unrelated.

**Describe the solution you'd like**
- "Attach file" moved in the cluster "Open folder"..."Open URL or DOI"
- "Merge entries" moved in the cluster "Copy"..."Delete"

### PR DESCRIPTION
**Pull request by rayinfinite**
Fixes #6099

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

## About issue 6099
In JabRef 5.3, when you right-click on an entry of the main table, you get the following menu:
before
In this menu, some items are not located properly. So we want to change the order of the menu. There are 3 changes we made. 
- place "Attach file" before "Open Folder"
- place "Merge entries" between "Cut" and "Delete Entry"
- rename "Delete Entry" to "Delete entry"

After changes, the menu should appears as follows:
after

### CODE REVIEW

**Comment by Siedlerchr** [comment]
LGTM from my side, please have a look at the failing localization language test, you probably need to remove "Delete Entry" from the en.properties file

**Comment by Siedlerchr** [comment]
@rayinfinite  can you please fix the last remaining issue, the localization? Then we can merge this!

**Review by Siedlerchr — CHANGES_REQUESTED** [review]
pleae fix the l10n

**Review by Siedlerchr — APPROVED** [review]

**Review by calixtus — APPROVED** [review]
I took the liberty to change the changelog entry a bit, since this PR does not really fix a bug, but changes just the order of the right click menu to a more fitting one.
Looks good to me, tests are green, two reviews. Merging now.
Thank you very much for your effort!

**Pull request merged**
