### PR TITLE
Changed context menu item order for library tabs

### PR DESCRIPTION
**Pull request by calixtus**
Fixed ollys rage

- [ ] Change in CHANGELOG.md described (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

**Review by Siedlerchr — APPROVED** [review]
🥇

**Review by koppor — APPROVED** [review]

**Comment by calixtus** [comment]
grafik

**Review by DominikVoigt — APPROVED** [review]
LGTM!

**Comment by koppor** [comment]
State before the PR:

grafik

State of firefox:

grafik

**Review by koppor — APPROVED** [review]

**Pull request merged**
