### PR TITLE
CPU leak

### PR DESCRIPTION
**Pull request by stefan-kolb**
See #3943
- Fix Java to later version
- Pretty restrictive for the user unfortunately!

### CODE REVIEW

**Comment by stefan-kolb** [comment]
@JabRef/developers I worked a little bit with Jabref 4.2 and the new JDK and I feel like also the problems with duplicated entries in the search box and freezes are less frequent now.
Maybe the constant load provokes these issues even more.
Therefore, I vote to release a new JR version where we force the users to upgrade to the newest Java JRE/JDK!

Also refs #3989.
Fixes #3943.

**Comment by stefan-kolb** [comment]
As this really improves the situation (at least for me), I think we should definitly include this in our release.

**Comment by koppor** [comment]
@stefan-kolb Which tool did you use for the CPU monitoring?

I tried `java version "1.8.0_171"` and it doesn't seem to cause high CPU load.

Focused entry editor:

grafik

Unfocused entry editor:

grafik

**Comment by stefan-kolb** [comment]
I used the visualvm. It is actually not caused by the entry editor but by switching between programs.

**Pull request merged**
