### PR TITLE
Added initial Swedish translations

### PR DESCRIPTION
**Pull request by oscargus**
I cannot really figure out what "entry" should be...

### CODE REVIEW

**Comment by stefan-kolb** [comment]
Nice, when you're ready to merge you can also add a changelog entry :smile:

**Comment by lenhard** [comment]
Tricky :-) With my limited non-native swedish, I can only be of limited help. Maybe an alternative? After all, a BibTeX entry is nothing but an *element* of a BibTeX database. So how does *ett BibTeX element* sound to you?

**Comment by stefan-kolb** [comment]
There's no"Eintrag" in Swedish? :smile:

**Comment by lenhard** [comment]
According to my dictionary, Eintrag translates to införande (~ Eintragung, Registrierung) or anteckning (~ Anmerkung), neither of which seem very fitting here.

**Comment by matthiasgeiger** [comment]
Google proposes "entry - inträde, post, inresa, tillträde, artikel, entre".
But as I do not speak any swedish I cannot decide whether those make any sense ;-)

**Comment by oscargus** [comment]
Element is OK but there might be better ones (strictly it can be used, but sounds a bit _krystat_). Same with post. Artikel is sort of interesting as well, but there's the duplicate meaning article.

**Comment by oscargus** [comment]
I think post is probably the best. That is what is commonly used in databases, so from that perspective it should be OK. Thanks all for your input!

**Comment by oscargus** [comment]
Just merge this before releasing 3.3. Most menu entries are translated and a decent part of the other strings (I use a plain text editor, so no idea what percentage). I will add a few more every now and then, but would need to install some standard software in Swedish to figure out certain terms, like "redo"... ;-)

**Pull request merged**
