### PR TITLE
Add merge_group trigger on tests and deployment

### PR DESCRIPTION
**Pull request by koppor**
In DevCalls (or gatherings), we often say: "Just let the tests pass, then merge". For this scenario, the [merge queue](https://github.blog/2023-07-12-github-merge-queue-is-generally-available/)s of GitHub have been invented. Docs available at https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions.

To put this live:

- [ ] Change [branch protection rules](https://github.com/JabRef/jabref/settings/branch_protection_rules/14701014) to include "Require merge queue "
- [ ] Select "Merge method": squash
- [ ] Select "Build concurrency": 1 (should be enough for our needs - not sure what that means and how it affects builds not having the latest main)
- [ ] Ensure "Only merge non-failing pull requests" is "yes"
- [ ] Adjust "Merge limits" (maybe: min 1: max: 3)

### Mandatory checks
- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Review by Siedlerchr — APPROVED** [review]

**Comment by koppor** [comment]
I go with these settings:

grafik

Collecting more than 1 PR, but the merge queue should kick-off after 5 minutes if no more PRs are coming in. This should leave us enough discusion time, but also quick enough to keep things moving.

**Comment by koppor** [comment]
Merge queue takes the branch protection rules serious:

grafik

We like the merge queue feature.

We like that new commits dismiss old reviews.

We like two have two reviewers on a PR.

To make use of the merge queue feature, we change the formal number of required reviewers to 1, but "enforce" the two-reviewer-rule manually.

**Comment by koppor** [comment]
Checking after change to 1 required reviewer:

grafik

**Comment by koppor** [comment]
Link to merge queue: https://github.com/JabRef/jabref/queue/main

**Comment by koppor** [comment]
Screenshot merge queue:

grafik

**Comment by koppor** [comment]
Due to the cancelling of currenet builds, we needed to adapt the settings.

**Please vote up https://github.com/orgs/community/discussions/63136**

grafik

**Comment by koppor** [comment]
We discussed whether we should remove the cancelling of previous jobs. However, we weigh the cancelling of previous runs higher then having a "fast" merge queue.

**Comment by koppor** [comment]
Queue with 2 PRs (and concurrency limit 1)

grafik

**Comment by koppor** [comment]
How a merge looks like:

grafik

Commit:

grafik

**Comment by koppor** [comment]
There is no indication whether a PR is selected to put into the queue. Only if the pre-conditions are fulfilled and GitHub put the PR into the merge queue, there is an icon

grafik

**Comment by koppor** [comment]
Drawback: If a PR was taken out of the merge queue, there is no notification.

**Comment by koppor** [comment]
We have timeout issues:

grafik

Therefore we increased the timeout from 60 to the maximum of 360 minutes

**Comment by koppor** [comment]
The merge queue seems to have issues with status reporting sometimes:

grafik

**Comment by koppor** [comment]
It hang because of an error in the YAML file:

grafik

**Comment by koppor** [comment]
Interestingly, there is no cancelling of merge builds when new commits are added. These are just ignored:

grafik

**Comment by koppor** [comment]
Note that all requires status checks have to be checked by the merge queue: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions

**Pull request merged**
