### PR TITLE
Moved cleanup out of background thread to stick with the architecture…

### PR DESCRIPTION
**Pull request by johannes-manner**
@r0light  and I tried to resolve the build issue introduced by #4818 as a temporary solution.
We took all cleanup tasks out of the background task, so that everything runs in the JavaFX thread.

This fix is needed to resolve the build problem in all other currently open pull requests.

### CODE REVIEW

**Comment by johannes-manner** [comment]
@tobiasdiez, our architecture problem is resolved now, but a new one was introduced by #4787 in src/main/java/org/jabref/logic/net/URLUtil.java.

**Comment by Siedlerchr** [comment]
@johannes-manner  It's because of the ExternalFiles class. Move the UrlUtil class to gui, that should work

**Comment by r0light** [comment]
@Siedlerchr @tobiasdiez From our point of view, it is ready to be merged, because the last build suceeded

**Comment by Siedlerchr** [comment]
Thanks a lot!

**Comment by tobiasdiez** [comment]
With these changes the `URLUtil` is split in half and moved to the gui. Why was this necessary? (I feel really bad for asking this as it was me who destroyed the build and I'm very thankful to both of you for fixing it again...).

**Comment by Siedlerchr** [comment]
External Files is unfortunately still a gui class thus creating an architecture violation if used in logic.

**Pull request merged**
