### PR TITLE
Reorganized "General tab" (preamble still here) and "String constants…

### LINKED ISSUE #9818: Rearrange content of Library Properties Dialog
Currently, the "Library properties" dialog has tabs. Which is good.

Tab 2 to 4 has one content.

However, Tab 1 has three contents:

image

Proposal: 

1. Refactor General as follows:

image

2. Move "Preamble" to tab "Preamble" (as last tab, since it is the most unimportant)
3. Move "String constants" after "Citation key patterns" (as it is IMHO not used very often)

Final ordering:

General, Saving, Citation key patterns, String Constants, Preamble

### PR DESCRIPTION
**Pull request by deybis17**
…" placed after "Citation key patterns"

Fixes #9818

- **Reorganization of the Order of Tabs:**
             **Before:** General, Saving, String constants, Citation key patterns and Content selectors
             **Now:** General, Saving,  Citation key patterns, String constants and Content selectors

- **Reorganization of the contents in General Tab:**
             **Before:** General, Override default file directories and Preamble
             **Now:** Override default file directories, General  and Preamble

- It still missing to separate Preamble seccion in General tab  and locate it in its own tab (Preamble Tab)

image

```[tasklist]
### Compulsory checks
- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.
```

### CODE REVIEW

**Comment by Siedlerchr** [comment]
Please also add a changelog entry

**Comment by koppor** [comment]
@deybis-villegas Thank you for working on this.

One more thing. Can you rename the 2nd general heading to "Miscellaneous". You will also need to add this string to `JabRef_en.properties`.

image

**Comment by deybis17** [comment]
General and preamble tab look like this now

image
image


> Can't do quick comment, because new screenshot is there. - I merged `main` so that this branch has no conflicts.

**Comment by koppor** [comment]
I am so sorry that I did not describe the picture content of the issue description as text.

May I mark the demand of the issue with an arrow and a yellow box?

image

As text: Swap "library mode" and "library encoding".

**Comment by deybis17** [comment]
> I am so sorry that I did not describe the picture content of the issue description as text.
> 
> May I mark the demand of the issue with an arrow and a yellow box?
> 
> image
> 
> As text: Swap "library mode" and "library encoding".

Now it looks like this:

image

**Comment by calixtus** [comment]
I took the liberty to shorten the changelog message a little bit. I hope you don't mind.

**Review by Siedlerchr — APPROVED** [review]

**Comment by Siedlerchr** [comment]
Thanks a lot for your contribution!

**Pull request merged**
