### PR TITLE
Remove application insights writer from meta inf

### PR DESCRIPTION
**Pull request by Siedlerchr**
Fixes https://github.com/JabRef/jabref-issue-melting-pot/issues/313
Fixes https://github.com/JabRef/jabref-issue-melting-pot/issues/312

>LOGGER ERROR: Service implementation 'org.jabref.gui.logging.ApplicationInsightsWriter' not found 

### Mandatory checks
- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by koppor** [comment]
Could you try to fix following issues, too?

```
LOGGER ERROR: Service implementation 'application insights' not found
...
warning: [options] module name in --add-exports option not found: org.junit.jupiter.engine
```

Source: https://github.com/JabRef/jabref/actions/runs/6598284269/job/17926106702?pr=10533

**Comment by Siedlerchr** [comment]
yes is inlcuded

**Comment by koppor** [comment]
> yes is inlcuded

Not at the latest check. Link: https://github.com/JabRef/jabref/actions/runs/6598284269/job/17926106404?pr=10533. Expand "Run Modernizer".

Screenshot:

image

**Comment by Siedlerchr** [comment]
warning: [options] module name in --add-exports option not found: org.junit.jupiter.engine
This is the only one that I cannot find. must be coming from testfx or so

**Review by koppor — APPROVED** [review]

**Pull request merged**
