### PR TITLE
Additional filter functionality for Check Integrity popup

### LINKED ISSUE #2718: Check integrity action filter should have an option to select none and all
It is tedious to deselect all of the issues first to select a single one after that to fix it

### PR DESCRIPTION
**Pull request by Andrew-Lev**
Fixes #2718 

I added new 'Filter All' and 'Filter None' buttons.  They can be clicked by the user to
check/uncheck all options in the filter menu.  When one of the buttons gets clicked the system will iterate through the existing menu components and toggle the checkmarks and info displayed.

I wasnt sure on the best placement of the buttons in the window so went with the simplest solution
image

Updated localization info with text for aforementioned buttons.

### CODE REVIEW

**Comment by koppor** [comment]
We still have many open translations (
http://help.jabref.org/en/TranslatingGUI), so that is not a con. The
feature has a very low risk break anything. I would just include it.

Am 18.08.2017 11:32 schrieb "Jörg Lenhard" <notifications@github.com>:

**Comment by lenhard** [comment]
Ok, perfect!

@Andrew-Lev Thank you very much for your contribution! You're very welcome to provide more :-)

**Comment by mlep** [comment]
@koppor Does the timeframe for the release of 4.0  allow a call to translators?

**Comment by koppor** [comment]
Absolutely!!

Am 18.08.2017 14:47 schrieb "MLEP" <notifications@github.com>:

**Pull request merged**
