### PR TITLE
Add gradle task downloadDependencies and use it at CircleCI

### PR DESCRIPTION
**Pull request by koppor**
I discovered a gradle task fetching all dependencies without building. I added that and adapted the CircleCI script accordingly.

I also made some cleanups, which should ease the migration from CircleCI 1.0 to CircleCi 2.0.

### CODE REVIEW

**Comment by koppor** [comment]
CircleCI runs perfectly: https://circleci.com/gh/JabRef/jabref/tree/fix%2Fgradle-dependencies-on-circleci

**Comment by stefan-kolb** [comment]
Why do we need this? Is it faster than building?

**Comment by koppor** [comment]
Yes. Second run: no additional dependencies are fetched.

Stefan Kolb <notifications@github.com> schrieb am Mo., 4. Juni 2018, 09:05:

**Comment by koppor** [comment]
I just merge. It will also help to update to CircleCI 2.0, because of the [1.0 sunset end of August](https://circleci.com/blog/sunsetting-1-0/)

**Pull request merged**
