### PR TITLE
Fix entry editor column visibility

### LINKED ISSUE #7986: Entry editor columns not well adjusted
JabRef 5.3--2021-07-16--c99d61c
Linux 5.13.8-200.fc34.x86_64 amd64 
Java 16.0.1 
JavaFX 16+8

Screenshot from 2021-08-15 10-31-24

shows the three "columns" view of the entry editor with two left hand columns of fields.
This is the default view on my system.

This has been a visibility bug (for many months/years). I cannot see the left hand fields well.

### PR DESCRIPTION
**Pull request by xiaoxianma**
Fixes #7986 

Description:
This PR is to fix the entry editor -> Optional Fields tab first column fields invisibility issue when the width is too small. 

Solution:
As "Optional Fields tab" is a compressed double columns layout, I'd like to make two columns grow/shrink equally. As such, the first column won't be invisible anymore while the second column is shown.

image

### CODE REVIEW

**Comment by Siedlerchr** [comment]
Thanks for working on this. Somehow the formatting looks a bit odd. Please check the settings https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace#configuration-of-intellij-idea

**Comment by xiaoxianma** [comment]
> Thanks for working on this. Somehow the formatting looks a bit odd. Please check the settings https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace#configuration-of-intellij-idea

Will do. thx

**Comment by xiaoxianma** [comment]
> > Thanks for working on this. Somehow the formatting looks a bit odd. Please check the settings https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace#configuration-of-intellij-idea
> 
> Will do. thx

Code format has been fixed.

**Review by koppor — APPROVED** [review]
Better than the old state 🤩. With a small screen, I still have issues. Can be fixed in a follow-up PR.

grafik

**Pull request merged**
