### PR TITLE
Add link to contribute.jabref.org

### PR DESCRIPTION
**Pull request by koppor**
I am not sure about a good way to link http://contribute.jabref.org. WDYT?

### CODE REVIEW

**Comment by tobiasdiez** [comment]
What about putting it in the "Contributing" section? But not so prominently, the stuff written on this page is not that important (except the help which nobody updates except us and the translation stuff which works quite well).

**Comment by koppor** [comment]
It is in the contributing section: 😇 

grafik

**Comment by tobiasdiez** [comment]
ah sorry, its late. The location and style is fine with me. Maybe hide the url, e.g. "[We also need help with other things](contributing)".

**Comment by koppor** [comment]
grafik

**Comment by LinusDietz** [comment]
How about: "Not a Programmer? Learn how you can help."?

**Comment by koppor** [comment]
grafik

**Pull request merged**
