### PR TITLE
Solve formatting in test bib files

### LINKED ISSUE #5116: Unify month field formatting in test bib files
In several bib files we have not a unique formatting for the month:

Example:
Some bib files used for testing have different formats for the months. 
This should be made consistent across all files

correct; 
```
  number    = {1},
  pages     = {55--68},
  month     = oct,
```
other looks like
```
  number    = {1},
  pages     = {55--68},
  month     = #oct#,
```

other looks like
```
  number    = {1},
  pages     = {55--68},
  month     =  {#oct#},
```

### PR DESCRIPTION
**Pull request by allisonsampaio**
I solved the problem of bib format by changing {#sep#} to sep

### CODE REVIEW

**Comment by Siedlerchr** [comment]
Thanks, were this the only affected files?

**Comment by allisonsampaio** [comment]
I believe these were the only bib files with the format problem

**Comment by koppor** [comment]
@allisonsampaio Can you show us the output of [ack](https://beyondgrep.com/). ack is similar to grep, but ignores the `.git` sub directory.

**Comment by LinusDietz** [comment]
What is the status here?

**Comment by tobiasdiez** [comment]
I think there are a few more instances with a wrong format, e.g
https://github.com/JabRef/jabref/blob/master/src/test/resources/org/jabref/logic/importer/fileformat/RisImporterTest3.bib#L8

**Comment by allisonsampaio** [comment]
I'll check if there is more bib files with the format problem

**Comment by stefan-kolb** [comment]
Friendly ping from the JabRef folks at JabCon developer meeting 🎉

**Pull request merged**
