### PR TITLE
Open event log when clicking on collapsed notification

### PR DESCRIPTION
**Pull request by claell**
In https://github.com/JabRef/jabref/pull/8775#discussion_r870153000, I suggested a change for collapsed notifications to improve their UX. Since this has not been implemented there, I went ahead with my own approach.

The collapsed notifications contain a hint to the event log. However, for users, it is likely tiresome to find the menu entry and open the event log from there. Thus, when clicking the collapsed notification, the event log opens now.

Not sure, whether the way I did it is clean, so open for feedback.

An additional thing I noticed is that the event log is empty for me (not the case on the stable build). Probably not related, possibly, an issue should be created for it.

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Review by calixtus — COMMENTED** [review]
I like this idea very much. Maybe there should be also a check if the user really left-clicked on the messagebox to avoid unexpected side-effects.

**Review by Siedlerchr — APPROVED** [review]

**Comment by Siedlerchr** [comment]
@claell  Thanks for the work! Looks good to me. The issue with the empty event log was fixed recently. Your fork was not yet up to date

**Comment by claell** [comment]
> I like this idea very much. Maybe there should be also a check if the user really left-clicked on the messagebox to avoid unexpected side-effects.

Good point, I'll check on that when I have time.

@Siedlerchr thanks for the hint with the empty log, I already feared that this was related to my not up to date fork.

**Comment by Siedlerchr** [comment]
I would merge this in now to reduce the number of PRs. Works fine and we still can create a follow up PR.

**Comment by claell** [comment]
@calixtus I just checked the behavior. It is correct, also right mouse button clicks and probably further actions can trigger this.

I didn't find a fast solution to this, though. I don't know, how to add an event handler for `MouseEvent` (that contains information about the button). Help is appreciated. Maybe, this is not how the class was designed.

**Comment by claell** [comment]
Adding a custom subclass of `Notifications` which has a custom EventHandler also proves difficult, as the class `Notifications` uses a private constructor.

**Pull request merged**
