### PR TITLE
added error specific messages

### LINKED ISSUE #9826: Improve error message when downloading a file fails
Copy the following bibtex code:

```bibtex
@Article{levy_organising_2023,
  author       = {Levy, David L.},
  date         = {2023-04},
  journaltitle = {Environmental Politics},
  title        = {Organising responses to climate change: the politics of mitigation, adaptation and suffering},
  doi          = {10.1080/09644016.2023.2204045},
  issn         = {0964-4016},
  number       = {0},
  pages        = {1--3},
  url          = {https://doi.org/10.1080/09644016.2023.2204045},
  urldate      = {2023-05-01},
  volume       = {0},
  file         = {Full Text PDF:https\://www.tandfonline.com/doi/pdf/10.1080/09644016.2023.2204045:application/pdf},
  publisher    = {Routledge},
  shorttitle   = {Organising responses to climate change},
}

```

Paste it on the maintable in a new library 
See the error message: 403 forbidden

Context:
  It's a known issue that sometimes the browser extension shows an error page although the import was successful (and there is an issue already for this).

However, the error dialog on the JabRef side needs improvement: explain what 403 means and suggest solutions (not everyone knows this), and also report the url it tried to download; finally, it should proceed with the import and save the file url just as an linked url in the file field.

Solution: 

1. Improve the error message in https://github.com/JabRef/jabref/blob/e34cd37ea3af7f8997bb1eadf1640431cb471c20/src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java#L475-L478

Include the URL in the error message

For a reference/similar handling, see:  
https://github.com/JabRef/jabref/blob/e34cd37ea3af7f8997bb1eadf1640431cb471c20/src/main/java/org/jabref/gui/EntryTypeViewModel.java#L154-L162

3. Store the url in the file field of the corresponding entry

_Originally posted by @tobiasdiez in https://github.com/JabRef/jabref/issues/9816#issuecomment-1529439931_

### PR DESCRIPTION
**Pull request by DohaRamadan**
I added error specific message for when a download from URL fails. 
Fixes #9826

### Mandatory checks
- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by DohaRamadan** [comment]
There are 2 tests in org.jabref.logic.l10n.LocalizationConsistencyTest that are failing, The first is because there is a space at the end of the sentence that I'm willing to fix, but the second test is findMissingLocalizationKeys and I don't really understand what it does or why it fails, any help?

**Comment by Siedlerchr** [comment]
The missing l10n key fails because you added new Strings using localisation Lang

See https://devdocs.jabref.org/code-howtos/localization.html

**Comment by DohaRamadan** [comment]
> The missing l10n key fails because you added new Strings using localisation Lang
> 
> See https://devdocs.jabref.org/code-howtos/localization.html
 I edited the LinkedFileViewModel based on the documentation hints to be: 
 ```
          if (ex instanceof FetcherClientException clientException) {
                    statusCode = clientException.getStatusCode();
                    if (statusCode == 401) {
                        dialogService.showInformationDialogAndWait(Localization.lang("Failed to download from URL"), Localization.lang("401 Unauthorized: Access Denied. You are not authorized to access this resource. Please check your credentials and try again. If you believe you should have access, please contact the administrator for assistance.\nURL: %0 \n %1", urlDownload, fetcherExceptionMessage));
                    } else if (statusCode == 403) {
                        dialogService.showInformationDialogAndWait(Localization.lang("Failed to download from URL"), Localization.lang("403 Forbidden: Access Denied. You do not have permission to access this resource. Please contact the administrator for assistance or try a different action.\nURL: %0 \n %1", urlDownload, fetcherExceptionMessage));
                    } else if (statusCode == 404) {
                        dialogService.showInformationDialogAndWait(Localization.lang("Failed to download from URL"), Localization.lang("404 Not Found Error: The requested resource could not be found. It seems that the file you are trying to download is not available or has been moved. Please verify the URL and try again. If you believe this is an error, please contact the administrator for further assistance.\nURL: %0 \n %1", urlDownload, fetcherExceptionMessage));
                    }
                } else if (ex instanceof FetcherServerException serverException) {
                    statusCode = serverException.getStatusCode();
                    dialogService.showInformationDialogAndWait(Localization.lang("Failed to download from URL"),
                                Localization.lang("Error downloading form URL. Cause is likely the server side. HTTP Error %0 \n %1 \nURL: %2 \nPlease try again later or contact the server administrator.", statusCode, fetcherExceptionMessage, urlDownload));
                    } else {
                        dialogService.showErrorDialogAndWait(Localization.lang("Failed to download from URL"), Localization.lang("Error message: %0 \nURL: %1 \nPlease check the URL and try again.", fetcherExceptionMessage, urlDownload));
                    }
                });

```
But still the findMissingLocalizationKeys Test fails with error: 
```
Expected :[]
Actual   :[401 Unauthorized: Access Denied. You are not authorized to access this resource. Please check your credentials and try again. If you believe you should have access, please contact the administrator for assistance.\nURL: %0 \n %1 (src\main\java\org\j ...

```

**Comment by Siedlerchr** [comment]
Yes, you nee to see the output of the test, it says you should add the new ones to src/main/resources/l10n/en.properties

**Comment by DohaRamadan** [comment]
Thank you for clarifying this, I wasn't sure where was i supposed to add the error messages, I added them and all LocalizationConsistencyTest tests pass now, Should I make another pull request for this update?

**Review by Siedlerchr — APPROVED** [review]

**Comment by Siedlerchr** [comment]
Can you please add a changelog entry?
Make sure that you add it to the unreleased section

**Review by Siedlerchr — APPROVED** [review]

**Pull request merged**
