### PR TITLE
Improvements to search

### PR DESCRIPTION
**Pull request by tobiasdiez**
Cleaned-up version of #162.

### CODE REVIEW

**Comment by simonharrer** [comment]
Can you please remove the `DONE` tags in your comments?

**Comment by tobiasdiez** [comment]
DONE :sunglasses:

**Comment by koppor** [comment]
Sorry for being picky at the formatting. When reading the diff, the indents don't seem to be right. Besides the content of the code, we also want to have the formatting consistent to ease newcomers to read and understand the code.

Do you use Eclipse or IntelliJ? With the recent master, `gradlew cleanEclipse eclipse` should generate an Eclipse config with the right indent settings.

**Comment by tobiasdiez** [comment]
@koppor I totally agree about the formatting/indenting issues. However, the last time I run the formatter on the files resulted in many formatting changes. Is it possible that you run the formatter on the files after accepting the PR? Otherwise, my commit will be again screwed. 
Moreover, yes the searched text should be always highlighted. I don't understand the purpose of the preference. Maybe this should be done in a new PR.
The split button is necessary because both sides of the button are clickable whereas for a combobox only the right is clickable.

**Comment by koppor** [comment]
I will discuss that with the other developers. Meanwhile, I'd like to ask whether you are aware that [git gui](https://git-scm.com/docs/git-gui) can do line-based committing: Mark the lines to commit, right click, choose "stage lines to commit". Then, you can collect only the "important" modified lines. I would propose to do the formatting and create a new commit. Amending does not work as your PR already consists of two commits. You could use `git rebase -i` and then "fixup" the last two commits (DONE and formatting) into the first one. Afterwards, you have to do a `git push -f` ("force overwrite existing branch" in git gui). BTW: As far as I remember, it is possible to mark some lines in the code and then push "CTRL+SHIFT+f" to format. Then, the line-based commit is not necessary; only the merging of the three commits into one ("fixup" at `git rebase -i`).

**Comment by koppor** [comment]
I created a new branch `uisearchhistory` and merged the content there. We will continue working on the code there. Hope, that's OK!

**Pull request closed without merging**
