### PR TITLE
Adding an advanced data structure for Title/Word in the CaseChangers …

### PR DESCRIPTION
**Pull request by simonharrer**
…implementation.

@koppor this is what I ment. What do you think?

### CODE REVIEW

**Comment by koppor** [comment]
While trying to make test cases, I discovered `net.sf.jabref.bst.BibtexCaseChangersTest.testChangeCase()`, which seems to cover most of our wishes and even can handle intra word casings correctly: `Vall{\\'e}e` -> `VALL{\\'E}E`. `HAllo {worLD}. HOW` -> `hallo {worLD}. how`.

I would suggest to remove `CaseChangers` completely and to use `net.sf.jabref.bst.BibtexCaseChanger` only to avoid code redundancy. I am aware that the code of BibtexCaseChanger is more ugly than the current code of CaseChangers, but it covers the strange cases (e.g., case also LaTeX characters).

**Comment by simonharrer** [comment]
I will have a look. But the bst package is a candidate to be thrown away as
it is unmaintainable.
Am 09.10.2015 6:26 nachm. schrieb "Oliver Kopp" <notifications@github.com>:

**Comment by simonharrer** [comment]
I had a look: The CaseChangers have Title, Upper, Lower, UpperEachFirst and UpperEach whereas the BibtexCaseChangers only have Title, Upper and Lower. Small words are not detected in the BibtexCaseChangers algorithm. The only thing that the BibtexCaseChangers are better in is the detection of special latex characters like umlauts. 

From my perspective, the BibtexCaseChangers class is hard to maintain. And it is used heavily in the `bst` package, making it very hard to improve the class as its interface has to stay the same. I think the current solution is good enough for a lot of use cases already. We would loose a lot and gain too little if we would replace the CaseChangers by the BibtexCaseChangers.

I would suggest to leave the BibtexCaseChangers class alone, and in the future remove the `bst` package and replace it with something else. Or just delete it. ;)

If someone has really a lot of time, they can use the test cases to drive an improved CaseChangers version. One simply has to determine a different `boolean[] protectedChars` array based on the title, namely, to not make every char within curly braces protected.

**Comment by koppor** [comment]
I made the interface a bit more modern (using enum instead of char as parameter). Still procedural style than object oriented, but for that use case, I think procedural style is more fitting. :innocent:

I made test cases based on https://github.com/JabRef/jabref/pull/176#issuecomment-14272379 at https://github.com/JabRef/jabref/blob/03703a5517601c3e38f5f9a68a6f7d15ff760460/src/test/java/net/sf/jabref/bst/BibtexCaseChangersTest.java#L107. Think, it's time for a call.

**Pull request merged**
