### PR TITLE
Cleanup and format some files

### PR DESCRIPTION
**Pull request by tobiasdiez**
Run cleanup and format in eclipse on some files to make comparison in #162 easier.

### CODE REVIEW

**Comment by koppor** [comment]
Regarding the `private final AbstractAction toggleGroups = new GeneralAction` statements (see my second comment), you don't agree?

**Comment by matthiasgeiger** [comment]
@koppor I agree. But I think, this behavior was introduced by a change you made in 77d1ea868c3381d78b19f5e15a1364de9033eb2a - using this setting IntelliJ creates endless lines using auto-format.

**Comment by tobiasdiez** [comment]
I don't have a strong opinion about this. Sometimes it is more important to see what variables exists (then the new formatting is better) and sometimes you are more interested in how the initialization is done (then the old formatting is better). So should I revert this too?

**Comment by koppor** [comment]
Yeah. I thought, I did run the gradle formatter plugin, but it seems, it didn't touch that file somehow :(

@tobiasdiez Could you revert and add @formatter:on/off strings? I prefer to see the initialization code :innocent: That would really help!

----- Ursprüngliche Nachricht -----
Von: "Matthias Geiger" <notifications@github.com>
Gesendet: ‎17.‎09.‎2015 09:09
An: "JabRef/jabref" <jabref@noreply.github.com>
Cc: "Oliver Kopp" <koppdev@googlemail.com>
Betreff: Re: [jabref] Cleanup and format some files (#166)

@koppor I agree. But I think, this behavior was introduced by a change you made in 77d1ea8 - using this setting IntelliJ creates endless lines using auto-format.

**Comment by simonharrer** [comment]
What is the current state of the eclipse xml @koppor @matthiasgeiger

**Comment by matthiasgeiger** [comment]
Updated after discussion with @koppor in 0fd8a0c

**Comment by koppor** [comment]
As new formatter rules are in place, we should close this and follow up at #249.

**Comment by matthiasgeiger** [comment]
:+1:

**Pull request closed without merging**
