### PR TITLE
Fixed typo that prevented ant builds

### PR DESCRIPTION
**Pull request by nikmilpv**

### CODE REVIEW

**Comment by koppor** [comment]
What do you mean by "prevent ant builds"? Even with the patch, `ant jars` outputs `Compile failed; see the compiler error output for details.`, because the compiler cannot find certain packages.

`gradlew antTargets.release` runs through even without the patch.

`Apache Ant(TM) version 1.9.5 compiled on May 31 2015`. Which version do you have, what is your output?

**Comment by nikmilpv** [comment]
I'm building on Linux. Without the patch, both `./gradlew antTargets.jars` and `./gradlew antTargets.release.linux` fail, because the compiler can't find the dependencies. On the other hand, `./gradlew generateSource` and `./gradlew jar` run fine.

After some digging around, I found that paths in `configurations.compile.asPath` are separated by `:` instead of `;`, at least on Linux, don't know if thats the case on other platforms.

I haven't tried `ant jars` and I doubt it will work, because the paths to dependencies are now passed through gradle.

**Comment by koppor** [comment]
It is different on Linux and Windows. I wrapped the thing in an if statement :). Thank you for testing and providing a PR.

**Comment by nikmilpv** [comment]
Sure, no problem :)

**Pull request merged**
