### PR TITLE
Remove edit preamble and edit strings from toolbar. It is still avail…

### PR DESCRIPTION
**Pull request by simonharrer**
…able under the bibtex menu.

### CODE REVIEW

**Comment by koppor** [comment]
May I ask, why? I have to confess, that I only use the "push to application" icon to change the application where I push my entry to (as I don't know, where else to change).

There are also "mark entry" related buttons in the toolbar. - Is the reason that the removed functionality is used seldomly? Would it make sense to add it to the context menu of the database tab, because it somehow affects the whole database?

Refs #113

**Comment by oscargus** [comment]
I use strings quite regularly (a common .bib file with correct abbreviations for journals and conferences) but always access it in the menu. Now that I know there is an icon, I do not want to get rid of it. ;-)

Preamble I've never even used. But I think it is OK to remove the strings icon as well. Either way, there may be a slightly more intuitive way to group these and nearby icons.

**Comment by oscargus** [comment]
Oh, and add it to the context menu of the database tab would clearly be a good idea (it = strings), or maybe an edit menu with subitems preamble and strings (and encoding?).

**Comment by simonharrer** [comment]
Hm, this may open the box of pandora. Discussing the menu maybe should be done in a separate issue? Because I see a lot of issues with the current menu/UI.

**Comment by stefan-kolb** [comment]
I don't know if we should remove both functionalities from the toolbar. I strongly second removing the preamble icon tho!

**Comment by simonharrer** [comment]
Okay, removing only the "edit preamble" for now as this has the most consensus. The other things we have to discuss somewhere else.

**Pull request merged**
