### PR TITLE
Dev 2.11:  Add of Persian localization (by Behrouz Javanmardi)

### PR DESCRIPTION
**Pull request by mlep**

### CODE REVIEW

**Comment by stefan-kolb** [comment]
@mlep This PR is missing the JabRef Bundle. will this be added soon? This is not a complete localization.

**Comment by mlep** [comment]
I am not sure what you mean by  "missing the JabRef Bundle".
The menu have been translated, but not the strings for JabRef_fa.properties. Is it the issue?

**Comment by stefan-kolb** [comment]
Correct, I mean JabRef_fa.properties.

**Comment by mlep** [comment]
I am going to contact the translator. A proposed deadline?
Should an untranslated file JabRef_fa.properties be added to the repository? (I mean a file with only the strings to be translated)

**Comment by stefan-kolb** [comment]
We will add an untranslated file for now.

**Pull request merged**
