### PR TITLE
Remove the option move-to-systray

### PR DESCRIPTION
**Pull request by simonharrer**
Why?

- only applications that do background work are put in the systray, e.g., Dropbox or Anti-Virus-software. 
- other software stays in the normal task bar
- JabRef currently does no background stuff, hence, should stay in the task bar only

Gains?

- less code
- lesser quirky workarounds (see commit)

### CODE REVIEW

**Comment by koppor** [comment]
Think, that was a use case when screens weren't large. Regarding the alternativeto.net infopage about [TrayIt!](http://alternativeto.net/software/trayit-/), it seems that generic tools for that are also vanishing. Think [RBTray](http://rbtray.sourceforge.net/) is a good solution for users still wanting this functionality.

**Comment by stefan-kolb** [comment]
Do any other OS than Windows support this functionality? With the addition of pin to taskbar and Window grouping this should be near obsolete in my opinion. Therefore, giving a weak :+1:

**Comment by ThomasA** [comment]
I don't know about this specific way of implementing it, but Ubuntu also 
has a "systray" (I don't know if that's what they call it, but a small 
icon area in the top right part of the desktop where "background" 
services are shown. For example Skype and Dropbox.)

**Comment by koppor** [comment]
Let's see whether users want that feature back. Then we can discuss about reverting this merge :innocent:

**Comment by matthiasgeiger** [comment]
Should be added to the CHANGELOG

**Comment by simonharrer** [comment]
Done in master branch

2015-10-07 11:22 GMT+02:00 Matthias Geiger <notifications@github.com>:

**Pull request merged**
