### PR TITLE
Make sure that unregistered event sources do not stop JabRef from shu…

### LINKED ISSUE #2486: Force Shutdown after accepting external changes
JabRef 3.8.1-dev
windows 7 6.1 amd64 
Java 1.8.0_92

External changes mean that JabRef will no longer shut down normally and you have to force kill the process.

Steps to reproduce:

1. Open a database in JabRef
2. Change the file externally
3. JabRef notices external changes
4. Review and accept all external changes
5. Try closing the window (click on X). JabRef refuses to shut down and the following message appears in the error console.

```
14:38:15.275 [AWT-EventQueue-0] INFO  net.sf.jabref.logic.importer.OpenDatabase - Opening: \\nas-a1\redirected$\jorglenh\Desktop\test.bib
14:38:39.993 [AWT-EventQueue-0] ERROR net.sf.jabref.FallbackExceptionHandler - Uncaught exception Occurred in Thread[AWT-EventQueue-0,6,main]
java.lang.IllegalArgumentException: missing event subscriber for an annotated method. Is net.sf.jabref.logic.autosaveandbackup.BackupManager@7772aed registered?
	at com.google.common.eventbus.SubscriberRegistry.unregister(SubscriberRegistry.java:111) ~[guava-20.0.jar:?]
	at com.google.common.eventbus.EventBus.unregister(EventBus.java:201) ~[guava-20.0.jar:?]
	at net.sf.jabref.model.metadata.MetaData.unregisterListener(MetaData.java:257) ~[main/:?]
	at net.sf.jabref.logic.autosaveandbackup.BackupManager.shutdown(BackupManager.java:149) ~[main/:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_92]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_92]
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1548) ~[?:1.8.0_92]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_92]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_92]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_92]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_92]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_92]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_92]
	at net.sf.jabref.logic.autosaveandbackup.BackupManager.shutdown(BackupManager.java:85) ~[main/:?]
	at net.sf.jabref.gui.JabRefFrame.quit(JabRefFrame.java:859) ~[main/:?]
	at net.sf.jabref.gui.JabRefFrame$CloseAction.actionPerformed(JabRefFrame.java:1778) ~[main/:?]
	at net.sf.jabref.gui.JabRefFrame$2.windowClosing(JabRefFrame.java:604) ~[main/:?]
	at java.awt.AWTEventMulticaster.windowClosing(AWTEventMulticaster.java:349) ~[?:1.8.0_92]
	at java.awt.Window.processWindowEvent(Window.java:2054) ~[?:1.8.0_92]
	at javax.swing.JFrame.processWindowEvent(JFrame.java:305) ~[?:1.8.0_92]
	at java.awt.Window.processEvent(Window.java:2013) ~[?:1.8.0_92]
	at java.awt.Component.dispatchEventImpl(Component.java:4889) ~[?:1.8.0_92]
	at java.awt.Container.dispatchEventImpl(Container.java:2294) ~[?:1.8.0_92]
	at java.awt.Window.dispatchEventImpl(Window.java:2746) ~[?:1.8.0_92]
	at java.awt.Component.dispatchEvent(Component.java:4711) ~[?:1.8.0_92]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) ~[?:1.8.0_92]
	at java.awt.EventQueue.access$500(EventQueue.java:97) ~[?:1.8.0_92]
	at java.awt.EventQueue$3.run(EventQueue.java:709) ~[?:1.8.0_92]
	at java.awt.EventQueue$3.run(EventQueue.java:703) ~[?:1.8.0_92]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_92]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76) ~[?:1.8.0_92]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) ~[?:1.8.0_92]
	at java.awt.EventQueue$4.run(EventQueue.java:731) ~[?:1.8.0_92]
	at java.awt.EventQueue$4.run(EventQueue.java:729) ~[?:1.8.0_92]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_92]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76) ~[?:1.8.0_92]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) ~[?:1.8.0_92]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [?:1.8.0_92]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_92]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_92]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_92]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_92]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_92]

```

### PR DESCRIPTION
**Pull request by lenhard**
…tting down

Fixes #2486. Unregistering event sources that have not been registered before should not stop JabRef from shutting down orderly. This PR logs such a problem instead of halting the shutdown of the program

- [X] Change in CHANGELOG.md described
- [X] Manually tested changed features in running JabRef

### CODE REVIEW

**Comment by Siedlerchr** [comment]
Would it be possible to first check if the event is registered and only doing a shutdown then?
This should be implemented at best in unregister itself

**Comment by lenhard** [comment]
@Siedlerchr: Unfortunately, the implementation of the event bus (from Google) supports no such checking functionality. Hence, we would have to remember subscribers in a custom list, which in my point of view would be an unnecessary overhead. However, I have now moved the exception handling code to all the different event sources in JabRef (I hope I found them all). That way, we catch the Exception as early as possible. I cannot think of a circumstance where trying to remove a listener that never listened should crash the complete application.

It is not always logged, though, since not all of the classes that are event sources use a logger. But again, I do not think that this is very tragic, or indeed important.

**Comment by Siedlerchr** [comment]
There is already discussion about checking it ... https://github.com/google/guava/issues/784
For fixing check style you should add the comments for switching it off at hat position;
http://stackoverflow.com/questions/4023185/how-to-disable-a-particular-checkstyle-rule-for-a-particular-line-of-code?noredirect=1&lq=1

**Comment by lenhard** [comment]
@Siedlerchr Sorry, but I am not getting your comment regarding checkstyle. 

The builds seem to fail because of the usual random fetcher errors.

**Comment by Siedlerchr** [comment]
@lenhard I meant the codacy, which will complain about the empty catch blocks.
It should work if you put around:
```
//CHECKSTYLE.OFF 
catch (Exception e)
//CHECKSTYLE.ON
```

**Comment by lenhard** [comment]
@Siedlerchr Ok, I understand. However, I am not too fond of codacy and refuse to add comments, just because the tool produces false positives. I am well aware that it is near impossible for a tool to tell if an empty catch block makes sense or not, but it is false positive nonetheless. The existing comment in there is meaningful to humans, which is way more important.

I just pushed a few minor formatting fixes.

**Comment by lenhard** [comment]
I'll take the "thumps-up" as an "ok-for-merge", which I'll do right away.

**Pull request merged**
