### PR TITLE
Change optional fields tabs

### LINKED ISSUE #4688: Entry Editor: change Optional Fields tab
entryoption

|Description of Issue|Possible Solution|  Warnings |
|:-----------------------------------------:|:-------------------------------------------------:|:---------------:|
|Optional information is split between tabs (e.g. _deprecated fields_,_optional fields 2_)|unify all information that is not mandatory in the _optional fields_|if the number of fields gets large, make the liest of fields scrollable or reduce text field size|
| text fields are too big (height and width) to give a good overview of information|reduce size of text fields| -|
|dropdown fields look too similar to text fields (month)|make dropdown fields more unique| -|
|ISBN has a special role;|_ISBN_ and other identifiers are migrated to _Web Resources_|-|
|-|-|other changes are found in #4686 |

### PR DESCRIPTION
**Pull request by a1819644**
Fixes #4688

The changes we have made are the followings : 
-  delete OtherFieldsTab.java class, OptionalFields2Tab.java files from the jabref
   why-> as we were merging the optionalfields tab and otherFieldsTab, these both java class files existence were not required        anymore. Hence got deleted. 

- Deleted +136 to +151 lines of code from FieldEditorTab.java 
   why->these lines of the codes were responsible the column division. As a result of this merged text field were looking ugly(see the fig-1.1 and fig-1.2)
fig 11
fig 1 1 column issue

-  updated the code of the OptionalsTabBase.java 
   why-> we wrote the codes for merging the field of the requested tab. 

---> Tittle pr : Fix issue #4688 by UofA

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [x] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

How to see the fix: 
1. Create a new lib 
image

2. Click on the "new Entry" as marked on the snapshot and then add the doi of any article or your preferred the document type.
image

3. Last thing is just double click on the entry to see the changes. 
image

### CODE REVIEW

**Comment by ThiloteE** [comment]
Thank you for the PR :-) This still needs a few changes though. I tried the pr and for the following entry no optional fields are showing in the `optional fields` tab apart from the `files` field:
```
@Article{test,
  author = {test},
  file   = {:unknown file.txt:Text;:testpdf.pdf:PDF},
}
```

See here:
grafik

On the plus side: the `other fields` tab is gone :)

**Comment by a1819644** [comment]
> 

Ohh, sure I will have a look as soon as possible.

**Comment by calixtus** [comment]
Thanks for your interest in JabRef development.

As your changes are affecting several fundamental concepts of the JabRef entry editor UI please provide some rationale for your changes, preferably in an ADR (https://devdocs.jabref.org/adr.html) discussing the pros and cons with proper constraints (can be kept short), so we could make a decision about the further ui development in the next devcall.

Please mind that biblatex itself is distinguishing between required entry fields and optional entry fields. Yet there are still fields left, that are not used by the entry field description for an entry type (the formerly called 'other fields') and the deprecated fields, that biblatex is not using anymore. I totally agree that using multiple tabs to provide access to the optional fields, the other fields and deprecated fields is not the most intuitive and understandable way. If you decide to merge the tabs for different kinds of fields - what you can do - you still need to somehow distinguish between the different kind of fields for an entry type, so it is clear for the user, which fields are not part of the biblatex standard (https://ctan.ebinger.cc/tex-archive/macros/latex/contrib/biblatex/doc/biblatex.pdf) and which are not. Maybe a small heading between the tabs is possible or to display them in a slightly different color...

Also mind that the compressed version of the entry editor is especially provided in case someone wants to put the entry preview in a seperate tab. In that case the fields would take the whole width of the entry editor. This is in my eyes a total waste of screen space as well as needless scrolling around in the entry editor to find the right field. Just because 'it's ugly' is imho no argument at all. Maybe a better approach would be to make the compressed view of the empty editor dependend on if the preview tab is shown seperately?

Also you should create only one pull request per feature change. In this PR we need to handle now two completly different issues (abandon the compressed view AND merge the different tabs for fields) in one. What if we agree to merge one, but not the other?

Thanks!

**Comment by calixtus** [comment]
Any update here?

**Comment by ThiloteE** [comment]
Closing this pr to reduce the number of open pull-requests. (This pr definitely cannot be merged in this stage and the pr looks kinda stale).

Feel free to reopen, once/if you decide to continue working on this.

**Pull request closed without merging**
