### PR TITLE
Introduce formatter to remove word-enclosing braces 

### LINKED ISSUE #11222: Introduce formatter to remove word-enclosing braces
We have `RemoveBracesFormatter`, which removes the outer braces. See org.jabref.logic.formatter.bibtexfields.RemoveBracesFormatterTest for examples.

We have `org.jabref.model.entry.Author#removeStartAndEndBraces`, which also removes inner braces enclosing complete words:

* `{Vall{\'e}e} {Poussin}` -> `Vall{\'e}e Poussin` <-- here, `{Poussin}` is changed to `Poussin`. This is not available to users (in the [cleanup entry dialogue](https://docs.jabref.org/finding-sorting-and-cleaning-entries/cleanupentries))
* `{Vall{\'e}e Poussin}` -> `Vall{\'e}e Poussin` <-- here, the outer braces are removed
* `Vall{\'e}e Poussin` -> `Vall{\'e}e Poussin` <-- here, everything is kept as is

We should make this formatter "globally" available:

1. Rename `RemoveBracesFormatter` to `RemoveEnclosingBracesFormatter`. 
   - Also rename all used fields.
2. Introduce `RemoveWordEnclosingAndOuterEnclosingBracesFormatter` by moving the code of `org.jabref.model.entry.Author#removeStartAndEndBraces` to here
   - Introduce class
   - Create test cases (similar to `RemoveBracesFormatterTest`)
   - Replace call to `removeStartAndEndBraces`  in Author to call to `RemoveWordEnclosingAndOuterEnclosingBracesFormatter.format`. The `RemoveWordEnclosingAndOuterEnclosingBracesFormatter` needs to be initialized as class constant in `Author`
   - Name the formatter `"Remove word enclosing braces"`
   - Use description `"Removes braces encapsulating a complete word and the complete field content."`
3. Create a pull request for the user documentation (update the page https://docs.jabref.org/finding-sorting-and-cleaning-entries/saveactions#remove-enclosing-braces).

### PR DESCRIPTION
**Pull request by rohit-garga**
Closes  #11222 

### Mandatory checks

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by rohit-garga** [comment]
Apologies for not creating a seperate branch, just realised that I forgot to do that. Also is there a way to run all the unit tests locally first?

**Comment by subhramit** [comment]
> Apologies for not creating a seperate branch, just realised that I forgot to do that. Also is there a way to run all the unit tests locally first? 

I think you're looking for ````gradlew test``

**Comment by koppor** [comment]
> Apologies for not creating a seperate branch, just realised that I forgot to do that. Also is there a way to run all the unit tests locally first?

We have to apologize that we have "(optional)" in our DevDocs. See https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace/intellij-12-build.html#final-build-system-checks-optional

Please follow these steps to see how tests can be executed locally.

I think, I need to remove "(optional)" in the heading, don't it?

**Comment by subhramit** [comment]
> > Apologies for not creating a seperate branch, just realised that I forgot to do that. Also is there a way to run all the unit tests locally first?
> 
> We have to apologize that we have "(optional)" in our DevDocs. See https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace/intellij-12-build.html#final-build-system-checks-optional
> 
> Please follow these steps to see how tests can be executed locally.
> 
> I think, I need to remove "(optional)" in the heading, don't it?

Yes, I too ignored that section because of optional written on it, as I wanted to get started with the development fast.

**Comment by rohit-garga** [comment]
Thanks for the prompt response.
@koppor The link that you are pointing to shows how to run automated tests in a single class. I was looking for a way to run all unit tests locally before committing, am I missing something? 
I have noted that I need to push a new branch, I could not find a clean way to change the branch for this PR so I will close this one and open a new PR.

**Pull request closed without merging**
