### PR TITLE
TLS for worldcat

### PR DESCRIPTION
**Pull request by KOLANICH**

### CODE REVIEW

**Comment by Siedlerchr** [comment]
Please make sure that you manually execute the fetcher tests on your system to ensure that they are working. As the CI server is blocked,, some fetcher tests are disabled

**Comment by KOLANICH** [comment]
I have not run any tests, I even don't have any tools to build java apps installed. I only been opening the sites in a browser, and if that worked, I had added `s`.

**Comment by Siedlerchr** [comment]
I really recommend setting up the workspace https://github.com/JabRef/jabref/wiki/Guidelines-for-setting-up-a-local-workspace

**Comment by KOLANICH** [comment]
In fact I have no plans being seriously involved into developing it, since it is written in Java, and I dislike Java and JVM. I may either drop some python code (see https://github.com/open-source-ideas/open-source-ideas/issues/46 for my plans and the features I need, I guess it is partly implemented in JabRef, but there are many features it lacks, like reconstructing bookmarks tree from text (doing this requires classification the pieces of text into labels for their structure role, like "h1 header", "h2 header", I guess it can be solved by clustering fonts and then sorting them by size, and then extracting some features and [xgboosting](https://github.com/dmlc/xgboost))) in future, letting someone else to translate it into Java.

**Comment by Siedlerchr** [comment]
Sorry to hear that you don't like Java, it's actually pretty neat once you are familiar with it. Don't let you fool by the guys who tell you it's not fast, since its beginnings Java has improved very well.

Have you tried the XMP importer/exporter for metadata and for pdfs, we also support annotations, e.g. comments. And we also want to soon extend the search to cover fulltext in pdfs.
For working with PDFs we use  pdfbox https://pdfbox.apache.org/

**Comment by KOLANICH** [comment]
>Sorry to hear that you don't like Java, it's actually pretty neat once you are familiar with it. Don't let you fool by the guys who tell you it's not fast, since its beginnings Java has improved very well.

Thank you for the info. But not now, for now I'm pretty busy.

>Have you tried the XMP importer/exporter for metadata and for pdfs

I have.

>And we also want to soon extend the search to cover fulltext in pdfs.

I guess there are more suitable projects for fulltext search.

For integration java (non-java brings some problems for now) modules into python code I can use jpype.

**Comment by koppor** [comment]
Fetcher tests run through, so I merge. Thank you for the PR.

**Pull request merged**
