### PR TITLE
Improve citation relations

### PR DESCRIPTION
**Pull request by ror3d**
Includes more information in the requests to Semantic Scholar to make the Citation Relations tab more useful.
Adds a button in the relations display to open the DOI url (or the semantic scholar url if no DOI) in the browser, to be able to explore that article before adding it to the library.
Implements part of what is discussed in #10869

image

### Mandatory checks

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [x] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by ror3d** [comment]
About the OpenRewrite check complaining:
I could change the StringBuilder with a String for the `org.openrewrite.staticanalysis.ReplaceStringBuilderWithString` complaint, although before the refactor it was a stringbuilder and it made more sense to me that it was kept like that, since the functionality it had before was exactly the same as now, but now it is just able to detect that there aren't any special things done with the builder, I guess.
About the other complaint `org.openrewrite.java.ShortenFullyQualifiedTypeReferences` in `src/main/java/org/jabref/gui/entryeditor/citationrelationtab/CitationRelationsTab.java`, I have no idea what that is referring to.

**Comment by Siedlerchr** [comment]
Regarding the openRewrite checks: The best thing about it, you can just execute it and let openrewrite fix it for you:
`Run 'gradle rewriteRun' to apply the recipes.`
Motivation for Stringbuilder https://docs.openrewrite.org/recipes/staticanalysis/replacestringbuilderwithstring

**Review by Siedlerchr — APPROVED** [review]

**Comment by Siedlerchr** [comment]
Sorry for the late review, I just improved the optional handling a bit more using the functional style the rest was good

**Comment by ror3d** [comment]
Ah thanks for that, I'm really not used to that kind of syntax

**Pull request merged**
