### PR TITLE
Add hide button for user comments

### PR DESCRIPTION
**Pull request by koppor**
Fixes https://github.com/JabRef/jabref/issues/10424 by adding a button.

By default the user comments will be shown. However, there is now a button to make it possible to hide the field.
It can be re-activated in the preferences. 

This PR also refs https://github.com/JabRef/jabref-issue-melting-pot/issues/268 and makes use of the new JDK21 data structures. (See https://openjdk.org/jeps/431).

grafik

After pressing the button:
grafik

New preference option to re-enable: 

grafik

---

I am not sure about the label "Add". Maybe "Add JabRef-featured user-specific comment"? Exact, but too long.

---

Alternatives considered:

- Global preference to show the user-specific field --> too hidden for me - users won't find it
- Library-specific setting to enable --> requires pro-users to setup the .bib file accordingly (and much more coding effort)

### Mandatory checks

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by tobiasdiez** [comment]
I think this "add" functionality should go to the settings (probably in the form of a checkbox).

**Comment by calixtus** [comment]
I like the button. Makes the feature easier to find instead of looking in the prefs and activating, going back etc etc. Dynamically added, just missing a remove button now.

Label maybe "Add user comment"?

**Comment by koppor** [comment]
BTW nice that GitHub renders the arrow properly

**Comment by koppor** [comment]
Whitespace: This is the best I could come up with. -- Without massive EntryEditor refactoring. Maybe you have an idea how to stack the button below the gridpane?

Priority: Debatable how to make features prominent and accessible in JabRef. Our welcome screen (for new users) is still a TODO. And this would be one item for it...

**Comment by koppor** [comment]
When working in group, someone might not want to add comments while others do

I'll add a preference to disable the feature

**Comment by tobiasdiez** [comment]
> Whitespace: This is the best I could come up with. -- Without massive EntryEditor refactoring. Maybe you have an idea how to stack the button below the gridpane?

Negative bottom margin/padding?

> Priority: Debatable how to make features prominent and accessible in JabRef. Our welcome screen (for new users) is still a TODO. And this would be one item for it...

My philosophy would be to present actual functionality to the users, and less so configuration options. Config options in the main view are only a good idea if you often need to switch between different options depending on context (e.g. union vs intersection select for groups, different toggles for search). For the user comments: If you don't use the feature, the button doesn't give you any value. If you do use the feature, then you are annoyed that you have to click the button every time.

I think it would make more sense for visibility if you write a nice documentation page with "consider these options if you work in a team".

**Comment by calixtus** [comment]
Negativ padding is the highway to ui hell.
Honestly, I think the whitespace gap is ok.

**Comment by Siedlerchr** [comment]
After thinking about I think it makes sense to show the user specific comment by default and then add a button: Hide comment with a notification that this can be re-activated in the prefs.
After the user clicked hide the button is no longer shown

**Comment by Siedlerchr** [comment]
Github currently has issues...

**Comment by Siedlerchr** [comment]
entry editor preferences needs to be mocked for gui test

**Comment by koppor** [comment]
Looks OK. However, user-specific comments not sorted well. The idea was to put the general comment field fiirst and then the user-specific comments. Currently, it is a mix:

- first own-comments
- then general comments
- then comments from other users

grafik

It should be 

- first: general comments
- then comments from other users and own - sorted by username.

**Comment by Siedlerchr** [comment]
Okay, I see what I can do

**Pull request merged**
