### PR TITLE
syncLang.py: link in markdown output

### PR DESCRIPTION
**Pull request by mlep**
To allow for a more direct edit of the localization files.

Please, triple check, I am in no way a python programmer.

- [ ] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [ ] Screenshots added (for bigger UI changes)
- [ ] Manually tested changed features in running JabRef
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)
- [ ] If you changed the localization: Did you run `gradle localizationUpdate`?

### CODE REVIEW

**Comment by koppor** [comment]
Tried id out locally - and it works. Thank you for the PR!

**Comment by lynyus** [comment]
as a follow up: I have tested it as well, works.

What about automatically generating this data with each push to master and publish a html version on jabref.org?

**Comment by mlep** [comment]
It would be nice!

**Comment by mlep** [comment]
Although: it would be nice if the order of the languages would be always the same.

**Comment by lynyus** [comment]
That should be feasible. Is that all the requirements you can think of? I would volunteer to program that. Would you be so kind to file an issue to separate the discussion and point out all potential requirements?

**Comment by mlep** [comment]
Done (Issue #3181)

**Pull request merged**
