### PR TITLE
[WIP] Adapt log4j configuration for junit tests

### LINKED ISSUE #3510: Only log failed junit tests in travis
Currently, all stuff from all tests is logged and printed out.
This makes it really hard to identify real failed tests, because some test throw exceptions, which are expected.
Nonetheless the internal JabRef logger log4j2 logs all this stuff, which makes it hard to find the real probelmatic issue

### PR DESCRIPTION
**Pull request by Siedlerchr**
Fixes #3510 

After searching and reading around I now set the log level to off. 
Failures are still reported, but the travis output is no longer cluttered

----

- [ ] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [ ] Screenshots added (for bigger UI changes)
- [ ] Manually tested changed features in running JabRef
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)
- [ ] If you changed the localization: Did you run `gradle localizationUpdate`?

### CODE REVIEW

**Comment by tobiasdiez** [comment]
For travis this is ok, but with this configuration no errors and warnings are reported during debug sessions of tests, right?

**Comment by Siedlerchr** [comment]
@tobiasdiez  This only applies if you run the tests through gradle. If you manually debug the test in the IDEA, it should be normal behaviour

**Comment by tobiasdiez** [comment]
I just tried it and sadly it does not work in IntelliJ. For example, the method `FileUtilTest.testRenameFileWithFromFileExistAndOtherToFileExist` currently prints an error, while with the proposed configuration nothing is displayed in the console.

**Comment by lenhard** [comment]
So what about this PR? It is marked as ready-to-review, but it seems it is not functional?

**Comment by lenhard** [comment]
Can we get some progress here? The travis log is really annoying at the moment. I'll add this to jabcon in the hope that it gets done then.

**Comment by Siedlerchr** [comment]
I think I have an idea: I commit my changes and add the files to .gitignore So it won't overwrite @tobiasdiez  changes on merge/pull right?

**Comment by stefan-kolb** [comment]
https://blog.turingg.com.au/configuring-how-exception-stack-traces-appear-in-log-entries-using-log4j2-e3a3dc5e48bc

**Pull request closed without merging**
