### PR TITLE
Fix order of other fields

### LINKED ISSUE #5028: Entry Editor: "Other fields"
current snap version on Fedora 30.

It seems to me that the algorithm that sorts what fields to show in the tab "other fields" is well identifying and showing those fields that are not default or optional. 
The algorithm does not seem to check whether a "custom" field is displayed in another tab.

Use case: I have defined as general fields a field called "teachingmodule" and show that field in a separate tab. However, it is also shown in tab "other fields". The latter seems not clean.

### PR DESCRIPTION
**Pull request by CyraxSector**
Fixes #5028 

----

- [ ] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [ ] Manually tested changed features in running JabRef
- [ ] Screenshots added in PR description (for bigger UI changes)
- [ ] Ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)

### CODE REVIEW

**Comment by Siedlerchr** [comment]
Thanks for your contribution. Could you please adjust your title of the PR and describe how/ or why the fix works? 
Thanks in advance

**Comment by CyraxSector** [comment]
@tobiasdiez sure I'll add comment descriptions for the next PRs. BTW I cannot merge this PR. Any reason?

**Comment by Siedlerchr** [comment]
Only members of the core JabRef development team are able to merge PRs. This is normal for most github organizations/projects. 
Each PR should ideally be reviewed by at least two JabRef core developers to maintain a high quality of the code base.

**Comment by CyraxSector** [comment]
@Siedlerchr sure. I thought the reason might be something like a CI build failure or any.

**Pull request merged**
