### PR TITLE
Fix XMP write

### PR DESCRIPTION
**Pull request by koppor**
Follow-up to https://github.com/JabRef/jabref/pull/8656 after feedback.

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by ThiloteE** [comment]
fixes #8657

**Comment by koppor** [comment]
We need the hacky workarounds because of Apache PDF Box 3.0 limitations

```
Save the document to a file using default compression.
Don't use the input file as target as this will produce a corrupted file.
```

**Comment by koppor** [comment]
Some other programmers might also have issues with corrupt PDFs: https://stackoverflow.com/q/68904812/873282

**Comment by koppor** [comment]
Think, we need a log bridge for `import org.apache.commons.logging.LogFactory;`

**Comment by koppor** [comment]
I set this ready-for-review. I can undo the logging change if you want. See https://www.slf4j.org/legacy.html

I "hacked" with `synchronized`, but it works :)

**Comment by Siedlerchr** [comment]
The logging change results in method too large on windows

**Comment by ThiloteE** [comment]
Now I get this error:

```
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: 1-based index not found: 11
	at com.google.common@31.1-jre/com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2055)
	at com.google.common@31.1-jre/com.google.common.cache.LocalCache.get(LocalCache.java:3966)
	at com.google.common@31.1-jre/com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3989)
	at com.google.common@31.1-jre/com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4950)
	at com.google.common@31.1-jre/com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4956)
	at org.jabref@100.0.0/org.jabref.logic.pdf.FileAnnotationCache.getFromCache(FileAnnotationCache.java:52)
	at org.jabref@100.0.0/org.jabref.gui.entryeditor.fileannotationtab.FileAnnotationTabViewModel.lambda$reloadAnnotations$1(FileAnnotationTabViewModel.java:104)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._enterNestedEventLoopImpl(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._enterNestedEventLoop(WinApplication.java:211)
	at javafx.graphics/com.sun.glass.ui.Application.enterNestedEventLoop(Application.java:515)
	at javafx.graphics/com.sun.glass.ui.EventLoop.enter(EventLoop.java:107)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.enterNestedEventLoop(QuantumToolkit.java:631)
	at javafx.graphics/javafx.stage.Stage.showAndWait(Stage.java:469)
	at javafx.controls/javafx.scene.control.HeavyweightDialog.showAndWait(HeavyweightDialog.java:162)
	at javafx.controls/javafx.scene.control.Dialog.showAndWait(Dialog.java:346)
	at org.jabref@100.0.0/org.jabref.gui.JabRefDialogService.showErrorDialogAndWait(JabRefDialogService.java:192)
	at org.jabref@100.0.0/org.jabref.gui.FallbackExceptionHandler.lambda$uncaughtException$0(FallbackExceptionHandler.java:26)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalStateException: 1-based index not found: 11
	at pdfbox@3.0.0-RC1/org.apache.pdfbox.pdmodel.PDPageTree.get(PDPageTree.java:316)
	at pdfbox@3.0.0-RC1/org.apache.pdfbox.pdmodel.PDPageTree.get(PDPageTree.java:297)
	at pdfbox@3.0.0-RC1/org.apache.pdfbox.pdmodel.PDPageTree.get(PDPageTree.java:243)
	at org.jabref@100.0.0/org.jabref.logic.pdf.PdfAnnotationImporter.importAnnotations(PdfAnnotationImporter.java:49)
	at org.jabref@100.0.0/org.jabref.logic.pdf.EntryAnnotationImporter.lambda$importAnnotationsFromFiles$2(EntryAnnotationImporter.java:53)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at org.jabref@100.0.0/org.jabref.logic.pdf.EntryAnnotationImporter.importAnnotationsFromFiles(EntryAnnotationImporter.java:53)
	at org.jabref@100.0.0/org.jabref.logic.pdf.FileAnnotationCache$1.load(FileAnnotationCache.java:39)
	at org.jabref@100.0.0/org.jabref.logic.pdf.FileAnnotationCache$1.load(FileAnnotationCache.java:36)
	at com.google.common@31.1-jre/com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3533)
	at com.google.common@31.1-jre/com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2282)
	at com.google.common@31.1-jre/com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2159)
	at com.google.common@31.1-jre/com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049)
	... 27 more

```

**Comment by Siedlerchr** [comment]
Works without erros for me.

**Comment by koppor** [comment]
Note to self: File Annotation Service worked better if temp file is written to

**Review by calixtus — APPROVED** [review]

**Pull request merged**
