### PR TITLE
Removes splash screen

### PR DESCRIPTION
**Pull request by simonharrer**
This PR removes both the splash screen and the CLI option to disable the splash screen. 

Why?
- splash screen on modern systems is shown only for a very short period of time as JabRef starts fast
- we should focus on making JabRef to start as fast as possible. A splash screen reduces the time to start the software as additional code needs to be executed. 
- for each new version (even for beta and dev versions), we have to check in a png with 200KB file size into the repository. This increases the amount of storage required for the git repository by 200KB for each version/dev-version.
- The splash screen interferes with using JabRef via the CLI. 
- It reduces code in JabRef. Hence, less code needs to be maintained.

This is a PR that is open for discussion. Please add any pros/cons as you see fit.

### CODE REVIEW

**Comment by stefan-kolb** [comment]
I second this proposal :+1:

**Comment by mlep** [comment]
Make sense to me.
Additionally, among the feature requests, I found only one related to the splash screen, and the request was about an option to disable it.

**Comment by ThomasA** [comment]
I guess I have always taken the splash screen for granted, but this 
proposal actually makes sense. I support it.

**Comment by koppor** [comment]
Something similar is wished at [sf feature request 884](https://sourceforge.net/p/jabref/feature-requests/884/).

Microsoft Office products also show a splash screen. but it is shown much quicker than in JabRef. In JabRef, the time to show the splash screen is the same as from the splash screen to the full app, isn't it? Furthermore, most other apps don't have any splash screen.

Therefore: :+1:

**Pull request merged**
