### PR TITLE
Convert DOAJ fetcher to new interface

### PR DESCRIPTION
**Pull request by tobiasdiez**
Previously, the DOAJ fetcher was able to get all results by pagination. This version is restricted to the first 20 entries; I think, this is enough for the moment.

----

- [ ] Change in CHANGELOG.md described
- [x] Tests created for changes
- [ ] Manually tested changed features in running JabRef
- [ ] Screenshots added in PR description (for bigger UI changes)
- [ ] Ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)

### CODE REVIEW

**Comment by stefan-kolb** [comment]
Should we really limit all fetchers to 20 results, even if they would support more?

**Comment by Siedlerchr** [comment]
same architecture violation as in your Springer fetcher

**Comment by tobiasdiez** [comment]
We have to specify some number, the default used by the API is 10. I've now increased the limit to 30. Do you think that suffices?

**Comment by tobiasdiez** [comment]
ok, I completely agree with this: we should support pagination at some point. However, it was not easy to integrate it in the current infrastructure and thus I left it out for the moment...

**Pull request merged**
