### PR TITLE
LateXToUnicode Formatter does not handle commands correctly

### PR DESCRIPTION
**Pull request by stefan-kolb**
that are a substring of a special LaTex command like \c \~ \'...

A big problem is to support all kinds of special circumstances in LaTeX code.
The only chance to get the real output is to use the value of a real LaTeX run for stripping LaTeX commands and stuff. Can we somehow write a wrapper for this? Then we could transfer all the hard work to the LaTeX interpreter.

```tex  
\documentclass{article}
\begin{document}
$\chi$ some other italic \textit{text}
\end{document}
```

https://github.com/mcmtroffaes/latexcodec/

### CODE REVIEW

**Comment by simonharrer** [comment]
@oscargus how much effort would this be to implement a solution? You are our expert for encodings. :)

**Comment by oscargus** [comment]
Regarding the encodings in general there is a quite substantial list. The weird thing, which I do not get, is that sometimes the Unicode characters ends up wrong. In the particular case `\chi` is not converted correctly (Unicode 967) while both `\phi` (966) and `\psi` (968) works without any problems... There is a related issue #1264 with another character `\v{S}` (352) behaving the same way. No obvious reason why exactly those characters should misbehave... In the latter case `\v{S}` is converted to a square, which can be converted back to `\v{S}`...

**Comment by oscargus** [comment]
Implemented in #1581

**Comment by matthiasgeiger** [comment]
Can delete the branch? @stefan-kolb @oscargus

**Pull request closed without merging**
