### PR TITLE
Extracted native Windows logic and fixed #194

### LINKED ISSUE #194: JabRef 2.11 beta4 starting problem in Windows XP or no more support for XP ?
I tried to run JabRef 2.11 beta4 in my virtual Windows XP (clean install).
I found that the beta 4 cannot start, but 2.10 stable can.
here you have the message : 
<pre>
C:\Program Files\JabRef>java -jar JabRef-2.11b4.jar
Exception in thread "main" java.lang.UnsatisfiedLinkError: Error looking up func
tion 'GetCurrentProcessExplicitAppUserModelID': The specified procedure could no
t be found.
        at com.sun.jna.Function.<init>(Function.java:208)
        at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:536)
        at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:513)
        at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:499)
        at com.sun.jna.Native.register(Native.java:1509)
        at com.sun.jna.Native.register(Native.java:1396)
        at com.sun.jna.Native.register(Native.java:1156)
        at net.sf.jabref.JabRef.<clinit>(Unknown Source)
        at net.sf.jabref.JabRefMain.main(Unknown Source)
C:\Program Files\JabRef>
</pre>

the same message for 2.10 under command line:
<pre>
C:\Program Files\JabRef>java -jar JabRef-2.10.jar
Found 2 plugin(s):
  - net.sf.jabref.core (jar:file:/C:/Program%20Files/JabRef/JabRef-2.10.jar!/plu
gins/net.sf.jabref.core/plugin.xml)
  - net.sf.jabref.export.misq (jar:file:/C:/Program%20Files/JabRef/JabRef-2.10.j
ar!/plugins/net.sf.jabref.export.misq/plugin.xml)
Opening: C:\Documents and Settings\PC\my.bib
</pre>
Is there something wrong, or just there is no more compability for XP ?
Thank you all.

<b>same error in 2.11 beta 3</b>
<pre>
C:\Program Files\JabRef>java -jar JabRef-2.11b3.jar
Exception in thread "main" java.lang.UnsatisfiedLinkError: Error looking up func
tion 'GetCurrentProcessExplicitAppUserModelID': The specified procedure could no
t be found.
        at com.sun.jna.Function.<init>(Function.java:208)
        at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:536)
        at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:513)
        at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:499)
        at com.sun.jna.Native.register(Native.java:1509)
        at com.sun.jna.Native.register(Native.java:1396)
        at com.sun.jna.Native.register(Native.java:1156)
        at net.sf.jabref.JabRef.<clinit>(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at net.sf.jabref.JabRefMain.main(Unknown Source)
</pre>

### PR DESCRIPTION
**Pull request by stefan-kolb**
This should fix the problem with Windows XP and Vista being unable to use the pin to taskbar feature.
However, I'm not certain if the feature works on Windows 7 and up.
My first tests on Windows 10 didn't allow me to pin JabRef.
We need to investigate this.

Likewise, we should also extract other OS-dependent logic from our code.

### CODE REVIEW

**Comment by simonharrer** [comment]
:+1: 

I am a little bit unsure about the underscore in the package name. Has a strange feeling to me. http://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html

**Comment by stefan-kolb** [comment]
Looks like the WinShell plugin is not working in our current setup.
I cannot find the AppUserModelID inside our *.lnk" file.
See http://stackoverflow.com/questions/5438651/launch4j-nsis-and-duplicate-pinned-windows-7-taskbar-icons

**Comment by simonharrer** [comment]
As far as I know we do not use the unicode version of NSIS, but the older one instead. 
NSIS 2.46 instead of 3.0b2

I am not sure if this ever worked. But it would be really helpful on windows machines.

**Comment by stefan-kolb** [comment]
WinShell on CircleCI build is working now:
```hex
J.a.b.R.e.f...2...8.0.d.e.v.-.-.s.n.a.p.s.h.o.t.-.-.2.0.1.5.-.1.0.-.0.2.
```

**Comment by stefan-kolb** [comment]
Should work correctly now only the pin option in the menu is not showing up.
http://stackoverflow.com/questions/1834599/pinning-a-java-application-to-the-windows-7-taskbar

**Comment by stefan-kolb** [comment]
Possible further taskbar stuff:
https://msdn.microsoft.com/en-us/library/dd378460(v=vs.85).aspx

**Comment by simonharrer** [comment]
Is there a use case to have different JabRef versions installed separately? Because we could just use the String "JabRef" for the AppID. Then, we do not need to pass around the current version number. This would make things a lot easier.

**Comment by mlep** [comment]
Useful for working with a version, and testing another one, no?

**Comment by koppor** [comment]
I think, testing can be done using `java -jar`. Other applications also don't enable installing of two different versions. This might also get difficult when having preferences updated (and downgraded?!)

**Pull request merged**
