### PR TITLE
Only update auto completion suggestions upon major changes

### PR DESCRIPTION
**Pull request by tobiasdiez**
Fixes https://github.com/JabRef/jabref/issues/2998. Reused logic from recent change to the backup manager to only propagate mayor changes.

- [x] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [ ] Screenshots added (for bigger UI changes)
- [x] Manually tested changed features in running JabRef
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)
- [ ] If you changed the localization: Did you run `gradle localizationUpdate`?

### CODE REVIEW

**Comment by iTao8** [comment]
@tobiasdiez I didn't see any improvement. The problems are still there.

**Comment by lenhard** [comment]
@iTao8 Please clarify. This is meant to fix https://github.com/JabRef/jabref/issues/2998#issuecomment-316968028 and from what I see it does. 

As Tobias wrote in the issue, there is nothing to be done about author duplicates and so far no one managed to replicate overlapping dropdown box here (I tried as well and couldn't).

**Comment by iTao8** [comment]
@lenhard 1. Do you mean no one can reproduce the overlapping dropdown box? 
2. I reported another problem in #2998: the autocompletion dropdown box for the journal field covers the input. When you are typing a journal name in the journal filed, the input was covered by the autocompletion dropdown box, so you can not see any inputing. 
3. I find new problems. I have a .bib for all my publications (20 papers) and my name are all listed as "Wang, Tao". When I input "Wang, Tao" in the search bar and click "enter", the input automatically changed to "Wang, T." and only ONE entry was found. 
4. Another problem. If I input "WangTao" in the search bar, and then I found this is wrong and want to move the cursor and insert a space between "Wang" and "Tao", but the left key and right key do not work.

**Comment by lenhard** [comment]
@iTao8 Thanks for clarifying! Here's my feedback:

1. Tobias and me have tried and couldn't reproduce it. I am not aware of anyone else trying, but as long as we can't reproduce this, we can't fix it.

2. Same here, no one could reproduce the overlap in the journal field (I tried just now). Maybe this is all OSX specific? @chochreiner Can you see how these things look on your machine?

3. This is already tracked in #3068 There are two simple solutions to this right now: 1. Don't hit enter. The main table will be sorted as you type anyway. 2. Instead of enter, hit escape. Then the autocompletion suggestions go away.

4. This one I can reproduce :) And I agree with you that the left and right keys should work differently. Could you open a new issue for this? @Siedlerchr This is about key bindings (again). Can you have a look?

**Comment by tobiasdiez** [comment]
@iTao8 Thank you very much for your feedback. 
In fact this PR was not meant to fix any of the issues you mention. I only fixed that you don't get "Te" and "Tes" as autocompletion suggestions if you write "Test" in the field (I thought this is what you meant with "autocompletion covers input").

May I ask you to open a new issue of each of the problems you describe separately. I know this is more work on your side, but would help us to keep track of all the issues and not skip one. Thanks!
(Concerning the overlapping dropdown box: this is maybe a MacOS specific problem).

**Comment by iTao8** [comment]
@lenhard @tobiasdiez Thanks very much! 

The autocompletion dropdown box covers the input, see the screenshot. The dropdown box started at the bottom of the title filed, so all the input letters in the journal field are covered by this box. 
28460120-3a96268c-6e43-11e7-8089-d62c815a35d8

**Comment by chochreiner** [comment]
I can confirm the overlap on MacOS (latest development build) 
screen shot 2017-08-07 at 12 44 55

**Comment by matthiasgeiger** [comment]
Also reproducible on Windows if there is not enough space to display the whole list of suggestions (i.e., the suggestions would be placed over the task bar)

**Comment by lenhard** [comment]
@matthiasgeiger Indeed! Maybe we should just make the size of the drop down list shorter by default.

**Comment by tobiasdiez** [comment]
Its a known bug of the library we use: https://bitbucket.org/controlsfx/controlsfx/issues/701/auto-complete-box-overlaps-textfield-when

**Pull request merged**
