### PR TITLE
New database structure (add schema in PgSQL, and prefix tables in MySQL/MariaDB)

### LINKED ISSUE #9312: Add Schema in PostgreSQL DB
**Is your suggestion for improvement related to a problem? Please describe.**

I have only one postgreSQL database with a lot of tables in public schema.

In my opinion, JabRef's table names are very generic and it's easy to find another application that uses names like METADATA, ENTRY or FIELD.

**Describe the solution you want**

The easiest way to solve the problem is to add a suffix to the names, for example:
*jabref*_ENTRY, *jabref*_FIELD, *jabref*_METADATA.

In postgreSQL it is possible to create tables in a different schema, for example: *jabref*

In my case I prefer this

**Additional context**

In my local 5.7 release I made what I described with a few changes to the code.

If you think it will be useful, I can share the patch.

Greetings!

### PR DESCRIPTION
**Pull request by robyquin**
# Changed database structure: table names are very generic [#9312](https://github.com/JabRef/jabref/issues/9312)

Fixes #9312

- **PGSQL**: `jabref` schema added (table names unchanged).
- **MySQL**/**MariaDB**: prefix `JABREF_` added to table names.
- **ORACLE**: code unchanged as much as possible.

In any case, fields of the tables unchanged.

## checkBaseIntegrity (VersionDBStructure)

To check the integrity of the DB and to implement the automatic migration, variable `VersionDBStructure` was added in the table` METADATA`  to indicate the version of structure.

## Automatic migration

By comparing the `VersionDBStructure` read in the DB and the desired one, the automatic migration is performed or not.

**IMPORTANT**: To avoid data loss, old tables will not be deleted during migration. Old tables will need to be deleted manually.

---

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [x] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by calixtus** [comment]
Hi, thanks for the PR that was discussed before in the issue. Yet I feel a bit unsure about approving the pr without tests. Is there any way to integrate some? Would that mean we have to set up an instance of my/py?

**Comment by robyquin** [comment]
Hi @calixtus,
what tests are you talking about?

In addition to manual tests, related to soft migration (**non-destructive migration**), I have also taken care to modify tests already present in the project.

In fact, during the development, to satisfy all the required automatic tests, I corrected the feature code, and then those related to specific tests.

If necessary I can write about this on the issue #9312

Lastly, I'm sorry but what do you mean by "set up an instance of my / py"?

**Comment by calixtus** [comment]
I meant tests on migration. Sorry is was not precise.

**Comment by Siedlerchr** [comment]
I really like the idea, but would suggest we target this for the 6.0 release?

**Comment by robyquin** [comment]
# Test automatic migration

**I am unable to suggest any tests to implement, but I can try to be clearer on some aspects.**

If the goal is to migrate from any previous DB structure to structure proposed, we should:

1. have a clear understanding of all the variations of the DB structure in the history of JabRef,
2. to verify that the source structure has all the requirements for the new one, this assumes that we know where to find the information in the old structure in order to insert it correctly in the new one.

From this list I see that there would be a huge amount of interpretation work to be done on version compatibility; so, I tried to analyze the problem from another perspective: does the DB know if its structure is compatible with a certain version of JabRef client?
The answer seems to me to be No.
To date (JabRef v5.7) the DB does not know if its structure is compatible with a certain version of the JabRef client that has had access. so automatic migration is just an attempt not to do it manually.

From this reflection, I thought about the VersionDBStructure = 1 variable, assuming the existence of 0 and -1.

Unfortunately this variable, today, does not yet have a history that can help us for the implementation of the migration test.

Let's not forget that:
1. the migration between v5.7 and the new release is non-destructive, a copy and paste between two structures that we know are already compatible.
2. If the automatic migration fails we can attempt the manual migration as described in the issue or as described in the user documentation https://docs.jabref.org/collaborative-work/sqldatabase/sqldatabasemigration

```mermaid
flowchart TB

STATUS[Status: VersionDBRequired = 1] --> Check1
Check1{{ENTRY, FIELD, METADATA\ntables exist?}}
NewInstallation[VersionDBStructure==null\nThis is a new installation]
NoMigration([No Migration])
MigrationMysqlStep1([Create JABREF_ENTRY\nCreate JABREF_FILED\nCreate JABREF_METADATA])
MigrationPgsqlStep1([Create jabref.ENTRY\nCreate jabref.FILED\nCreate jabref.METADATA])
MigrationStep2([`Insert into newTable Select * from oldTable`])
Check2{{VersionDBStructure exists in DB?}}
CheckError{{Return Error?}}
NoCompatibility([There isn't compatibility between old and new structure])
Compatibility([OK, Well done!])
PrevVer([VersionDBStructure=0])
GetVersionValue([Get VersionDBStructure Value])
Check3{{VersionDBStructure < VersionDBRequired}}

Check1 -->|NO| NewInstallation --> NoMigration
Check1 -->|YES| Check2
Check2 -->|NO| PrevVer
PrevVer -->|Try Migration MySQL| MigrationMysqlStep1
PrevVer -->|Try Migration PgSQL| MigrationPgsqlStep1
MigrationMysqlStep1 --> MigrationStep2
MigrationPgsqlStep1 --> MigrationStep2
MigrationStep2 --> CheckError
CheckError -->|YES| NoCompatibility
CheckError -->|NO| Compatibility
Check2 -->|YES| GetVersionValue
GetVersionValue --> Check3 -->|Perform Migration| Migration([Future Migrations])
```

**Comment by Siedlerchr** [comment]
Thank you really much for the detailed explanation, I think this looks good the way it is described. 
 have not yet taken a look at the code. But will do soon.

**Review by calixtus — DISMISSED** [review]

**Review by Siedlerchr — DISMISSED** [review]

**Comment by Siedlerchr** [comment]
@robyquin  Thanks again for your work! As we have released 5.8 and now are starting the development cycle of 6.0 we have merged this now!

**Pull request merged**
