### PR TITLE
integrate JabRef online

### PR DESCRIPTION
**Pull request by Ali96kz**
- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by Ali96kz** [comment]
I send next requests: 
`
{
  "operationName": "getDocumentById",
  "variables": {
    "id": "ckph1zzv600141wzgtgbe2eg2"
  },
  "query": "query getDocumentById($id: ID!) {\n  getUserDocumentRaw(id: $id) {\n    type\n    citationKey\n    fields {\n      field\n      value\n    }\n  }\n}\n"
}
`
To get entry by id 

And next request to save it by id 
`
{
  "data": {
    "addUserDocumentRaw": {
      "id": "ckpi4mtn800191wves7cxzwhi"
    }
  }
}
`

**Comment by Ali96kz** [comment]
Is it ok? 
If it's ok, I will add test cases and prettify the code

**Comment by Ali96kz** [comment]
I have a problem with adding Appollo as a dependency, and the next reason is I am not sure that we need a special library to make HTTP request, cause in all other places we fetch data from web with the simple `HTTPUrlConnection`

**Comment by tobiasdiez** [comment]
Thanks a lot for your work. This already looks very nice.

Two general comments:
- Please try to use the apollo library. For simple, queries and mutations manually creating the http requests may work. But for more advanced things like subscriptions and caching, it would be good if we wouldn't need to reinvent the wheel. Moreover, apollo creates most of the data holder classes automatically from the schema, which will easy maintenance in the future. @Siedlerchr just now made some progress in this direction, see https://github.com/JabRef/jabref/issues/7582#issuecomment-855217863.
- As @koppor  remarked in one of the sync-issues (cannot find the exact comment right now), the goal would be to implement some form of the https://github.com/JabRef/jabref/blob/main/src/main/java/org/jabref/logic/shared/DBMSProcessor.java class (probably it's a good idea to first extract an interface from this class that abstracts the "shared sync" functionality, but doesn't rely on the database-specifics).

**Comment by tobiasdiez** [comment]
Can you please try this version after downloading https://repo1.maven.org/maven2/com/apollographql/apollo/apollo-api/2.5.8/apollo-api-2.5.8.jar and putting this jar file in `lib`.

**Comment by Siedlerchr** [comment]
@tobiasdiez  That worked partly. I could at least generate some files now
. @Ali96kz https://github.com/JabRef/jabref/tree/jabrefonline

However, it's still not building, there seems to be api missing

**Comment by Siedlerchr** [comment]
I am still working on integration the apollo libs and make it possible for eclipse. I will therefore close your PR for the moment.
Feel free to contribtute to  https://github.com/koppor/jabref/pull/505

**Pull request closed without merging**
