### PR TITLE
Added extra stats to be sent with MrDLib recommendations

### PR DESCRIPTION
**Pull request by conorfos**
* Added the following stats to hopefully improve quality of recommendations:
 ** OS, OS version, Java version, Timezone
 * Added a couple of minor fixes
 ** Changed endpoint url
 ** Updated name of some of the expected JSON fields
 

----

- [ ] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [x] Manually tested changed features in running JabRef
- [ ] Screenshots added in PR description (for bigger UI changes)
- [x] Ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)
- [x] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)

### CODE REVIEW

**Comment by stefan-kolb** [comment]
Hm, what do the properties `OS, OS version, Java version, Timezone` have to do with the recommendations? 🤔

**Comment by conorfos** [comment]
Hi @stefan-kolb ,

First, let us provide some background information for those who are not familiar with the recommender system and the changes. In JabRef 4.x, the following data was sent to Mr. DLib: partner_id ("jabref"), app_id ("jabref_desktop") app_version (JabRef version), and app_lang (JabRef language). For JabRef 5.x we would like to add the Operating System and Version, Java Version and Timezone. Ideally, we would sooner or later add additional information such as screen resolution and the window size of JabRef. 

Generally, the more information a recommender system has about its users, the better the recommendations can potentially be. We will use all collected information to apply machine learning, i.e. learning in which context which items or recommendation algorithms may be best. Which information may be needed can never be said in advance, only after we have done some experiments. For instance, in some situations, there are notable differences between Apple and Windows users when it comes to recommendations (see e.g. https://www.forbes.com/sites/adriankingsleyhughes/2012/06/26/mac-users-have-money-to-spare-says-orbitz/). Hence, the operating system is a valuable piece of information. We don't know if the same applies e.g. to the JAVA version, but we would like to try it out. Hence, we would like to transmit this information. 

We know that there is always a trade-off between privacy and recommendation effectiveness. In this case, we feel that OS, OS version, Java version, and Timezone would not pose a significant risk to user privacy. We also made it clear in the "Mr. DLib for JabRef information page" http://mr-dlib.org/information-for-users/information-about-mr-dlib-for-jabref-users/ what data is being collected and why. We would also be happy to add this information to the initial consent dialogue in JabRef. (The web page mentions that we would collect some data such as screen resolution though we don't do this yet. We thought we would just mention it on the page so that users are aware of our medium-term plans.)

In the long run, we would like to have three options in JabRef relating to the recommender system. 1. Deactivate 2. Standard Recommendations (that would be recommendations as they are now) 3. Advanced Personalized Recommendations (with unique user IDs) for which users, again, would have to explicitly opt-in. 

We are happy to discuss this further over Skype or any other method that suits.
Thanks.

**Comment by conorfos** [comment]
I am adding a mockup here of changes we could make to the privacy dialog so that users could decide between different recommendation services.
jabref-dialog-2 0

**Comment by LinusDietz** [comment]
Hi @conorfos,
there have been ongoing discussions among the JabRef team and we have come to the following final conclusion for the current issue:

**You may use the `Title` (of the article), `OS`, and `Timezone` for the recommendations.**

For the 'basic recommendation' based on the title the current opt-in is sufficient.  For the 'advanced recommendations' using (`OS`, and `Timezone`) there must be an explicit user opt-in for each of these.

This is our compromise trading off your efforts for recommender systems research and protecting our users' privacy, also accounting for what is reasonable with regard to the general principle of data economy.

**Comment by Joeran** [comment]
Hi @LinusDietz ,

ok, it's no problem to change the dialogue to make the users agree for every piece of data explicitly. Regarding the specific data to be transferred, I am not sure if I am understanding you correctly. 

Currently, the "old" JabRef that uses Mr. DLib, transfers the JabRef version and I believe also the language. Now, you mention that we are allowed to submit OS and timezone.  Is that _in addition to_ or _instead of_ the JabRef version and language? To us, the JabRef version and language are actually more important for the recommendations than OS and timezone . The JabRef version may also be important one day to ensure backwards compatibility with our service. 

Also, do we understand you correctly that you do not want us to create a unique user id as part of the "advanced recommendations", in which case we would not be able to give personalized recommendations? 

Best,
Joeran

**Comment by LinusDietz** [comment]
Whoops, I overlooked that one. Of course, you can also use the JabRef Version and the Language as done before.

Regarding personalized recommendations, we have not reached any consensus/decision yet.

**Comment by conorfos** [comment]
I have implemented this functionality as agreed. Below is a screenshot of the privacy dialog and the code sending data can be found in the MrDLibFetcher class.
jabref privacy dialog

**Pull request merged**
