### PR TITLE
Multiple messages in the SnackBar

### LINKED ISSUE #7340: Multiple messages in the SnackBar
If JabRef has do display several messages very shortly after each other, the messages are stacked and played one after each other. This is confusing, since the SnackBar is still displaying a message, which is already obsolete. E.g. if you cycle quickly through the preview styles.

A simple solution would be to stack the messages inside an already showing SnackBar, separated by a new line and to lengthen the display time of the SnackBar for the time only the last message should show.

### PR DESCRIPTION
**Pull request by yogeshvar**
Thanks to @EduRibeiro00 & @X1nbb for documenting the findings and working on this issue. ❤️ 

## **Previous Discussion for Handling Multiple Messages**: #7577 #7968 
From the [Snackbars Design Guidelines](https://material.io/components/snackbars#usage) the frequency of the Snackbar should be only once at a time is recommended. I believe the implementation of https://github.com/sshahine/JFoenix/blob/2dbb8515da236140c41eabe22eb549b458f1e867/jfoenix/src/main/java/com/jfoenix/controls/JFXSnackbar.java#L321 is also based on that. The ideal choice to show Multiple Messages would be moving from Snackbar to Notifications (with custom CSS changes to replicate snack bar design) 

## **Proposed Solution**: _Moving from Snackbar to Notifcations_ 
Fixes #7340 
```
Notifications notificationBuilder = Notifications.create()
        .text(message)
        .position(Pos.BOTTOM_CENTER)
        .threshold(5, thresholdNotification)
        .hideAfter(TOAST_MESSAGE_DISPLAY_TIME)
        .hideCloseButton();
notificationBuilder.show();
```

https://user-images.githubusercontent.com/17572818/164216381-f49be03d-421b-44a4-ab50-c7cc9e3a9a9a.mp4

## **Few Open Questions while Implementation**:
- The Maximum Notification is set as `5`, as per the current draft PR. I have displayed a threshold notification that says `"Too much happening... Hang on.."` **_Can someone suggest a better UX/message/way handle this, let's discuss._** 
- For a different workflow, I tried accessing the inner class of Notification. And ended up with this error `“Unable to make private void org.controlsfx.control.Notifications$NotificationPopupHandler.hide(javafx.stage.Popup,javafx.geometry.Pos) accessible: module org.controlsfx.controls does not "opens org.controlsfx.control" to module org.jabref”.` If someone suggests **_how to resolve this?_** I thought of removing the threshold notification and hiding the top of the stack with the help of this while inserting the next incoming notification.

## PR Checklist:

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by calixtus** [comment]
Hi @yogeshvar, thanks for your PR, whick looks very promising.
About your questions:
- The big advantage is, that more than 1 message can be displayed. Maybe there is a way to close the least recent message after the fifth message instead of a new message?
- This seems to be a problem of the java module system. You probably have to edit module-info.java to get access to the NotificationPane? There should be examples inside.

**Comment by Siedlerchr** [comment]
For the java open module problem you need to modify the build.gradle file and add a line to the addOpens for the concrete class 


```

        addOpens = [
                'javafx.controls/javafx.scene.control' : 'org.jabref',
                'org.controlsfx.controls/org.controlsfx.control.textfield' : 'org.jabref',
                'javafx.controls/com.sun.javafx.scene.control' : 'org.jabref',
```

**Comment by calixtus** [comment]
We try to avoid reflection if possible and we are accepting tradeoffs, as in the veeeeery long run we wanted to play a bit with GraalVM around.

**Comment by yogeshvar** [comment]
I'm making this PR ready with the removal of the threshold notification because the notification timeout is 3 seconds which helps the notification to fade out and the new notifications are not restricted by the threshold notification. 

### Few other findings: 
These are the few other works/ideas that I would like to document for future reference if anyone works on this.
- Accessing the `hide` function from the Notification ControlFx needs reflection. ([Try to avoid reflections](https://github.com/JabRef/jabref/pull/8733#issuecomment-1113400467))
- `NotificationPane` will be inside the application window, so it wouldn't fit this story. 
- With a help of Queue, moving to the Observer pattern can be an option. Although, we are back to square one. (`hide` function). With more code, we could write an Observer pattern that also holds the Timer (Date object to find the notification duration every second, then remove it.) with every notification in the queue. It might lead to weird fading in and out notifications as we will push all the notifications.
- Returning null with `doAction` and when the user clicks on the notification it will be closed. (Not a good solution, but it is an alternative for `hide`) Here are the rough `x,y` coordinates that I could find for the 5 notifications stacked. (x is approx. always 1024 & y is 745 for the first notification and the rest falls by 65+ approx.)

**Comment by calixtus** [comment]
Normally it should be sufficient to document your thoughts in this GitHub PR or in the corresponding issue, since the issue number should be recorded in the merge commit message.

**Comment by calixtus** [comment]
Alternatively you could maybe introduce a short paragraph in the development documentation.

**Comment by calixtus** [comment]
Is this ready-for-review?

**Comment by yogeshvar** [comment]
Yes @calixtus

**Comment by calixtus** [comment]
As this includes a ui change, can you please add a small note in the changelog?
Codeweise looks good to me so far!

**Comment by yogeshvar** [comment]
@calixtus Thanks, I have updated the changelog, and please let me know whether the note is fine. (I'm confused with added and fixed.)

**Review by calixtus — APPROVED** [review]

**Review by Siedlerchr — APPROVED** [review]
Thanks for your contribution!

**Pull request merged**
