### PR TITLE
Showing number of total citations of an entry 

### LINKED ISSUE #8954: Show number of total citations of an entry
**Problem:**
There is metadata out there that JabRef is unable to capture (yet). One type of this data is the total number of an entry being cited.

**Describe the solution you'd like**

Show the number of total citations of an entry *somewhere*.

**Additional context**
- This issue is inspired by the following feature request in the forum: https://discourse.jabref.org/t/number-of-paper-citation-information/2616
- this issue here is a sub-issue of the more general issue of showing more citation-related diverse metadata, such as information about the journal, author and so on. A related issue would be #6189

**To do:**
- Implementation difficulties:
   - [ ] Discussion is necessary to decide, where exactly the total number of citations should show in JabRef. Screenshots would be good.
   - [ ] Prefered: Finding public sources that do not require an API key.
      - [ ] If no public sources can be found, implement a solution that works, if users insert their own personal API key.

### PR DESCRIPTION
**Pull request by YesWeCandrew**
Fixes #8954. Show number of total citations of an entry.

Users can see the number of times that an entry has been referenced by others by fetching or updating from Crossref. This information is displayed in a new standard field, Referencedbycount.

If this data is successfully scrapped, it appears in the Other fields tab. 

Work in the future/improvements to this pull request should automate the checking to make Other fields tab appear after fetching from Crossref. Currently, after fetching from Crossref in the entry editor tab the user needs to click away from the entry and return before it updates and shows the Other fields tab. 

**Would appreciate guidance on how best to make the tab appear after running the fetcher, or advice on better places to store the data if an additional standardField is not appropriate.**

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

Demonstration:
Referencedbycount appearing in the Other fields tab
image

### CODE REVIEW

**Comment by ThiloteE** [comment]
added devcall label to explore the idea if this feature can also be added to "import bibliographic data from DOI" in entry editor general tab or "import by ID" in main UI

**Comment by YesWeCandrew** [comment]
Hi @ThiloteE thanks for considering this pull request at the next devcall. 

I'm happy to implement this to both "import bibliographic data from DOI" and "import by ID", but it will slow down these operation significantly. Both functions call DOI.org, but DOI.org doesn't provide ReferencedByCount information so getting it would require a call to the CrossRef API to be made. CrossRef generally has more data than DOI, but it is slower.

Would be happy to implement this or discuss options if the dev team are interested.

**Comment by koppor** [comment]
Short dev call notes - hope, they help:

- Showing in entry table is good
- Storing in BibTeX is bad (what if the library is shared and two persons have different numbers. Conflicts should not occur there)
- The data provider surely has a rate limit. JabRef should not always read the numbers at startup (they don't change that often)
- The numbers should be stored in a local H2 database
- The location of the H2 database should be determined using [appdirs](https://github.com/harawata/appdirs)
- The H2 database should be created for each library (or globally - unsure)
- The index is the BibTeX cite key. The value is the citation count.

Updating ideas:

- The value should be updated when an entry is selected in the entry table
- There should be a button in the toolbar to fetch citation data
- Maybe, citation data can only be fetched for 10 entries in one badge (to prevent rate limit exceed)

**Comment by Siedlerchr** [comment]
Closing this PR due to inactivity :zzz: 
Please reopen the PR with additional changes if you plan to continue working on this

**Pull request closed without merging**
