### PR TITLE
Fix NPE in Medline fetcher on missing ISSN

### PR DESCRIPTION
**Pull request by Siedlerchr**
Fix for #2110

When issn was null, calling a method on it resulted in NPE.

### CODE REVIEW

**Comment by tobiasdiez** [comment]
As a quick fix this seems to be ok. Two remarks:
- Are all other fields always not null (e.g. JournalIssue ?)
- Can we change the Journal class to return optionals instead of null?

**Comment by Siedlerchr** [comment]
@tobiasdiez  I will check it if Journal issue is also possible  null from the annotation in the Journal class
Changing the code of Journal is not possible because it is autogenerated from the jaxb stuff on base of the xml class 

But I wanted to add a test, too

**Comment by lenhard** [comment]
In theory, all fields can be null. JAXB will take whatever is there and will set null for everything that it cannot find. Ultimately, null values depend on how consistent the data from medline are, and I guess we should be rather conservative in our assumptions...

There is already a fair amount of null checking code in the importer and it is quite hard to see what could be missing. @Siedlerchr We will rely on your knowledge and intuition here, but of course it is easy to miss something and then we will have to fix the error when someone opens an issue.

Apart from that I second @tobiasdiez: Please add a test and this is ready to go!

**Comment by tobiasdiez** [comment]
Apparently there is a way to let JAXB convert nulls to empty optionals http://stackoverflow.com/a/23113540/873661. Not sure how complicated this is versus just checking for null.

**Comment by lenhard** [comment]
@tobiasdiez If I understand it correctly, this solution is not feasible for us. It requires changing the annotations in the Java class and in our case this Java class is generated from an XSD.

Apart from that I am always happy when we can avoid that darn Optional and do a good ol' null check ;-D

**Comment by Siedlerchr** [comment]
Apart from codecov having problems with parameterizest test, all works

**Pull request merged**
