### PR TITLE
[WIP] Update latex2unicode from 0.2.2 -> 0.2.4

### PR DESCRIPTION
**Pull request by LinusDietz**
- [ ] Investigate why this is failing
- [ ] fix tests

### CODE REVIEW

**Comment by LinusDietz** [comment]
So this is due to @tomtung fixing a feature we wished for long: https://github.com/tomtung/latex2unicode/issues/8

https://github.com/tomtung/latex2unicode/commit/6879cbb40ca41b9a3fea41138f3547d3e6ee1cbd

**Comment by Siedlerchr** [comment]
It maybe failing because we use our own replacement char as a workaround , I think. Not sure if it's this issue or another

**Comment by stefan-kolb** [comment]
Looks like this is the case. The question is do we really want this behavior?

```
Failures (4):
  JUnit Jupiter:LatexToUnicodeFormatterTest:unknownCommandKeepsArgument()
    MethodSource [className = 'org.jabref.logic.layout.format.LatexToUnicodeFormatterTest', methodName = 'unknownCommandKeepsArgument', methodParameterTypes = '']
    => org.opentest4j.AssertionFailedError: expected: <bbbb> but was: <\aaaabbbb>
       org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:52)
       org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
       org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:186)
       org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:181)
       org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:486)
       org.jabref.logic.layout.format.LatexToUnicodeFormatterTest.unknownCommandKeepsArgument(LatexToUnicodeFormatterTest.java:118)
       sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
       sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       java.lang.reflect.Method.invoke(Method.java:498)
       [...]
  JUnit Jupiter:LatexToUnicodeFormatterTest:unknownCommandWithEmptyArgumentIsIgnored()
    MethodSource [className = 'org.jabref.logic.layout.format.LatexToUnicodeFormatterTest', methodName = 'unknownCommandWithEmptyArgumentIsIgnored', methodParameterTypes = '']
    => org.opentest4j.AssertionFailedError: expected: <> but was: <\aaaa>
       org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:52)
       org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
       org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:186)
       org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:181)
       org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:486)
       org.jabref.logic.layout.format.LatexToUnicodeFormatterTest.unknownCommandWithEmptyArgumentIsIgnored(LatexToUnicodeFormatterTest.java:123)
       sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
       sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       java.lang.reflect.Method.invoke(Method.java:498)
       [...]
  JUnit Jupiter:LatexToUnicodeFormatterTest:testFormatStripLatexCommands()
    MethodSource [className = 'org.jabref.logic.layout.format.LatexToUnicodeFormatterTest', methodName = 'testFormatStripLatexCommands', methodParameterTypes = '']
    => org.opentest4j.AssertionFailedError: expected: <-> but was: <\mbox->
       org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:52)
       org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
       org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:186)
       org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:181)
       org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:486)
       org.jabref.logic.layout.format.LatexToUnicodeFormatterTest.testFormatStripLatexCommands(LatexToUnicodeFormatterTest.java:25)
       sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
       sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       java.lang.reflect.Method.invoke(Method.java:498)
       [...]
  JUnit Jupiter:LatexToUnicodeFormatterTest:unknownCommandIsIgnored()
    MethodSource [className = 'org.jabref.logic.layout.format.LatexToUnicodeFormatterTest', methodName = 'unknownCommandIsIgnored', methodParameterTypes = '']
    => org.opentest4j.AssertionFailedError: expected: <> but was: <\aaaa>
       org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:52)
       org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
       org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:186)
       org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:181)
       org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:486)
       org.jabref.logic.layout.format.LatexToUnicodeFormatterTest.unknownCommandIsIgnored(LatexToUnicodeFormatterTest.java:113)
       sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
       sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       java.lang.reflect.Method.invoke(Method.java:498)
       [...]
```

**Comment by stefan-kolb** [comment]
Currently the new update preserves the command `\a`for example, but strips the brackets like `\a{hhh}`->`\ahhh`.

**Comment by koppor** [comment]
+1 for preserving the braces

**Comment by LinusDietz** [comment]
Devcall: We cannot update to 0.2.4 because this destroys valid latex code. Need to create a Pull Request at latex2Unicode.

**Comment by stefan-kolb** [comment]
We got an answer from Tom and need to discuss this. decision seems nontrivial to me.

**Comment by tobiasdiez** [comment]
Whats the status here? If we want to upgrade to Java 9, we need to update the latex2unicode library, see https://github.com/JabRef/jabref/pull/3421.

**Comment by koppor** [comment]
If I recall it correctly, we need to fork the librrary or reimplement it on
our own ... again. @oscargus? 😇

Am Mi., 19. Dez. 2018, 22:34 hat Tobias Diez <notifications@github.com>
geschrieben:

**Comment by tobiasdiez** [comment]
https://github.com/tomtung/latex2unicode/issues/9 is now fixed. Updating the library leads some export test failures, which I have already fixed on the jdk9 branch. Thus, I've pushed the update there https://github.com/JabRef/jabref/pull/3421/commits/d54d6ff22a2b758791b2a406f8d9ff2c3ce1529b

**Comment by stefan-kolb** [comment]
Great Work Tobias!

Tobias Diez <notifications@github.com> schrieb am Mo., 3. Juni 2019, 22:20:

**Pull request closed without merging**
