### PR TITLE
Fulltext fetcher for IACR eprints

### PR DESCRIPTION
**Pull request by SECtim**
Adds fulltext fetching for IACR eprint PDFs.

My Java skills are a bit rusty, and while the code works, I'm happy to make additional changes if there are more elegant ways to do things.

I am unsure about whether to add anything to the developer docs on fetchers, as they seem to only cover a subset of all fetchers anyway (so far, the IACR fetcher isn't mentioned at all).

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable) 
- [x] Tests created for changes (if applicable) 
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
  - (not applicable)
- [x] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.
  - There does not seem to be fetcher-specific documentation for users (regarding fulltext fetching)

### CODE REVIEW

**Comment by SECtim** [comment]
The failing fetcher tests seem unrelated to my changes. Will take a closer look later.

**Review by Siedlerchr — APPROVED** [review]
codewise lgtm! Thanks for the addition.

**Comment by Siedlerchr** [comment]
@SECtim you can ignore the unrelated fetcher tests. Sometimes they fail just on GitHub if they are executed to often or Github IPs are blocked

**Comment by Siedlerchr** [comment]
Just did a small simplification of the tests, it's easier to directly compare the Optionals

**Review by calixtus — APPROVED** [review]

**Review by Siedlerchr — APPROVED** [review]

**Pull request merged**
