### PR TITLE
Jdk17

### PR DESCRIPTION
**Pull request by Siedlerchr**
- [] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [] Tests created for changes (if applicable)
- [] Manually tested changed features in running JabRef (always required)
- [] Screenshots added in PR description (for UI changes)
- [] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by Siedlerchr** [comment]
Still not working on gradle

**Comment by koppor** [comment]
Follow up is https://github.com/JabRef/jabref/pull/7834.

**Comment by Siedlerchr** [comment]
Waiting for a new nightly https://github.com/gradle/gradle/pull/17712

**Comment by Siedlerchr** [comment]
./gradlew wrapper --gradle-version=7.2-20210715231856+0000  seems to work at least it compiles

**Comment by Siedlerchr** [comment]
As this works now in principle I close this and we wait until it's released

**Pull request closed without merging**
