### PR TITLE
French translation correction

### PR DESCRIPTION
**Pull request by MBunel**
Some corrections in translation:
- Conjugaison
- Truncated words

- [x] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [ ] Screenshots added (for bigger UI changes)
- [ ] Manually tested changed features in running JabRef
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)
- [ ] If you changed the localization: Did you run `gradle localizationUpdate`?

### CODE REVIEW

**Comment by mlep** [comment]
Merci ! Your first contribution to JabRef is much appreciated!
Do you know about [the other ways of helping in JabRef's developments](https://help.jabref.org/en/FAQcontributing)?

**Comment by lenhard** [comment]
Thanks for your contribution! I'll merge directly.

**Comment by LinusDietz** [comment]
@MBunel We are about to release a new Version of JabRef and would like to attribute you with your full name. Can you tell us your name so we can include it?

**Comment by MBunel** [comment]
Yes of course, "Mattia Bunel"

**Pull request merged**
