### PR TITLE
Issue 10431 relevance star

### LINKED ISSUE #10431: Relevance star should only appear when toggled
When the `Relevance (Special)` column is shown in the entry table and the relevance of an entry is `false`, hovering over the entry makes a star appear in that column, regardless of the actual value. This makes it hard to identify and select the intended value, because relevance always appears `true` for the entry under the cursor. For instance, clicking with the intention of removing the star when relevance is already `false` will set it to `true` (opposite of the intended result).

The relevance status should be discernable regardless of hovering state.

Possible solutions
* Show relevance star only when relevance = `true`
* Use a different indicator on hover when relevance = `false`

JabRef 5.10--2023-09-01--779e555
Linux 6.4.12-1-default amd64 
Java 21-internal 
JavaFX 20+19

### PR DESCRIPTION
**Pull request by LenkaBuebnkova**
A relevance field was modified so it can  no longer be visible upon hovering as it was causing confusion regarding the actual value of selected entry. It has been modified so a new menu appears upon clicking on the "Relevance" field of a selected entry with a selection of 2 options to set it to - Set as Relevant / Set as Irrelevant. Upon choosing one of the mentioned options, the selected entry will be then marked / unmarked with the star icon based by the chosen option. Adding a menu option for "Relevance" was to maintain visual consistency with the existing menu options for special fields such as "Read" and "Priority." Basic tests were also created for this. 

Screenshot 2023-11-09 at 19 09 02

Resolves #10431

### Mandatory checks

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [x] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by ThiloteE** [comment]
To ease organizational workflows I have linked the pull-request to the issue with syntax as described in https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

> <h2 id="linking-a-pull-request-to-an-issue-using-a-keyword">Linking a pull request to an issue using a keyword</h2>
> <p>You can link a pull request to an issue by using a supported keyword 
> in the pull request's description or in a commit message. The pull 
> request <strong>must be</strong> on the default branch.</p>
> <ul>
> <li>close</li>
> <li>closes</li>
> <li>closed</li>
> <li>fix</li>
> <li>fixes</li>
> <li>fixed</li>
> <li>resolve</li>
> <li>resolves</li>
> <li>resolved</li>
> </ul>
> <p>If you use a keyword to reference a pull request comment in another 
> pull request, the pull requests will be linked. Merging the referencing 
> pull request also closes the referenced pull request.</p>
> <p>The syntax for closing keywords depends on whether the issue is in the same repository as the pull request.</p>


### Example:
- ✅ `Fix #xyz` links pull-request to issue. Merging the PR will close the Issue.
- ✅ `Fix https://github.com/JabRef/jabref/issues/xyz` links pull-request to issue. Merging the PR will close the Issue.
- ✅ `Fix https://github.com/Koppor/jabref/issues/xyz` links pull-request to issue. Merging the PR will close the Issue.
- ❌ `Fix [#xyz](https://github.com/JabRef/jabref/issues/xyz)` links pull-request to issue. Merging the PR will **NOT** close the Issue.

**Comment by ryan-carpenter** [comment]
The proposed solution would change what is currently a simple toggle into a two-click operation, making this convenient feature harder to use. The main issue is that the star appears on row selection, even when the entry is not relevant. This creates an opportunity for confusion _before_ I hover or click on the star. Confusion related to hovering or clicking (on the star) occurs mainly because of the row selection and not because of the hover or click.

**Comment by LenkaBuebnkova** [comment]
I have also solution for the hovering, I will upload my solution without menu part.

**Comment by LenkaBuebnkova** [comment]
Solution of issue with icon showing while hovering is fixed and uploaded changes in one file are pushed.

**Comment by Siedlerchr** [comment]
I didn't see any new code? Did you push your changes because now the diff shows no changes

**Comment by Siedlerchr** [comment]
Ah okay I see! I will test it later

**Comment by koppor** [comment]
We had a longer discussion and refined the intended solution for the issue https://github.com/JabRef/jabref/issues/10431#issuecomment-1874501604

Unfortunately, this is different from yours. Thus, we close this PR.

The fix was to **add** the "right" CSS class.

```diff
+    -fx-icon-color: -jr-gray-2;
```

I found it while browsing through [/src/main/java/org/jabref/gui/icon/InternalMaterialDesignIcon.java#L42](https://github.com/JabRef/jabref/blob/ffa6fcfd80190fb55bd15d030356886661e8b864/src/main/java/org/jabref/gui/icon/InternalMaterialDesignIcon.java#L42) (`org.jabref.gui.icon.InternalMaterialDesignIcon#getGraphicNode`).

**Pull request closed without merging**
