### PR TITLE
Update search results when active database changes

### LINKED ISSUE #11267: Keep search string across library shows "No results found" even there are entries in the other library
### JabRef version

Latest development branch build (please note build date below)

### Operating system

macOS

### Details on version and operating system

mac os 14.4.1 latest jabref dev version 

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Create or open a new empty 
2. Open jabref-authors bib file
3. Search for e.g. "Kopp"  
4. Activate option "Keep search string across library" (the globe icon)
5. Search results say "No results found" 
6. Switch tabs and see that there are many results in the second library

Switching back and forth does not change 

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

### PR DESCRIPTION
**Pull request by LoayGhreeb**
Closes #11267

### Mandatory checks

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Review by calixtus — COMMENTED** [review]
I think this won't work. Now you update when changing the database, but not if the search query itself is altered.
Maybe a new string binding with multiple observables will work here.

**Comment by LoayGhreeb** [comment]
> I think this won't work. Now you update when changing the database, but not if the search query itself is altered.

the search query has a listener too.
https://github.com/JabRef/jabref/blob/3abdefd5050a291f89ebe47b9c5218750c459348/src/main/java/org/jabref/gui/search/GlobalSearchBar.java#L240

**Review by Siedlerchr — APPROVED** [review]

**Comment by Siedlerchr** [comment]
Thanks for the quick fix

**Comment by calixtus** [comment]
so this line was just duplicated?

**Comment by LoayGhreeb** [comment]
> so this line was just duplicated?

yes, I accidentally did this in #11032.

```diff
- this.stateManager.activeDatabaseProperty().addListener((obs, oldValue, newValue) -> stateManager.activeSearchQueryProperty().get().ifPresent(this::updateSearchResultsForQuery));

+ this.searchQueryProperty.addListener((obs, oldValue, newValue) -> searchQueryProperty.get().ifPresent(this::updateSearchResultsForQuery));

```

**Comment by calixtus** [comment]
Ah ok. Forgiven and forgotten. 😄

**Pull request merged**
