### PR TITLE
Fix expected result

### PR DESCRIPTION
**Pull request by koppor**
Somehow, the result by the fetchers changed. This just adapts

### CODE REVIEW

**Comment by koppor** [comment]
I don't see where travis fails. The log is too cluttered for me. Maybe, we should invest time in https://github.com/JabRef/jabref/issues/3510 again.

**Comment by Siedlerchr** [comment]
This is partially because you merged my wip PR about the database Tests. I changed the log test output in gradle.

**Comment by koppor** [comment]
@siedlerchr You mean https://github.com/JabRef/jabref/pull/5394? With follow-up https://github.com/JabRef/jabref/issues/5602?

Would it be possible to provide a PR reducing the output again?

**Comment by koppor** [comment]
Help pages are (also) fixed at https://github.com/JabRef/jabref/pull/5609.

**Pull request merged**
