### PR TITLE
Remove the folder on build server once PR is merged

### PR DESCRIPTION
**Pull request by tobiasdiez**
----

- [ ] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [ ] Manually tested changed features in running JabRef
- [ ] Screenshots added in PR description (for bigger UI changes)
- [ ] Ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)

### CODE REVIEW

**Comment by koppor** [comment]
Something with passing the key does not work: 

```
/usr/bin/docker run --name bb817c797bff84b949cda5e39ce26401ce5d_447033 --label 04bb81 --workdir /github/workspace --rm -e INPUT_SCRIPT -e INPUT_HOST -e INPUT_USERNAME -e INPUT_PRIVATEKEY -e INPUT_PORT -e INPUT_PASSWORD -e INPUT_TIMEOUT -e INPUT_COMMAND_TIMEOUT -e INPUT_KEY -e INPUT_KEY_PATH -e INPUT_SCRIPT_STOP -e INPUT_ENVS -e INPUT_DEBUG -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/jabref/jabref":"/github/workspace" 04bb81:7c797bff84b949cda5e39ce26401ce5d
2019/09/29 20:03:04 Error: can't connect without a private SSH key or password
```

**Comment by tobiasdiez** [comment]
Should be fixed now: https://github.com/JabRef/jabref/commit/3e1195d5d551014068a1731fa77f5f96b99a3be2

**Comment by tobiasdiez** [comment]
Still does not work because "out: This service allows sftp connections only." Should be fixable by editing sshd_config.

**Comment by koppor** [comment]
This is the security thing I mentioned.

I did not want to give arbitrary scripts access. Therefore, sftp only. --> "Block direct server access" (https://bobcares.com/blog/sftp-security-risks/)

**Comment by Siedlerchr** [comment]
We could use a chrooted jail for the ssh user:
https://www.prado.lt/restrict-ssh-user-access-to-certain-directory-using-chrooted-jail-on-debian-9

**Comment by koppor** [comment]
Decision: Keep the setup as is. No user complained, because a development branch was available even if the PR was merged.

Will come back if builds.jabref.org is migrated to another server.

@Siedlerchr Thank you for the link.

**Pull request merged**
