### PR TITLE
Removed "Fetch" in title from Database Fetchers 

### PR DESCRIPTION
**Pull request by Siedlerchr**
- [x] Changes in pull request outlined? (What, why, ...)
- [x] Tests green?

Removed Translation of Fetcher names, because that are proper nouns.
#941

### CODE REVIEW

**Comment by tobiasdiez** [comment]
LGTM

**Comment by koppor** [comment]
This fixes #941, doesn't it?

**Comment by koppor** [comment]
Side comment: The entires in Menu_*.properties had to be removed, too. See 04cff82.

**Comment by koppor** [comment]
Further changes in the language files are done at #948. Still missing: Medline, OAI2, ACM, ... are still in the language files. @Siedlerchr Do you want to take over?

**Comment by Siedlerchr** [comment]
First this fix was for #941, but I did not remove the GVK long Description. Is still useful. About the rest I can document this on the website.
Oh, I just saw that I only checked the normal language property files. Will continue removing and will propose a PR for documentation on the website

**Pull request merged**
