### PR TITLE
Moved Add group button between Groups title and filter search field

### LINKED ISSUE #8398: Move 'Add group' button somewhere closer to groups
**Problem:**
When i first started using Jabref I vividly remember that i could not find the add groups button immediately, because i first found the `Groups` and `Filter groups` field and naively thought, the add groups button must be close to that. Or to say it differently: The `Add group` button is so close to the `Web search` panel, that on first glance it will be associated with it. Try to look at Jabref from a far distance and you might see what i mean.

**Desired Solution:**

Move the `Add group` button somewhere closer to groups.

Maybe it could be
- Between Filter groups and All entries.
OR
- Between Groups and Filter groups
OR
- Beneath the last group

**Additional context**
image

### PR DESCRIPTION
**Pull request by dimitrisdimos00**
I have moved the Add group button between the Groups title and the filter search field in the groups side pane

## Before
image

## After

image

Fixes #8398

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by calixtus** [comment]
Refs https://github.com/JabRef/jabref/issues/4681

Thanks for you contribution, although i'm not yet sure if we should merge this change. UI changes should be discussed before merging, especially since we had a big scientific usability study a few years ago that established some principles for the UI.

**Comment by Siedlerchr** [comment]
I am in favor of adding this. A small step which improves usability

**Comment by dimitrisdimos00** [comment]
Whatever you say

**Comment by ThiloteE** [comment]
There HAS BEEN a discussion in https://github.com/JabRef/jabref/issues/4682. Sorry, I was not aware of this thread. Funny enough, the thread started with https://github.com/JabRef/jabref/issues/4682#issue-412605828 advocating for locating it somewhere at the top, but somewhere along the way, it ended up being at the bottom of the group nevertheless.

I think the trigger was https://github.com/JabRef/jabref/issues/4682#issuecomment-808891723, which argues for differentiation between the state "no/a few groups existing" and "many groups existing". Remember, new users have "no/a few groups existing", so for them it would be more intuitive to have the `add groups` button closer to the top.

**Comment by calixtus** [comment]
Oh sorry, i just saw this PR and remembered #4682, so i posted the reference here

**Comment by calixtus** [comment]
maaaaan, #4681 and #4682, this is difficult today.

**Comment by ThiloteE** [comment]
Actually i am glad this was discussed before. There were some good points. Probably the worst case scenario would be
1. for the add group button to be within the scrollable group tree as is. If there are 500 groups, nobody would want to scroll down to the last group just to add a new group.
2. also problems with collapsing/expending the group tree. "You do not want the panel to enlarge/shrink each time.", as Mlep mentioned here: https://github.com/JabRef/jabref/issues/8398#issuecomment-1015170673.

So as long as these two points are avoided, a decision based on aesthetics, clarity and the ability to catch peoples eye should be possible. :)

**Comment by ThiloteE** [comment]
Also:

**Two ideas for having button below last group:**

   I think having the button below the last group could technically work.
   - Idea 1:
      Let the groups panel remains its current size even when groups are added or removed and there is some mechanism that detects when the button hits the wall of the web search and libre office/open office panels. Maybe take screen size into account.
   - Idea 2:
      Let the groups panel remain its current size, even when groups are added or remove and have the button below the last group if there are 10 groups/subgroups/sub...subgroups or less and have it at the bottom of the groups panel if there are 11 or more, but i fear this will not take screen size into account and will at one point create a weird "jump".
   
These two options would be the obvious compromise: For both states "no/a few groups existing" and "many groups existing", `add group` would be at the bottom of groups AND it would also be close to the other group related buttons.

Of course, technically these two would probably be possible and even thought it might be a good compromise, i am not sure if worth the effort...
   
   What dimitris implemented in https://github.com/JabRef/jabref/pull/8462#issue-1112947394 seems good enough 👍 . At least in my opinion.

**Comment by tobiasdiez** [comment]
I think the current order of first having the filter text box, then the list of groups and only afterwards the add buttons makes sense. You select more often a group then adding one, so the groups tree is more important then the add button and thus should come first. Filtering usually is on top of the things that are filtered, so should be above the tree.

**Comment by dimitrisdimos00** [comment]
> Also:
> 
> **Two ideas for having button below last group:**
> 
> I think having the button below the last group could technically work.
> 
> * Idea 1:
>   Let the groups panel remains its current size even when groups are added or removed and there is some mechanism that detects when the button hits the wall of the web search and libre office/open office panels. Maybe take screen size into account.
> * Idea 2:
>   Let the groups panel remain its current size, even when groups are added or remove and have the button below the last group if there are 10 groups/subgroups/sub...subgroups or less and have it at the bottom of the groups panel if there are 11 or more, but i fear this will not take screen size into account and will at one point create a weird "jump".
> 
> These two options would be the obvious compromise: For both states "no/a few groups existing" and "many groups existing", `add group` would be at the bottom of groups AND it would also be close to the other group related buttons.
> 
> Of course, technically these two would probably be possible and even thought it might be a good compromise, i am not sure if worth the effort...
> 
> What dimitris implemented in [#8462 (comment)](https://github.com/JabRef/jabref/pull/8462#issue-1112947394) seems good enough 👍 . At least in my opinion.

Thanks much!

**Comment by Siedlerchr** [comment]
You can always do right-click -> Add subgroup

/polls "Under the group tree as is"  "Above filter at the top" "Beneath filter at the top"

**Comment by koppor** [comment]
DevCall result:

The proposal my @martinkarim at https://github.com/JabRef/jabref/issues/4681#issue-412596432 is good:

groupgeneral

- The button is below the groups
- The button is NOT separated by a space between the groups, right below

**Comment by dimitrisdimos00** [comment]
> You can always do right-click -> Add subgroup TO vote click on the option
> 
> [](https://api.gh-polls.com/poll/01FTP79KFFE7X6F88JET00C15J/Under%20the%20group%20tree%20as%20is/vote) [](https://api.gh-polls.com/poll/01FTP79KFFE7X6F88JET00C15J/Above%20filter%20at%20the%20top/vote) [](https://api.gh-polls.com/poll/01FTP79KFFE7X6F88JET00C15J/Below%20filter%20at%20the%20top/vote)

Hey, I falsely voted the first option while I was going for the third

**Comment by dimitrisdimos00** [comment]
So the right path would be to have the add group button right below the filter groups option, just like it was before, just without the huge space between them. Is that correct?

**Comment by ThiloteE** [comment]
The option proposed by devcall is not on the voting list xD (This is the one i would have gone for, if it were and if it were technically possible.)

**Comment by dimitrisdimos00** [comment]
> The option proposed by devcall is not on the voting list xD (This is the one i would have gone for, if it were and if it were technically possible.)

Yeah.. agreed, I think that's better too

**Comment by dimitrisdimos00** [comment]
> The option proposed by devcall is not on the voting list xD (This is the one i would have gone for, if it were and if it were technically possible.)

Yeah.. agreed, I think that's better too

**Comment by dimitrisdimos00** [comment]
We better add the devcall option to the poll too, I suggest

**Comment by koppor** [comment]
Since we do not reach the mass of the users, the poll is not representative. The poll results were condidered at the DevCall. Just put the button below the group list without the large white space. This is also described at https://github.com/JabRef/jabref/pull/8462#issuecomment-1026276429.

**Comment by dimitrisdimos00** [comment]
Can someone merge this?

**Comment by ThiloteE** [comment]
I tried to test your pull request before merging, but I can't access it via git and it also does not show up at https://builds.jabref.org/pull/

**Comment by Siedlerchr** [comment]
@ThiloteE It's because it's from a user fork and not on the main JabRef-Repo.
If you want to try it out via git you can use github's cli tool https://cli.github.com/

**Comment by Siedlerchr** [comment]
@dimitrisdimos00  We first review before we merge. Please update your screenshot in the description

**Comment by Siedlerchr** [comment]
This somehow looks like a waste of space for me:
grafik

**Comment by Siedlerchr** [comment]
For me it looks like:
grafik

**Comment by ThiloteE** [comment]
dito :/

**Comment by dimitrisdimos00** [comment]
I fixed the height bug in the library, now it looks like this: 
image
I used VBox to contain the filter search HBox and the button Hbox and set it on Top

**Comment by ThiloteE** [comment]
There is just one more tiny legitimacy problem (apart from testing): This position neither goes along with the results of the [poll](https://github.com/JabRef/jabref/pull/8462#issuecomment-1025212895), nor the decision of the [dev-call](https://github.com/JabRef/jabref/pull/8462#issuecomment-1063485676). I personally think it looks fine 👍 (Apart from my personal preference of having Group and Websearch left aligned, but whatever xD) I personally would not mind merging this, but since this is a community project, I am willing to refrain from placing my preference above that of the community that has so readily and in large numbers voiced their preferences and maybe so can you 😅. (50+ people that participated in this poll that did not even have all the options? Respect!)

**Comment by ThiloteE** [comment]
LOL. I just realized one can click on the poll as often as one wants. It allows users to be counted multiple times. Ok this poll is NOT representative at all. Democracy my ass xD

**Comment by dimitrisdimos00** [comment]
Lol yeah, this poll was kinda weird...
> Since we do not reach the mass of the users, the poll is not representative. The poll results were condidered at the DevCall. Just
I just did what koppor said here

**Comment by dimitrisdimos00** [comment]
Ok I now realized it is different from the devcall. I will try to fix that.

**Pull request closed without merging**
