### PR TITLE
update user agent and change acm to https

### LINKED ISSUE #3500: Importing from the ACM Digital Library hangs after selection
- [X] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef version 4.1-dev--snapshot--2017-12-08--master--6f39151a7, Linux 4.13.0-17-generic amd64, Java 1.8.0_121 on Ubuntu 17.10

Steps to reproduce:

1. Search for a paper on the ACM Portal.
2. Select to import one the returned entries.

Expected result:
Entry appears in my bibliography.

Actual result:
JabRef hangs.

<details>
  <summary>Log File</summary>
  
  ```
  10:06:08.970 [JavaFX Application Thread] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
java.lang.NullPointerException: null     
        at org.jabref.gui.search.GlobalSearchBar.lambda$new$5(GlobalSearchBar.java:196) ~[JabRef--master--latest.jar:?]
        at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295) ~[jfxrt.jar:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_121]
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294) ~[jfxrt.jar:?]
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:?]
        at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method) ~[jfxrt.jar:?]
        at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139) ~[jfxrt.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]                     
File: grouptree.fxml not found, attempting with camel case                         
File: grouptree.css not found, attempting with camel case                          
10:06:44.558 [JabRef CachedThreadPool] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[JabRef CachedThreadPool,6,main]
java.lang.StringIndexOutOfBoundsException: String index out of range: -1           
        at java.lang.String.substring(String.java:1960) ~[?:1.8.0_121]             
        at org.jabref.gui.importer.fetcher.ACMPortalFetcher.downloadEntryBibTeX(ACMPortalFetcher.java:325) ~[JabRef--master--latest.jar:?]
        at org.jabref.gui.importer.fetcher.ACMPortalFetcher.getEntries(ACMPortalFetcher.java:181) ~[JabRef--master--latest.jar:?]
        at org.jabref.gui.importer.fetcher.GeneralFetcher.lambda$actionPerformed$2(GeneralFetcher.java:198) ~[JabRef--master--latest.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
  ```
</details>

### PR DESCRIPTION
**Pull request by Siedlerchr**
Fix acm fetcher
Fixes #3500 

----

- [x] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [ ] Screenshots added (for bigger UI changes)
- [x] Manually tested changed features in running JabRef
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)
- [ ] If you changed the localization: Did you run `gradle localizationUpdate`?

### CODE REVIEW

**Comment by Siedlerchr** [comment]
Hmmmm that's odd, for me it worked. Will take a look at it

**Comment by Siedlerchr** [comment]
Okay, I tested things again and I cannnot reproduce your error. Works fine on my side

**Comment by lenhard** [comment]
Tested again, still same error, regardless of how I configure the fetcher in the UI.

It seems that someone else should be testing this as well.

**Comment by koppor** [comment]
Is this the right test setting? --> Works here.

grafik

**Comment by lenhard** [comment]
I get the same error on current master, so this is probably unrelated to this PR. 

Seems what I get back from acm is Chinese instead of a web page, which probably means some encoding problem:
acm

This shouldn't block the current PR, which I am merging now.

**Pull request merged**
