### PR TITLE
Fix icon color in dark mode 

### LINKED ISSUE #7853: Icons in Entry Edit Window not visible in Dark Mode
JabRef version 5.3--2021-06-27--aa60dd6 on Windows 10

I have tested the latest development version from http://builds.jabref.org/main and the problem persists

The icons in the entry edit window are frequently too dark to be visible in dark mode. A bright color would be better suited

1. change to dark mode
2. edit an entry
3. view icons

Screenshot 2021-06-28 132651

### PR DESCRIPTION
**Pull request by Joe11028**
Solution to, fixes #7853
After checking [dark.css](https://github.com/JabRef/jabref/blob/main/src/main/java/org/jabref/gui/Dark.css) and [base.css](https://github.com/JabRef/jabref/blob/main/src/main/java/org/jabref/gui/Base.css), and tempting change color of the icons, but find out the color of icons can not be changed, because the icon imported from Package org.kordamp.ikonli.mamaterialdesign is colored and can not be changed. So rather than import another set of icons, I prefer adjusting icon-background-color in dark mode. Then you can find the icon button easily. The effect is shown in the [figure.](https://img-blog.csdnimg.cn/20210718163715348.png)

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by Siedlerchr** [comment]
Thanks for your PR, can you please add some Screenshots so we can see your changes?

**Comment by Joe11028** [comment]
In light theme:[figure1](https://img-blog.csdnimg.cn/20210718172100710.png),[figure2](https://img-blog.csdnimg.cn/20210718172101231.png),[figure3](https://img-blog.csdnimg.cn/20210718172101226.png)
In dark theme(original):[figuer1](https://img-blog.csdnimg.cn/20210718172100939.png) ,[figure2](https://img-blog.csdnimg.cn/20210718172101377.png),[figure3](https://img-blog.csdnimg.cn/20210718172101437.png)
In dark theme(modified):[figure1](https://img-blog.csdnimg.cn/20210718172101169.png),[figure2](https://img-blog.csdnimg.cn/20210718172101437.png),[figure3](https://img-blog.csdnimg.cn/20210718172101427.png)

**Comment by calixtus** [comment]
This seems very odd, that the icon color could not be changed and would be a major bug in the ikonli  package.
Did you try changing the ikonli-font-icon css class like described here? https://kordamp.org/ikonli/#_javafx

**Comment by calixtus** [comment]
A great tool for debugging javafx guis is https://github.com/JonathanGiles/scenic-view . This should help here too.

**Comment by Joe11028** [comment]
@calixtus Thank you for providing infomations, I will improve this a few days later.

**Comment by Joe11028** [comment]
@calixtus @Siedlerchr I modified the icon colors by changing color of each icon in fxml files, not in css file. Then there's a problem that no matter in light mode or in dark mode these icons' color will not changed. So I wonder how can i change these icons in css files. And there's some figures after change, do you have any suggestion?
In dark mode:[figure1](https://img-blog.csdnimg.cn/20210719160054321.png), [figure2](https://img-blog.csdnimg.cn/20210719160054563.png), [figure3](https://img-blog.csdnimg.cn/20210719160054555.png)
In light mode:[figure1](https://img-blog.csdnimg.cn/20210719160054439.png), [figure2](https://img-blog.csdnimg.cn/20210719160308441.png), [figure3](https://img-blog.csdnimg.cn/20210719160054562.png)

**Comment by Joe11028** [comment]
I change the color of icon by adding icon-color of the buttons in fxml files. Though it works partly, i think there may a better way to solve this problem.

**Comment by Siedlerchr** [comment]
I think you can simply override the icon color in the dark.css
Have a look at the glyph-icon and also test with scenic view

**Comment by Joe11028** [comment]
@Siedlerchr  I‘ve tested glyph-icon, but it didn't work. I think override the icon color in dark.css may work. But, how to reference these button-icon in css file is kinda hard for me? But i will try.

**Comment by calixtus** [comment]
According to the documentation of ikonli https://kordamp.org/ikonli/#_javafx you need to change the -fx-icon-color in the css subclass `ikonli-font-icon`. Please use scenicview to determine the right hierarchy this subclass belongs to.

See here:
Screenshot_20210719-133741

There is also an exception for stacked panes.

**Comment by calixtus** [comment]
Btw. according to our documentation the base color of icons should always be the same as the text.

**Comment by Joe11028** [comment]
@calixtus Okay, i will follow the documentation to modify the color of icons, thanks.

**Comment by Siedlerchr** [comment]
Just asking, @Joe11028  Have you made any progress? Are there any things where you struggle?

**Comment by Joe11028** [comment]
> Just asking, @Joe11028 Have you made any progress? Are there any things where you struggle?

I got stuck in altering the color of icons that i can change the background color of these buttons but failed to change the color of icons in this figure.
QQ截图20210730101548
I set id for these buttons in fxml file, and then in css file i attempt  to change the icon color by modifying  '-fx-icon-color' or '-fx-fill', but it doesn't work. So can you offer me some suggestions?

**Comment by Siedlerchr** [comment]
@Joe11028 as @calixtus  has quoted from the Ikonli documentation, you just need to add this to the end of the Dark.css:
An example (I tested with the light one)
No need to adjust anything in the fxml

```
.ikonli-font-icon {
	-fx-icon-color: red;
}
```

grafik

**Comment by Joe11028** [comment]
@Siedlerchr I add these at the end of base.css and set -fx-icon-color: -fx-text-base-color. Here's the outcome.
QQ截图20210802080601
QQ截图20210802080608
QQ截图20210802080758
QQ截图20210802080808
I think it works, and i gonna open a new PR.

**Comment by Joe11028** [comment]
@Siedlerchr  I've tried to add this in PreferencesDialog.css instead of Base.css, it looks prettier. I think this one is better.
 
QQ截图20210802081841
QQ截图20210802081849
QQ截图20210802081717
QQ截图20210802081729

**Pull request closed without merging**
