### PR TITLE
Update gradle from 6.3 to 6.5.1

### PR DESCRIPTION
**Pull request by koppor**
See https://docs.gradle.org/6.4/release-notes.html and https://docs.gradle.org/6.5/release-notes.html for the release notes.

Not sure how following impacts us:

> With this release, Gradle supports the Java Module System with everything you need to compile and execute tests for Java modules. You can also build Javadoc and run applications.

We need to fix our build file (?)

```terminal
Execution failed for task ':generateBstGrammarSource'.
 
Caused by: java.lang.IllegalStateException: The value for task ':generateBstGrammarSource' property 'mainClass' is final and cannot be changed any further.
```

### CODE REVIEW

**Comment by Siedlerchr** [comment]
https://docs.gradle.org/6.4/userguide/upgrading_version_6.html#new_properties_may_shadow_variables_in_build_scripts

**Comment by koppor** [comment]
The issue seems to be here: https://github.com/JabRef/jabref/blob/2af41eb82353e37e2a6730485dc76276457fd4af/buildSrc/src/main/groovy/org/jabref/build/antlr/AntlrTask.groovy#L28

We need this special plugin as we use both ANTLR3 and ANTLR4. We cannot udpate our ANTLR3 grammar to ANTLR4. This is more than one hour effort since ANTLR changed consideradibly.

**Comment by tobiasdiez** [comment]
According to https://docs.gradle.org/6.4/userguide/java_library_plugin.html#declaring_package_visibility_and_services
> The Java module system supports additional more fine granular encapsulation concepts than Gradle itself currently does. For example, you explicitly need to declare which packages are part of your API and which are only visible inside your module. Some of these capabilities might be added to Gradle itself in future versions.

Until this is implemented, there is no real hope for us to use these now module system features of gradle.

**Comment by Siedlerchr** [comment]
Regarding the grammar task, would it be sufficient to change the variable name?
from what I understand the problem is that the variable name main has to be changed

**Comment by koppor** [comment]
Idea: Extend from a general gradle task and instantiate JavaExec internally (and do not inherit from it anymore)

**Comment by Siedlerchr** [comment]
I maybe found a solution, the "=" has to  be changed to set.
See: 
https://github.com/gradle/gradle/issues/12841
And https://github.com/franzbecker/gradle-lombok/pull/77/files for an implementation

**Comment by Siedlerchr** [comment]
Unfortunately my fixes didn't work, they compile, but afterwards the path is not found. Fck gradle.

**Comment by Siedlerchr** [comment]
Still does not work with gradle 6.7 , however I noticed that they reworked the plugin:
I don't know much of this gradle stuff, but maybe this helps?

https://github.com/gradle/gradle/blob/fa4d3ad3ffd3ec3c321e5715879cecbb85a2aebd/subprojects/antlr/src/main/java/org/gradle/api/plugins/antlr/AntlrPlugin.java#L53-L57

**Pull request closed without merging**
