### PR TITLE
Refactor main table preferences

### LINKED ISSUE #6515: The maintable authors' column does not update on preference change
In JabRef 5.0--2020-03-09--6bff936 changes in `preferences -> entry table -> Format of author and editor names` updates the column. E.g., changing from "Firstname Lastname" to "Lastname, Firstname" is immediately shown.

In the current master (built from Intellij on Mac OS 10.15.4 the 23rd of May) changes requires a restart before the author column updates.
It also does not work with
JabRef 5.1--2020-05-22--ef2a31c
Mac OS X 10.15.4 x86_64 
Java 14.0.1

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Attempt to change the style of the authors' column
2. Press save
3. Notice that the format of the authors' names are not changed
4. Easiest to spot with "Firstname Lastname" to "Lastname, Firstname"

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

### PR DESCRIPTION
**Pull request by calixtus**
Follow up to #6509 

Merged table preferences, see the screenshot.

grafik

Fixes #6515 

- [ ] Change in CHANGELOG.md described (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by tobiasdiez** [comment]
I think the "Enable special fields" should move to another preference tab as this is not really related to the main table. Moreover, is the "Extra column" still needed (and what does it do)?

**Comment by calixtus** [comment]
'Show extra columns' adds additional columns to the combobox providing a column for every filetype (instead of one column displaying different icons for each filetype). In refactoring the tabs to the mvvm pattern we discussed removel of these columns and decided to keep them, as they were not really complicated to implement or maintain. We didn't want to kill a feature (even though there is probably hardly a use case) without need.

About special fields: I did not yet have any better idea to place them but the general tab. But this is no permanent solution. So I decided to keep this as it is and leave it to a dedicated SpecialFields PR, because I would like to focus here on extracting the calls to JabRefPreferences out of the codebase.

NatBib style is (if i remember right) 'Lastname' or 'Lastname et al.'

**Comment by calixtus** [comment]
Done what I planned to do here.
@tobiasdiez do you have a suggestion for the natbib label?

**Comment by tobiasdiez** [comment]
What about "Show only lastname" instead of natbib? (but this is already in abbreviations...so I'm not sure what natbib actually does ;-)).

Ok, then I would vote to remove the "Show extra columns" option and always add these fields to the dropdown. It's not hurting if there are a couple of more options to select.

I agree with the special fields, it was just an observation as you were already touching the code.

I'll review the code later....

**Comment by Siedlerchr** [comment]
I fear a merge conflict in/with #6479  regarding the maintableformatter. Therefore I would propose to first merge the other PR and then this.

**Comment by calixtus** [comment]
Agreed. I took a look at it, we definitely should merge #6479 first. Integrating the changes shouldn't be that hard. Although we worked on the same code, we were working on different aspects.

**Comment by Siedlerchr** [comment]
#6479  has been merged now.

**Pull request merged**
