### PR TITLE
Fixes issue #9281: Let right-click menu more accurately represent selected (sub-)group(s)

### LINKED ISSUE #9281: "Remove group" options are presented for clicked group, but actions are taken on all selected groups
### JabRef version

Latest development branch build (please note build date below)

### Operating system

Windows

### Details on version and operating system

Windows 21H2, jabref build date: 22/10/22

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Create new library
2. In new library, create 2 groups
3. Select first group using left click
4. Right click on second group
5. Options for second group show up
6. Click `Remove group > Also remove subgroups` or `Remove group > keep subgroups`
7. First group is deleted, second group is kept

image
image
image

The `group` passed to `removeGroupKeepSubgroups` and `removeGroupAndSubgroups` is only used for dialog text, `selectedGroups` is used for all actual removals. 

Potential solutions could be to check that clicked group is part of selected groups, or to update context menu and dialogs to reflect selected groups more accurately.

### Appendix

Appears to be caused by changes from #8390.
<details>

<summary>Problematic methods</summary>

 
org.jabref.gui.groups.GroupTreeViewModel.java:
```
public void removeGroupKeepSubgroups(GroupNodeViewModel group) {
        boolean confirmed;
        if (selectedGroups.size() <= 1) {
            confirmed = dialogService.showConfirmationDialogAndWait(
                    Localization.lang("Remove group"),
                    Localization.lang("Remove group \"%0\" and keep its subgroups?", group.getDisplayName()),
                    Localization.lang("Remove"));
        } else {
            confirmed = dialogService.showConfirmationDialogAndWait(
                    Localization.lang("Remove groups"),
                    Localization.lang("Remove all selected groups and keep their subgroups?"),
                    Localization.lang("Remove all"));
        }

        if (confirmed) {
            // TODO: Add undo
            // final UndoableAddOrRemoveGroup undo = new UndoableAddOrRemoveGroup(groupsRoot, node, UndoableAddOrRemoveGroup.REMOVE_NODE_KEEP_CHILDREN);
            // panel.getUndoManager().addEdit(undo);

            List<GroupNodeViewModel> selectedGroupNodes = new ArrayList<>(selectedGroups);
            selectedGroupNodes.forEach(eachNode -> {
                GroupTreeNode groupNode = eachNode.getGroupNode();

                groupNode.getParent()
                         .ifPresent(parent -> groupNode.moveAllChildrenTo(parent, parent.getIndexOfChild(groupNode).get()));
                groupNode.removeFromParent();
            });

            if (selectedGroupNodes.size() > 1) {
                dialogService.notify(Localization.lang("Removed all selected groups."));
            } else {
                dialogService.notify(Localization.lang("Removed group \"%0\".", group.getDisplayName()));
            }
            writeGroupChangesToMetaData();
        }
    }

public void removeGroupAndSubgroups(GroupNodeViewModel group) {
        boolean confirmed;
        if (selectedGroups.size() <= 1) {
            confirmed = dialogService.showConfirmationDialogAndWait(
                    Localization.lang("Remove group and subgroups"),
                    Localization.lang("Remove group \"%0\" and its subgroups?", group.getDisplayName()),
                    Localization.lang("Remove"));
        } else {
            confirmed = dialogService.showConfirmationDialogAndWait(
                    Localization.lang("Remove groups and subgroups"),
                    Localization.lang("Remove all selected groups and their subgroups?"),
                    Localization.lang("Remove all"));
        }

        if (confirmed) {
            // TODO: Add undo
            // final UndoableAddOrRemoveGroup undo = new UndoableAddOrRemoveGroup(groupsRoot, node, UndoableAddOrRemoveGroup.REMOVE_NODE_AND_CHILDREN);
            // panel.getUndoManager().addEdit(undo);

            ArrayList<GroupNodeViewModel> selectedGroupNodes = new ArrayList<>(selectedGroups);
            selectedGroupNodes.forEach(eachNode -> {
                removeGroupsAndSubGroupsFromEntries(eachNode);
                eachNode.getGroupNode().removeFromParent();
            });

            if (selectedGroupNodes.size() > 1) {
                dialogService.notify(Localization.lang("Removed all selected groups and their subgroups."));
            } else {
                dialogService.notify(Localization.lang("Removed group \"%0\" and its subgroups.", group.getDisplayName()));
            }
            writeGroupChangesToMetaData();
        }
    }
```

</details>

### PR DESCRIPTION
**Pull request by William-Yao425**
Fixes #9281

----
### Proposed solution 
---
We assume that the user would like to apply removal only to the current clicked group if the clicked group is not in `selectedGroups`  
- When `removeGroupKeepSubgroups()` or `removeGroupAndSubgroups()` are called, check whether the clicked group is presented in `selectedGroupds` 
  - if yes, we do not take anything actions 
  - if no, clear `selectedGroups` and add the current clicked group into `selectedGroups`

### Single group in `selectedGroup` but does not contain `group` removal
before `removeGroupKeepSubgroups()` or `removeGroupAndSubgroups()`:
`selectedGroups`: test2
`group`: test3 
#### Steps:

image
image
image

### Multi group in `seletedGroup` but does not contain `group`
before `removeGroupKeepSubgroups()` or `removeGroupAndSubgroups()`:
`selectedGroups`: test1, test2,test3
`group`: test4
#### Steps:
image
image
image

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by William-Yao425** [comment]
Hi, could anyone please me some instructions of solving the deployment for macOS. Is it test fail due to my implementation is based on Window system in my local workplace? 
>"Error: At least one of p12-filepath or p12-file-base64 must be provided"

**Comment by Siedlerchr** [comment]
Thanks for the pr, you can ignore the failure of the mac tests. It require some signing keys that are only available in the original Jabref repor

**Comment by ThiloteE** [comment]
To ease organizational workflows I have linked the pull-request to the issue with syntax as described in https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

> <h2 id="linking-a-pull-request-to-an-issue-using-a-keyword">Linking a pull request to an issue using a keyword</h2>
> <p>You can link a pull request to an issue by using a supported keyword 
> in the pull request's description or in a commit message. The pull 
> request <strong>must be</strong> on the default branch.</p>
> <ul>
> <li>close</li>
> <li>closes</li>
> <li>closed</li>
> <li>fix</li>
> <li>fixes</li>
> <li>fixed</li>
> <li>resolve</li>
> <li>resolves</li>
> <li>resolved</li>
> </ul>
> <p>If you use a keyword to reference a pull request comment in another 
> pull request, the pull requests will be linked. Merging the referencing 
> pull request also closes the referenced pull request.</p>
> <p>The syntax for closing keywords depends on whether the issue is in the same repository as the pull request.</p>

**Comment by William-Yao425** [comment]
Thanks for your suggestion. May I please ask is there anything in our implementation need be improved? We would like to have some feedback.

**Comment by calixtus** [comment]
Thanks for your interest in JabRef programming. After taking a quick look into your solution, this seems to be rather a workaround, but a solution. Before deciding on this issue, i think its best to have some comparisons, eg. how does windows explorer or mac or any other file manager handle the case, that the right click happens not on the entry, which is selected?

**Comment by calixtus** [comment]
Can you please offer some insight in your rationale and provide some examples, how windows explorer or other applications handle right-click on a list?
What's the status here?

**Comment by calixtus** [comment]
I sorry to see you may have lost interest in fixing this issue. Would be still great though if this issue could be fixed. Maybe someone else is interested looking into best practices on right click handling in lists?

**Pull request closed without merging**
