### PR TITLE
Added Ordinal formatter

### PR DESCRIPTION
**Pull request by oscargus**
Motivated by http://tex.stackexchange.com/questions/292491/numerals-to-ordinals-in-jabref-jstyle-layout-file

### CODE REVIEW

**Comment by simonharrer** [comment]
Should be documented in the documentation that we have an additional LayoutFormatter available.

**Comment by oscargus** [comment]
Yeah, that will be a separate PR (or can one do a joint PR to two different repositories?). Added a ChangeLog entry though.

**Comment by simonharrer** [comment]
:+1: I would link the other PR for the documentation.

**Comment by oscargus** [comment]
(English) Documentation at JabRef/help.jabref.org#5

**Pull request merged**
