### PR TITLE
Fix Preferences style value too long

### LINKED ISSUE #6198: Storing selected preview throws java.lang.IllegalArgumentException: Value too long:
Current dev version

1. Go to Preferences ->  Entry Preview
2. Search American Psychological Association...
3. Move the style to the right
4. Select it or move it up to the top
5. Save preferences:
6. Exception occurs

The problem is that the maximum allowed value for the Preferences Value is:
8192 characters  (MAX_VALUE_LENGTH)

Solution: I think the solution would be to store the name of the style

```
20:45:28.751 [JavaFX Application Thread] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
java.lang.IllegalArgumentException: Value too long: <?xml version="1.0" encoding="utf-8"?> (omitted here) 
	at java.util.prefs.AbstractPreferences.put(AbstractPreferences.java:253) ~[?:?]
	at org.jabref.preferences.JabRefPreferences.put(JabRefPreferences.java:937) ~[main/:?]
	at org.jabref.preferences.JabRefPreferences.storePreviewPreferences(JabRefPreferences.java:1441) ~[main/:?]
	at org.jabref.gui.preferences.PreviewTabViewModel.storeSettings(PreviewTabViewModel.java:203) ~[main/:?]
	at org.jabref.gui.preferences.AbstractPreferenceTabView.storeSettings(AbstractPreferenceTabView.java:30) ~[main/:?]
```

### PR DESCRIPTION
**Pull request by leitianjian**
Fixes #6198 

Here are some explanations

**origin** of the bug
The listener add on chosenSelectionModelProperty

https://github.com/JabRef/jabref/blob/14e979051abc329e4d111c0066c0610fe8eb1b44/src/main/java/org/jabref/gui/preferences/PreviewTabView.java#L146

When we want to remove some cell from the chosenListProperty, before the remove operation is done. The selectionModel modified listener was fired (remove modified selectionModel too). Then the sourceTextProperty in PreviewTabViewModel.java was modified, which will fire the listener add on sourceTextProperty

https://github.com/JabRef/jabref/blob/14e979051abc329e4d111c0066c0610fe8eb1b44/src/main/java/org/jabref/gui/preferences/PreviewTabViewModel.java#L79-L83

The lambda above will modify the choseListProperty first elements.

So, my solution is clear the selection before we remove some elements
The drag cases are a little bit difficult.
I add a field named dragSourceSelectionModel which is similar to dragSourceList
After these modifications, I think the bug was solved.

I don't know why the merged changes appear again, maybe someone has rollbacked the master branch? I checked the code in the master, which seems the fixes of the issues #6169 have been dropped?

Thanks for any instruction in advanced.

- [x] Change in CHANGELOG.md described (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by Siedlerchr** [comment]
>I don't know why the merged changes appear again, maybe someone has rollbacked the master branch? I checked the code in the master, which seems the fixes of the issues #6169 have been dropped?

Try to merge in the changes from upstream/master

**Comment by calixtus** [comment]
Codewise looks good to me, thank you very much.

**Comment by calixtus** [comment]
I think the changelog entry is wrong. Please change that.

**Comment by leitianjian** [comment]
> > I don't know why the merged changes appear again, maybe someone has rollbacked the master branch? I checked the code in the master, which seems the fixes of the issues #6169 have been dropped?
> 
> Try to merge in the changes from upstream/master

I don't know why ```git fetch upstream``` does not fetch the upstream changes. After pull the changes from upstream. I think the problem was solved. Thank for your tips。

> I think the changelog entry is wrong. Please change that.
> Or at least not complete. Just add another entry for the fix about issue #6198

I modified the changelog entry. Please check it again. Thanks

**Pull request merged**
