### PR TITLE
Simplify check-links.yaml (markdown-link-check)

### PR DESCRIPTION
**Pull request by koppor**
Just internal changes - no need to review

### CODE REVIEW

**Comment by koppor** [comment]
Blocked by https://github.com/gaurav-nelson/github-action-markdown-link-check/issues/41#issuecomment-664816921

**Comment by Siedlerchr** [comment]
What is the status here?

**Comment by koppor** [comment]
Can be merged after the release.

**Comment by koppor** [comment]
The file filter works here. Strange. Refs https://github.com/JabRef/jabref/pull/6803.

**Pull request merged**
