### PR TITLE
[WIP] New iconset

### PR DESCRIPTION
**Pull request by matthiasgeiger**
see #130

### CODE REVIEW

**Comment by simonharrer** [comment]
The following icon keys are not used in JabRef at the moment:

abstract
close2
quality
plugin
setRelevant
medline
jabrefIcon
importFromKeywords
exportToKeywords

What is used in the code but not supplied by the icon set

openFolder
groupRegular

This is part of the effort to add a new icon set.

**Comment by koppor** [comment]
Oh, why is "setRelevent" there, but not "setRead", "setPrinted". What is the reason for that?

Why is there importFrom/exportTo keywords? What is the intended use?

**Comment by tobiasdiez** [comment]
There is no "setRead" or "setPrinted" because when I implemented these features there was no need for such an icon.

**Comment by simonharrer** [comment]
This is tracked in the icons branch now. Closing this.

**Pull request closed without merging**
