### PR TITLE
Remove empty entries automatically

### PR DESCRIPTION
**Pull request by koppor**
Fixes https://github.com/JabRef/jabref/issues/8645.

Empty entries IMHO do not contain any information.

Exmaple for empty entries:

```bibtex
@misc{}

@article{}
```

With a citation key or any other field, they are not empty:

```bibtex
@misc{test}

@article{test2}
```

This PR adds a functionality so that these entries are automatically removed while writing.

## Outdated

In case they are removed, JabRef will (**udate** NOT) issue a warning "changed on disk". I think, this warning is OK, isn't it?

image

```[tasklist]
### Compulsory checks
- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.
```

### CODE REVIEW

**Comment by Siedlerchr** [comment]
This defeats the purpose of the dialog. I would rather have an option to automatically always delete them

**Comment by koppor** [comment]
The dialog was there to warn about null information being in the library. 

Is there anyone wanting to keep information that an entry with `@article` is in the database?

Back in https://github.com/JabRef/jabref/issues/8096#issuecomment-1124408639, we agreed that deleting the entries is a solution.

I updated the PR link to link the issue which explains why empty entries cause a headache: https://github.com/JabRef/jabref/issues/8645

**Comment by Siedlerchr** [comment]
Not happy about this leading to a changed on disk

**Comment by koppor** [comment]
> Not happy about this leading to a changed on disk

Fixed.

**Comment by koppor** [comment]
This (now) also fixes https://github.com/JabRef/jabref/issues/8645, because `isEmpty` currently includes a check for auto generated fields:

```bibtex
@Article{,
  creationdate = {2022-04-05T10:41:54},
  owner        = {mlep},
}
```

**Review by Siedlerchr — DISMISSED** [review]

**Review by calixtus — DISMISSED** [review]

**Pull request merged**
