### PR TITLE
Greek Translation

### PR DESCRIPTION
**Pull request by motorcyclist**
Need help finishing it...

- [ ] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [ ] Screenshots added (for bigger UI changes)
- [ ] Manually tested changed features in running JabRef
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)
- [ ] If you changed the localization: Did you run `gradle localizationUpdate`?

### CODE REVIEW

**Comment by lenhard** [comment]
@motorcyclist Unfortunately, I don't know anyone close to the development team who is fluent in Greek, so I don't know how we could help you :-/ 

Are you planning to add more translations? If yes, just keep doing and we can keep this open. If not, we can merge it into master. A little bit of translation is better than no translation.

**Comment by mlep** [comment]
@motorcyclist Which kind of help do you need? If it is about continuing the translation, you may post your request here: http://discourse.jabref.org

**Comment by motorcyclist** [comment]
@lenhard that's okay. Thank you for trying to help. In that case I will be adding new translation bit-by-bit and hope consider putting it in next jabref version...

**Comment by lenhard** [comment]
@motorcyclist Ok, good to know! Just keep on adding translations and we will merge in whatever is there directly before we release v4.0 (no fixed date yet).

Also, no worries: Your changes to jabref_el.properties are approved. You can view the changes by @stefan-kolb  here: https://github.com/JabRef/jabref/pull/2835/commits/f60967651fafcdfa25ba4bba06147ee8c3944d5b
All he did was to delete the file header that your editor probably wrote in there. The translations themselves are fine.

**Comment by lynyus** [comment]
I would argue that the PR should be merged now, and @motorcyclist should open a new PR for the next chunk he wants to translate.
See Issue https://github.com/JabRef/jabref/issues/2893

**Pull request merged**
