### PR TITLE
Fix command line export for --exportMatches

### LINKED ISSUE #9581: Command line export does not create an output bib file
### JabRef version

5.9 (latest release)

### Operating system

MacOS

### Details on version and operating system

MacOS Ventura 13.0.1 (22A400)

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

I am trying to create sub-databases (one database by author) from a global .bib file using the filtering features of the command line tool. Here is the commande I use to filter only AuthorOneName related papers from the global Input_bib.bib file:

`JabRef --exportMatches Author=AuthorOneName,Output_bib.bib,bib -i Input_bib.bib -n`

I do not receive any error message, everything seems to be ok, including the filtering. Nevertheless, no output file is created.
Important information: it fails when using bib format as output, but it works for other formats such as bibtexml, endnote, html for instance.

Am I doing something wrong or is it a bug related to the bib format ? 

### Appendix

<details>

<summary>Input_bib.bib</summary>

```
@article{AutOne2022,
author = 	 {AuthorOneName, AuthorOneFirstName and AuthorTwoName, AuthorTwoFirstName},
title = 	 {An interesting paper},
journal = 	 {Mickey Mouse Magazine},
year = 	 {2023}
}

@article{AutTwo2023,
author = 	 {AuthorOneName, AuthorOneFirstName and AuthorTwoName, AuthorTwoFirstName},
title = 	 {Another interesting paper},
journal = 	 {Donald Duck Magazine},
year = 	 {2023}
}

@Article{AutThree,
  author  = {AuthorThreeName, AuthorThree3FirstName and AuthorTwoName, AuthorTwoFirstName},
  journal = {I love datahseets magazine},
  title   = {Look at this one},
  year    = {2021},
}

@Comment{jabref-meta: databaseType:bibtex;}
```

</details>

### PR DESCRIPTION
**Pull request by aqurilla**
This fixes #9581 by creating an export bib file when the `bib` export format is specified, or when there is no specified export format. 

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [x] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [x] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by Siedlerchr** [comment]
Thank, codewie looks already good! Will test this later

**Comment by aqurilla** [comment]
Thanks, appreciate it!

**Review by Siedlerchr — DISMISSED** [review]

**Comment by Siedlerchr** [comment]
Please add a changelog entry!

**Review by koppor — APPROVED** [review]

**Comment by Siedlerchr** [comment]
Thanks for the very good work! This and the other PR were both good!

**Comment by aqurilla** [comment]
Great to hear that, thanks!

**Pull request merged**
