### PR TITLE
fix java.nio.file.FileSystemNotFoundException and reorganize code

### PR DESCRIPTION
**Pull request by springzfx**
If you run the [jar file](https://builds.jabref.org/master/ ) ouside IDE, then an error will be reprted:

> [JavaFX Application Thread] ERROR org.jabref.JabRefMain - Unexpected exception
java.nio.file.FileSystemNotFoundException: null
	at com.sun.nio.zipfs.ZipFileSystemProvider.getFileSystem(ZipFileSystemProvider.java:171) ~[zipfs.jar:1.8.0_172]
	at com.sun.nio.zipfs.ZipFileSystemProvider.getPath(ZipFileSystemProvider.java:157) ~[zipfs.jar:1.8.0_172]
	at java.nio.file.Paths.get(Paths.java:143) ~[?:1.8.0_172]
	at org.jabref.gui.util.ThemeLoader.<init>(ThemeLoader.java:52) ~[JabRef--master--latest.jar:?]
	at org.jabref.Globals.startBackgroundTasks(Globals.java:82) ~[JabRef--master--latest.jar:?]
	at org.jabref.JabRefMain.start(JabRefMain.java:63) ~[JabRef--master--latest.jar:?]
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$161(LauncherImpl.java:863) ~[jfxrt.jar:?]
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$174(PlatformImpl.java:326) ~[jfxrt.jar:?]
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295) ~[jfxrt.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_172]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294) ~[jfxrt.jar:?]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:?]
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method) ~[jfxrt.jar:?]
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139) ~[jfxrt.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]

It is just an url problem, simple to fix. I added some logs, and reorganized  a little code.

----

- [ ] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [ ] Manually tested changed features in running JabRef
- [ ] Screenshots added in PR description (for bigger UI changes)
- [ ] Ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)

### CODE REVIEW

**Comment by Siedlerchr** [comment]
Please fix the checkstyle issues from travis and we can mergei t.

**Comment by springzfx** [comment]
In travis, I get this, what should I do:
> `Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.2/userguide/command_line_interface.html#sec:command_line_warnings`

**Comment by Siedlerchr** [comment]
You can ignore the other warning about gradle. But you should check the checkstyle output

**Comment by springzfx** [comment]
yes, i have fixed the checkstyle issue.

**Comment by tobiasdiez** [comment]
The gui tests seems to have been crashed, as they sometimes do. I'll merge now and hope it still works on master.

**Pull request merged**
