### PR TITLE
Upgrade EndNote XML exporter to StAX

### PR DESCRIPTION
**Pull request by subhramit**
Follow-up to https://github.com/JabRef/jabref/pull/11157

## Upgrade EndNote XML exporter
Refs. https://github.com/JabRef/jabref/pull/11157#issuecomment-2043417540
- Upgrades existing EndNote XML exporter to **StAX** for better memory efficiency.
- Removes transformer to improve memory efficiency further (like Zotero).

**Note:** In the existing lambdas, now `XMLStreamException` is caught and thrown as `RuntimeException`  as lambdas don't allow checked exceptions to be directly thrown from them.
### Mandatory checks

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [x] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by calixtus** [comment]
About RuntimeException: ModsExporter also uses StAX and works with the so called SaveException. Does this maybe help?

**Comment by subhramit** [comment]
> About RuntimeException: ModsExporter also uses StAX and works with the so called SaveException. Does this maybe help?

It did, took some inspiration. Used `SaveException` to handle the file export (the class mostly handles files unavailable for writing due to locking by another process). 
Also added more precise exceptions to lambdas.

**Comment by subhramit** [comment]
Another prominent change - removed the transformer.
Tradeoff - can't pretty-print the XML anymore.
Benefit - even more memory efficient (for large databases) as we directly write to the output stream instead of building the unformatted xml in memory and then transforming it.
Zotero does it the same way.

**Comment by koppor** [comment]
> Tradeoff - can't pretty-print the XML anymore. 

Why? StackOverflow says different:

- https://stackoverflow.com/a/3625359/873282
- https://stackoverflow.com/a/485126/873282
- https://stackoverflow.com/a/2368681/873282


 

Benefit - even more memory efficient (for large databases) as we directly write to the output stream instead of building the unformatted xml in memory and then transforming it. Zotero does it this way too.

**Comment by koppor** [comment]
@Siedlerchr I find the new code less maintainable than the old one. In both codes, we do NOT need to generate Java-classes based on some XSD file. -- I propose to use this PR as learning for Subhramit for StAX, but close the PR due to maintenance concerns (see for example the necessary comment on closing XML elements).

**Comment by Siedlerchr** [comment]
Yes that seems to be odd

**Comment by koppor** [comment]
DevCall: Longer discussion. We close. However, in case someone shows up with a large library and gets out of memory exceptions, we will reconsider.

**Pull request closed without merging**
