### PR TITLE
Add log on disk

### PR DESCRIPTION
**Pull request by koppor**
JabRef has a build-in logging framework. Howver, the log is hard to find and to open after JabRef has closed.

This PR adds logging to `%APPDATA%` using [AppDirs](https://github.com/harawata/appdirs).

The log is a rolling log and also configured for parallel writing (in case there are multiple local instances of JabRef - who knows...)

Example:

grafik

Content:

```
2022-05-13 08:50:57 [JavaFX Application Thread] org.jabref.logic.net.ssl.TrustStoreManager.createTruststoreFileIfNotExist()
INFO: Trust store path: C:\Users\koppor\AppData\Local\org.jabref\ssl\truststore.jks
2022-05-13 08:50:57 [JavaFX Application Thread] org.jabref.gui.JabRefMain.clearOldSearchIndices()
INFO: Deleting out-of-date fulltext search index at C:\Users\koppor\AppData\Local\org.jabref\JabRef\Cache.
2022-05-13 08:50:57 [JavaFX Application Thread] org.jabref.gui.JabRefMain.clearOldSearchIndices()
INFO: Deleting out-of-date fulltext search index at C:\Users\koppor\AppData\Local\org.jabref\JabRef\Logs.
2022-05-13 08:50:57 [JavaFX Application Thread] org.jabref.gui.theme.ThemeManager.addStylesheetToWatchlist()
INFO: Watching css C:\git-repositories\jabref\jabref\build\resources\main\org\jabref\gui\Base.css for live updates
2022-05-13 08:50:57 [JavaFX Application Thread] org.jabref.gui.theme.ThemeManager.updateThemeSettings()
INFO: Not updating theme because it hasn't changed
2022-05-13 08:50:57 [JavaFX Application Thread] org.jabref.gui.theme.ThemeManager.updateThemeSettings()
INFO: Theme set to Theme{type=DEFAULT, name=''} with base css StyleSheet{file:/C:/git-repositories/jabref/jabref/build/resources/main/org/jabref/gui/Base.css}
```

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by Siedlerchr** [comment]
I would like to have the ability to turn this off in the preferences and maybe it's better to write to /tmp?

**Comment by koppor** [comment]
> and maybe it's better to write to /tmp?

The directory is coming from [AppDirs](https://github.com/harawata/appdirs#supported-directories)

grafik

On Windows, these few bytes do not matter - currently, the AppDat directory has 244 GB on my disk...

grafik

> I would like to have the ability to turn this off in the preferences

@calixtus Can you support here or can we pospone that to a follow-up PR? 😇

**Comment by koppor** [comment]
The jdk-stirpping is explained at https://tinylog.org/v2/configuration/#strip-stack-trace-elements

**Review by calixtus — APPROVED** [review]

**Comment by koppor** [comment]
Switched to [SharedFileWriter](https://tinylog.org/v2/configuration/#shared-file-writer) to enable re-creation of the log file at each start (and to enable concurrent instances writing to the log file). Thus, the amount of disk space used should be low.

@calixtus and me fear that diving into the preferences could render logging unusable in certain situations. Therefore, we decided to always write the log.

**Comment by calixtus** [comment]
Solution now: only one file is created / overwritten when starting jabref.
I think making the path of the log file editable and enabling writing a log file via the prefs is not neccessary anymore.

**Review by calixtus — APPROVED** [review]

**Pull request merged**
