### PR TITLE
Change delimiter of csv from `;` to `,`

### PR DESCRIPTION
**Pull request by northword**
Change delimiter of csv from `;` to `,`

Fixes JabRef/abbrv.jabref.org#130
Refs JabRef/abbrv.jabref.org#139

### Mandatory checks
- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by Siedlerchr** [comment]
Please have a look at the failing tests, its seems there are still some test files that need to be converted

**Comment by northword** [comment]
@Siedlerchr done, please review again, thanks!

**Comment by calixtus** [comment]
Codewise looks good, probably missing a changelog entry yet. Please add a short one.

**Comment by northword** [comment]
@calixtus A short description of the change has been added to CHANGELOG.md under the subsection "Change", and pr has been rebased to the latest main branch.

**Comment by Siedlerchr** [comment]
I would propose we wait with merge this one after the release of 5.10 as this includes potential breaking changes. Users who have their own custom journal abbrevs would need to convert their files as well

**Comment by Siedlerchr** [comment]
Superseeded by https://github.com/JabRef/jabref/pull/10281

**Pull request closed without merging**
