### PR TITLE
Jump to entry from cli

### PR DESCRIPTION
**Pull request by u7282852**
Fixes https://github.com/koppor/jabref/issues/540

Command line now supports option "jumpToEntryKey" or "-j" folowed by one entrykey argument.
Upon start up, jabref will search the imported files (BibTex files given as command line arguments) for the entrykey and focus this library and select this entry. Recently opened files will not be searched for this key, as it may be out of the scope of my knowledge of the repository to handle this gracefully. 

As mentioned by @calixtus refactoring is likely necessary to create a better way to mix the cli commands into the UI. Though functionality works as expected. 

If this change is merged user documentation at https://docs.jabref.org/advanced/commandline may need to add this feature.

Feature demonstration
image
image

### Mandatory checks

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [x] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by calixtus** [comment]
Hi, thanks for your Pull Request.
Although this functionality is fine, I am not convinced that it is the right way to mix in commands to the gui into the ParserResult, which is as mere model/logic only class. So I think this has to be implemented differently. Maybe there needs to be a whole different apprach to send ui commands from the command line to the gui.

**Comment by calixtus** [comment]
What I immediately imagine would be a List<UiCommand> of sth like `JumpToEntry implements UiCommand`, `OpenDatabase implements UiCommand` or `InsertBibEntries implements UiCommands`. This could be handled inside JabRefGUI. I sense this could be some training on cutting edge java pattern matching stuff. Actually implementing this could be fun! 😄

**Comment by u7282852** [comment]
@calixtus Thank you for the feedback! I assume UiCommand is some interface that I would create, however I am not sure exactly what would be included in this interface. Unless you are referring to https://docs.oracle.com/javaee/7/api/javax/faces/component/UICommand.html. I also not familiar with Java pattern matching so I am not sure where to apply pattern matching to this problem. 

Considering my current approach does not easily allow me to check for the argument citation key in recently opened databases, I was thinking of adding a String field to JabRefFrame storing the key which gets passed from the Launcher class. Then during the openDatabase() method I could check all databases for the key and open the respective library and entry. Would this approach be too simplistic or even applicable given it woud require changing multiple Constructors and class fields to pass this string to the JabRef. 
I might continue with this approach and refactor where necessary :)

**Comment by calixtus** [comment]
I made UiCommand up when i was commenting, I did not know there is already a idk class the same name.

Give me some days, I will try to support you with this, although I'm a bit of a very tight schedule the next days.

**Comment by u7282852** [comment]
@calixtus Thank ou again. If my changes are useful I could submit a PR and someone else could pick this up where I left off. Otherwise I can also continue working on this in the coming weeks, however I also am very busy the next few weeks.

**Comment by koppor** [comment]
- [ ] Remote messages should be logged (visible through the menu)
- [ ] Opening in running JabRef (whith library opened) does not work
- [ ] Opening a file in running JabRef does not work (JabRef does not have library opened)
- [ ] Opening a file in new JabRef instance does not work.

Test setting:

```bibtex
@Article{test,
}

@Article{lala,
}

@Article{coverpage,
  title = {YEAH},
}

@Comment{jabref-meta: databaseType:bibtex;}
```

gradle run configuration

    run --args="-j coverpage C:\temp\b.bib"

**Comment by koppor** [comment]
The functionality is WRONG.

I have OPENED LIBRARIES. The jump-to-entry should search in the OPENED LIBRARIES!

It is OK if **additionally** one can jump to an entry of a library which is given by the command line. However, the idea is just to call `jabref.bat -j entryId23` and then JabRef searches `entryId23` first in the current library. If not found, it searches the other libraries.

**Comment by Siedlerchr** [comment]
jumpToKey should only use the String citation key. No parser result needed

**Comment by calixtus** [comment]
> The functionality is WRONG.
> 
> I have OPENED LIBRARIES. The jump-to-entry should search in the OPENED LIBRARIES!
> 
> It is OK if **additionally** one can jump to an entry of a library which is given by the command line. However, the idea is just to call `jabref.bat -j entryId23` and then JabRef searches `entryId23` first in the current library. If not found, it searches the other libraries.

Took a while and some refactoring, but should be fixed now.

**Comment by calixtus** [comment]
- Selecting an entry from cli while already running needs still to be tested (@ThiloteE ?)
- As this PR is already somewhat complex, a followup should concern on searching first in the already opened library tab for the citation key.

**Comment by koppor** [comment]
Current issue: Two popups:

image

Not sure whether we should really have a second popup during loading...

**Comment by koppor** [comment]
We have more dialogs showing and waiting during loading: See `org.jabref.gui.importer.actions.OpenDatabaseAction#loadDatabase`. There will be more conflicts...

**Comment by koppor** [comment]
Removed the dialog. Checked if all points of checklist at work.

Missing thing:

Opening a library w/ remote client.

Currently, running JabRef instance rejects connections?!




My tinylog.properties:

```properties
level@org.jabref.gui.JabRefFrame = trace
level@org.jabref.logic.remote.client.RemoteClient = debug
```

**Comment by koppor** [comment]
I have following output

    TRACE: Waiting for all tabs beging loaded

Even if all tabs are loaded...

**Comment by koppor** [comment]
When a file is loaded from outside, `onDatabaseLoadingSucceed` is not called.

**Review by calixtus — DISMISSED** [review]

**Comment by calixtus** [comment]
As far as i can approve koppors changes, @Siedlerchr should also approve.

**Review by Siedlerchr — APPROVED** [review]

**Pull request merged**
