### PR TITLE
Fixes tests remaining from bibtexkey to citationkey rebranding

### PR DESCRIPTION
**Pull request by calixtus**
Refs #6875 
Refs https://github.com/JabRef/user-documentation/commit/789b631b5b48a1b7be6a55c0eef70ac81f739b6d

Quick fix for helpfile tests and preferences migrations.
No changelog, since it does not have any visual effect and is just an follow-up to @MLEP s work on the user documentation.
Comments?

- [ ] Change in CHANGELOG.md described (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by Siedlerchr** [comment]
seems like you need to adjust the other preview related migration tests as well

**Comment by calixtus** [comment]
On it, used this to test the tests... :wink:

**Comment by tobiasdiez** [comment]
Thanks a lot! I'm traveling right now, and don't have the chance to program, otherwise I would have a look at this myself.

**Comment by calixtus** [comment]
Although I think i fixed the tests on the JabRef side (documentation needs a rebranding of bibtexkeypattern.md to citationkeypattern.md too), i strongly believe that `PreferenceMigrationTest::testPreviewStyle` and `::upgradePreviewStyleAllowMarkupDefault` do have a faulty test design. Suggestions?

**Review by tobiasdiez — APPROVED** [review]
LGTM.

I agree the tests are somewhat suboptimal. Not sure though if its worthwhile to spend more time improving them.

**Review by Siedlerchr — APPROVED** [review]

**Pull request merged**
