### PR TITLE
Fix for issue 7416: font size of the preferences dialog does not update with the rest of the GUI.

### LINKED ISSUE #7416: Font size of the preferences dialog does not update with the rest of the GUI.
JabRef version  on 

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

If you change the preferred font size of JabRef under preferences/appearance, the font size of the GUI is updated on reload of JabRef, but the font size of the preferences dialog remains the same.

1. Open JabRef.
2. Press Options, Preferences and then open the Appearance tab.
3. Change the font size to `12` or `14` as an example.
4. Save the changes and reload JabRef.
5. Open the Preferences dialog again. You can see that the font size of this dialog remains the same.

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

### PR DESCRIPTION
**Pull request by XDZhelheim**
Fix #7416 

The font size of preferences dialog does not update after changing the main font size. I think this problem is about the style settings of the dialog. Therefore, in the constructor of `PreferencesDialogView` class, I assigned the main font size to the font size of the dialog via `setStyle()`.

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

fix7416

### CODE REVIEW

**Review by Siedlerchr — APPROVED** [review]
Thanks for your contribution an the fix!

**Comment by Landi29** [comment]
@XDZhelheim  Thank you for the fix. I was unaware that I could use `preferencesService.getAppearancePreferences().getMainFontSize()`. This should fix the problem. It seems that the CHANGELOG file has some conflicts that must be resolved.

**Comment by XDZhelheim** [comment]
Thanks for your acknowledgement and notice! I made some mistakes on my IDE's auto-formatting, however, it seems there is no conflict now.

**Comment by calixtus** [comment]
Hi, thanks for the effort you put in this fix here. As this PR may be conflicting with a huge PR @docrjp is preparing in #7336 I would like to ask you to be patient and wait for his PR to be merged, before we review and merge this one.

**Comment by XDZhelheim** [comment]
I'm OK, take your time : )

**Review by calixtus — APPROVED** [review]
Since the other PR seems to take some more time, I'll approve this and think we should merge these changes to be ready for the next release.

**Review by Siedlerchr — APPROVED** [review]

**Pull request merged**
