### PR TITLE
[WIP] Partial translation in Farsi by Behrouz Javanmardi

### PR DESCRIPTION
**Pull request by mlep**

### CODE REVIEW

**Comment by mlep** [comment]
Please, could this be "copied" to branch dev_2.11?

**Comment by matthiasgeiger** [comment]
Will Behrouz provide some more translated strings in the near future?

Then I would wait with the integration until a more reasonable amount of Strings is translated.

**Comment by mlep** [comment]
Behrouz plans to complete the translation in the next 2 days.
In such a case, why not releasing it into 2.11?

**Comment by matthiasgeiger** [comment]
Great! 
I think I misformulated this a bit. I meant, that the current status should not be part of a release - as most of the strings are not translated (and as 2.11 was planned to be released yesterday it would not have been included). 

But as the release will be delayed we might include the more complete version of the Farsi translation.

**Comment by mlep** [comment]
It makes sense. Thanks for clarifying.

**Comment by koppor** [comment]
Is it possible to use `git commit --author="Behrouz Javanmardi <javanmardy@live.com>"` so that Behrouz gets credit also by automatic tooling such as being listed as current contributor [on openhub](https://www.openhub.net/p/jabref/contributors?sort=latest_commit&time_span=12+months)?

**Comment by koppor** [comment]
I currently lean against inclusion of the translation in JabRef 2.11 as 3.0 is scheduled end of this month. I can, however, wait for a complete translation, but there is no need for Behrouz to rush through.

**Comment by simonharrer** [comment]
Should we integrate this for JabRef 3.1?

**Comment by matthiasgeiger** [comment]
Same reasoning as before: I don't think it is useful to integrate the current state, as it will result in a UI which is 95% English with only a few words in Farsi.

**Comment by mlep** [comment]
I have just mailed Behrouz Javanmardi to know if he was able to send us a more complete localization.
BTW, a 5% Farsi localization could help in motivating new people in contributing to the localization.

**Comment by simonharrer** [comment]
Any progress on this?

**Comment by stefan-kolb** [comment]
How should we proceed with this PR?

**Comment by simonharrer** [comment]
I think we can close it for now, as nothing happened for several months. It can still be reopened when there is traction again.

**Pull request closed without merging**
