### PR TITLE
adding extra optional field as modifier for BibTeX key generator.

### PR DESCRIPTION
**Pull request by Piaoshi**
- [ ] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [ ] Screenshots added (for bigger UI changes)

### CODE REVIEW

**Comment by Piaoshi** [comment]
if an field is empty, use another field to generate BibTeX key.

**Comment by simonharrer** [comment]
Hi. Thank you for your willingsness to improve JabRef. The thing is, however, that I do not understand what you are trying to accomplish here. Can you please elaborate what kind of feature you are trying to add and what problem this new feature solves?

**Comment by lenhard** [comment]
Closed due to inactivity

**Comment by stefan-kolb** [comment]
Closing this issue due to inactivity :zzz: 
Please reopen the issue with additional information if the problem persists.

**Comment by koppor** [comment]
Test cases are really required to illustrate the issue solved.

**Pull request closed without merging**
