### PR TITLE
Entitlements file Mac

### PR DESCRIPTION
**Pull request by stefan-kolb**
- Remove unused entitlements file
- Rename entitlements file to jabref project name

Refs #6748 

- [ ] Change in CHANGELOG.md described (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

**Review by koppor — APPROVED** [review]

**Comment by Siedlerchr** [comment]
Why did you delete the file? Mac is no longer building!

**Review by Siedlerchr — CHANGES_REQUESTED** [review]
That file is needed!

**Comment by stefan-kolb** [comment]
We will look into this. The file was not referenced and duplicated inside `buildres/mac/`

**Comment by koppor** [comment]
> That file is needed!

Do you have an idea why the GitHub workflow (`.yml`) loads it as parameter, but it also resides in the root of the repository without any other appearance of the filename in the `.yml`?

Is there an implicit assumption?

**Comment by stefan-kolb** [comment]
```
Run codesign --entitlements buildres/mac/***.entitlements --options runtime -vvv -f --sign "Developer ID Application: Tobias Diez (W2PU6LW5U5)" build/distribution/JabRef.app/Contents/runtime/Contents/MacOS/libjli.dylib
  codesign --entitlements buildres/mac/***.entitlements --options runtime -vvv -f --sign "Developer ID Application: Tobias Diez (W2PU6LW5U5)" build/distribution/JabRef.app/Contents/runtime/Contents/MacOS/libjli.dylib
  codesign --entitlements buildres/mac/***.entitlements --options runtime -vvv -f --sign "Developer ID Application: Tobias Diez (W2PU6LW5U5)" build/distribution/JabRef.app/Contents/MacOS/JabRef
  codesign --entitlements buildres/mac/***.entitlements --options runtime -vvv -f --sign "Developer ID Application: Tobias Diez (W2PU6LW5U5)" build/distribution/JabRef.app
  jpackage --type pkg --dest build/distribution --name JabRef --app-version "5.3" --app-image build/distribution/JabRef.app --verbose --type dmg --vendor JabRef --app-version "5.3" --file-associations buildres/mac/bibtexAssociations.properties --resource-dir buildres/mac
  codesign -s "Developer ID Application: Tobias Diez (W2PU6LW5U5)" --options runtime --entitlements buildres/mac/***.entitlements -vvvv --deep "build/distribution/JabRef-5.3.dmg"
  jpackage --type pkg --dest build/distribution --name JabRef --mac-package-identifier JabRef --app-version "5.3" --app-image build/distribution/JabRef.app --verbose --type pkg --vendor JabRef --app-version "5.3" --file-associations buildres/mac/bibtexAssociations.properties --resource-dir buildres/mac
  productsign --sign "Developer ID Installer: Tobias Diez (W2PU6LW5U5)" "build/distribution/JabRef-5.3.pkg" "build/distribution/JabRef-5.3-signed.pkg"
  shell: /bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    SpringerNatureAPIKey: ***
    AstrophysicsDataSystemAPIKey: ***
    IEEEAPIKey: ***
    OSXCERT: ***
  
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
    GitVersion_Major: 5
    GitVersion_Minor: 3
    GitVersion_Patch: 0
    GitVersion_PreReleaseTag: PullRequest7317.55
    GitVersion_PreReleaseTagWithDash: -PullRequest7317.55
    GitVersion_PreReleaseLabel: PullRequest7317
    GitVersion_PreReleaseLabelWithDash: -PullRequest7317
    GitVersion_PreReleaseNumber: 55
    GitVersion_WeightedPreReleaseNumber: 30055
    GitVersion_FullBuildMetaData: Branch.pull-7317-merge.Sha.e56df18e4b6b4419e7007b575508335dfd5275ea
    GitVersion_MajorMinorPatch: 5.3.0
    GitVersion_SemVer: 5.3.0-PullRequest7317.55
    GitVersion_LegacySemVer: 5.3.0-PullRequest7317-55
    GitVersion_LegacySemVerPadded: 5.3.0-PullRequest7317-0055
    GitVersion_AssemblySemVer: 5.3.30055
    GitVersion_AssemblySemFileVer: 5.3.0.0
    GitVersion_FullSemVer: 5.3.0-PullRequest7317.55
    GitVersion_InformationalVersion: 5.3-PullRequest7317.55--2021-01-08--e56df18
    GitVersion_BranchName: pull/7317/merge
    GitVersion_EscapedBranchName: pull-7317-merge
    GitVersion_Sha: e56df18e4b6b4419e7007b575508335dfd5275ea
    GitVersion_ShortSha: e56df18
    GitVersion_NuGetVersionV2: 5.3.0-pullrequest7317-0055
    GitVersion_NuGetVersion: 5.3.0-pullrequest7317-0055
    GitVersion_NuGetPreReleaseTagV2: pullrequest7317-0055
    GitVersion_NuGetPreReleaseTag: pullrequest7317-0055
    GitVersion_VersionSourceSha: 6a2a5129888053559d2ff1d9d5a5630cb4b99838
    GitVersion_CommitsSinceVersionSource: 55
    GitVersion_CommitsSinceVersionSourcePadded: 0055
    GitVersion_UncommittedChanges: 0
    GitVersion_CommitDate: 2021-01-08
    GITVERSION_MAJOR: 5
    GITVERSION_MINOR: 3
    GITVERSION_PATCH: 0
    GITVERSION_PRERELEASETAG: PullRequest7317.55
    GITVERSION_PRERELEASETAGWITHDASH: -PullRequest7317.55
    GITVERSION_PRERELEASELABEL: PullRequest7317
    GITVERSION_PRERELEASELABELWITHDASH: -PullRequest7317
    GITVERSION_PRERELEASENUMBER: 55
    GITVERSION_WEIGHTEDPRERELEASENUMBER: 30055
    GITVERSION_BUILDMETADATA: 
    GITVERSION_BUILDMETADATAPADDED: 
    GITVERSION_FULLBUILDMETADATA: Branch.pull-7317-merge.Sha.e56df18e4b6b4419e7007b575508335dfd5275ea
    GITVERSION_MAJORMINORPATCH: 5.3.0
    GITVERSION_SEMVER: 5.3.0-PullRequest7317.55
    GITVERSION_LEGACYSEMVER: 5.3.0-PullRequest7317-55
    GITVERSION_LEGACYSEMVERPADDED: 5.3.0-PullRequest7317-0055
    GITVERSION_ASSEMBLYSEMVER: 5.3.30055
    GITVERSION_ASSEMBLYSEMFILEVER: 5.3.0.0
    GITVERSION_FULLSEMVER: 5.3.0-PullRequest7317.55
    GITVERSION_INFORMATIONALVERSION: 5.3-PullRequest7317.55--2021-01-08--e56df18
    GITVERSION_BRANCHNAME: pull/7317/merge
    GITVERSION_ESCAPEDBRANCHNAME: pull-7317-merge
    GITVERSION_SHA: e56df18e4b6b4419e7007b575508335dfd5275ea
    GITVERSION_SHORTSHA: e56df18
    GITVERSION_NUGETVERSIONV2: 5.3.0-pullrequest7317-0055
    GITVERSION_NUGETVERSION: 5.3.0-pullrequest7317-0055
    GITVERSION_NUGETPRERELEASETAGV2: pullrequest7317-0055
    GITVERSION_NUGETPRERELEASETAG: pullrequest7317-0055
    GITVERSION_VERSIONSOURCESHA: 6a2a5129888053559d2ff1d9d5a5630cb4b99838
    GITVERSION_COMMITSSINCEVERSIONSOURCE: 55
    GITVERSION_COMMITSSINCEVERSIONSOURCEPADDED: 0055
    GITVERSION_UNCOMMITTEDCHANGES: 0
    GITVERSION_COMMITDATE: 2021-01-08
    JAVA_HOME_15.0.1_x64: /Users/runner/hostedtoolcache/jdk/15.0.1/x64
    JAVA_HOME: /Users/runner/hostedtoolcache/jdk/15.0.1/x64
    JAVA_HOME_15_0_1_X64: /Users/runner/hostedtoolcache/jdk/15.0.1/x64
buildres/mac/***.entitlements: cannot read entitlement data
Error: Process completed with exit code 1.
```

Doesn't look like the workflow is looking for the root folder file?!

**Comment by Siedlerchr** [comment]
Have you checked the build gradle?
It might be referenced there as well

**Comment by Siedlerchr** [comment]
Sorry it was a misunderstanding. The entitlement file is not the same or now missing:
Run codesign --entitlements buildres/mac/***.entitlements --options runtime -vvv -f --sign "Developer ID Application: Tobias Diez (W2PU6LW5U5)" build/distribution/JabRef.app/Contents/runtime/Contents/MacOS/libjli.dylib
buildres/mac/***.entitlements: cannot read entitlement data

**Comment by Siedlerchr** [comment]
when the mac build succeeds can be merged

**Review by Siedlerchr — APPROVED** [review]

**Pull request merged**
