### PR TITLE
Closes #3027 and updates install4j to v7

### LINKED ISSUE #3027: Update java version to Update 141 (JDK 8u141)
Released yesterday
http://www.oracle.com/technetwork/java/javase/8u141-relnotes-3720385.html

### PR DESCRIPTION
**Pull request by stefan-kolb**
We need to check if the install4j migration did change something inside the installer.

### CODE REVIEW

**Comment by Siedlerchr** [comment]
Could you provide a Screenshot if you changed the layout?

**Comment by stefan-kolb** [comment]
Waiting for the build, this was just an auto migration by intsall4j7.

**Comment by stefan-kolb** [comment]
@JabRef/developers Windows x64 installation looked ok on my end.

**Comment by stefan-kolb** [comment]
@chochreiner Thanks for testing. Not sure if I we can disable this, I didn't see an option yet, although I dunno where to look really 😄

**Comment by chochreiner** [comment]
The warning looks like this after the second installation/update of Jabref after the installation and before the "File association" step 
I've had a look at the install4j configuration, but I could not find the setting to turn this of.

screen shot 2017-08-01 at 11 33 04

**Comment by Siedlerchr** [comment]
Just another idea: I think we already discussed that a while ago:
Add a page/button to open donations, e..g like in Tortoise SVN:
grafik

**Comment by stefan-kolb** [comment]
@lenhard I don't have an icon for it other than that it would be a 5 minute task 😄

**Comment by stefan-kolb** [comment]
@chochreiner Probably caused by adding this to the Info.plist? <key>NSSupportsAutomaticGraphicsSwitching</key>
<string>YES</string>
Do we still need this?

**Comment by stefan-kolb** [comment]
Or maybe did the deinstallation not work properly?

**Comment by chochreiner** [comment]
The deinstallation should have worked fine and I would keep the NSSupportsAutomaticGraphicsSwitching attribute, since there may be quite some macbooks around with two graphic cards

**Pull request merged**
