### PR TITLE
Fixed #883

### LINKED ISSUE #883: NPE during cleanup -> PDF renaming
JabRef 2016-02-28--master--a0444ab

I have following bib entry:

```
@Article{MLU2011,
  author =        {Ralph Mietzner and Frank Leymann and Tobias Unger},
  title =         {Horizontal and vertical combination of multi-tenancy patterns in service-oriented applications},
  journal =       {Enterprise Information Systems},
  year =          {2011},
  volume =        {5},
  number =        {1},
  pages =         {59--77},
  month =         feb,
  doi =           {10.1080/17517575.2010.492950},
  file =          {:Veröffentlichungen\\ART-2010-06 - Patterns Journal Version.pdf:PDF},
  publisher =     {Informa {UK} Limited}
}
```

(The wrong indent is solved by #851)

I do a cleanup on that entry with "Rename PDFs to given filename format pattern" only. The file does not get renamed, but a NPE is risen.

Side comment: The status box still shows "Doing a cleanup for entries..." and does not show "Error during cleanup" (or "Error" or something similar).

```
14:22:11.427 [AWT-EventQueue-0] ERROR net.sf.jabref.gui.BasePanel - runCommand error: null
java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Unknown Source) ~[?:1.8.0_66]
	at net.sf.jabref.logic.layout.LayoutHelper.<init>(LayoutHelper.java:59) ~[JabRef-dev-fat.jar:?]
	at net.sf.jabref.util.Util.getLinkedFileName(Util.java:207) ~[JabRef-dev-fat.jar:?]
	at net.sf.jabref.logic.cleanup.RenamePdfCleanup.cleanup(RenamePdfCleanup.java:66) ~[JabRef-dev-fat.jar:?]
	at net.sf.jabref.logic.cleanup.CleanupWorker.cleanup(CleanupWorker.java:64) ~[JabRef-dev-fat.jar:?]
	at net.sf.jabref.gui.actions.CleanupAction.doCleanup(CleanupAction.java:161) ~[JabRef-dev-fat.jar:?]
	at net.sf.jabref.gui.actions.CleanupAction.run(CleanupAction.java:106) ~[JabRef-dev-fat.jar:?]
	at sun.reflect.GeneratedMethodAccessor23.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_66]
	at spin.Invocation.evaluate(Invocation.java:175) ~[JabRef-dev-fat.jar:?]
	at spin.off.SpinOffEvaluator$1.run(SpinOffEvaluator.java:108) ~[JabRef-dev-fat.jar:?]
	at java.lang.Thread.run(Unknown Source) ~[?:1.8.0_66]
```

### PR DESCRIPTION
**Pull request by oscargus**
Should solve #883.

- [x] Change in CHANGELOG.md described?
- [x] Changes in pull request outlined? (What, why, ...)
- [x] Tests created for changes? No, tests already passed, this is a GUI issue.
- [x] Tests green? Yes.

### CODE REVIEW

**Comment by oscargus** [comment]
Merging this as the changed visibility of the constructors prohibits a proper build at the moment.

**Comment by tobiasdiez** [comment]
If you pass null to the database, then getResolvedField is invoked with a null database. Thus the crossref functionality is not supported in the rename pattern. I think this is not a big deal, but easy to fix (just pass the right db)

**Comment by oscargus** [comment]
I think that at the moment null is always passed in the code.

(Which also means that it the two one- and two-argument constructors are
only used in tests they can be removed and nulls passed, which of course is
the current behaviour but seems to make more sense to provide alternative
constructors if they are used in actual code...).

**Comment by tobiasdiez** [comment]
Yes you are right, null is always passed....but this is not a feature but a bug :smiley:

**Pull request merged**
