### PR TITLE
Permanent other fields tab

### PR DESCRIPTION
**Pull request by grimes2**
The other fields tab is now permanently shown.
Reason: This avoids major layout rearrangements of the entry editor tabs on entry change.
Advantage: Better usability and performance.
Disadvantage: A useless (empty) other fields tab is shown in databases without other fields.

- [x] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [ ] Screenshots added (for bigger UI changes)
- [x] Manually tested changed features in running JabRef
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)
- [ ] If you changed the localization: Did you run `gradle localizationUpdate`?

### CODE REVIEW

**Comment by Siedlerchr** [comment]
Just one thing about I have thought. Would it be possible to "create" the other fields tab everytime, but not showing (visible=false)  if it is empty ? 
Would that work, too?

**Comment by grimes2** [comment]
Do you mean, that the other fields tab is grayed out (inactive)?

**Comment by Siedlerchr** [comment]
Yeah kind of. But  when thinking again about it, graying out is a bad idea. Leave it empty, All fine. I just had the idea it could be complete hidden as it was before.

**Comment by koppor** [comment]
My current feeling is that always shown and with the text "no other fields
found" would be the most intuitive.

Double check: If I add a field "realotherfield" at the bibtex source, the
content of the other tab should show this field.

**Comment by grimes2** [comment]
Other fields tab is not updated after adding an other field to source. This is not surprising, because changing the tab in entry editor does not instanciate the EntryEditor object. You can choose another entry and go back to rebuild the Entry Editor.

**Comment by grimes2** [comment]
I found an alternative solution. I have added an empty field "otherfield" to every other fields tab. So the tab is never empty. The advantage is, that it's possible to add a field to the source easily. This field can be renamed in the source panel. Please set label "ready-for-review". Thanks.

**Comment by stefan-kolb** [comment]
Imho, I only want to see the other field tab if there are other fields.

**Comment by koppor** [comment]
In the devcall, we discussed that this is not an ideal solution and we should really work on the other fields tab being handled correctly.

**Pull request closed without merging**
