### PR TITLE
Fixed(?) PostgreSQL problems

### PR DESCRIPTION
**Pull request by oscargus**
This may solve the problem in #473 

I was apparently a bit to enthusiastic in introducing try-with resources...

### CODE REVIEW

**Comment by oscargus** [comment]
The important change is in PostgreSQLExporter where the connection is not automatically closed, which is probably what causes the issue.

The other changes are:
* Better code by not having two try directly following each other (now both statements are in one try)
* Avoided duplicate translations which is bound to give warnings using another locale

The reformatting may make it hard to see though.

**Comment by koppor** [comment]
@oscgarcus If you created the branch in `upstream` (meaning `JabRef/jabref`) instead of your fork, the build would be available at http://builds.jabref.org/. Reason: We authenticate the upload with an SSH key which doesn't seem to be available when branches of forks are being built. - Refs https://github.com/JabRef/jabref/issues/473#issuecomment-162327856

I created a `databasefix` branch in the main repo and now the build is available at http://builds.jabref.org/databasefix/.

**Comment by oscargus** [comment]
:+1:

**Comment by oscargus** [comment]
For reference, this PR is now primarily hosted in JabRef/jabref databasefix. I'll try to keep this branch updated as well.

**Comment by stefan-kolb** [comment]
Any updates on the progress of this PR?

**Comment by oscargus** [comment]
Not really. It works again, but there are some issues with escaping which probably should be fixed (but is not introduced as far as I can tell between 2.11 and 3.0). So, the issues I introduced in 3.0 is removed, which is the part I was primarily looking at solving, but some other issues with the database management have been revealed.

**Comment by simonharrer** [comment]
Please add CHANGELOG and rebase on master. We will merge this then. Other issues can be fixed in other PRs.

**Comment by oscargus** [comment]
Rebased and added change log entry.

**Pull request merged**
