### PR TITLE
Switched from jfoenix to gemsfx

### PR DESCRIPTION
**Pull request by calixtus**
Since jfoenix seems not to be in active development anymore and already several compatibility issues with java module system have risen this PR switches from jfoenix chipview to [gemsfx TagsView](https://github.com/dlsc-software-consulting-gmbh/GemsFX#tags-field) by @dlemmermann.

One Issue remaining with the a remaining annoying border.
grafik

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by Siedlerchr** [comment]
Method too large.. :(

**Comment by calixtus** [comment]
huh? i removed so much stuff...

**Comment by Siedlerchr** [comment]
Ah damn :( java.lang.module.FindException: Module javafx.swing not found, required by com.dlsc.gemsfx

**Comment by Siedlerchr** [comment]
As this is still blocked by the jlink bug I have moved this PR to koppor

**Comment by calixtus** [comment]
Yeah, I hope to get the antlr PR done soon, so the gemsfx PR can be merged too

**Pull request closed without merging**
