### PR TITLE
Sync lang fix

### PR DESCRIPTION
**Pull request by koppor**
Fixes https://github.com/JabRef/jabref/issues/3573.

### CODE REVIEW

**Comment by koppor** [comment]
I found https://github.com/JabRef/jabref/issues/3573 and saw that @Brainsucker92 worked on it, fixed it, but did not create a pull request. So, I just did it.

@Brainsucker92 Thank you for your work! You are very welcome to join #hacktoberfest.

**Comment by Siedlerchr** [comment]
With Crowdin the script should be obsolete  as crowdin automatically handles this.

**Comment by koppor** [comment]
Sorry, I did not link my comment, why I still need this:

https://github.com/JabRef/jabref/issues/3573#issuecomment-362865145

**Comment by Brainsucker92** [comment]
Actually I think all these commits shown above were merged already with this pull request: https://github.com/JabRef/jabref/pull/3743/
But I'm still glad I could help you guys!

**Pull request merged**
