### PR TITLE
Remove JavaFX-Font-Tweak

### PR DESCRIPTION
**Pull request by calixtus**
As asked by @tobiasdiez in the gitter-chat, a seperate PR to test if the font tweak can be safely removed, as probably the dependencies were removed in JavaFX anyways. See https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8187147

----

- [ ] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [x] Manually tested changed features in running JabRef
- [ ] Screenshots added in PR description (for bigger UI changes)
- [x] Ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)

### CODE REVIEW

**Comment by tobiasdiez** [comment]
As the original author of https://github.com/JabRef/jabref/pull/3305, @halirutan could you please check if this font tweak is still necessary? Thanks a lot!

**Comment by halirutan** [comment]
@tobiasdiez Yes I can, but I'm not at home on my Linux mache until the weekend. But then, I can have a look.

**Comment by tobiasdiez** [comment]
@halirutan Have you already found the time to look at this?

**Comment by halirutan** [comment]
@tobiasdiez I looked at this tonight and I cannot see a difference between the tweak turned on or off. So I guess it can be removed.

**Comment by tobiasdiez** [comment]
Thanks for having a look at this @halirutan

**Pull request merged**
