### PR TITLE
Enables JUnit Jupiter best practices

### PR DESCRIPTION
**Pull request by koppor**
This enables [JUnit Jupiter best practices](https://docs.openrewrite.org/recipes/java/testing/junit5/junit5bestpractices)

Two main changes:

- [Statically import JUnit Jupiter assertions](https://docs.openrewrite.org/recipes/java/testing/junit5/staticimports)
- [Remove public visibility of JUnit 5 tests](https://docs.openrewrite.org/recipes/java/testing/cleanup/testsshouldnotbepublic), which is [SonarSource Rule S5786](https://sonarsource.github.io/rspec/#/rspec/S5786)

(Follow-up to https://github.com/JabRef/jabref/pull/11642)

### Mandatory checks

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by koppor** [comment]
Fetcher tests for quey transformation start to fail - need to investigate

---

```
org.jabref.logic.importer.fetcher.transformers.ArXivQueryTransformerTest
  Test convertYearRangeField() FAILED
  org.opentest4j.AssertionFailedError: expected: <Optional[]> but was: <Optional.empty>

  Test convertYearField() FAILED
  org.opentest4j.AssertionFailedError: expected: <Optional[2018]> but was: <Optional[all:2018]>

org.jabref.logic.importer.fetcher.transformers.CollectionOfComputerScienceBibliographiesQueryTransformerTest
  Test convertYearField() FAILED
  org.opentest4j.AssertionFailedError: expected: <Optional[year:2018]> but was: <Optional[2018]>

org.jabref.logic.importer.fetcher.transformers.DBLPQueryTransformerTest
  Test convertYearField() FAILED
  org.opentest4j.AssertionFailedError: expected: <Optional[2015]> but was: <Optional.empty>

  Test convertYearRangeField() FAILED
  org.opentest4j.AssertionFailedError: expected: <Optional[2012|2013|2014|2015]> but was: <Optional.empty>

org.jabref.logic.importer.fetcher.transformers.DefaultQueryTransformerTest
  Test convertYearRangeField() FAILED
  org.opentest4j.AssertionFailedError: expected: <Optional[]> but was: <Optional.empty>

  Test convertYearField() FAILED
  org.opentest4j.AssertionFailedError: expected: <Optional[]> but was: <Optional.empty>

org.jabref.logic.importer.fetcher.transformers.GVKQueryTransformerTest
  Test convertYearField() FAILED
  org.opentest4j.AssertionFailedError: expected: <Optional[ver:2018]> but was: <Optional[pica.erj=2018]>

org.jabref.logic.importer.fetcher.transformers.JstorQueryTransformerTest
  Test convertYearField() FAILED
  org.opentest4j.AssertionFailedError: expected: <Optional[sd:2018 AND ed:2018]> but was: <Optional[sd:2018 AND ed: 2018]>

org.jabref.logic.importer.fetcher.transformers.ScholarQueryTransformerTest
  Test convertYearRangeField() FAILED
  org.opentest4j.AssertionFailedError: expected: <Optional[]> but was: <Optional.empty>

  Test convertYearField() FAILED
  org.opentest4j.AssertionFailedError: expected: <Optional[]> but was: <Optional.empty>
```

**Comment by koppor** [comment]
OK, we forgot to add `@Test` annotations. The tests were never executed.

**Comment by koppor** [comment]
All should be good now. https://github.com/JabRef/jabref/pull/11644 is kind of a pre-condition to get the OK checkmark for FetcherTests here, too.

**Comment by koppor** [comment]
> All should be good now. #11644 is kind of a pre-condition to get the OK checkmark for FetcherTests here, too.

We merged - could not fix one test. This test is also red here, all others green. Thus, this is good to go.

**Review by Siedlerchr — APPROVED** [review]

**Pull request merged**
