### PR TITLE
Remove unuseful search syntax feedback

### LINKED ISSUE #7349: When typing a "-" after a long title into web search the application freezes
JabRef 5.3--2021-01-14--e66f5be
Windows 10 10.0 amd64 
Java 14.0.2 
JavaFX 15.0.1+1

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

The following also works with other titles containing "-". And also with other search engines. The below example triggers the bug every time:

1. Under Web Search -> Select DBLP
2. Type "Collecting Performance Data with PAPI" into the web search field
3. Type a "-" afterward and now the app does not respond anymore.

<details>
  <summary>Log File</summary>
  
  ```
  I did not find any log file or information in the event log.
  ```
</details>

### PR DESCRIPTION
**Pull request by DominikVoigt**
This PR removes unuseful feedback from the web search text field, as it is not necessary and provides no advantage.
With the introduction of transformers in #7350, the syntax feedback will be adapted  and provide adequate and useful feedback.

Fixes #7349, addresses #7277.

- [ ] Change in CHANGELOG.md described (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

**Review by koppor — APPROVED** [review]

**Review by koppor — APPROVED** [review]

**Review by koppor — APPROVED** [review]

**Comment by tobiasdiez** [comment]
I'm against removing the syntax check. From a user perspective, you want to be notified as early as possible that your search query is not valid and not only after you click the search button. Moreover, showing the query syntax problem as some kind of overlay is nicer than a modal error dialog.

That being said, the user experience can indeed be improved. For example, I'm a fan of a more visual representation of the search query as for example in https://dribbble.com/shots/6323387-Job-Search or http://evoluteur.github.io/structured-filter/index.html

**Comment by DominikVoigt** [comment]
Yeah, I really like the chips design of dribbble.com/shots/6323387-Job-Search.
I just wanted to disable the current syntax highlighting as it leads to issues.
I will start working on a chips design using the lucene library for tokenization.

**Comment by tobiasdiez** [comment]
Nice! Then I would prefer to remove the check in the same PR that also converts to the chip-based design (or in two PRs that are merged directly after each other). Or is the check currently so broken that the fetchers are not useable?

**Comment by koppor** [comment]
The issues are:

- JabRef currently freezes when searching (https://github.com/JabRef/jabref/issues/7349). Users are blocked.
- Including the solution with chips design takes more than a few hours

I believe we can re-add the feedback before a new release (https://github.com/JabRef/jabref/issues/7411). Assigned the issue to the next milestone.

**Comment by Fu188** [comment]
I think it is unreasonable to remove the syntax check.

**Comment by koppor** [comment]
@Fu188 Please not my comment above:

> I believe we can re-add the feedback before a new release (https://github.com/JabRef/jabref/issues/7411). Assigned the issue to the next milestone.

Only users using a non-released version will have no syntax checks. We will work on #7411. This will be possible with our new query syntax, which will be translated to the fetchers. Currently, the user has to know the differences between IEEE, ACM, arXiv and modify the query when changing the fetcher. With the new infrastructure, JabRef will do the translation for you.

**Pull request merged**
