### PR TITLE
Fixed #890

### LINKED ISSUE #890: NPE when renaming a file
JabRef v3.3dev 2016-02-28--master--a0444ab

I've searched for an entry as I lost it somehow:

grabbed_20160228-211449

Now, I'm dropping the PDF onto the preview. Nothing happens, but an NPE is raised and output at "Exceptions":

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Unknown Source)
	at net.sf.jabref.logic.search.MatchesHighlighter.highlightWordsWithHTML(MatchesHighlighter.java:26)
	at net.sf.jabref.logic.layout.LayoutEntry.doLayout(LayoutEntry.java:234)
	at net.sf.jabref.logic.layout.Layout.doLayout(Layout.java:123)
	at net.sf.jabref.logic.layout.Layout.doLayout(Layout.java:110)
	at net.sf.jabref.util.Util.getLinkedFileName(Util.java:212)
	at net.sf.jabref.external.DroppedFileHandler.showLinkMoveCopyRenameDialog(DroppedFileHandler.java:363)
	at net.sf.jabref.external.DroppedFileHandler.handleDroppedfile(DroppedFileHandler.java:143)
	at net.sf.jabref.gui.fieldeditors.FileListEditorTransferHandler$1.run(FileListEditorTransferHandler.java:133)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
```

My filename format pattern is `\bibtexkey\begin{title} - \format[RemoveBrackets]{\title}\end{title}`.

### PR DESCRIPTION
**Pull request by oscargus**
This should fix #890 

- [x] Change in CHANGELOG.md described?
- [x] Changes in pull request outlined? (What, why, ...)
- [ ] Tests created for changes? Not relevant
- [x] Tests green?

### CODE REVIEW

**Comment by simonharrer** [comment]
:+1:

**Comment by tobiasdiez** [comment]
I think the method 
``` 
public String doLayout(BibEntry bibtex, BibDatabase database) {
        return doLayout(bibtex, database, null);
    }
```
in layout.java should be changed too. Otherwise :+1:

**Comment by oscargus** [comment]
I think that is the method I changed. Is there another method (I searched, but rather quickly)?

Yes, the layout package could benefit from more testing...

**Comment by tobiasdiez** [comment]
No you are right...you exactly changed the method I mentioned. My bad :smile:.
What I meant in the second part is that setting the higlightPattern to null does not throw an exception (since the test pass) although I would have expected one.

**Comment by oscargus** [comment]
But there is a corresponding method in LayoutEntry, which I think should be fixed as well.

Ah, OK! I'll have a look (or maybe the highlighter is never invoked in the test case?).

**Comment by oscargus** [comment]
I fixed the other place as well, but happened to change to more use of switching... In the long term it would make sense to change the integers now used to an enumeration.

I also realized that all `\n` are stripped from the fields when doing a layout, so even though e.g. HTMLChars will convert the line breaks to something clever, they are not there anymore once the formatter is invoked... Not sure where they go missing though...

**Comment by tobiasdiez** [comment]
:+1:

**Pull request merged**
