### PR TITLE
Observable Preferences T (NameDisplayPreferences, MainTablePreferences, ColumnPreferences)

### PR DESCRIPTION
**Pull request by calixtus**
Follow up to #9493

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by Siedlerchr** [comment]
java.util.NoSuchElementException: java.lang.IndexOutOfBoundsException
	at java.base/java.util.AbstractList$Itr.next(AbstractList.java:379)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1921)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.jabref@100.0.0/org.jabref.gui.maintable.MainTable.getSelectedEntries(MainTable.java:478)
	at org.jabref@100.0.0/org.jabref.gui.LibraryTab.lambda$createMainTable$9(LibraryTab.java:511)
	at javafx.base@19/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
	at javafx.base@19/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	at javafx.base@19/javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:239)
	at javafx.base@19/javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
	at javafx.base@19/javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	at javafx.base@19/javafx.collections.ObservableListBase.endChange(ObservableListBase.java:211)
	at javafx.controls@19/com.sun.javafx.scene.control.SelectedItemsReadOnlyObservableList.lambda$new$0(SelectedItemsReadOnlyObservableList.java:91)
	at javafx.base@19/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
	at javafx.base@19/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	at javafx.base@19/javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:239)
	at javafx.base@19/javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
	at javafx.base@19/javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	at javafx.base@19/javafx.collections.ObservableListBase.endChange(ObservableListBase.java:211)
	at javafx.controls@19/com.sun.javafx.scene.control.ReadOnlyUnbackedObservableList._endChange(ReadOnlyUnbackedObservableList.java:64)
	at javafx.controls@19/javafx.scene.control.MultipleSelectionModelBase$SelectedIndicesList._endChange(MultipleSelectionModelBase.java:918)
	at javafx.controls@19/javafx.scene.control.ControlUtils.updateSelectedIndices(ControlUtils.java:218)
	at javafx.controls@19/javafx.scene.control.TableView$TableViewArrayListSelectionModel.fireCustomSelectedCellsListChangeEvent(TableView.java:3032)
	at javafx.controls@19/javafx.scene.control.TableView$TableViewArrayListSelectionModel.clearSelection(TableView.java:2804)
	at javafx.controls@19/javafx.scene.control.TableView$TableViewArrayListSelectionModel.updateDefaultSelection(TableView.java:2993)
	at javafx.controls@19/javafx.scene.control.TableView$TableViewArrayListSelectionModel.lambda$new$2(TableView.java:2182)
	at javafx.base@19/javafx.collections.WeakListChangeListener.onChanged(WeakListChangeListener.java:88)
	at javafx.base@19/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
	at javafx.base@19/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	at javafx.base@19/javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:239)
	at javafx.base@19/javafx.collections.transformation.SortedList.sourceChanged(SortedList.java:114)
	at javafx.base@19/javafx.collections.transformation.TransformationList.lambda$getListener$0(TransformationList.java:106)
	at javafx.base@19/javafx.collections.WeakListChangeListener.onChanged(WeakListChangeListener.java:88)
	at javafx.base@19/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
	at javafx.base@19/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	at javafx.base@19/javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:239)
	at javafx.base@19/javafx.collections.transformation.FilteredList.refilter(FilteredList.java:338)
	at javafx.base@19/javafx.collections.transformation.FilteredList$1.invalidated(FilteredList.java:102)
	at javafx.base@19/javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
	at javafx.base@19/javafx.beans.property.ObjectPropertyBase$Listener.invalidated(ObjectPropertyBase.java:234)
	at javafx.base@19/com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:136)
	at javafx.base@19/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.base@19/javafx.beans.binding.ObjectBinding.invalidate(ObjectBinding.java:181)
	at javafx.base@19/com.sun.javafx.binding.BindingHelperObserver.invalidated(BindingHelperObserver.java:52)
	at javafx.base@19/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:348)
	at javafx.base@19/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.base@19/javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(ObjectPropertyBase.java:106)
	at javafx.base@19/javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:113)
	at javafx.base@19/javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:147)
	at javafx.base@19/javafx.beans.property.ObjectProperty.setValue(ObjectProperty.java:78)
	at org.jabref@100.0.0/org.jabref.gui.StateManager.setSearchQuery(StateManager.java:155)
	at org.jabref@100.0.0/org.jabref.gui.search.GlobalSearchBar.performSearch(GlobalSearchBar.java:295)
	at reactfx@2.0-M5/org.reactfx.util.FxTimer.lambda$restart$0(FxTimer.java:89)
	at javafx.graphics@19/com.sun.scenario.animation.shared.TimelineClipCore.visitKeyFrame(TimelineClipCore.java:239)
	at javafx.graphics@19/com.sun.scenario.animation.shared.TimelineClipCore.playTo(TimelineClipCore.java:180)
	at javafx.graphics@19/javafx.animation.Timeline.doPlayTo(Timeline.java:172)
	at javafx.graphics@19/javafx.animation.AnimationAccessorImpl.playTo(AnimationAccessorImpl.java:39)
	at javafx.graphics@19/com.sun.scenario.animation.shared.SingleLoopClipEnvelope.timePulse(SingleLoopClipEnvelope.java:103)
	at javafx.graphics@19/javafx.animation.Animation.doTimePulse(Animation.java:1189)
	at javafx.graphics@19/javafx.animation.Animation$1.lambda$timePulse$0(Animation.java:207)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at javafx.graphics@19/javafx.animation.Animation$1.timePulse(Animation.java:206)
	at javafx.graphics@19/com.sun.scenario.animation.AbstractPrimaryTimer.timePulseImpl(AbstractPrimaryTimer.java:343)
	at javafx.graphics@19/com.sun.scenario.animation.AbstractPrimaryTimer$MainLoop.run(AbstractPrimaryTimer.java:266)
	at javafx.graphics@19/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:571)
	at javafx.graphics@19/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:555)
	at javafx.graphics@19/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:548)
	at javafx.graphics@19/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:352)
	at javafx.graphics@19/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
Caused by: java.lang.IndexOutOfBoundsException
	at javafx.base@19/javafx.collections.transformation.SortedList.get(SortedList.java:168)
	at javafx.controls@19/javafx.scene.control.TableView$TableViewSelectionModel.getModelItem(TableView.java:2034)
	at javafx.controls@19/javafx.scene.control.MultipleSelectionModelBase$1.getModelItem(MultipleSelectionModelBase.java:74)
	at javafx.controls@19/com.sun.javafx.scene.control.SelectedItemsReadOnlyObservableList.get(SelectedItemsReadOnlyObservableList.java:100)
	at java.base/java.util.AbstractList$Itr.next(AbstractList.java:373)
	... 72 more

**Comment by Siedlerchr** [comment]
Seems to work fine.

**Review by Siedlerchr — APPROVED** [review]

**Comment by koppor** [comment]
It seems, this has to do with column ordering in the main table and in the global search. For the main table, it works great. For the search, column re-ordering leads to a hidden column:

1. Reorder Title / Author (so that Title is last)
   image
2. Restart
3. Start Global Search. See "Title" being missing
    image

**Comment by koppor** [comment]
When starting the `main` branch, the column "Author/Title" is completely lost:

image

I think, we should nevertheless move forward with this and add fixes after this is merged?

**Comment by calixtus** [comment]
Is the maintable fine? Since this pr is reducing code duplication with the search dialog and the main table, this is probably a bug in the search dialog and hopefully not caused by my changes 😅 . So I agree, a follow up issue (maybe "good first") with bugs in the global search dialog should be filed and adressed

**Comment by Siedlerchr** [comment]
As far as I remember the columns in the search are just based on the main table but are stored separate. So they should be independent

**Comment by calixtus** [comment]
So as both reviewers approved or voted to merge, im merging.

**Pull request merged**
