### PR TITLE
Fix RTF formatter bug

### LINKED ISSUE #1457: Bug in the conversion of \emph{...} in RTF export?
JabRef version 3.3 on Windows 7 64bit

Steps to reproduce:

% BEGIN OF BIBLATEX file:
% Encoding: UTF-8

@Article{article:0000,
  author       = {A. Author},
  title        = {An article title with \emph{a book title} emphasized},
  journaltitle = {Journal},
  volume       = {1},
  date         = {2016},
  pages        = {1-10},
}

@Comment{jabref-meta: databaseType:biblatex;}
% END OF BIBLATEX file

1. Open the file, select the only entry and click on File, Export selected entries
2. Select any of the RTF formats (DIN 1505, Harvard, MIS Quarterly) and save
3. In the resulting RTF file only "a" is in italics, not "book title".
The same problem does not seem to appear in the HTML exports.

Extract from the RTF file for the Harvard RTF conversion:
{\scaps Author, A.}
: An article title with {\i a} book title emphasized}
. In: {\i Journal} {1} (2016), S. 1-10 \par

Attachment: Wordpad screen shot
[harvard-test](https://cloud.githubusercontent.com/assets/19624893/15628199/7f6f207a-24fb-11e6-82ae-a3b98a9bc771.jpg)

### PR DESCRIPTION
**Pull request by stefan-kolb**
Fix #1457 Whole formatter needs a refactoring...

### CODE REVIEW

**Comment by simonharrer** [comment]
LGTM

**Comment by tobiasdiez** [comment]
LGTM :+1:

**Comment by bvdalen** [comment]
Thank you very much. I tested the result and it appears to work well.
I know the following may be too much to ask, but I nevertheless wanted to pose one more related question: If the \emph appears within a book title, which will usually be typeset in italics already, \i0 needs to be inserted in the RTF rather than \i in order to obtain the desired result (namely that the emphasized text appears in roman instead of in italics). Would this be possible to implement within the current formatter? Please let me know if you need a detailed example.

**Comment by stefan-kolb** [comment]
Can you please open a new issue for that? Also, if you or your colleague still has interest in contributing, we would love to see a refactoring of the formatter!

**Pull request merged**
