### PR TITLE
FIX NPE while merging entries 

### PR DESCRIPTION
**Pull request by 1160300909**
#4233 
----

- [ ] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [x] Manually tested changed features in running JabRef
- [ ] Screenshots added in PR description (for bigger UI changes)
- [ ] Ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)

### CODE REVIEW

**Comment by tobiasdiez** [comment]
What do you mean by "there is a dialog box"?

**Comment by 1160300909** [comment]
@tobiasdiez
Sorry, I didn’t express it clearly.
When I run it with eclipse (windows, java7) and press the "merge entries" key, the dialog is stuck.
The following error was reported:
[AWT-EventQueue-0] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[AWT-EventQueue-0,6,main] - java.lang.IllegalStateException: Not on FX application thread; currentThread = AWT-EventQueue-0
	at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:236)
	at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:423)
	at javafx.scene.Parent$2.onProposedChange(Parent.java:367)
	at com.sun.javafx.collections.VetoableListDecorator.clear(VetoableListDecorator.java:294)

**Comment by Siedlerchr** [comment]
I think the problem is more complex than at first thought.  I would propose we use the same approach as with the quality dialog. Use an FXDialog as base and embed the swing stuff as SwingNode or better, completely convert the whole dialog to javafx

**Comment by Siedlerchr** [comment]
Superseeded by  #4289

**Pull request closed without merging**
