### PR TITLE
Fix some fetcher tests

### PR DESCRIPTION
**Pull request by calixtus**
refs #6369 

- [ ] Change in CHANGELOG.md described (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by Siedlerchr** [comment]
I think the INSPIRE test can also be fixed, seems like the bib item changed

**Comment by calixtus** [comment]
The INSPIRE test leaves me clueless. The text is exactly the same. Maybe it's about the line seperators? I was unable to debug the test myself. Can you maybe take a look at it, @Siedlerchr ?

**Comment by Siedlerchr** [comment]
For inspire change the line in the second entry to this:
`        article.setField(StandardField.JOURNAL, "Nucl. Phys. B");`
without the double slashes

**Comment by calixtus** [comment]
@Siedlerchr and @tobiasdiez , could you do me a favor and take a look on the buildinfo stuff, i'm not sure if I did that right and i'm unable to debug that. According to the test log, instead of the api key the IEEE fetcher only recieves three asterisks from the build script. Is this normal? Did I do something wrong?

**Comment by koppor** [comment]
The test log does not output the API keys, it just outputs starts. This is perfectly OK.

**Comment by calixtus** [comment]
This PR is done for now and should fix all the fetcher tests, except IEEE fetcher, which depends most likely on a new api key.

**Comment by Siedlerchr** [comment]
So we now only have MrDlib and IEEE not working

**Comment by calixtus** [comment]
Strange, MrDlib Ran through an hour ago without complaining...

**Pull request merged**
