### PR TITLE
"Use Processing %0" and "Error while fetching from %0" in fetchers

### PR DESCRIPTION
**Pull request by Siedlerchr**
- [x] Changes in pull request outlined? (What, why, ...)
- [x] Tests green?
Update of #948

### CODE REVIEW

**Comment by koppor** [comment]
Think, you will have to rebase on master as soon as #948 went through :innocent:

**Comment by Siedlerchr** [comment]
@koppor  It is only existing in the non-english translation files.
I didn't want to delete it, as it can be reused for a translation and simply adding the %0 parameter could possibly change the semantics for some languages. Don't know if any language may has it the other way round

**Comment by koppor** [comment]
I thought: better some translation than none.

Please look carefully on my regular expression. It just adds the new translation:

grabbed_20160312-163252

**Comment by Siedlerchr** [comment]
Changed the translations now.
Do I have to rebase now?

**Comment by koppor** [comment]
Could you merge your last two commits into one? (`git rebase -i HEAD^^` and so on)

Then, we have to wait until #948 is merged. Then, you can rebase.

**Comment by simonharrer** [comment]
#948 is merged

**Comment by koppor** [comment]
@Siedlerchr Please do as described at https://github.com/JabRef/jabref/wiki/Tools#rebase-everything-as-one-commit-on-master to have one commit in this PR.

**Comment by Siedlerchr** [comment]
@koppor  Done. Just got stuck with rebasing. The reset helped.

**Comment by simonharrer** [comment]
:+1: looks good.

**Pull request merged**
