### PR TITLE
Added a strong border on hover to the file field

### LINKED ISSUE #6859: Invisible buttons for File field
JabRef 5.1--2020-08-30--e023aa0
Windows 10 10.0 amd64 
Java 14.0.2

- [x ] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

The buttons near the File field are not visible (screenshot 1). If the File entry has problems all the following fields disappear (screenshot 2).

1. Open a library containing the following entry:
```
@InCollection{Favre2004,
  Title                    = {{AVS and AVS/Express}},
  Author                   = {Jean Favre and Mario Valle},
  Booktitle                = {{The Visualization Handbook}},
  Publisher                = {Academic Press},
  Year                     = {2004},
  Editor                   = {Chuck Hansen and Chris Johnson},
  Month                    = dec,
  Pages                    = {655--672},
  File                     = {Paper:file\:///D\:\\Books\\Publications\\ch33%20favre.pdf:PDF},
  Keywords                 = {books},
  Mvpubtype                = {books},
  Langid                   = {english},
  Url                      = {http://www.elsevierdirect.com/product.jsp?isbn=9780123875822}
}
```
2. Select the entry and an exception appears (exception stack below):
```
Illegal char <:> at index 4: file:///D:/Books/Publications/ch33%20favre.pdf
```
Note this entry pertains to a library created in a very old version of JabRef.
3. Go to the General tab and notice the buttons are not visible.
4. Click on the File field and all the following fields disappear.
5. Now try to reload the entry selecting the file with the leftmost invisible button.
6. Nothing appears in the field

Missing buttons:
image

After clicking on the File field:
image

Exception text:
```
java.nio.file.InvalidPathException: Illegal char <:> at index 4: file:///D:/Books/Publications/ch33%20favre.pdf
	at java.base/sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
	at java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at java.base/sun.nio.fs.WindowsPath.parse(Unknown Source)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
	at java.base/java.nio.file.Path.of(Unknown Source)
	at org.jabref@5.1.60000/org.jabref.gui.fieldeditors.LinkedFileViewModel.isGeneratedNameSameAsOriginal(Unknown Source)
	at org.jabref@5.1.60000/org.jabref.gui.fieldeditors.LinkedFilesEditor.createContextMenuForFile(Unknown Source)
	at org.jabref@5.1.60000/org.jabref.gui.util.ViewModelListCellFactory$1.updateItem(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.control.ListCell.updateItem(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.control.ListCell.indexChanged(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.control.IndexedCell.updateIndex(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.control.skin.VirtualFlow.setCellIndex(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.control.skin.VirtualFlow.getCell(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.control.skin.VirtualFlow.getCellLength(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.control.skin.VirtualFlow.computeViewportOffset(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.control.skin.VirtualFlow.layoutChildren(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.Scene.doLayoutPass(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.Scene$ScenePulseListener.pulse(Unknown Source)
	at org.jabref.merged.module@5.1.60000/com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.1.60000/com.sun.javafx.tk.Toolkit.runPulse(Unknown Source)
	at org.jabref.merged.module@5.1.60000/com.sun.javafx.tk.Toolkit.firePulse(Unknown Source)
	at org.jabref.merged.module@5.1.60000/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
	at org.jabref.merged.module@5.1.60000/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
	at org.jabref.merged.module@5.1.60000/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(Unknown Source)
	at org.jabref.merged.module@5.1.60000/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(Unknown Source)
	at org.jabref.merged.module@5.1.60000/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at org.jabref.merged.module@5.1.60000/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.1.60000/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

### PR DESCRIPTION
**Pull request by Fu188**
Since we do not set the border property for file field, the button are invisible in some cases. Such that, I add the border property in the css file. Now, the file field is invisible. Fixes #6859 

- [x] Change in CHANGELOG.md described (if applicable)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

image
image

### CODE REVIEW

**Comment by tobiasdiez** [comment]
Thanks for working on this. 

How is the border connected to the display problems of the buttons as in #6859?

**Comment by Fu188** [comment]
> Thanks for working on this.
> 
> How is the border connected to the display problems of the buttons as in #6859?

emmmm... I feel very sorry that I cannot get your idea.
Can you rediscribe your question more specifically?

**Comment by tobiasdiez** [comment]
In #6859, the buttons next to the listview are positioned rather strange. In this PR you don't change anything related to the buttons, but instead change the styling of the listview to have a border. I don't understand how this fixes the issue and would thus like you to describe your solution in more detail.

**Comment by Fu188** [comment]
> In #6859, the buttons next to the listview are positioned rather strange. In this PR you don't change anything related to the buttons, but instead change the styling of the listview to have a border. I don't understand how this fixes the issue and would thus like you to describe your solution in more detail.

On my side, the strange position of the buttons is releated to we cannot handle illegal file path before. But thanks to the #7347 , we can consider this problem now. In this case, only we need to do is to keep the file field border. (In the original version, the border is invisible in some time and will not highlight when we hover it.) Such that, I add the border property and the style of border looks well now.

**Comment by calixtus** [comment]
It seems, that the issue to be fixed was already (really) fixed by another PR, so this PR is just about some visual improvements. We can talk about that too.

**Comment by calixtus** [comment]
Devcall decision: As this would outstand just for the listview control, we decided not to merge this one, since we try to avoid ui inconsistencies.

**Pull request closed without merging**
