### PR TITLE
Change representation of encodings to Charset

### PR DESCRIPTION
**Pull request by tobiasdiez**
Instead of representing an encoding as a string we now use a Charset.
This idea was already discussed in PR #370.

### CODE REVIEW

**Comment by simonharrer** [comment]
I do like this. Can there be any issues if a previous file has an encoding format that is not understood and is loaded with a newer version of jabref?

**Comment by tobiasdiez** [comment]
As far as I can see there is no problem. The encoding from the file is given to `Charset.forName()`, which is the same behavior as previously. Maybe some encodings are now written to the bib-file in a slightly different way, but this shouldn't be a big problem.

**Comment by simonharrer** [comment]
Ok. Please rebase, I will merge it in.

**Comment by tobiasdiez** [comment]
Rebased.

**Pull request merged**
