### PR TITLE
[#4494] Add key bindings

### LINKED ISSUE #4494: RIS export empty
Would  it be possible to add key bindings for export (ctrl+E) and export selected entries (ctrl+shift+E)?

### PR DESCRIPTION
**Pull request by RonakLakhotia**
Fixes #4494

### CODE REVIEW

**Comment by RonakLakhotia** [comment]
@Siedlerchr also mentioned [here](https://github.com/JabRef/jabref/issues/4494#issuecomment-470421518) that The action/menu item needs to be modified as well to support the keybinding. I didnt quite understand this

**Comment by CaptainDaVinci** [comment]
I think you have to display in the menu item the corresponding short cut key for exporting.

**Comment by RonakLakhotia** [comment]
Seeing the import action 
is it `                factory.createSubMenu(StandardActions.EXPORT,
                        factory.createMenuItem(StandardActions.EXPORT_ALL, new ExportCommand(this, false, Globals.prefs)),
                        factory.createMenuItem(StandardActions.EXPORT_SELECTED, new ExportCommand(this, true, Globals.prefs)),` because this is already implemented

**Comment by CaptainDaVinci** [comment]
Yes, I think the shortcut keys should already be displayed in the menu item.

**Comment by Siedlerchr** [comment]
If it works it's good. Failing test is not related.

**Comment by Siedlerchr** [comment]
Thanks for your contribution!

**Pull request merged**
