### PR TITLE
Fixed groups scrolling

### LINKED ISSUE #9754: Quirks with groups panel scrolling when adding groups as subgroups or adding items to groups
### JabRef version

JabRef 5.10--2023-04-05--643319b
Windows 10 10.0 amd64
Java 19.0.2
JavaFX 20+19

### Operating system

Windows

### Details on version and operating system

Windows 10

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

Initial comment here: https://github.com/JabRef/jabref/issues/2869#issuecomment-1497179500 

There are a few quirks, which may or may not be related to the fix for scrolling in the groups panel when adding groups as subgroups (https://github.com/JabRef/jabref/pull/9728):

1. Open a JabRef database with a large number of static groups and items (thousands of groups and items)
2. Add a group to another group as subgroup using drag'n'drop with the newly implemented scrolling feature. To see the scrolling feature in action, you need to add the group to another group that is not already visible in the groups panel (i.e. the group needs to be further distant from the other group in the groups panel).
3. Note, that the scrolling speed is really high.
On one hand this is a nice feature for large databases with thousands of groups when you want the child group to be added to a parent group that is very distant in the group table view. On the other hand, it makes it nearly impossible to precisely add a child group to a parent group, since it is very likely that you will whoosh past the parent group due to the scrolling speed. It would be nice if the user could control the scrolling speed by moving the mouse more or less into the direction he wants to put the child group.

Another issue that may or may not be related can be triggered as follows:
1. Open a JabRef database with a large number of static groups and items (thousands of groups and items)
2. Add an item to a group using drag'n'drop with the newly implemented scrolling feature. To see the scrolling feature in action, you need to add the item to a group that is not already visible in the groups panel (i.e. the items current position in the groups panel needs to be further distant from the other group in the groups panel).
3. If you add an article to a group that is far distant (using the new scrolling groups feature) the group table view gets `confused' sometimes and either scrolls to the bottom of the groups panel (after the article has been added) or starts scrolling from top to bottom non-stop. Sometimes it appears to be necessary to have a search term (e.g. a bibtex key) in the search form to trigger this behaviour (at least, that is what it appears to me).

### PR DESCRIPTION
**Pull request by calixtus**
Fixed #9754 

### Mandatory checks
- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by tobiasdiez** [comment]
Thanks! The "always scroll to bottom" bug seems to be fixed, nice. For my taste, the scroll speed however is too slow now.

**Review by Siedlerchr — APPROVED** [review]

**Comment by Siedlerchr** [comment]
Follow up

**Comment by koppor** [comment]
Merged, because JabRef was unusable before. Follow-up takes more time than 10 minutes.

**Comment by tobiasdiez** [comment]
Sure, no problem. But next time please add a short comment, and reopen the issue.

**Pull request merged**
