### PR TITLE
Improved CaseChangers

### PR DESCRIPTION
**Pull request by oscargus**
New attempt with the same code and same limitations, but using branches. So hopefully possible to merge. I also used the JabRef formatter and clean up. Hopefully, I got it correct.

### CODE REVIEW

**Comment by simonharrer** [comment]
Would you mind adding just a few test cases to the already existing `CaseChangersTest` class so that the new feature is covered as well in the tests?

**Comment by oscargus** [comment]
OK! Will generate some test cases and change the tab in ChangeLog.

**Comment by oscargus** [comment]
Much fewer commits now and I think it is good to go.

**Comment by simonharrer** [comment]
One final remark from my side regarding the comments: this class previously worked on Strings with words. Now it works on Strings with words with special behaviour for words in {}. Can you please add a comment for this?

From the code side, I give my :+1:

**Comment by koppor** [comment]
@simonharrer I added comments at 96cf1d2a8f4ca

**Comment by oscargus** [comment]
@koppor Thanks for sorting out the comments!

**Pull request merged**
