### PR TITLE
Update the templates for opening a new issue

### PR DESCRIPTION
**Pull request by k3KAW8Pnf7mkmdSMPHz27**
Add links to the discourse forum. When you are attempting to open an issue to JabRef,

---

Skärmavbild 2021-01-08 kl  13 19 06

---

 **this is what is shown right now**,

---

Skärmavbild 2021-01-08 kl  13 04 34

---

and with the current version of GitHub, **this is what I want to change it to**,

---

Skärmavbild 2021-01-08 kl  13 04 09

---

Clicking the links will open https://discourse.jabref.org/c/help/ or https://discourse.jabref.org/c/features/ .
This relates to a recent issue since neither I nor the creator of the issue ticket appear to have noticed/known that it should have been in the discourse and not it in issue tracker (sorry :flushed:)

- [x] ~Change in CHANGELOG.md described (if applicable)~
- [x] ~Tests created for changes (if applicable)~
- [x] ~Manually tested changed features in running JabRef (always required)~
- [x] Screenshots added in PR description (for UI changes)
- [ ] ~[Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.~

### CODE REVIEW

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
I made a PR to the wrong repository. In the unlikely circumstance someone sees this before I have had time to test it in my fork, that is why it is currently in draft.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
Well, these are changes that work in my fork. Add/change/delete whichever seems appropriate. I am not an advanced GitHub user so I don't know if this can break anything. It is mostly a suggestion to use the optional `config.yml` file which is now available on GitHub.

The details are available at https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser

**Review by tobiasdiez — APPROVED** [review]
Cool!  I didn't know this was possible. Thanks 👍

**Review by calixtus — APPROVED** [review]
Looks good, let's merge.

**Pull request merged**
