### PR TITLE
Add script to remove local merged branches

### PR DESCRIPTION
**Pull request by tobiasdiez**
Based on https://gist.github.com/danvk/a715357444ff3c1a05c4cff730eea8e1, slightly changed

Add a small script that removes merged branches. Normally, git provides a few commands that detect merged branches (`git branches --merged`) and deletes obsolete ones (`git prune`). However, these commands do not work for PRs that were squashed. 

The script below goes through all github PR's and deletes the corresponding local branches if the PR was merged.

----

- [ ] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [ ] Manually tested changed features in running JabRef
- [ ] Screenshots added in PR description (for bigger UI changes)
- [ ] Ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)

### CODE REVIEW

**Comment by koppor** [comment]
I am against it. There is [`git delete-merged-branches`](https://github.com/stevemao/awesome-git-addons#delete-merged-branches). Found via https://github.com/stevemao/awesome-git-addons. 

Just install [git-extras](https://github.com/tj/git-extras).

**Comment by tobiasdiez** [comment]
Well, the problem is that this command also only "Deletes branches that are listed in git branch --merged.". But squash-merged PRs are not correctly recognized as part of `git branch --merged`.

**Comment by koppor** [comment]
Can we publish that as separate project - we are not the only ones with these issues. - The best would be if that was integrated in git-extras, but that is much more effort...

**Comment by tobiasdiez** [comment]
Yeah sure, feel free to publish it somewhere else (too). I just felt like you guys may also profit from it thus the urge to share the script. I do recognize that it is not JabRef specific but it was the easiest way to share it.

**Comment by tobiasdiez** [comment]
Decision. move to gist

**Comment by tobiasdiez** [comment]
The script is now at https://gist.github.com/tobiasdiez/766346cb3323dcba59a72753ea10c57e

**Pull request closed without merging**
