### PR TITLE
Update citeproc to released version

### PR DESCRIPTION
**Pull request by Siedlerchr**
### Mandatory checks

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by koppor** [comment]
I wonder why dependabot did not arrive here?

**Comment by koppor** [comment]
"Changelog": https://github.com/michel-kraemer/citeproc-java/releases/tag/3.0.0

**Review by koppor — APPROVED** [review]

**Comment by koppor** [comment]
Uhoh, did this break something? https://github.com/JabRef/jabref/issues/10676#issuecomment-2018874315. The mentioned commit is the one of the merge of this PR.

**Comment by Siedlerchr** [comment]
We should report it to the repo

Oliver Kopp ***@***.***> schrieb am Mo., 25. März 2024, 22:15:

**Comment by koppor** [comment]
> We should report it to the repo

No. It is "just" a module-info thing (again). See https://github.com/JabRef/jabref/pull/11103.

**Comment by Siedlerchr** [comment]
Citeproc java is not modularized, that is the key problem here that's why it's "merge" in our jar and because it requires commons-text in implementation and because we didn't have it it failed. But I wonder why it failed now... 
Maybe because it now uses java 11 and no longer 8. 

It should definitely be modularized.

**Pull request merged**
