### PR TITLE
migrate maintable.css to base css

### PR DESCRIPTION
**Pull request by Siedlerchr**
add style class for main table

Make @ryan-carpenter happy :)

### Mandatory checks

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by calixtus** [comment]
Did you remove the old maintable.css?

**Comment by Siedlerchr** [comment]
Yup, it's deleted now and removed the stylesheet loading

**Review by koppor — APPROVED** [review]
Tried. Works good.

I needed to fix an indent.

**Review by calixtus — APPROVED** [review]

**Comment by koppor** [comment]
This PR destroyed highlighting on mouse over. @koppor Please do more checks when trying out things!!!

**Pull request merged**
