### PR TITLE
Better preference for default file-based mode

### PR DESCRIPTION
**Pull request by stefan-kolb**
See #789.

- Description rewritten to say "Default TeX mode".
- Dropdown for bibtex & biblatex
- Moved to general tab
- Decided to keep old boolean preference to avoid preference migration for now

image

@JabRef/developers WDYT?

### CODE REVIEW

**Comment by koppor** [comment]
`TeX` is misleading as this lets me think about pdflatex and latex or pure tex. Maybe "Default bibliography mode" as we treat the bibliography?

**Comment by tobiasdiez** [comment]
:+1: 
Two minor remarks:
- I would write "BibTeX" and "BibLaTex" instead of everything upper case (what are our convention on this?)
- You can rename JabRefPreferences.BIBLATEX_MODE to something containing 'defaut' without forcing migration (i.e. leave the underlying string unchanged)

**Comment by koppor** [comment]
The spelling is discussed at https://github.com/koppor/jabref/issues/73. BibTeX is set, but Biblatex or BibLaTeX is not yet finally decided.

**Comment by simonharrer** [comment]
Looks good to me.

**Pull request merged**
