### PR TITLE
Add ADR for sync with external databases

### PR DESCRIPTION
**Pull request by tobiasdiez**
Based on earlier discussion in https://github.com/JabRef/jabref/issues/7618.

Also closes https://github.com/JabRef/jabref/issues/7618.

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by koppor** [comment]
Note that the current implementation is based on the [Optimisitc Offline Lock](https://martinfowler.com/eaaCatalog/optimisticOfflineLock.html), which does not appear in the ADR. (Was also part at the discussion - see https://github.com/JabRef/jabref/issues/7618#issuecomment-856187954)

**Comment by tobiasdiez** [comment]
The proposed design is an optimistic currency control. 

> Optimistic Offline Lock solves this problem by validating that the changes about to be committed by one session don't conflict with the changes of another session.

That's also so in the proposal. But the main part of the proposal concerns the question "how do you recognize that things changed on the server and on the client"?

**Comment by koppor** [comment]
I started to review the ADR - and put it more in the ADR format.

It seems, you describe what we already implemented 5 years ago. We also introduced separate IDs. Will need to dig deeper in this. More input will come the next days. - Thereby, I will also add some results of our discussions of edge cases in the issue.

**Comment by tobiasdiez** [comment]
Of course there are similarities with the current algorithm. The current version corresponds roughly to what is described in the paragraph "At this point, we could already sync the server and client by asking the server for all up-to-date entries and then using the `Revision` information to merge with the local data."
For example, at the start of the sync process we currently get the versions of all entries from the server: https://github.com/JabRef/jabref/blob/a90ee23410fabbef12c8114885f2cda1c226de9d/src/main/java/org/jabref/logic/shared/DBMSProcessor.java#L576-L582
This works of course but is not efficient.

**Comment by koppor** [comment]
Compare with https://automerge.org/blog/automerge-2/

**Comment by tobiasdiez** [comment]
CRDTs would be another option, the problem is however that you would need to locally store a lot more metadata (e.g. for operational CRDTs you essentially need to have the full history of all edits). So you would need another file next to the bib file to store these. Also CRDTs are mainly used when you need low latency and high frequency of edits (e.g. multi-user chat or text editing). Not really something we care about.

**Review by Siedlerchr — APPROVED** [review]

**Pull request merged**
