### PR TITLE
Fix Short DOI error

### LINKED ISSUE #7127: Additional Short DOI fatal exception cases: java.lang.IllegalArgumentException: <string> is not a valid DOI/Short
```
JabRef 5.2--2020-11-26--f1a2fa7
Windows 10 10.0 amd64 
Java 14.0.2
```

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

Summary
---------

JabRef produces fatal exceptions for files containing non-DOI-related strings such as `10:51` (a timestamp) and `10/B(C)/15` (an arbitrary designation/ID)

The ShortDOI parsing subsystem was improved in #6920 to fix failure cases, but it appears there are additional cases and strings (probably an arbitrarily high number) that produces fatal exceptions.

Given the issues associated with arbitrary strings in arbitrary documents, I suspect it is unlikely sustainable in the long-term to fixed pattern match, particularly if the behaviour of the system for failing cases, remains a fatal exception from which the user must manually recover (ie: identify the document containing the string, and exclude it from import).

I propose the behaviour be changed to fall-through (not fail). If it is desirable to not lose the failing semantics, files/entries may potentially be with a note or status that the parsing resulted in a null result, though I'm not sure that is particularly valuable.

Steps to reproduce the behavior
---------------------------------
1. Prepare local PDF files with contents that contain strings that produce exceptions (see below)
2. Create `New library`
3. Run `Tools` -> `Search for unlinked local files`
4. `Browse` to folder containing local files -> `Scan` -> `Import`

Log Files
---------

<details>
  <summary>Log File</summary>
  
```
java.lang.IllegalArgumentException: 10/B(C)/15 is not a valid DOI/Short DOI.
	at org.jabref@5.2.298/org.jabref.model.entry.identifier.DOI.<init>(Unknown Source)
	at org.jabref@5.2.298/org.jabref.model.entry.identifier.DOI.findInText(Unknown Source)
	at org.jabref@5.2.298/org.jabref.logic.importer.fileformat.PdfContentImporter.importDatabase(Unknown Source)
```
</details>

<details>
  <summary>Log File</summary>
  
```
java.lang.IllegalArgumentException: 10:51 is not a valid DOI/Short DOI.
	at org.jabref@5.2.298/org.jabref.model.entry.identifier.DOI.<init>(Unknown Source)
	at org.jabref@5.2.298/org.jabref.model.entry.identifier.DOI.findInText(Unknown Source)
	at org.jabref@5.2.298/org.jabref.logic.importer.fileformat.PdfContentImporter.importDatabase(Unknown Source)
```
</details>

### PR DESCRIPTION
**Pull request by PremKolar**
Fixes #7127 

In issue #6920 the detection of exact short dois was improved. This was relevant where short dois were misplaced under the wrong field of an entry. This did not affect the method `public static Optional<DOI> findInText(String text)`, which looks for dois _within_ text (not exact matches). 
With this commit, I have carried the improvements over to the _within-text_ detection. I had to make the detection more stringent, to avoid mis-detections for cases like _bla bla 10:30 bla bla_ or _bli blubb 10/12/2020 blibb blabb_ etc. Short dois within text will now only be detected if there is any _doi_ or _urn_ within the substring. E.g. any of the following will be detected:

- doi:10/12ab
- /urn:doi:10/12ab
- doi.org/10/1234
- doi.org/ab123 (shortcut doi)
- etc..

I also introduced the concept of _shortcut dois_ to the in-text detection. (e.g. _doi.org/xyz123_)

- [ ] Change in CHANGELOG.md described (if applicable)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

**Review by Siedlerchr — APPROVED** [review]
LGTM, please fix the checkstyle error 
Error: eckstyle] [ERROR] /home/runner/work/jabref/jabref/src/test/java/org/jabref/model/entry/identifier/DOITest.java:260:5: 'METHOD_DEF' has more than 1 empty lines before. [EmptyLineSeparator]

**Comment by koppor** [comment]
We're just having a (light) mob programming session and will take over. 😅

**Comment by koppor** [comment]
GitHub shows too much changed files. Maybe due to database errors at GitHub - see https://github.com/JabRef/jabref/compare/master...PremKolar:shortDOIexceptionsFix_issue7127

**Comment by koppor** [comment]
When opening the diff:

grafik

**Comment by PremKolar** [comment]
Oh wow :) Thank you for doing all the hard work!! :)

**Comment by PremKolar** [comment]
sorry for referencing the wrong issue #... no idea how that happened ¯\_(ツ)_/¯

**Comment by Siedlerchr** [comment]
@PremKolar  We have to thank you for impoving and fixing the regex We just moved the tests to paramterized ones

**Comment by koobs** [comment]
Thank you all 👍

**Comment by Siedlerchr** [comment]
@PremKolar  As you recently adapted the DOI find in text. I just stumbled upon an issue, which results in an error when the method finds a DOI with a dot at the end:
This results in a not found error from doi.org 

**doi:10.1007/s10549-018-4743-9.**
It would be cool if you could add a replacement at the end

The following text is coming from the PDF content importer. It extracts the text content of the first page and then calls 
`DOI.findInText(firstPageContents);`
```
HHS Public Access
Author manuscript
Breast Cancer Res Treat. Author manuscript; available in PMC 2019 July 01.

Published in final edited form as:
Breast Cancer Res Treat. 2018 July ; 170(1): 77–87. doi:10.1007/s10549-018-4743-9.

Acupuncture for breast cancer-related lymphedema: a 
randomized controlled trial
```

**Comment by PremKolar** [comment]
Hi, yes i would love to look into it. I'm not sure it's the `.`, but we will see..
Maybe the 25th I'll find the time 🙂

**Comment by Siedlerchr** [comment]
Thanks in advance! No hurry. Happy holidays!

**Comment by koobs** [comment]
> 
> 
> @PremKolar As you recently adapted the DOI find in text. I just stumbled upon an issue, which results in an error when the method finds a DOI with a dot at the end:
> This results in a not found error from doi.org
> 
> **doi:10.1007/s10549-018-4743-9.**
> It would be cool if you could add a replacement at the end
> 
> The following text is coming from the PDF content importer. It extracts the text content of the first page and then calls
> `DOI.findInText(firstPageContents);`
> 
> ```
> HHS Public Access
> Author manuscript
> Breast Cancer Res Treat. Author manuscript; available in PMC 2019 July 01.
> 
> Published in final edited form as:
> Breast Cancer Res Treat. 2018 July ; 170(1): 77–87. doi:10.1007/s10549-018-4743-9.
> 
> Acupuncture for breast cancer-related lymphedema: a 
> randomized controlled trial
> ```

I was going to report the same error, but I wanted to check whether DOI's could syntactically (validly) end in periods before I did so.

**Pull request merged**
