### PR TITLE
Issue 9646: Right-click context menu "Attach file from URL"

### LINKED ISSUE #9646: Context Menu: "Attach File from URL" / "Download File from URL"
**Is your suggestion for improvement related to a problem? Please describe.**
Often times you find the PDF version of a file at a different website than the BIBTex citation. I'd like to have an more easy way to attach the PDF file via URL to a certain entry in my reference library without having to download it first. JabRef should handle download and storing PDF in right location, not me.

**Describe the solution you'd like**
Currently when you right-click on an entry the context menu appears. The context menu has an "Attach File..." button which allows you to use the file chooser to attach a PDF file. However, when doing this, the file is not copied into your "referenced files" folder and if you have the PDF file open in a browser tab you'd need to download it and then select the downloaded file.

**Additional context**
I'm away this functionality "Attach File From Url" is already implemented. But the user experience to get to it is quite cumbersome. First the entry needs to be created for the article, then you need to select it in Jabref, navigate the detail menu to register "General", then go to the "File" list and then on the right of the file list there is a tiny button labeled "Download from URL".

My - and I think many other's - workflow would be much easier if we can just navigate to a page in our browser tab (e.g. the official journal website), use JabRef browser extension to import the bibtex reference into JabRef, then copy the PDF URL from another browser tab (e.g. the researcher's github page where PDF is freely available) and then paste the URL via right-click context menu "Attach File from URL..." to the new entry.

If you agree I'm happy to provide a PR.

### PR DESCRIPTION
**Pull request by bf**
Fixes #9646 

Add "Attach file from URL" to right-click context menu. Same functionality as the "download file" from the detail dialog.

right-click context menu:
image

url dialog:
image

file added:
image

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [x] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by bf** [comment]
I had to duplicate some code from `LinkedFilesEditorViewModel` because of the way where taskexecutor and preferences come from. I now forward taskexecutor from RightClickMenu like other actions in that file are doing.

The one thing that AttachFileAction has and AttachFileFromURLAction doesn't is the undo() functionality. I was unsure how to implement it as in LinkedFilesEditorViewModel I couldn't find any `change` events that the undo system seems to need.

**Comment by bf** [comment]
god eclipse is so bad

**Comment by bf** [comment]
Can you please fix the checkstyle for me. I can't seem to get it to work in Eclipse. Eclipse is so shitty it hurts me.

**Comment by Siedlerchr** [comment]
@bf  Yes, Eclipse (although I use it myself) is not really compatible with the style we use in intellij (all others use intellij)

**Comment by bf** [comment]
thank you so much!

**Comment by Siedlerchr** [comment]
Regarding undo, you can ignore this for now. That's still an issue on our list to provide a better solution.
I'll try to take a closer look at the code tomorrow but so far it seems fine

**Review by Siedlerchr — APPROVED** [review]

**Comment by bf** [comment]
Thanks for the kind refactor @Siedlerchr. I've been working with the most recent version since a few hours and it works well. 

Only thing I noticed is that some downloads return a 403 (I think it was sciencedirect.com) because the website is protected by cloudflare. But the download is also failing via curl (chrome dev tools -> copy request as curl) due to lack of Cloudflare cookies. So I think this is an unrelated issue because it also happens with the existing "download from url" feature. Also it is out of scope for JabRef to circumvent CloudFlare protections.

Again, thanks for the kind collaborative environment on this project and your super-quick turnaround times. Really appreciate it.

**Comment by calixtus** [comment]
Hi bf, I took the liberty to refactor your very neat PR just a little bit. I hope you don't mind. I just moved the method from the utility class as a static method to your new attach command.
Looks good to me!

**Review by calixtus — APPROVED** [review]

**Review by Siedlerchr — APPROVED** [review]

**Comment by Siedlerchr** [comment]
Many thanks again for your contribution! Looking forward for more ;)

**Pull request merged**
