### PR TITLE
Add FAQ to devdocs (Code Howtos)

### PR DESCRIPTION
**Pull request by subhramit**
This introduces an ```faq.md``` inside devdocs (Code Howtos) which is intended to contain common issues faced by developers (e.g. failing tests) while developing JabRef and their most probable solutions.

image
### Mandatory checks

- ~[ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)~
- ~[ ] Tests created for changes (if applicable)~
- ~[ ] Manually tested changed features in running JabRef (always required)~
- ~[ ] Screenshots added in PR description (for UI changes)~
- [x] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by subhramit** [comment]
Okay apparently inline HTML is not allowed. Will have to let go of the colored text.

**Comment by subhramit** [comment]
Getting the changed submodules commit issue again.
IntelliJ is already configured as per https://github.com/JabRef/jabref/pull/11138#issuecomment-2044452708
Would need help fixing this.

**Comment by koppor** [comment]
> Okay apparently inline HTML is not allowed. Will have to let go of the colored text.

Please bring them back again and let's check how it shows up in "just the docs".

Please configure markdown-lint. A hint was given at https://github.com/DavidAnson/markdownlint/blob/v0.34.0/doc/md033.md. But do it the easy way: Put `<!-- markdownlint-disable-file MD033 -->` at the end of the md file

**Comment by koppor** [comment]
> Getting the changed submodules commit issue again. IntelliJ is already configured as per [#11138 (comment)](https://github.com/JabRef/jabref/pull/11138#issuecomment-2044452708) Would need help fixing this.

I am sorry that I do not use IntelliJ for committing. I should say to everyone: Please use `git gui`.

- Ensure everything is committed
- `gitk --all&` (to start gitk to have the commit IDs ready if something goes wrong)
- `git merge upstream/main` (to merge the latest upstream changes)
- `git reset upstream/main` (to discard all commits and start a fresh commit)
- `git gui` (to craft a new commit. Do NOT commit the changes in the submodule. Try to revert these changes using "Commit" -> "Revert Changes")
- Create a new commit using `git gui` (maybe other git tooling you use)
- `git push -f` (to overwrite the changes also in this PR)

**Comment by subhramit** [comment]
> > Getting the changed submodules commit issue again. IntelliJ is already configured as per [#11138 (comment)](https://github.com/JabRef/jabref/pull/11138#issuecomment-2044452708) Would need help fixing this.
> 
> I am sorry that I do not use IntelliJ for committing. I should say to everyone: Please use `git gui`.
> 
> * Ensure everything is committed
> * `gitk --all&` (to start gitk to have the commit IDs ready if something goes wrong)
> * `git merge upstream/main` (to merge the latest upstream changes)
> * `git reset upstream/main` (to discard all commits and start a fresh commit)
> * `git gui` (to craft a new commit. Do NOT commit the changes in the submodule. Try to revert these changes using "Commit" -> "Revert Changes")
> * Create a new commit using `git gui` (maybe other git tooling you use)
> * `git push -f` (to overwrite the changes also in this PR)

Done. Thank you for the detailed steps.

**Review by Siedlerchr — APPROVED** [review]

**Review by calixtus — APPROVED** [review]

**Pull request merged**
