### PR TITLE
[WIP] First attempt at fixing second jabref instance detection

### LINKED ISSUE #4023: Multiple jabref instances with 4.3 maintable-beta while Port 6050 is checked
- [x] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef 4.1; Windows 7 6.1 amd64; Java 1.8.0_171
JabRef 4.3-dev--snapshot--2018-05-07--maintable-beta--35b068386

Steps to reproduce:

1. Run 4.1, run 4.3 on the same file...
2. do some group actions in 4.3
3. .data in the 4.1 file are lost when saving

<details>
  <summary>I was very astonished to see in parallel to JabRef 4.1; Windows 7 6.1 amd64 ; Java 1.8.0_171
JabRef 4.3-dev--snapshot--2018-05-07--maintable-beta--35b068386.
Both programs have the port 6500 checked and tell me that only one instance of jabref would be running.
I think an error of the snapshot version which does not respect that an instance of jabref is already running.  
</summary>

</details>

```
Port is blocked
        java.net.BindException: Address already in use: JVM_Bind
	at java.net.DualStackPlainSocketImpl.bind0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketBind(Unknown Source)
	at java.net.AbstractPlainSocketImpl.bind(Unknown Source)
	at java.net.PlainSocketImpl.bind(Unknown Source)
	at java.net.ServerSocket.bind(Unknown Source)
	at java.net.ServerSocket.<init>(Unknown Source)
	at org.jabref.logic.remote.server.RemoteListenerServer.<init>(RemoteListenerServer.java:26)
	at org.jabref.logic.remote.server.RemoteListenerServerThread.<init>      (RemoteListenerServerThread.java:18)
	at org.jabref.logic.remote.server.RemoteListenerServerLifecycle.open(RemoteListenerServerLifecycle.java:43)
	at org.jabref.JabRefMain.start(JabRefMain.java:163)
	at org.jabref.JabRefMain.lambda$start$0(JabRefMain.java:57)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
```

### PR DESCRIPTION
**Pull request by Siedlerchr**
Detection works now , but there remain some threads open
Remote the exception for empty arguments.
Fixes #4023

----

- [ ] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [ ] Manually tested changed features in running JabRef
- [ ] Screenshots added in PR description (for bigger UI changes)
- [ ] Ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)

### CODE REVIEW

**Comment by NorwayMaple** [comment]
Hi,

I'm curious why you eliminated the parser check in the message handler.

Also, I'm looking into how JabRef detects instances already running. Is it true that it checks for a connection to the port specified in preferences?

Thanks!

**Comment by Siedlerchr** [comment]
For the drckb

**Comment by NorwayMaple** [comment]
I had trouble running two instances of JabRef through Gradle. Should I be running `./gradlew run` in two separate bash windows or is that wrong because it tries to compile both times?

**Comment by Siedlerchr** [comment]
In Eclipse I simply can start two instances.
In terminal you probably need to start a new window 
PS: happy new year

**Comment by NorwayMaple** [comment]
Happy New Year!

In Eclipse I have been getting an error `Error: Could not find or load main class org.jabref.JabRefMain`, so I had been using `gradlew`. When I open a second window and run `gradlew run`, it tries to compile, but it throws an error. It works fine for the first JabRef instance.

**Comment by Siedlerchr** [comment]
Run gradlew Eclipse

**Comment by NorwayMaple** [comment]
I get:

MacBook-Air-2:jabref Abe$ ./gradlew eclipse

> Task :eclipse
UI preferences already exist and will not be overridden. Use task 'cleanEclipse' first.

BUILD SUCCESSFUL in 5s`

Then I run JabRef in Eclipse and get the same error.

**Comment by tobiasdiez** [comment]
The build process should create a jar which you can run as often as you want using `java -jar ...` (or you use the jar of an installed version of JabRef in addition to gradlew run).

**Pull request closed without merging**
