### PR TITLE
ISBNtoBibTeX error mesage is now more clear

### PR DESCRIPTION
**Pull request by Siedlerchr**
This is my first Pull Request. 

Refs #684.

### CODE REVIEW

**Comment by koppor** [comment]
Your commit 33bd952df6c002f1ec06a2b07d59d1f3692e9c44 changes each line in the file. Did you use Eclipse eGit? This causes issues at Windows because of the line endings or [to change to `LF` at the git checkout](http://stackoverflow.com/a/13154031/873282). I would recommend to always use `git gui` instead of eGit.

Please read [CONTRIBUTING.md](https://github.com/JabRef/jabref/blob/master/CONTRIBUTING.md) which explains some details on the PRs. Especially that one should not use the `master` branch: All future updates to your master branch will be shown here in this PR. This is a known issue.

Finally, for small changes such as merging the master branch or the correct usage of the [localization](https://github.com/JabRef/jabref/wiki/Code-Howtos#using-localization-correctly), please do

1. `git fetch upstream --prune`
1. `git merge upstream/master`
1. `git reset upstream/master`
1. `git gui`

In git gui, review and commit your changes. Then do a force push to overwrite your changes here. This squashes all commits into a single one. If you want to keep multiple commits, please continue reading at [using-git-rebase](https://help.github.com/articles/using-git-rebase/).

The first two steps are basically https://help.github.com/articles/syncing-a-fork/, where step 4 is skipped.

Hint: At Windows: set the environment variable `LANG` to `en`.

You can also send me a private mail if you have any issues in using git.

**Comment by simonharrer** [comment]
And can you please merge your 4 commits into 1 commit as well as add a changelog entry describing your change?

What is more:
- Localization.lang does not use %s as placeholders but %0 and %1 etc. 
- When updating Localization.lang keys, we have a test in place which ensures that the localizations are correct. You may need to look into this as well.

**Comment by Siedlerchr** [comment]
Thanks for all the tips. I will look at this today in the evening.

**Comment by simonharrer** [comment]
@Siedlerchr I think this would be helpful to be merged in for the next release. Could you perhaps complete the PR in the next days?

**Comment by Siedlerchr** [comment]
@simonharrer  I've been busy, but I will try to finish the PR tomorrow.

**Comment by simonharrer** [comment]
Duplicate of #761

**Pull request closed without merging**
