### PR TITLE
Add notification when adding previous entries to new group configuration

### LINKED ISSUE #8911: Add notification or documentation for: Adding original entries to new group configuration unexpectedly modifies original entries
### JabRef version

Latest development branch build (please note build date below)

### Operating system

Windows

### Details on version and operating system

Windows 10

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

Steps to reproduce:
Part 1:
1. Create a new library.
2. Click on `Add group` button.
3. Input name `test1` for the group and create the group.
4. Create 2 articles in `All entries`.
5. Input author field with `steven` and `mike` for each article respectively.

Part 2:
1. Right click on `test1` group -> `Edit group`
2. Select `Searching for a keyword` under `Collect by`.
3. Input `author` as field and `steven` as keyword, then click on ok button and ok button for warning dialog.
(`test1` group has a steven article entry)

Part 3:
1. Right click on `test1` group -> `Edit group`
2. Select `Searching for a keyword` under `Collect by`.
3. Input `author` as field and `mike` as keyword, then click on ok button and ok button for warning dialog.
(`test1` group now has 2 articles which are `steven,mike` and `mike` articles)

<br/>
EXPECTED:
<br/>
I am expecting that part 3 will return both `steven` and `mike` articles.

ACTUAL:
However, 1 of the articles' author field has been merged to `steven,mike`. Is this an expected behaviour?
From my understanding, `Collect by` should only return filtered entries without any entries modification.
<br/>

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

### PR DESCRIPTION
**Pull request by LIM0000**
Fixes #8911

`(Note: If original entries lack keywords to qualify for the new group configuration, confirming here will add them)`

## Proposed solution
1. Change from `showConfirmationDialogAndWait` to `showCustomButtonDialogAndWait`. This `showCustomButtonDialogAndWait` with warning alert allow user to select:

    - `Yes` button, proceed to add previous entries into new group
    - `No` button, proceed to remove previous entries from new group
    - `Cancel` button, cancel the group editing process

2. If `Collect by` is selected to be `Searching for a keyword`, warning dialog will display extra information of `(Note: If original entries lack keywords to qualify for the new group configuration, confirming here will add them)` for `WordKeywordGroup`. Please refer to [keyword append discussion](https://github.com/JabRef/jabref/issues/8911#issuecomment-1161239043) for more details.

## PR checklist:

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by Siedlerchr** [comment]
PLease have a look at the faling l10n tests, otherwise looks good to me already

**Comment by Siedlerchr** [comment]
I was to free to fix the l10n tests and to make the buttons more explicit.

grafik

**Comment by ThiloteE** [comment]
I tested this pr. Looking good :+1: 

JabRef 100.0.0
Linux 5.4.0-121-generic amd64 
Java 18.0.1 
JavaFX 18+12

**Comment by LIM0000** [comment]
Thank you @ThiloteE and @Siedlerchr for helping this PR out!
Unfortunately I am not available recently.
Thanks again.

**Review by Siedlerchr — APPROVED** [review]

**Review by koppor — APPROVED** [review]
OK for me to move on here.

This is nevertheless "tough" business logic happenning here, which should be tested automatically. To track that, I opened https://github.com/koppor/jabref/issues/584.

**Pull request merged**
