### PR TITLE
Fix harvard exporter by changing AuthorsFormatter

### LINKED ISSUE #4508: export to Harvard/RTF incorrect when name contains (properly escaped) "and"
JabRef version 3.2

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists (JabRef-5.0-dev--snapshot--2018-11-23--master--742cfce7e.jar)

The export filter interprets all "and"s in name fields as breaking multiple names even when the author is properly escaped with curly braces.

1. consider the bibtex
```bibtex
@article{test,
  author = {{Organization for Economic Cooperation and Development}}
}
```
2. verify that latex+biber properly output "Organization for Economic Cooperation and Development" as author
3. export with Harvard filter and find "Organization for Economic Cooperation & Development".
4. change name to {{Organization for Economic Cooperation and Development and other stuff}} and rejoice at "for Economic Cooperation, O.; Development & other stuff"

Clearly, the export plugin does not honor the double curly braces that should prohibit breaking names.

I haven't found any other way of quoting the "and" to avoid breaking the name into multiple names that are then recombined, either.

### PR DESCRIPTION
**Pull request by Siedlerchr**
The layout files were still using the old formatter chaining for authors and therefore were responsible for removing braces 
Also fix extension.

Fixes #4508 

- [x] Change in CHANGELOG.md described (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by Siedlerchr** [comment]
For other layout files I have created a follow up issue https://github.com/JabRef/jabref/issues/7356

**Comment by Siedlerchr** [comment]
@k3KAW8Pnf7mkmdSMPHz27  I simply had to replace the old formatters. Totally forgot that we changed the format implementation. So sorry for bothering you.

**Comment by tobiasdiez** [comment]
We don't have any tests for this exporter?

**Comment by Siedlerchr** [comment]
We don't have any tests for the TemplateExporter (the layout file based). But I guess it would make sense to add some.

**Review by tobiasdiez — APPROVED** [review]

**Pull request merged**
