### PR TITLE
Add paging support

### PR DESCRIPTION
**Pull request by koppor**
By @JoHaHu. Let's discuss how to go on here.

Refs #5518.

### CODE REVIEW

**Comment by tobiasdiez** [comment]
@koppor @JoHaHu any update?

**Comment by koppor** [comment]
Open point: Add UI

**Comment by koppor** [comment]
Merged, because required as logic module for https://github.com/koppor/jabref/issues/369.

**Comment by tobiasdiez** [comment]
Why did you merged this? I thought we don't want to have half-finished code in our code base...

You could have implemented the UI etc easily by PRs against this branch, as we had it for the JavaFX project.

**Comment by koppor** [comment]
This functionality is required to get @DominikVoigt's implementation finished. As we write, he is working on it. Lean back and prepare for incoming pull requests the next days and weeks. 

Regarding the UI for the use case linked at https://github.com/JabRef/jabref/pull/5518 we still need a volunteer though.

**Pull request merged**
