### PR TITLE
Add file path in the Delete dialog text.

### PR DESCRIPTION
**Pull request by Racheal7**
Fixes [koppor#534](https://github.com/koppor/jabref/issues/534). The issue is about the file path being too long to fit in the title of the "Delete File" dialog.

My current solution is that instead of the absolute file path, only the file name is shown in the dialog title. The file's absolute path is added in the dialog text.

Add only file name in title

The alternatives are: 

1. Delete the file path in the dialog title and replace it with "Delete File", which is consistent with the "Delete entry" dialog. Add the full file path in the text.
Add file name to text

2. Keep the file path in the title and also add it to the text.
Only add file path in text

I'd love to know what you guys think.

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [x] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by Racheal7** [comment]
I just modified the l10n properties in the JabRef_en.properties file.

**Comment by Gpax971** [comment]
Looks good, I think your current solution of file name in title, file path in dialog is better than the alternatives.

**Review by Siedlerchr — APPROVED** [review]
Thanks, looks good to me! Like the solution

**Comment by Racheal7** [comment]
@Siedlerchr @tobiasdiez Thanks for approving and merging my changes~

**Pull request merged**
