### PR TITLE
Fix "&" on previews

### PR DESCRIPTION
**Pull request by JosejeSinohui**
Proposed solution for #3840 

I deleted a line where the & was getting escaped when generating the preview, apparently CSL already handles some kind of escaping.

The following entry
```
@Misc{b1111,
  author = {b, a},
  title  = {c \& d},
  year   = {1111},
}
```
generates this HTML
```
<div class="csl-entry">
  <div class="csl-left-margin">[1]</div><div class="csl-right-inline"> a b, ôc &#38; d.ö 1111.</div>
</div>
```
which renders in the PreviewLayout like this
ampersand

- [x] Change in CHANGELOG.md described (if applicable)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for bigger UI changes)
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not: Issue created at <https://github.com/JabRef/user-documentation/issues>.

### CODE REVIEW

**Comment by Siedlerchr** [comment]
I fear that will destroy the HTML export and other custom html exports.
The HTMLChars formatter is used there a lot.
https://docs.jabref.org/import-export/export/customexports#adding-a-custom-export-filter

Another idea which just came to my mind. Have you tried without the HTML chars formatter, e.g. if it works if you remove the HTML chars formatter in that step?

**Comment by JosejeSinohui** [comment]
You are right! I removed the formatter from the CSL Adapter and it works just fine. I'll update the PR

**Comment by koppor** [comment]
@JosejeSinohui Thank you for working on JabRef - could you please merge upstream/master so that our automated checks are triggered on your PR?

**Comment by koppor** [comment]
Would it be possible to add test cases here? You already provided a snippet. - The reason is that in one year someone touching CSLAdapter won't know that the HtmlCharsFormatter was removed and will re-add it again. There won't be any automatism preventing that.

**Comment by JosejeSinohui** [comment]
Hi, sorry for the delay. I will add tests and update my PR.

**Comment by tobiasdiez** [comment]
Perfect, thanks for the quick followup!

**Pull request merged**
