### PR TITLE
Update codesign action due to Node 16 deprecation

### PR DESCRIPTION
**Pull request by Siedlerchr**
Fixes https://github.com/JabRef/jabref-issue-melting-pot/issues/411
v

### Mandatory checks

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Review by koppor — CHANGES_REQUESTED** [review]
I am not sure if we should share our certificates with a 2-star-GitHub action.

Possibilities:

a) Follow https://github.com/Apple-Actions/import-codesign-certs/issues/57#issuecomment-2031100366 and just copy the commands in here
b) Use `1923310662e8682dd05b76b612b53301f431cd5d` instead of `node20` so that we are safe for future modifications or high-jacking of the repostiory.

**Comment by Siedlerchr** [comment]
https://github.com/Apple-Actions/import-codesign-certs/pull/58
Basically the guy proposed the PR that is still not merged

**Comment by koppor** [comment]
> https://github.com/Apple-Actions/import-codesign-certs/pull/58
> Basically the guy proposed the PR that is still not merged 
> 

Does he have 2FA activated? Is it sure that he doesn't get hacked?

How fast can we revoke certidiates if he is hacked and someone uses our certificates?

**Comment by Siedlerchr** [comment]
Well, we trusted the origiinal user as well without knowing. Plus we can still see the source. but to be safe we can use the hash

**Review by koppor — APPROVED** [review]

**Pull request merged**
