### PR TITLE
Rename pt_BR to pt_br, because the locale is converted to lowercase

### PR DESCRIPTION
**Pull request by Siedlerchr**
in EncodingControl resource bundle loading
Fix for #1182 
(I could not test it directly because I only have Win atm, which is case insensitive, but from debugging it was clear that it was a case-sensity).
So please test that. 

@mlep  Please notice that I renamed the files to lowercase only. You can try this directly in your JabRef installation, it should then work.

### CODE REVIEW

**Comment by Siedlerchr** [comment]
Could someone of the linux users please take a look at that failing test? Can't reproduce that on win.

**Comment by mlep** [comment]
Indeed, this works on my Linux computer: I get the menus translated in Brazilian Portuguese.
Great!

**Comment by matthiasgeiger** [comment]
@Siedlerchr The problem is again casing: In `Languages.java` Portuguese is added as `        LANGUAGES.put("Brazilian Portugese", "pt_BR");` - and this locale abbreviation is used in the tests to find the files...

However, the format `pt_BR` or `languange_COUNTRY` are the official abbreviations so I don't like to change all keys and files to lowercase but I'd prefer to remove the lowercasing on resource loading. Can you change this in this PR?

**Comment by mlep** [comment]
This could also be the opportunity to correct the missing "u":
"Brazilian Portugese" --> "Brazilian Portuguese"

**Comment by Siedlerchr** [comment]
@matthiasgeiger  I will look at it, however the problem with the case is implicit in the EncodingControl, there a Locale is passed in the ResourceBundle methods (which in fact is the JAVA SDK implementation). 
However, the Locale Object is internally converted to lowercase --at least that is what I saw.
I will setup my VM today for testing directly on linux.

**Comment by matthiasgeiger** [comment]
Ah okay... I thought we do this lowercasing somewhere... if this is an internal JDK thing it is indeed easier to use lowercase for our files.

**Comment by stefan-kolb** [comment]
This is caused by the missuse of the Locale class. See http://stackoverflow.com/questions/3318465/missingresourceexception-cant-find-bundle-for-base-name.

**Pull request closed without merging**
