### PR TITLE
Disable whole CiteSeer since it does not work as of 2024-05-20

### PR DESCRIPTION
**Pull request by koppor**
### Mandatory checks

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by koppor** [comment]
There is only one fetcher tests shown failing. Trying to get this fixed (so that all failing tests are shown)

**Comment by koppor** [comment]
This PR is marked as draft to investigate why only one failing fetcher test is displayed. There should be more fails.

Maybe refs https://github.com/JabRef/jabref/pull/9797 and https://github.com/JabRef/jabref/pull/11300

**Comment by koppor** [comment]
Before:

```
440 tests completed, 1 failed, 114 skipped
FAILURE: Executed 440 tests in 5m 50s (1 failed, 114 skipped)
```

After disablement of `maxParallelForks` 

    440 tests completed, 1 failed, 114 skipped

`main`:

    440 tests completed, 2 failed, 114 skipped

Thus, no change.

**Comment by koppor** [comment]
I will try to investigate gradle's behavior in https://github.com/JabRef/jabref/pull/11282

Thus, this is good to go.

**Review by Siedlerchr — APPROVED** [review]

**Pull request merged**
