### PR TITLE
Add assign-me-action

### PR DESCRIPTION
**Pull request by koppor**
We constantly get contributors wanting to have an issue assigned. To reduce the load, I propose the [assign-issue-action](https://github.com/takanome-dev/assign-issue-action). Contributors can then issue `/assign-me` and then they get assigned. Nice feature: After 30 days of inactivity, they get unassigned. (We can configure this time frame)

I also included text of our [newcomer text](https://github.com/JabRef/jabref/blob/main/.github/workflows/add-greeting-to-issue.yml).

Drawback: Our project boards are not updated accordingly. Filed as feature-wish to the action -> https://github.com/takanome-dev/assign-issue-action/issues/239

Alternative [`.take`](https://github.com/bdougie/take-action). Seems to have the same capabilities as the chosen action. Found via https://github.com/community/maintainers/discussions/447#discussioncomment-10756193.

Fixes https://github.com/JabRef/jabref-issue-melting-pot/issues/570

### Mandatory checks

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by HoussemNasri** [comment]
> Drawback: Our project boards are not updated accordingly. Filed as feature-wish to the action -> https://github.com/takanome-dev/assign-issue-action/issues/239

We could have it mention `@JabRef/developers` after assignment as a notification to manually update the project status?

**Comment by ThiloteE** [comment]
Only default Github Projects does not offer the feature of automatically update the project status upon assignment or pull-request. Maybe there is a GitHub action out there that can do it, but I have not been actively recently.

Problems I see with automatic assignment:

1. Students don't know how to trigger it.
2. Students will trigger it, even though other students are already assigned to a project.

I think it could be nice to know if somebody asks for assignment, that would make it much easier to focus on the assignment and I would not have to look at 100 other e-mails everyday just to find the ones that ask for an assignment.

I am in favour of a separate notification for people that ask for assignment. I am not in favour of automating assignment.

**Comment by ThiloteE** [comment]
Some issues have been tagged automatically, even though they are already assigned. What to do with it? Have you done this for testing?
image

**Comment by koppor** [comment]
> Some issues have been tagged automatically, even though they are already assigned. What to do with it? Have you done this for testing?

I assigned the label by hand. With that label in place, the student will get unassigned after 30 days. 😅

**Comment by koppor** [comment]
> Only default Github Projects does not offer the feature of automatically update the project status upon assignment or pull-request. 

Therefore, I posted the issue https://github.com/takanome-dev/assign-issue-action/issues/239.

> Maybe there is a GitHub action out there that can do it, but I have not been actively recently.

Maybe, even their API does not allow. Indication: [`gh issue edit`](https://cli.github.com/manual/gh_issue_edit) does not allow for setting states to a project.

> Problems I see with automatic assignment:
> 
>     1. Students don't know how to trigger it.

Thefore, I added it to the CONTRIBUTING.md.

image

https://github.com/JabRef/jabref/blob/add-assign-action/CONTRIBUTING.md

We still have the manual way to do it.

>     2. Students will trigger it, even though other students are already assigned to a project.

For this case, the action posts a comment posted when a user tries to assign themselves to an issue that is already assigned.

> I think it could be nice to know if somebody asks for assignment, that would make it much easier to focus on the assignment and I would not have to look at 100 other e-mails everyday just to find the ones that ask for an assignment.

This is more an LLM task to convert to "text" to "assign" or "NOOP". We could have an LLM running which posts `/assign-commenter` (refs https://github.com/takanome-dev/assign-issue-action/issues/240) in case it is sure the student asks for an assignmetn.
 
> I am in favour of a separate notification for people that ask for assignment. I am not in favour of automating assignment.

Let's discuss in the devcall. - I like most the unassignment feature of the action. For the assignment I tend to like to - to reduce load on our side.

**Comment by koppor** [comment]
> > Drawback: Our project boards are not updated accordingly. Filed as feature-wish to the action -> [takanome-dev/assign-issue-action#239](https://github.com/takanome-dev/assign-issue-action/issues/239)
> 
> We can have it mention `@JabRef/developers` after assignment as a notification to manually update the project status?

Too much noise for the developers. We could have another group `@JabRef/curators` (or `assigners`? or `maintainers`?) being notified.

> About the feature request, I don't think it is the responsibility of the assign-issue-action to update the project status, maybe a separate action would be responsible for listening for assignment status changes and acting on it. I don't know if it is possible though, I remember seeing @ThiloteE commenting on why it's not possible to automatically update project status.

It seems to lead to a complex GraphQL query: https://stackoverflow.com/a/77799377/873282

There is a kind of action moving in the precense of a label: https://github.com/marketplace/actions/move-issue-to-project-column. If the absence of a label also worked, it would be exactly what we search for.

---

Notes:

- [Project labeler](https://github.com/marketplace/actions/project-labeler) can only add/Remokve labels based on project itself.
- For claslsic projects, there is a kind of sync action: https://github.com/marketplace/actions/github-project-connect-action

**Comment by koppor** [comment]
DevCall: We try out.

**Review by calixtus — APPROVED** [review]

**Pull request merged**
