### PR TITLE
Update to UI: Remove some borders

### PR DESCRIPTION
**Pull request by tobiasdiez**
I tried to remove some 'clutter' in the UI by removing the gridlines and a few borders.
Before:
before
After:
after

### CODE REVIEW

**Comment by ThomasA** [comment]
I am not immediately convinced that this a good idea. I am afraid that it makes it harder to align various fields of each entry visually when looking over a large database.

**Comment by hakova** [comment]
Agreed with Thomas. Although it looks cleaner, for those of us who have
older eyes, it may get a little tricky not having the gridlines.


2015-05-11 12:57 GMT-05:00 Thomas Arildsen <notifications@github.com>:

**Comment by igorsteinmacher** [comment]
Is there a way to make is as an option in Preferences?

--
Igor Fabio Steinmacher, Ph.D.
Professor in Dept. of Computing at Universidade Tecnológica Federal do
Paraná

**Comment by mlep** [comment]
I had the same filling.
What about a gray strip every five entries?
(see attached file)

Frédéric

Le 11/05/2015 19:57, Thomas Arildsen a écrit :
> I am not immediately convinced that this a good idea. I am afraid that
> it makes it harder to align various fields of each entry visually when
> looking over a large database.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JabRef/jabref/pull/43#issuecomment-100998852>.
>

-- 
.......................................................
UR Science du Sol
INRA
2163 Avenue de la Pomme de Pin
CS 40001 - Ardon
F-45075 Orléans Cedex 2
France
  Ph:   +33 2 38 41 48 23
  Fax:  +33 2 38 41 78 69
  Email: <Frederic.Darboux@orleans.inra.fr>
  WebPage: <http://huit.re/DarbouxInraEn>
  Lab.: <http://www6.val-de-loire.inra.fr/ur-sols/>

**Comment by ThomasA** [comment]
I think it's a fine idea of it can be toggled in the preferences. 
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by tobiasdiez** [comment]
Ok, I will add an option to toggle the gridlines on and off. Originally, I also planned to add alternating background colors to better distinguish between rows. However, since JabRef also allows for marking entries, I doubt that this is a good approach.

**Comment by ThomasA** [comment]
I think you're right about the background colours. It could easily collide with marked entries.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mlep** [comment]
Also I am not a Java programmer (and may be because I am not...), I 
believe it may not be difficult to add some gray to every five lines to 
whatever is the color of the background (while, yellow, orange, red).


Frédéric

Le 11/05/2015 21:35, Tobias Diez a écrit :
> Ok, I will add an option to toggle the gridlines on and off. Originally,
> I also planned to add alternating background colors to better
> distinguish between rows. However, since JabRef also allows for marking
> entries, I doubt that this is a good approach.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JabRef/jabref/pull/43#issuecomment-101026697>.
>

-- 
.......................................................
UR Science du Sol
INRA
2163 Avenue de la Pomme de Pin
CS 40001 - Ardon
F-45075 Orléans Cedex 2
France
  Ph:   +33 2 38 41 48 23
  Fax:  +33 2 38 41 78 69
  Email: <Frederic.Darboux@orleans.inra.fr>
  WebPage: <http://huit.re/DarbouxInraEn>
  Lab.: <http://www6.val-de-loire.inra.fr/ur-sols/>

**Comment by tobiasdiez** [comment]
I added an option (under 'Appearance') to re-enable the gridlines. Moreover, it is now possible to change the row height.

**Pull request closed without merging**
