### PR TITLE
Simplify LO connection and fix threading errors

### PR DESCRIPTION
**Pull request by Siedlerchr**
Simplify LO connection

- [x] Test sucessful for mac

@LyzardKing  I simplified the LO connection. It's now enough to input the dir of the executable. JabRef now only calls the soffice.exe 
The jars are no longer needed.

Edit// Can you test if the connection to a snap LO or so is now possible?

- [ ] Change in CHANGELOG.md described (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by LyzardKing** [comment]
I'm testing the flatpak now.. it should work (like the latex editors..)
If I get that working I'll look at the snap, although for that it's a bit more complicated.
In the snap it's not possible to escape the confinement, so we'd need to set it to unconfined (classic)

**Comment by LyzardKing** [comment]
The flatpak JabRef works with the apt/rpm version of libreoffice.
Is it possible to set the default path to `/app/bin/soffice` in the flatpak?

**Comment by Siedlerchr** [comment]
@LyzardKing  I implemented an approach based on the [Env variable you suggested](https://discourse.jabref.org/t/jabref-snap-package-doesnt-work-on-ubuntu-20-04-18-04-cant-link-with-libreoffice/2460/5?u=siedlerchr).
to check if  `FLATPAK_SANDBOX_DIR` exists and then return the path `/app/bin/soffice`

Alternatively, we could add a variable e.g. `Linux_Variant` to the build.properties.

**Comment by LyzardKing** [comment]
@Siedlerchr I'll test in the next few days, but this should be enough to have (from the next release) a flatpak that works out of the box with libreoffice/browsers/tex editors

**Review by tobiasdiez — COMMENTED** [review]
Can the OO jars now also be removed from the gradle file?

**Comment by Siedlerchr** [comment]
> Can the OO jars now also be removed from the gradle file?

No! The only change is that we no longer need to load the jars from the libre office directory while we already need them for building and running (like other libraries). 
That is why I adjusted the LO bootstrap 
In addition, I fixed some threading errors for error messages.

**Review by koppor — APPROVED** [review]

**Pull request merged**
