### PR TITLE
 Change the popup to enter types to the combo box for custom entry types

### PR DESCRIPTION
**Pull request by LoayGhreeb**
Implemented task 3 from #10560. 

preview

Disabled the add field button if the entry type is not selected to prevent exceptions.

image

### Mandatory checks

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [x] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Review by Siedlerchr — DISMISSED** [review]
LGTM! Thanks for the improvement

**Comment by LoayGhreeb** [comment]
Apologies for the confusion, merged the main by mistake

**Comment by Siedlerchr** [comment]
No problem and often a good way to resolve conflicts early on
In end all commits are squashed together

Loay Ghreeb ***@***.***> schrieb am Sa., 24. Feb. 2024, 15:09:

**Review by Siedlerchr — APPROVED** [review]

**Review by calixtus — APPROVED** [review]

**Comment by LoayGhreeb** [comment]
@Siedlerchr, I want to add this change to the changelog file, I forgot to add it.

- We enhanced the dialog for adding new fields in the content selector with a selection box containing a list of standard fields.

**Comment by calixtus** [comment]
Fixed it.

**Pull request merged**
