### PR TITLE
Update IEEEJournalList

### PR DESCRIPTION
**Pull request by Ede123**
Update for `IEEEJournalListCode.txt` and `IEEEJournalListText.txt` compiled from [IEEEfull.bib](http://tug.ctan.org/tex-archive/macros/latex/contrib/IEEEtran/bibtex/IEEEfull.bib) and [IEEEabrv.bib](http://tug.ctan.org/tex-archive/macros/latex/contrib/IEEEtran/bibtex/IEEEabrv.bib) respectively.

### CODE REVIEW

**Comment by Siedlerchr** [comment]
Thank you very much for your contribution. I am not an expert in the IEEE Abbrev codes but to me it looks good.

**Comment by lynyus** [comment]
Would it be advisable to write an automated script that fetches those lists automatically before each release?

**Comment by Ede123** [comment]
The files were last changed 2015/08/28. Probably not be worth the effort...

**Comment by koppor** [comment]
Thank you for the PR! I think, syncing it with existing lists, is a very good idea!

Is there a script you wrote or is it manual effort? 🌞

**Comment by Ede123** [comment]
No, half-auto using regex and Notepad++

**Pull request merged**
