### PR TITLE
Snapcraft: set version from new xml file

### LINKED ISSUE #7022: Snap build no longer working
From the action: 

> Downloading 'JabRef-5.2-portable_linux.tar.gz'   0%                            
> Downloading 'JabRef-5.2-portable_linux.tar.gz' 100%                            
> Failed to generate snap metadata: 'adopt-info' refers to part 'jabref', but that part is lacking the 'parse-info' property.
> Run the same command again with --debug to shell into the environment if you wish to introspect this failure.
> Error: The process '/usr/bin/sg' failed with exit code 2

https://forum.snapcraft.io/t/failed-to-generate-snap-metadata-adopt-info-refers-to-part-synfig-studio-but-that-part-is-lacking-the-parse-info-property/18733/11
https://github.com/JabRef/jabref/runs/1262693776?check_suite_focus=true

### PR DESCRIPTION
**Pull request by LyzardKing**
Fix #7022 
A change in jpackage has moved the version to an xml file.
We can parse that to read the version and set it in the snap package

- [ ] Change in CHANGELOG.md described (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by LyzardKing** [comment]
@Siedlerchr The error in the CI is the upload part, the snap built succesfully (and set the version)

**Comment by Siedlerchr** [comment]
Yep I saw it. It's probably just a github secret thing which is not avaiable when non org members run the workflows. Nontheless, I added the switch to the image options  in build.gradle to see if the cfg file then contains again the versinn number.

**Comment by LyzardKing** [comment]
As long as there's one file that we can parse it's fine.

**Comment by Siedlerchr** [comment]
My fix attempt didn't help, but yours work so I merge

**Pull request merged**
