### PR TITLE
Library properties: no change but... #3562

### PR DESCRIPTION
**Pull request by PJozeph**
----

- [ ] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [ ] Screenshots added (for bigger UI changes)
- [ ] Manually tested changed features in running JabRef
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)
- [ ] If you changed the localization: Did you run `gradle localizationUpdate`?

### CODE REVIEW

**Comment by Siedlerchr** [comment]
For the next time, you should better create a branch where you commit the changes, so you don't have all the changes from your previous work. 

You should include a short description and to make your and our life easier, please use the issue in the description. In the title github can't find it.
See here for general information for a PR.
https://github.com/JabRef/jabref/blob/master/CONTRIBUTING.md

**Comment by PJozeph** [comment]
next time i will proceed like that

**Comment by PJozeph** [comment]
or do you want to me to resubmit this, as it it needed ?

**Comment by tobiasdiez** [comment]
Yes, please resubmit the PR or at least remove the previous changes related to the file extensions. You can use [git cherry-pick](https://git-scm.com/docs/git-cherry-pick) to reuse your commit, so this should be easy.

**Pull request closed without merging**
