### PR TITLE
Readd ACM style to csl

### PR DESCRIPTION
**Pull request by Siedlerchr**
JabRef searches this style when opening the preferences

Follow up fix for https://github.com/JabRef/jabref/pull/7306

- [ ] Change in CHANGELOG.md described (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by calixtus** [comment]
Why the acm style in particular? Could this maybe a config issue?

**Review by calixtus — APPROVED** [review]

**Comment by koppor** [comment]
Damn, did not see the PR while working on a fix at https://github.com/JabRef/jabref/commit/8c49600df0e714f4806e4a4d2cf3702994d8ec3b.

**Comment by Siedlerchr** [comment]
URL url = CitationStyle.class.getResource(STYLES_ROOT + "/acm-siggraph.csl");

**Comment by koppor** [comment]
Digging deeper:

@Siedlerchr spottet that at https://github.com/JabRef/jabref/pull/7306#issuecomment-756048759 that https://github.com/JabRef/jabref/blob/8c49600df0e714f4806e4a4d2cf3702994d8ec3b/src/main/java/org/jabref/logic/citationstyle/CitationStyle.java#L137

It was a decision at https://github.com/JabRef/jabref/pull/6010 to hard-code one specific `.csl` file to check whether CSL loading actually works. See especially the file-diff.

**Pull request closed without merging**
