### PR TITLE
[WIP] Testing bibtex key patterns and fixing title_case/capitalize modifiers

### PR DESCRIPTION
**Pull request by RolfStarre**
Related to https://github.com/koppor/jabref/issues/237
I'm working on adding tests for key patterns + key patterns in combination with modifiers.

I found out why the title_case and capitalize modifiers didn't work with shorttitle. It went wrong because before the modifier was applied the shorttitle was already a concatenated string, so the formatter would just see it as a single word.
For example if we have the title "An Awesome Paper on JabRef", it would first turn into "AnAwesomePaper", and then the modifier would turn it into "Anawesomepaper".

- [ ] Change in CHANGELOG.md described
- [x] Tests created for changes
- [ ] Screenshots added (for bigger UI changes)
- [ ] Manually tested changed features in running JabRef
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)
- [ ] If you changed the localization: Did you run `gradle localizationUpdate`?

### CODE REVIEW

**Comment by Siedlerchr** [comment]
Just as an idea, maybe you can check if you could include that feature request here?
https://github.com/JabRef/jabref/issues/457

**Comment by RolfStarre** [comment]
@Siedlerchr I've made a first attempt at adding the feature ^_^

**Comment by RolfStarre** [comment]
I have a problem with testing the regexFormatter, it doesn't take protected parts of a sentence into account. 

I don't really know how I can write the code so that it does take the protected characters into account, since it currently only seems to be done on a letter by letter basis.

**Comment by Siedlerchr** [comment]
Maybe anyone of the other @JabRef/developers  has an idea on how to check that

**Comment by koppor** [comment]
@tobiasdiez Maybe you have an idea?

**Comment by tobiasdiez** [comment]
Sorry, I've no deep knowledge about regular expressions in particular and about the formatters in general.

**Comment by koppor** [comment]
I understand the question https://github.com/JabRef/jabref/pull/2663#issuecomment-287796215 as follows:

If I replace regex `a` by `X` and I apply it at `abc{abc}`, the result is `Xbc{Xbc}`, but it should be `Xbc{abc}`.

As one cannot change the regex engine, I would `{...}` replace by something not matched by the regular expression, then apply the regex and then change it back.

1. Replace protected terms
1a. Replace first `{...}`by [unicode character 2580](https://unicode-table.com/de/#2580)
1b. Replace second `{...}`by [unicode character 2581](https://unicode-table.com/de/#2581)
1.c etc.
2. Apply regex
3. replace back

**Comment by koppor** [comment]
Closing this issue due to inactivity :zzz: 

@shitikanth will take over in another PR, because it is unlikely, that we get access to https://github.com/delftswa2017/jabref

**Pull request closed without merging**
