### PR TITLE
Fixed #545 - ACM fetcher works again

### LINKED ISSUE #545: JabRef 3.0: ACM Fetcher: Cannot parse number of hits
When I do a search in the ACM in JabRef (no matter which one ), I get the following error.
```
java.io.IOException: Cannot parse number of hits
	at net.sf.jabref.importer.fetcher.ACMPortalFetcher.getNumberOfHits(ACMPortalFetcher.java:427)
	at net.sf.jabref.importer.fetcher.ACMPortalFetcher.processQueryGetPreview(ACMPortalFetcher.java:136)
	at net.sf.jabref.importer.fetcher.GeneralFetcher$3.run(GeneralFetcher.java:241)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

### PR DESCRIPTION
**Pull request by oscargus**
Fixed #545 and some PMD cleanup.

### CODE REVIEW

**Comment by lenhard** [comment]
I just tried to check if this is fixed, but I am still getting the error:

```
java.io.IOException: Cannot parse number of hits
	at net.sf.jabref.importer.fetcher.ACMPortalFetcher.getNumberOfHits(ACMPortalFetcher.java:400)
	at net.sf.jabref.importer.fetcher.ACMPortalFetcher.processQueryGetPreview(ACMPortalFetcher.java:134)
	at net.sf.jabref.importer.fetcher.GeneralFetcher$3.run(GeneralFetcher.java:241)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:744)
```
The exception is thrown, since the matcher seems to find no match. Maybe `getNumberOfHits` should return zero in this case instead of throwing the exception?

**Comment by oscargus** [comment]
Ahh, that's right. Final fix: "let's remove all the checking as I have much better regexps now...". Not sure it I'll start up Eclipse again today, but I'll take care of it. :-)

**Comment by lenhard** [comment]
Sounds good :smile: And no need to hurry, there are enough other pull requests to review.

**Comment by oscargus** [comment]
Should be good to go now.

**Comment by lenhard** [comment]
Confirmed, works for me as well. Thanks a lot!

**Pull request merged**
