### PR TITLE
Fixes build for OSX #1481

### LINKED ISSUE #1481: Mac OS X binary seems broken for JabRef 3.4 release
I downloaded JabRef 3.4 binary from JabRef homepage and  tried to start Application by double click on El Capitan with java 1.8. The leftmost menu "JabRef" appears, but other menus don't appear and the program cannot be quitted.

At this stage, running 'ps ax | grep JabRef' gives 'path/to/JabRef.app/Contents/MacOS/JavaApplicationStub' so I tried to run it from the command line. Then it emits following stderr:
> JavaApplicationStub[3373:64431] Apple AWT Startup Exception: Cannot lock focus on image <NSImage 0x11bf59070 Size={0, 0} Reps=()>, because it is size zero.
> JavaApplicationStub[3373:64431] Apple AWT Restarting Native Event Thread

The program runs successfully if it is run manually by "java -jar path/to/JabRef.app/Contents/java/app/JabRef-3.4.jar".

### PR DESCRIPTION
**Pull request by chochreiner**
Fixes #1481
The metadata of the logo was broken which caused Jabref to be stuck at startup on OSX.

### CODE REVIEW

**Comment by stefan-kolb** [comment]
Hm, thanks for your fix! How did you correct this? I just automatically created the icon files with some tool.

**Comment by matthiasgeiger** [comment]
:+1: Thanks for fixing!

@JabRef/developers shall we release 3.4(.1) for Mac OS X?

**Comment by chochreiner** [comment]
I restored the old "JabRef-icon-mac.icns" file - Maybe this tool deletes some OSX specific metadata, because I also had some problems modifying the new file, because it had a dimension of 0x0 instead of 512x512

**Comment by matthiasgeiger** [comment]
Okay... Stefan tries to recreate a valid *.icns file with the "standard logo" which should be used.

**Comment by stefan-kolb** [comment]
Okay I used Greenfish icon editor. Just exported as Mac icon file...

**Comment by stefan-kolb** [comment]
@chochreiner Can you try this icon file and amend it in your branch if it is working?
[jabref.zip](https://github.com/JabRef/jabref/files/306924/jabref.zip)

**Comment by chochreiner** [comment]
works fine

**Comment by stefan-kolb** [comment]
Thank you again Christoph :smile:

**Pull request merged**
