### PR TITLE
Improve VSCode config

### PR DESCRIPTION
**Pull request by tobiasdiez**
- Add gradle extension
- Add basic vscode config for checkstyle and formatting

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by tobiasdiez** [comment]
@Siedlerchr can you please export the eclipse code formatter config as xml and add it here? Thanks!

> Eclipse's Preferences → Java → Code Style → Formatter and export the settings to an XML file via the Export All button (or Edit and then Export in dialog that opens up)

**Comment by Siedlerchr** [comment]
The key problem is that the eclipse code formatter is still not compatible with intelij regarding indentation. This will create chaos if people start using it

**Comment by tobiasdiez** [comment]
So how do you format your code then in eclipse?

**Comment by Siedlerchr** [comment]
I try to not format my code in Eclipse, at least I only execute it for a method or so and manually fix the indentation afterwards. The problem is that for wrapped lines I haven't found a way.
I uploaded the current generated style

[jabref2.xml.txt](https://github.com/JabRef/jabref/files/9727814/jabref2.xml.txt)

**Comment by tobiasdiez** [comment]
Thanks, it's not perfect as you say, but better than nothing.

**Pull request merged**
