### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by oscargus**
* Removed Codacy warnings sloppily introduced in TextInputDialog

### CODE REVIEW

**Comment by tobiasdiez** [comment]
Mhh. I'm against reintroducing FormatChars as a class. Reasoning:
- I don't like the name at all and it is not obvious what a `FormatChars` - formatter does.
- Even if we would like to support FormatChars for backwards compatibility, then there are better solutions for that. Just insert a corresponding if statement in `LayoutEntry.getLayoutFormatterByClassName` (and even better, remove the reflection stuff completely).

**Comment by oscargus** [comment]
Ok, as long as it works next Friday anything goes for me...

**Comment by oscargus** [comment]
Regarding naming I conceptually agree but it's been around for 10+ years so... (even before Unicode was well established) Legacy etc...

**Comment by oscargus** [comment]
I removed the FormatChars part and put it in #1114 so that there is a quick fix available before the release...

**Pull request merged**
