### PR TITLE
Place subgroups w.r.t. alphabetical ordering

### PR DESCRIPTION
**Pull request by 0x002A**
Fixes https://github.com/koppor/jabref/issues/577

Additionally, resorting when changing the group name is implemented accordingly.

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [x] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Review by calixtus — COMMENTED** [review]
Codewise looks good to me

**Comment by 0x002A** [comment]
I just fixed a reference in the changelog. Now it’s really ready for merge from my side

**Review by Siedlerchr — APPROVED** [review]
Thanks again!

**Comment by koppor** [comment]
Does this PR check the condition "In case the group sub tree is sorted alphabetically"? I did not see it in the code.

**Pull request merged**
