### PR TITLE
Move OS to logic util to fix architecture test

### LINKED ISSUE #6697: Failing architecture tests
Just as to remind that this is known, but not yet fixed.

We cannot fix it today, but hopefully a PR will come in soon.

```text
Test 10 -- is org.jabref.model independent of org.jabref.logic? FAILED

  org.opentest4j.AssertionFailedError: The following classes are not allowed to depend on org.jabref.logic ==> expected: <[]> but was: <[src/main/java/org/jabref/model/cleanup/NormalizeNewlinesFormatter.java]>
      at org.jabref@100.0.0/org.jabref.architecture.MainArchitectureTests.firstPackageIsIndependentOfSecondPackage(MainArchitectureTests.java:110)
```

### PR DESCRIPTION
**Pull request by Siedlerchr**
Fixes #6697

- [ ] Change in CHANGELOG.md described (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by tobiasdiez** [comment]
Having OS in model is ok for me, but why is the newlines formatter in model in the first place? All other cleanup ops are in logic (and belong there in my opinion). It becomes less and less clear where the boundary is. Probably something for the next devcall.

**Comment by Siedlerchr** [comment]
It all started with a simple line check . That changes created a mountain of work in chain reaction.
https://github.com/JabRef/jabref/blob/b264918135a30e50acb146734b4b322ca5ce4ec5/src/main/java/org/jabref/model/cleanup/FieldFormatterCleanup.java#L58-L61

This introduced the original error. model cannot depend on logic. However, now I am in the bad situation that those Cleanups are used in Metadata and therefore in model. So I can't move it up to logic without killing the whole model.
That's why I tried to move it down to model. At least that one Formatter. But that talks to OS.Newline and L10n.  SO I had to put OS down to model as well.
Argh!

**Comment by koppor** [comment]
The referenced code relates to https://github.com/koppor/jabref/issues/390. Thus, in the concrete case, this condition is a hack (fixing the cursor jumping), but not the underlying issue.

Thus, I would add an exception to the architecture tests for the release, revert it after the release and do a real fix at JabCon.

**Comment by tobiasdiez** [comment]
Surpassed by #6825

**Pull request closed without merging**
