### PR TITLE
Add jabfox json file to snap package

### PR DESCRIPTION
**Pull request by LyzardKing**
This PR adds a hook that copies the json needed for the jabfox plugin
in /usr/lib/mozilla/native-messaging-hosts
To do that it needs a special permission that would need to be granted on the snapcraft forum.
This has been discussed with @tobiasdiez 
The user would need to type (I chose the name of the plugin, it can be changed):
`snap connect jabref:jabfox-integration`
If the folder in which it needs to copy the json file does not exist it will print an error message:
```
Missing directory, create it manually then try again:
sudo mkdir -p /usr/lib/mozilla/native-messaging-hosts
```
----

- [ ] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [ ] Manually tested changed features in running JabRef
- [ ] Screenshots added in PR description (for bigger UI changes)
- [ ] Ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)

### CODE REVIEW

**Comment by Siedlerchr** [comment]
Looks good, thanks, could you please add a link to your question on the snapcraft forum so that the information does not get lost-

**Comment by LyzardKing** [comment]
Also, @tobiasdiez , should the json file be removed on uninstall/disconnect of the interface?
The problem might be an interference if someone installs more than one version, but it might be more clean to do a full remove on an uninstall..
What do you think?

**Comment by LyzardKing** [comment]
I changed the name to browser-extension and added a disconnect hook, so that if you uninstall, IF the file was not overridden it will remove it

**Comment by koppor** [comment]
Refs #3121

**Pull request merged**
