### PR TITLE
Fix Codacy Unused Params, Fields

### PR DESCRIPTION
**Pull request by LinusDietz**
follow up of https://github.com/JabRef/jabref/pull/3724

### CODE REVIEW

**Comment by LinusDietz** [comment]
on hold to mitigate merge conflicts in other PRs.

**Comment by tobiasdiez** [comment]
@LinusDietz You can also use the maintable-beta branch as the base for this PR.

**Comment by lenhard** [comment]
Rebasing this on maintable-beta sounds like a fine idea! And if you want to do more Codacy PRs on master, just make sure that they are limited to model or logic.

**Comment by LinusDietz** [comment]
@tobiasdiez I have merged maintable-beta into this to fix the conflicts. I think it can be merged now. The failing tests are the same as in the base branch.

**Comment by Siedlerchr** [comment]
You could just fix the one checkstyle issue in the ActionFactory (unused import)

**Comment by LinusDietz** [comment]
@Siedlerchr That was part of the base branch. I fixed it there.

**Comment by LinusDietz** [comment]
I guess here we can squash them.

**Pull request merged**
