### PR TITLE
Use JavaFX EA builds from web page

### PR DESCRIPTION
**Pull request by koppor**
On maven central, the JavaFX EA builds are not updated regularly. The web page https://jdk.java.net/javafx23/ is.

The Gradle OpenJFX plugin [allows to use a local SDK](https://github.com/openjfx/javafx-gradle-plugin?tab=readme-ov-file#5-using-a-local-javafx-sdk). We make use of this possibility.

This PR changes the matrix from downloading from maven central to download the JDK from the JavaFX EA page.

### Mandatory checks

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by koppor** [comment]
The pipeline says:

```
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find :javafx.base:.
     Searched in the following locations:
       - file:/home/runner/work/jabref/jabref/javafx/javafx-sdk-23/lib/javafx.base.jar
     Required by:
         project :
```

On my local machine (Windows 10), it runs. Don't know, how to resolve.

**Comment by Siedlerchr** [comment]
Could be a problem if the jdk already contains javafx libraries

**Comment by koppor** [comment]
I switched from Liberica (the version without (!) JavaFX) and Oracle's JDK (used for building) to Temurin for both (running gradle and building JabRef). No change.

**Comment by koppor** [comment]
The reason for the error was that I downloaded the JavaFX JDK **before** the `git pull` in a directory **inside** the code. Changed the order - and now, it works.

**Comment by koppor** [comment]
arm uses the distribution from maven central, because there is no linux-arm build available at https://jdk.java.net/javafx23/ (but at maven central). The script uses the latest version returned by the API.

**Comment by koppor** [comment]
I removed support for building with JDK23. I think, it is OK for now - or should I try to include it again? -- I need to have gradle having creating JDK22 bytecode, but use JDK23 as toolchain. (Currently, we use JDK21 as target language target)

**Review by Siedlerchr — APPROVED** [review]

**Pull request merged**
