### PR TITLE
[WIP] German translation fix java fx

### PR DESCRIPTION
**Pull request by mairdl**
This PR is a follow up of https://github.com/JabRef/jabref/pull/1988.

The German translation of JabRef has some issues, have a look at the following screenshot:

file-open

The function to open a database is called `Datei öffnen` the displayed hotkey is `F4`. In the English version of JabRef the file menu looks like this:

openfilemenu

As you can see the right hotkey for this function should be` CTRL + O`. Also, the word database gets translated as `Datei` instead of `Datenbank`.

This PR aims to fix this issue by rewording the translation. Every English occurrence of `database `is now translated as `Datenbank`. This is what it looks like now:

openfilemenu

- [x] Change in CHANGELOG.md described
- [x] Screenshot for changes
- [x] Manually tested changed features in running JabRef
- [ ] internal qs

### CODE REVIEW

**Comment by koppor** [comment]
@mairdl Please explain why this is a follow up. Do not copy and paste the old PR text. This makes it very hard to review. Further, you have way too much commits in your PR. Please always use `gitk --all` to check your commits.

**Comment by mairdl** [comment]
Resolved the issue of too much commits

**Comment by mairdl** [comment]
@koppor isn't the "old" PR text the reason why this is a follow up for the javafx branch?

**Comment by koppor** [comment]
Your PR text does NOT indicate, that the issue is solved in `master`, but not in `javafx`. You should have simply merged your `GermanTranslationFix` to `javafx` and check whether everything works fine. I did that (since your PR is merged, I just had to merge `master` into `javafx`). It turned out: Everything works fine.

Thus, this PR is obsolete.

**Pull request closed without merging**
