### PR TITLE
Fix libraries not being remembered when an unsaved library is discarded upon closing JabRef

### LINKED ISSUE #9190: JabRef forgets opened libraries
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

JabRef 5.8--2022-09-29--fca9fb9 Linux 5.10.0-18-amd64 amd64  Java 18.0.2.1  JavaFX 19+11

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. open a (pre-existing) library (e.g. https://github.com/JabRef/jabref/blob/main/src/test/resources/testbib/jabref-authors.bib)
2. create a new library (e.g. `File -> New library`)
3. edit a bit this new library (e.g. add/paste an entry)
4. close JabRef (e.g. `File -> Quit`)
_At this point, a window entitled "Save before closing" is displayed._
5. select `Discard changes`
_JabRef closes_
6. open JabRef
Bug: No library is displayed, while the pre-existing one (e.g. jabref-authors.bib) should be.

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

### PR DESCRIPTION
**Pull request by tomnguye**
Fixes #9190 

Made it so that when closing the app if the focused database is not saved look for the first saved open database to set as focused.

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [x] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by koppor** [comment]
Seems like a (working) quick fix, but not solving the underlying issue. Maybe, the direction is more into the listeners. See https://github.com/JabRef/jabref/pull/9238 for a discussion.

**Comment by tomnguye** [comment]
I think I need more information to go off of here. Could you describe how my implementation misses the underlying issue? otherwise what event do you feel requires listening?

**Comment by tomnguye** [comment]
I've made a change to the 'focused library' event listener that I hope better addresses the issue. Please point out if the revised fix has any issues

**Comment by koppor** [comment]
What happens at step 6 with your fix?

grafik

Maybe you can upload a video using [Loom](https://www.loom.com/)

**Comment by koppor** [comment]
This PR doesn't seem to fix the issue. See new comments at https://github.com/JabRef/jabref/issues/9190#issuecomment-1358239557.

**Pull request closed without merging**
