### PR TITLE
ISSUE-9145: implement isbn fetcher 

### LINKED ISSUE #9145: Implement an ISBN Fetcher for book-info.com
**Is your suggestion for improvement related to a problem? Please describe.**
Some ISBNs like 3-85869-197-6 and 3-549-05585-4 cannot  be found on OpenLibrary or Ebook.de

**Describe the solution you'd like**
Add book-info.com as a third fallback source for checking ISBN Data.

**Additional context**
The HTML needs to be parsed. Seems pretty straightforward to parse the data with jsoup
https://www.book-info.com/isbn/84-08-08890-4.htm

### PR DESCRIPTION
**Pull request by ezienecker**
Implemented a new ISBN Fetcher (doi-to-bibtex-converter.herokuapp.com). 

[Fixes #9145](https://github.com/JabRef/jabref/issues/9145)

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [x] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by ezienecker** [comment]
When I run the following command "./gradlew fetcherTest" locally on the `main` branch I get 29 test fails. I think my gradle configuration (or something else is broken). It makes no sense to work further on this task. Therefore I close this pull request.

**Comment by ezienecker** [comment]
@Siedlerchr Can you please tell me where to find the codestyle file so I can fix the checkstyle?

**Comment by HoussemNasri** [comment]
Hi, @ezienecker. Check out this link to learn how to configure JabRef code style in your environment. Once everything is in place, your IDE will start highlighting checkstyle errors and format the code according to JabRef style.

**Comment by ezienecker** [comment]
@HoussemNasri Thanks for pointing that out, it worked now.

From my point of view, the feature is complete. The tests in the places in the code where I have anticipated work. I have not worked on org.jabref.logic.importer.fetcher.CrossRefTest. I don't know why the test fails.

**Comment by calixtus** [comment]
Thanks for your contribution. Please excuse some delays. We are these days a bit busy with our day jobs, but we promise to look into it as soon as possible.

**Review by calixtus — COMMENTED** [review]
Looks good to me

**Comment by calixtus** [comment]
Thanks for your great addition to JabRef! Looking forward to see more 😄

**Comment by ThiloteE** [comment]
Post merger feedback:

`Fixes #9145`: Will close the issue automatically
`[Fixes #9145](https://github.com/JabRef/jabref/issues/9145)`: will **not** close the issue automatically


See GitHub documentation: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

> <h2 id="linking-a-pull-request-to-an-issue-using-a-keyword">Linking a pull request to an issue using a keyword</h2>
> <p>You can link a pull request to an issue by using a supported keyword 
> in the pull request's description or in a commit message. The pull 
> request <strong>must be</strong> on the default branch.</p>
> <ul>
> <li>close</li>
> <li>closes</li>
> <li>closed</li>
> <li>fix</li>
> <li>fixes</li>
> <li>fixed</li>
> <li>resolve</li>
> <li>resolves</li>
> <li>resolved</li>
> </ul>
> <p>If you use a keyword to reference a pull request comment in another 
> pull request, the pull requests will be linked. Merging the referencing 
> pull request also closes the referenced pull request.</p>
> <p>The syntax for closing keywords depends on whether the issue is in the same repository as the pull request.</p>

**Comment by koppor** [comment]
We needed to disable the fetcher, because the site is down. See https://github.com/JabRef/jabref/pull/9465.

**Comment by koppor** [comment]
@ezienecker As of today, <https://doi-to-bibtex-converter.herokuapp.com> shows 404. Do you have contact to that information provider?

**Comment by ezienecker** [comment]
@koppor no, I don't know him. I think we have to remove this feature.

**Comment by koppor** [comment]
@ezienecker Thank you for letting me know. We already disabled it. I had the slight hope that we could probaly resurrect the feature.

**Pull request merged**
