### PR TITLE
Preferences ui cleanup

### PR DESCRIPTION
**Pull request by calixtus**
- introduced web search tab
grafik
- renamed Import and Export tab to Export tab
grafik
- moved remaining content to entry tab, refined ui (reduced vertical space, added indentation)
grafik
- removed files tab
- removed unused code (TagBar / Tag, DiffHighlightingTextPane)

.

```[tasklist]
### Compulsory checks
- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.
```

### CODE REVIEW

**Comment by koppor** [comment]
Reorganization also relates to https://github.com/JabRef/jabref/pull/9836/.

**Comment by koppor** [comment]
We have "Always reformat BIB file on save and export". Should we a) keep this setting both in "Library"/"File"/"General" and in "Export" or should we b) split it into "Always reformat BIB file on save" and "Always reformat BIB file on export". I lean to the former. But then, the UI setting appears in two different tabs. Hopefully, they are synchronized!

**Comment by calixtus** [comment]
I removed the files tab. So the autosave setting should not appear twice.

**Comment by Siedlerchr** [comment]
Oh no please not, my other PR is using the files tab

**Comment by calixtus** [comment]
Should not be a big deal to fix the merge conflicts

**Comment by koppor** [comment]
> I removed the files tab. So the autosave setting should not appear twice.

It is about **reformatting**, not saving. 😅

Saving is only concerning the library, but reformatting both the library (.bib) and export (as .bib).

**Comment by calixtus** [comment]
I will make a follow up PR introducing a library tab. But I think it will be too much for this PR as I already changed 42 files with this one.

**Review by koppor — APPROVED** [review]

**Comment by calixtus** [comment]
Thx for #

**Pull request merged**
