### PR TITLE
Remove all @author comments and empty method/class comments

### PR DESCRIPTION
**Pull request by koppor**
This removes all `@author` patterns as we do not track author ship by these annotations, but with the version control system git.

Some other obsolete headers were also removed (e.g., `$Id`).

### CODE REVIEW

**Comment by Siedlerchr** [comment]
I would propose you take the maintable-beta branch as base branch, otherwise we will be getting tons of conflicts

**Comment by koppor** [comment]
For users of IntelliJ, there is a cool dialog helping to resolve conflicts. 🌞 I'll however based it again on the maintable-beta branch.

grafik

**Comment by Siedlerchr** [comment]
For merging I stick to http://meldmerge.org/

**Comment by Siedlerchr** [comment]
Please fix conflict and checkstyle error:;
:checkstyleMain[ant:checkstyle] [ERROR] /home/travis/build/JabRef/jabref/src/main/java/org/jabref/logic/layout/format/CurrentDate.java:21: 'METHOD_DEF' has more than 1 empty lines before. [EmptyLineSeparator]

**Comment by koppor** [comment]
I don't know, why Travis fails:

```
  JUnit Jupiter:LocalizationTest:testUnsetLanguageTranslation()
    MethodSource [className = 'org.jabref.logic.l10n.LocalizationTest', methodName = 'testUnsetLanguageTranslation', methodParameterTypes = '']
    => org.opentest4j.AssertionFailedError: expected: <&Groups> but was: <Groups>
       org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:52)
       org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
       org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:186)
       org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:181)
       org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:486)
       org.jabref.logic.l10n.LocalizationTest.testUnsetLanguageTranslation(LocalizationTest.java:95)
       sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
       sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       java.lang.reflect.Method.invoke(Method.java:498)
       [...]
```

I think, I only changed comments?!

**Comment by koppor** [comment]
The errors are from the maintable-beta branch (see https://travis-ci.org/JabRef/jabref/jobs/360715639). So, I just merge to move forward.

**Pull request merged**
