### PR TITLE
Keep group pane size when resizing window (#6180)

### LINKED ISSUE #6180: Groups panel does not keep size when resizing window
JabRef version 
```
JabRef 5.1--2020-03-23--67daf36
Linux 5.4.0-4-amd64 amd64 
Java 14
```
Debian bullseye/sid with i3 window manager.

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

Before, the groups panel would stay at it's size when the window is resized.
Now, it seems to scale proportionally with the whole window.
This is especially annoying when a tiling window manager is used and you open a PDF next to jabref: in this case the groups panel scales to about 50% of the whole window.

1. resize jabref window
2. groups panel scales proportionally instead of keep size

### PR DESCRIPTION
**Pull request by Hollyqqqqq**
Fixes #6180

Hello, I think I have fixed this bug. The main reason for this bug is group pane is resizable with parent(window size). I add one line in **JabRefFrame.java** to set group pane not resizable with parent. Thus it can keep size when resizing window. The following is manual test:

Before resizing window:
image

After resizing window:
image

- [x] Change in CHANGELOG.md described (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by Hollyqqqqq** [comment]
Thanks! But I don't understand what is the meaning of "it does not make sense to put them together". Put what together?

In fact, keeping group size when resizing window is similar to `project pane` of IntelliJ IDEA. In IDEA, project pane keeps size when resizing window. If it doesn't keep size, the following behavior will occur:
image
Since group pane only need to display group tree, it doesn't need too much space when resizing window and we need to resize group pane manully if this happens. Thus I think keeping size when resizing window has its utility.

What's more, in IDEA, it has scroll bar for project pane if the window size is too small.
image

I think this behavior can also be involved in JabRef. If this point can be agreed, I'd like to create a new issue about this and work for it.

**Comment by Siedlerchr** [comment]
@Hollyqqqqq  
>Thanks! But I don't understand what is the meaning of "it does not make sense to put them together". Put what together?

Sorry for the misunderstanding, I was meaning that you are right, a separation of the group reisze and the parent window resize is better.
You could also try to add the scrollbars in your PR as well or create a new one.

**Comment by Hollyqqqqq** [comment]
OK, I see. Thank you very much!

**Comment by Hollyqqqqq** [comment]
Yes, user can still resize the sidepane manually. And I have added the change log in CHANGELOG.md.

**Pull request merged**
