### PR TITLE
Minor improvements to the JavaFX about dialog

### PR DESCRIPTION
**Pull request by boceckts**
Follow up of #1959.
@bartsch-dev had a great idea to use his `Version` class to get the changelog url since it already provides a method for it. I only adjusted it slightly so dev versions will be redirected to https://github.com/JabRef/jabref/blob/master/CHANGELOG.md#unreleased. Links will also stay gighlighted after they have been visited.

normal version

for snapshot versions a new label will be added for the complete version string.
snapshot

- [ ] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [x] Screenshots added (for bigger UI changes)
- [x] Manually tested changed features in running JabRef
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)

### CODE REVIEW

**Comment by tobiasdiez** [comment]
I think the "License: " prefix is not really necessary. "MIT license" is already self-explanatory.  @koppor do you really want this?

**Comment by boceckts** [comment]
@tobiasdiez I get the version string from `Globals.BUILD_INFO.getVersion();` do you only want to remove "snapshot" in the about dialog or in general? For example copy version also calls the same method.

**Comment by Siedlerchr** [comment]
Like the idea with the VersioInfo solution! :+1: 
Is commit included?

**Comment by grimes2** [comment]
"snapshot" is part of the builds delivered by builds.jabref.org.
For example:

> JabRef 3.7dev--snapshot--2016-09-12--javafx--bd3dbe8
> windows 10 10.0 amd64 
> Java 1.8.0_101

The complete version string should be shown somewhere in the About dialog.  Does the text wrap work also for this long string without whitespace?

**Comment by boceckts** [comment]
@grimes2  yes it will automatically be broken down to fit multiple lines.

longversion

**Comment by tobiasdiez** [comment]
Ok, leave it like that (with snapshot)...it is only for the dev version, so no reason to be pixel perfect.

**Comment by grimes2** [comment]
That's fine. The normal versions JabRef 3.7 or JabRef 3.7dev will anyway fit in one line. And for the authors all informations are now delivered. Thank you!

**Comment by tobiasdiez** [comment]
I still have the opinion that "License:" should be removed, but apart from that 👍 for merge. @koppor your call.

**Comment by boceckts** [comment]
After talking to @koppor I changed minor things and how the snapshot versions will be displayed, I updated the screenshots in the description of this pr accordingly.

**Comment by koppor** [comment]
The about dialog is not centered on the JabRef window. See attached screenshot.

JabRef 3.7dev--snapshot--2016-10-06--javafx--5a4e79a
windows 10 10.0 amd64 
Java 1.8.0_101

grabbed_20161006-181713

**Comment by boceckts** [comment]
Hmm I just tried it with the jar available at http://builds.jabref.org/javafx/ and it worked perfectly for me :thinking:

aboutdialogcenter

JabRef 3.7dev--snapshot--2016-09-26--javafx--6134490
windows 8.1 6.3 amd64 
Java 1.8.0_102

**Comment by koppor** [comment]
Works on a single screen. Have to connect to an external screen and check again. I have the feeling that JavaFX does not work well with two screens having a different magnification.

**Comment by boceckts** [comment]
This was actually tested on a second screen, that's why there are no icons. Your build is also a newer one, maybe this is the reason.

**Pull request merged**
