### PR TITLE
Fix adding index column due to no qualifer property

### PR DESCRIPTION
**Pull request by Siedlerchr**
Found while testing https://discourse.jabref.org/t/does-the-field-still-exist/4029

### Mandatory checks
- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by Siedlerchr** [comment]
Probably not necessary

**Comment by calixtus** [comment]
? So whats the real problem here?

**Comment by Siedlerchr** [comment]
The guy in the forum said it worked for him

**Review by koppor — APPROVED** [review]

**Comment by koppor** [comment]
Tried here. Windows 10. Did not work on `main`, works with this PR.

**Pull request merged**
