### PR TITLE
Pattywxf112 patch 1 member

### PR DESCRIPTION
**Pull request by pattywxf112**
### Mandatory checks

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by pattywxf112** [comment]
change markdown of 1st testcase

**Comment by pattywxf112** [comment]
oops

**Comment by Siedlerchr** [comment]
seems like you accidentally created the PR in JabRef's upstream repo and not your fork ;)

**Comment by pattywxf112** [comment]
sorry, I'm a trying out PR from the forked repo and did this by accident :(
I'll find way to ask owner to remove it

**Comment by pattywxf112** [comment]
@Siedlerchr I'm really sorry, I'm trying this for a my university group project. could you delete his PR? :<

**Comment by Siedlerchr** [comment]
If you close it, that's fine. I cannot delete PRs. Just check to select the right repo when opening

**Comment by pattywxf112** [comment]
understood thank you have a nice day

**Pull request closed without merging**
