### PR TITLE
Refactor proxy registration and preferences

### PR DESCRIPTION
**Pull request by tobiasdiez**
Moves code from `JabRef` to own class and introduces new class encapsulating the proxy preferences.

### CODE REVIEW

**Comment by oscargus** [comment]
In the spirit of moving things from JabRefPreferences, wouldn't it make sense to let the ProxyPreferences class access the preferences directly?

So: `ProxyPreferences proxyPrefs = new ProxyPreferences()` and `proxyPrefs.save()` (possibly with a JabRefPreferences as an argument).

**Comment by tobiasdiez** [comment]
Yes you are right, this would also be a possibility. 

What I aim at in the end is to reduce the public interface of the `JabRefPreferences` class to like 20 methods which store/retrieve only complex types. In this way also the serialization is hidden in the class and the caller doesn't have to worry how to convert to string/boolean etc. Then it would be also very simple to replace the whole class with something completely different, for example writing the preferences as a json file.

**Comment by tobiasdiez** [comment]
I now moved some code from the JabRefPreferences class to the new ProxyPreferences class as @oscargus suggested. Looks indeed cleaner.

**Comment by simonharrer** [comment]
- no state in ProxyPreferences
- IDEA: logic and model should not know JabRefPreferences
- JabRefPreferences must not know ProxyPreferences; defaults and keys in JabRefPrefences

**Comment by tobiasdiez** [comment]
Done & rebased.

**Pull request merged**
