### PR TITLE
Enable JDK22 build

### PR DESCRIPTION
**Pull request by koppor**
Follow-up to https://github.com/JabRef/jabref/pull/11057 and https://github.com/JabRef/jabref/pull/11058.

The EA workflow now builds using JDK22 features (using gradle 8.7-rc.3, which supports JDK22 for compilation)

### Mandatory checks

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by koppor** [comment]
Blocked by https://github.com/gradle/gradle/issues/16791

**Comment by koppor** [comment]
For jpackage, we have

    Caused by: java.lang.module.InvalidModuleDescriptorException: Unsupported major.minor version 66.0

**Comment by koppor** [comment]
Our [jpackage plugin](https://github.com/beryx/badass-jlink-plugin) seems [not to support toolchain](https://github.com/beryx/badass-jlink-plugin/issues/214).

The alternative plugin https://github.com/petr-panteleyev/jpackage-gradle-plugin does.

**Comment by koppor** [comment]
Should work now. Norma build: JDK21, EA with JDK22

**Review by Siedlerchr — APPROVED** [review]

**Pull request merged**
