### PR TITLE
[WIP] New Crowdin translations

### PR DESCRIPTION
**Pull request by koppor**
In comparison to transifex, we have the automatic GitHub integration.

## Pros and cons of crowdin

- `+`: Easy translation interface. Users can start joining at https://crwd.in/jabref.
- `+`: Nice status overview - see https://crowdin.com/project/jabref - internal link: https://crowdin.com/project/jabref/settings#translations - fixes fixes https://github.com/JabRef/help.jabref.org/issues/171
- `+` Translators do not require a login at GitHub and do not need to work with pull requests etc.
- `+` Translations can still be made using our GitHub workflow
- Exclamation marks are escaped. However, this is no issue, because we unescape them: https://github.com/JabRef/jabref/blob/d45d7ca381c31fab2e41e0693948b11e5068887b/src/main/java/org/jabref/logic/l10n/LocalizationKey.java#L25
- `-` At least one review of the translated string is required
- `-` We cannot create [our translation status page](https://github.com/JabRef/help.jabref.org/blob/gh-pages/en/TranslatingGUI.md#localization-files-status-2017-11-29-1957---branch-master-42ba568ea) anymore (using `syncLang.py`) as crowdin either (i)  does not put a key at all or (ii) puts the English translation in the properties file. Checking for equality does not help as `OK` is translated to `OK`.
- `-` It seems that generating the pull request has to be triggered manually.

I would vote to go for crowdin to make it easy for interested people to work on the translation.

## TODOs

- [ ] Check why our language file checker fails and adapt it accordingly
- [x] `id` vs `in`. Result: The ISO-Code for Indonesia changed from "in" to "id". Java uses only the old one. See https://docs.oracle.com/javase/7/docs/api/java/util/Locale.html#Locale(java.lang.String), but Crowdin uses the new one. With a new mapping configuration on Crowdin, this is fixed.

### CODE REVIEW

**Comment by koppor** [comment]
In comparison to transifex, we have the automatic GitHub integration.

## Pros and cons of crowdin

- `+`: Easy translation interface
- `+`: Nice status overview - see https://crowdin.com/project/jabref - internal link: https://crowdin.com/project/jabref/settings#translations - fixes fixes https://github.com/JabRef/help.jabref.org/issues/171
- `+` Translators do not require a login at GitHub and do not need to work with pull requests etc.
- `+` Translations can still be made using our GitHub workflow
- `-` At least one review of the translated string is required
- `-` We cannot create [our translation status page](https://github.com/JabRef/help.jabref.org/blob/gh-pages/en/TranslatingGUI.md#localization-files-status-2017-11-29-1957---branch-master-42ba568ea) anymore (using `syncLang.py`) as crowdin either (i)  does not put a key at all or (ii) puts the English translation in the properties file. Checking for equality does not help as `OK` is translated to `OK`.
- `-` It seems that generating the pull request has to be triggered manually.

I would vote to go for crowdin to make it easy for interested people to work on the translation.

**Comment by Siedlerchr** [comment]
One reason for the failure are the missing underscores in the translation of german, e.g Prüfe Integrität

**Comment by koppor** [comment]
We should get rid off the underscores anyway... Seem, they are an old
relict!

Am 29.11.2017 20:40 schrieb "Christoph" <notifications@github.com>:

**Comment by tobiasdiez** [comment]
I'm fine with the change and the translation ui of crowdin looks nice. But in the end, the @JabRef/translators have to work with it. What is your opinion about this proposed change?

**Comment by ThomasA** [comment]
To my great shame, I have not updated the Danish translation for years (but hope I might get time for it again). To the extent that I still have any say in this, I vote for Crowdin. I was never that happy about popeye anyway. I remember experiencing problems with the Danish letters æ, ø, å (I haven't checked, but I hope Crowdin is better at that).
Two things I have not understood yet:
- Does Crowdin still use/generate the `.properties` files?
- Is it OK to just use spaces in strings instead of dealing with the horrible underscores?

**Comment by mlep** [comment]
My comments:
- Nice and convenient interface 
- While translators will not require a login at GitHub, they seem to require one at Crowdin. What about anonymous contributions through Crowdin? Possible? 
- I hope that review can be skipped (or at least that translations do not need to be reviewed one-by-one).
- Since the current Github workflow will continue to work, we can try out Crowdin and see if it helps to get better localizations of JabRef.

**Comment by koppor** [comment]
- `.properties`: Yes, no change. Therefore, the GitHub workflow still works.
- Yes, I will work on removing these underscores - I *hate* them 😇 
- Translators also need a login at GitHub. Otherwise, the pul requests don't work.
- I did not see a way to skip the reviews, but this is a one-click thing. We can do it always before/after each devcall or when an email comes in. Think, this is not a show stopper

**Comment by koppor** [comment]
I close this PR, but we can continue discussing here. I will have to create some more PRs to get this thing running...

**Pull request closed without merging**
