### PR TITLE
Springer search encoding fix

### PR DESCRIPTION
**Pull request by subhramit**
It was observed that while using Springer Web Search, the fetcher wasn't parsing the "authors" sometimes in their correct encoding format. This was especially true in case of authors whose names contained accented characters.

For instance, if we consider this entry:
Screenshot 2024-03-22 100003

Which, on importing and expansion, became:
Screenshot 2024-03-21 093748
(For purposes of replication, you can search for "multi-objective truss" to obtain this exact result).

These were the expected author names:
Screenshot 2024-03-21 093811

To fix this, the first character-set conversion I tried was from the ```ISO-8859-1``` character set to ```UTF-8```. However, this seemed to partially fix the problem:
Screenshot 2024-03-22 102332

Realizing it needed a more universal character-set to accommodate and convert, I finally went with ```"windows-1252"``` character set, which is a superset of ISO-8859-1 and includes additional characters. This finally fixed the problem completely:
Screenshot 2024-03-22 181302

Screenshot 2024-03-22 181515

UPDATE: Turns out the issue is not limited to authors, but fields like title, abstract, etc. too. Will be generalizing the pull request.
### Mandatory checks

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [x] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Review by koppor — CHANGES_REQUESTED** [review]
Is this covered by a test case?

The underlying issue is that https://github.com/JabRef/jabref/blob/2fd16dba014a122b796426b5c4f944d306c5d873/src/main/java/org/jabref/logic/net/URLDownload.java#L249 forces UTF8. 

The encoding should be passed down by the fetcher (there is the parameter for the encoding for asString). Maybe you can check for the springer fetched?

**Comment by subhramit** [comment]
> Is this covered by a test case?
> 
> The underlying issue is that https://github.com/JabRef/jabref/blob/2fd16dba014a122b796426b5c4f944d306c5d873/src/main/java/org/jabref/logic/net/URLDownload.java#L249 forces UTF8. 
> 
> The encoding should be passed down by the fetcher (there is the parameter for the encoding for asString). Maybe you can check for the springer fetched?

Good catch. Will investigate.

**Comment by subhramit** [comment]
@koppor I have started writing the test in my last commit. Could you have a look once and see if I need to change anything, meanwhile I'll manually check the json fetched.

**Comment by Siedlerchr** [comment]
I am really wondering why there is no longer UTF8 returned, it should be the de facto standard

**Comment by koppor** [comment]
Maybe there was never UTF8, but not yet covered by test cases

**Comment by subhramit** [comment]
> Good catch. Will investigate.

@koppor @Siedlerchr Here's what I found:
On manually querying using the Springer API, the characters returned are normal (UTF-8):
(I am pasting only the relevant section)
```
"title": "Solving multi-objective truss structural optimization problems considering natural frequencies of vibration and automatic member grouping",
      "creators": [
        {
          "ORCID": "0000-0001-8818-8658",
          "creator": "Carvalho, Érica C. R."
        },
        {
          "ORCID": "0000-0001-5266-0703",
          "creator": "Carvalho, José Pedro G."
        },
        {
          "ORCID": "0000-0003-2012-7802",
          "creator": "Bernardino, Heder S."
        },
        {
          "ORCID": "0000-0001-9938-294X",
          "creator": "Lemonge, Afonso C. C."
        },
        {
          "ORCID": "0000-0003-3224-9946",
          "creator": "Hallak, Patrícia H."
        },
        {
          "ORCID": "0000-0001-6098-0029",
          "creator": "Vargas, Dênis E. C."
        }
      ],
 ```
However, here is what the fetcher test I wrote is giving us:
image
(Focus on lines 180 and 196. If hard to see, you can check out these lines in the log [here](https://github.com/JabRef/jabref/actions/runs/8397854253/job/23001862092?pr=11077).

As you can see, it is not UTF-8. Now I am confused. Any directions?

**Comment by subhramit** [comment]
Okay, another find:
Screenshot 2024-03-23 063532

Seems like the issue is not limited to authors.
For now, I'll be making changes to fix these fields as well and change the name of the pull request to a more general one.

@koppor @Siedlerchr This is very similar to the issue I faced while writing the MathSciNet parser, remember? There too I had to fix for multiple fields, and Oliver suggested to make a separate method for it.

**Comment by subhramit** [comment]
Fixed.
image

**Comment by Siedlerchr** [comment]
CI still fails because it runs on Linux and that uses utf8  as default so your fix encoding does things worse here.
When I remove it all my tests are green.

**Comment by subhramit** [comment]
> CI still fails because it runs on Linux and that uses utf8 as default so your fix encoding does things worse here. When I remove it all my tests are green, I am on mac here as well. I guess gradle does not use utf on windows console?

Take a look at the fetcher test log that I attached above:


> > Good catch. Will investigate.
> 
> @koppor @Siedlerchr Here's what I found: On manually querying using the Springer API that we are using, the characters returned are normal (UTF-8) (I double checked using an [encoding detecter](https://onlinephp.io/mb-detect-encoding)). (I am pasting only the relevant section of the json retrieved)
> 
> ```
> "title": "Solving multi-objective truss structural optimization problems considering natural frequencies of vibration and automatic member grouping",
>       "creators": [
>         {
>           "ORCID": "0000-0001-8818-8658",
>           "creator": "Carvalho, Érica C. R."
>         },
>         {
>           "ORCID": "0000-0001-5266-0703",
>           "creator": "Carvalho, José Pedro G."
>         },
>         {
>           "ORCID": "0000-0003-2012-7802",
>           "creator": "Bernardino, Heder S."
>         },
>         {
>           "ORCID": "0000-0001-9938-294X",
>           "creator": "Lemonge, Afonso C. C."
>         },
>         {
>           "ORCID": "0000-0003-3224-9946",
>           "creator": "Hallak, Patrícia H."
>         },
>         {
>           "ORCID": "0000-0001-6098-0029",
>           "creator": "Vargas, Dênis E. C."
>         }
>       ],
> ```
> 
> However, here is what the fetcher test I wrote is giving us: image (Focus on lines 180 and 196. If hard to see, you can check out these lines in the log [here](https://github.com/JabRef/jabref/actions/runs/8397854253/job/23001862092?pr=11077).
> 
> Any directions?

Here, the characters being retrieved are not encoded properly as well.

**Comment by subhramit** [comment]
> CI still fails because it runs on Linux and that uses utf8 as default so your fix encoding does things worse here. When I remove it all my tests are green, I am on mac here as well. I guess gradle does not use utf on windows console?

Also, I can probably guess why that makes sense. Probably because the Character set I used for conversion was ```windows-1252```. So maybe it works properly only on Windows. I wonder if an equivalent universal character set exists as a standard one...

**Comment by Siedlerchr** [comment]
This more likely a Gradle thing not picking up the right encoding when using the console, at runtime it should work just fine

**Comment by subhramit** [comment]
> Should we add this as an issue? Since JabRef has a large share of Windows users, this might be a significant problem.

@Siedlerchr @koppor

**Comment by koppor** [comment]
> > Should we add this as an issue? Since JabRef has a large share of Windows users, this might be a significant problem.

@subhramit - No. Large discussion on that was done nearly 10 years ago: https://github.com/JabRef/jabref/pull/514

> Tests should not depend on the default encoding of the system. 

We DO have some encoding settings (in build.gradle)

```groovy
tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
```

but we do not change a **SYSTEM** property.


Similar solution as in 2015 is proposed at https://stackoverflow.com/a/71639886/873282. Without any reasoning why this is a good idea.

Reading the JDK-UTF-8-Default thing (https://inside.java/2021/10/04/the-default-charset-jep400/), I don't understand why there are encoding issues...

**Pull request closed without merging**
