### PR TITLE
Move Encoding from BasePanel to MetaData

### PR DESCRIPTION
**Pull request by tobiasdiez**
<describe the changes you have made here: what, why, ...>

- [ ] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [ ] Screenshots added (for bigger UI changes)

### CODE REVIEW

**Comment by lenhard** [comment]
Looks good overall.

I guess it makes sense to move the encoding, since it is nothing specific to `BasePanel`. However, it increases method call chains in quite a few places, which get the encoding via the panel. Maybe it is worth to consider leaving the `getEncoding`, `setEncoding` methods in `BasePanel` and have them delegate to `MetaData`, so you can write `panel.getEncoding()` instead of `panel.getBibDatabaseContext().getMetaData().getEncoding()`. WDYT?

**Comment by tobiasdiez** [comment]
Yes you are right, the call chain gets length with this change. In my opinion, this is not really a "bug" but more a feature in the sense that you now see that some other methods should be changed as well. For example the `export` or `saveDatabase` method can now simply accept a BibDatabaseContext and then get the encoding themselves. Moreover, the BasePanel has absolutely no business to know about the file encoding, since it is a GUI class. Thus I would prefer not to reintroduce the shortcut methods.

**Comment by simonharrer** [comment]
Compromise: add a getEncoding method to the BibDatabaseContext.

**Comment by simonharrer** [comment]
There seems to be a lot of NPE according to the travis report. When this is fixed, we can merge this in.

**Pull request merged**
