### PR TITLE
Fixes the auto-update problem with TexGroups on Ubuntu Linux and makes the detection of file modifications more reliable

### PR DESCRIPTION
**Pull request by systemoperator**
Fixes https://github.com/JabRef/jabref/pull/7173#issuecomment-768998167 in #7173.

On Ubuntu Linux the auto-update functionality does not work with `TexGroup`s, when the associated `.aux` file gets updated externally.

<strike>This is a quick fix for this issue, which may still be improved. Only one of both files needs to be changed in order to fix it.</strike>

- [x] Change in CHANGELOG.md described (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by tobiasdiez** [comment]
Thanks for your PR. Can you please explain what the problem is/was and why your fix works? It looks like you only have a relative file in your tex group and want to resolve this path relative to the latex folder, is this correct?

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
If the problem is that it is a relative path, perhaps this would be another location where the code could be added?
https://github.com/JabRef/jabref/blob/66a771c1792ebf2f7c70269bb2198d44176b3a81/src/main/java/org/jabref/gui/groups/GroupDialogViewModel.java#L339

**Comment by systemoperator** [comment]
Basically, the path for the `aux`-file is created for the wrong base directory.

https://github.com/JabRef/jabref/blob/66a771c1792ebf2f7c70269bb2198d44176b3a81/src/main/java/org/jabref/logic/importer/util/GroupsParser.java#L128

creates a Path object `path`="main.aux". When converting it to its absolute path (`path.toAbsolutePath()`), it uses the working directory of JabRef and not for the directory of the opened library.

**Comment by systemoperator** [comment]
Changing

https://github.com/JabRef/jabref/blob/4d8e4f0e1782af33e6e95c6ad6990b06d4e37c32/src/main/java/org/jabref/model/groups/TexGroup.java#L50

to

`fileMonitor.addListenerForFile(group.filePath, group);`

should fix both cases (I. simply opening the library and II. changing the a group to a `TexGroup`).

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
I am not up-to-date on how changing the group type works in practice, but it seems like a good solution to the relativized path issue.

**Comment by tobiasdiez** [comment]
Thanks for the explanation! https://github.com/JabRef/jabref/pull/7412#issuecomment-771886706 looks like the right approach to me. In addition, I would suggest to add a method `getFilePathResolved()` to `TexGroup` that simply returns the `filepath` object.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
Basically, I agree with @tobiasdiez, same regarding https://github.com/JabRef/jabref/pull/7173#issuecomment-771947832.

**Comment by systemoperator** [comment]
I have tested this fix for loading a library, for changing a group to a `TexGroup` and with different editors each. It works great for Ubuntu.

@k3KAW8Pnf7mkmdSMPHz27 Could you check for safety reasons, that your library on macOS is still getting updated with this version?

**Review by tobiasdiez — DISMISSED** [review]
Thanks!

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
> @k3KAW8Pnf7mkmdSMPHz27 Could you check for safety reasons, that your library on macOS is still getting updated with this version?

The library is still getting updated 👍 😃

**Comment by Siedlerchr** [comment]
Would be nice if someone can test this under Windows as well, because Windows and Linux behave differently regarding file watching events/file system operations

**Comment by calixtus** [comment]
Just a general thing: Please try to shorten your PR titles and commit messages and keep them meaningful, so after  months you still understand, what you did. See https://www.freecodecamp.org/news/writing-good-commit-messages-a-practical-guide/

**Review by k3KAW8Pnf7mkmdSMPHz27 — APPROVED** [review]
I don't have a full Windows 10 setup, but the relative path works when manually editing the .aux file. There is an issue in that `TexGroup.create` doesn't throw an exception if the file doesn't exist but it is not related to this PR.

**Review by Siedlerchr — APPROVED** [review]

**Pull request merged**
