### PR TITLE
Citavi Importer - Import all knowledge items

### PR DESCRIPTION
**Pull request by Siedlerchr**
Filter out empty strings and replace quot
Follow up from #9033 

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Review by koppor — APPROVED** [review]
As co-author, I like it 😇

**Comment by Siedlerchr** [comment]
I am waiting on feedback from ray-carpenter, so let's wait with merging a bit

**Comment by Siedlerchr** [comment]
I've now included the quotation index and the type of the quotation as well. Based on the mapping:
https://github.com/JabRef/jabref/issues/9025#issuecomment-1211108679

**Comment by koppor** [comment]
I like.

Future work should treat the quotation stuff as PDF highlights, shouldn't it? - This would enable "annotating" PDFs without altering the PDF. Similar as [CloudRef](https://jabref.github.io/cloudref/) does it. :)

**Comment by Siedlerchr** [comment]
Yes, but we don't have a concept for storing pdf annotations in bibtex fields, they are just read and kept in memory while JabRef is open.

**Comment by koppor** [comment]
We could create a YAML file - as we are going to do at https://github.com/JabRef/jabref/pull/7160#issuecomment-757556724.

**Pull request merged**
