### PR TITLE
Improve error handling for browser extension

### PR DESCRIPTION
**Pull request by tobiasdiez**
Still needs similar changes for the other problems and then some changes to the browser extension to actually show the error.

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by LyzardKing** [comment]
Looks good!
I'll check it properly, and see if something is necessary for the extension to log in the console. It might be an idea to show an alert for the user in the poup window.

**Comment by tobiasdiez** [comment]
This is now ready for review. Linux and Macos changes are not tested however.

**Comment by Siedlerchr** [comment]
What needs to be done to test this?

**Comment by tobiasdiez** [comment]
The important part would be to install this version and see if the browser extension still works.

If you want to verify the improvements of this PR, then best change `cmd = str(JABREF_PATH).split() + ["--importBibtex", r"{}".format(data)]` to something that returns with an error code and then check the browser console that the error is displayed there.

**Comment by Siedlerchr** [comment]
Tested the binaries from this PR and it still works under mac.
browser console says
```

JabRef: Got task to convert  
Array [ {…} ]
​
length: 0
​
<prototype>: Array []
  to BibTeX bibtexConverter.js:240:11
JabRef: Converting item(s) to BibTeX:  
Array [ {…} ]
```

**Comment by LyzardKing** [comment]
It works on Linux as well. I tested it with firefox and it works, with the correct webpage if it fails to find the native messaging info.
Great job!
I'll test it on other browsers later, but I assume it works there as well :smile:

**Comment by tobiasdiez** [comment]
Thanks for testing!

I take this as a positive review ;-)

**Comment by Tobi0** [comment]
I suspect there is a problem in the `buildres/windows/JabRefHost.bat` pwsh check for the case: **pwsh not installed, powershell.exe installed**.

https://github.com/JabRef/jabref/pull/8432/files#diff-e652989be8342b186ecf6bdf200fd7e9ce3e0b75dca438bd2f6c52bcd11b0c6c
If the command `where /q pwsh.exe` goes wrong, the errorlevel is maybe still 1 after the powershell.exe test. I could not reproduce this in the console but the behavior in the file might be different. 

Anyhow if I test the JabRefHost.bat I get
```
PS C:\Program Files\JabRef> .\JabRefHost.bat
"Could not find pwsh.exe or powershell.exe"
"Please install PowerShell and try again."
```
(But the `where /q powershell.exe` command alone does not return an error.)

This would explain why the Browser extension is not working for me.

**Pull request merged**
