### PR TITLE
Change blue and red colors in Merge entries dialog in Dark theme

### PR DESCRIPTION
**Pull request by MootezSaaD**
This PR is related to #6334 (blue text color in the Merge entries dialog in dark theme).
After modifications, the dialog looks like this
image

I have also tried to replace the red color upon @koppor 's comment (located in the aforementioned issue)

- [X] Change in CHANGELOG.md described (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [X] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by Siedlerchr** [comment]
Thanks for tackling this issue. I am not happy about that blue in general. Maybe a better contrast color e.g. a  blue with `#54A3F2`

See for example here for a combination of possible colors:
https://app.contrast-finder.org/result.html?foreground=%234281BE&background=%23272B38&ratio=4.5&isBackgroundTested=false&algo=HSV

**Comment by MootezSaaD** [comment]
I think #54A3F2 seems to be more suitable
image

**Comment by Siedlerchr** [comment]
Yep, that blue looks good! I also checked the red color, this one should have better contrast as well:
`#FA5B68` Could you also show a screenshot of both new colors?

**Comment by MootezSaaD** [comment]
Both colors seem more visibile to me

image

**Comment by Siedlerchr** [comment]
Yes, that looks good to mew now! Go ahead!

**Comment by koppor** [comment]
Awesome. Thank you for the quick action taken and the fast replies to the reviews @MootezSaaD. @Siedlerchr Thank you for the quick and constructive review, too!

**Comment by Siedlerchr** [comment]
@MootezSaaD  Maybe you can fix some other issues with the dark theme as well?
 This would be really cool! See #5522 for a list of issues

**Comment by MootezSaaD** [comment]
Absolutely, I'll give it a look

**Pull request merged**
