### PR TITLE
Ensure SSL truststore is present at startup

### PR DESCRIPTION
**Pull request by HoussemNasri**
Follow up on #8583.

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [x] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Review by Siedlerchr — APPROVED** [review]

**Comment by Siedlerchr** [comment]
Just a general question: Does the trustsotre content change with the java version? I might guess that new certifacates are added or revoked. So we need to ensure that we always copy the jdk's truststore in our resources and maybe also merge? the contents when the store already exists from an older version?

**Review by calixtus — APPROVED** [review]

**Comment by calixtus** [comment]
Thanks for the follow up!

**Comment by HoussemNasri** [comment]
@Siedlerchr That is correct; in JDK 17 they removed [Telia Company's Sonera Class2 CA Certificate](https://www.oracle.com/java/technologies/javase/17-relnote-issues.html#JDK-8225081) and added [2 HARICA Root CA Certificates](https://www.oracle.com/java/technologies/javase/17-relnote-issues.html#JDK-8256421). Merging new JDK truststore is an option; it can be done in 3 steps:
1. Add new truststore to resources.
2. Remove all jdk certificates from the old truststore at startup *(jdk certificates alias follow a specific pattern, so we can filter them in)*.


3. Finally, update the old truststore with new truststore certificates.

**Comment by Siedlerchr** [comment]
Thanks for the explanation. Okay, this seems like it could be implemented as part of a migration process in JabRef.

**Pull request merged**
