### PR TITLE
[WIP] Replaced BibEntry[] with List<BibEntry>

### PR DESCRIPTION
**Pull request by oscargus**
Replaced `BibEntry[]` with `List<BibEntry>` as return from `MainTable.getSelectedEntries()` and propagated it.

### CODE REVIEW

**Comment by tobiasdiez** [comment]
More or less the same changes as in #718 :crying_cat_face:

**Comment by oscargus** [comment]
Oh no...

**Comment by oscargus** [comment]
Wait with merging this until after #718 is merged. I will then rebase (and see if there are any changes left...).

**Comment by simonharrer** [comment]
#718 is merged.

**Comment by simonharrer** [comment]
Is this still relevant?

**Comment by oscargus** [comment]
New attempt in #793 (and #795).

**Pull request closed without merging**
