### PR TITLE
Upgrade to JavaFX 13

### PR DESCRIPTION
**Pull request by tobiasdiez**
Let's see if this works

----

- [ ] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [ ] Manually tested changed features in running JabRef
- [ ] Screenshots added in PR description (for bigger UI changes)
- [ ] Ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)

### CODE REVIEW

**Comment by Siedlerchr** [comment]
Before we merge this, we need to test it. Especially we need to check if our internal hacks also still work

**Comment by tobiasdiez** [comment]
I tested it (by clicking around a bit) and it appears to work. Thus ready for review.

**Comment by Siedlerchr** [comment]
At least one mac user should test it @LinusDietz

**Comment by koppor** [comment]
Saw it on MacOS X.

**Comment by matthiasgeiger** [comment]
There seems to be a problem (at least) with the windows version from builds.jabref.org/master:

```
PS C:\Users\...\Downloads\JabRef-portable_windows\JabRef> .\JabRef.exe
Error occurred during initialization of boot layer
java.lang.module.FindException: Two versions of module javafx.base found in C:\Users\mg\Downloads\JabRef-portable_windows\JabRef\app\mods (javafx-base-13-mac.jar and javafx-base-11.0.2-mac.jar)```

**Pull request merged**
