### PR TITLE
Refine documentation

### PR DESCRIPTION
**Pull request by koppor**
Some more documentation refinements.

Follow-up to https://github.com/JabRef/jabref/commit/3c247ff55708970d857dda8ac5e0472265466435

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by tobiasdiez** [comment]
I don't quite understand what you want to say with this. The medline importer inherits from `Parser`, and that is what is used in the fetcher.

**Comment by Siedlerchr** [comment]
We were discussing the differences between ParserBasedFetcher and non parser fetcher

**Comment by tobiasdiez** [comment]
Normally, the fetcher invokes an api and then parses the response (to get BibEntries). This kind of workflow is supported by the parser-based fetcher. Sometimes you need to have more flexibility, i.e. call multiple endpoints and merge the results etc. In theses cases, one has to use the non-parser-based fetcher interfaces. But I think this is already described in the docstrings.

**Comment by koppor** [comment]
The comments were not as clear as you provided in your comment. I added your text at [`57d1b2a` (#8551)](https://github.com/JabRef/jabref/pull/8551/commits/57d1b2a11516db298c8553991cd92cc29365e6af).

**Comment by koppor** [comment]
In general, I like the concept of links and would like to guide a novice in the code for more details.

**Pull request merged**
