### PR TITLE
Add Type Bachelor's Thesis to EntryType Thesis for Biblatex References

### LINKED ISSUE #10029: Type option for Bachelor's thesis
**Is your suggestion for improvement related to a problem? Please describe.**
A thesis can have different types, but right now, there is none for Bachelor's thesis.

**Describe the solution you'd like**
I want such a field, but not sure whether this also requires support for that in biblatex.

Do you know the best way to achieve this (or a good way, how to treat BA theses)?

### PR DESCRIPTION
**Pull request by cmgoodall**
I have added the Type 'Bachelor's Thesis' to the dropdown of Types when choosing the EntryType of Thesis.

resolves #10029

### Mandatory checks
- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [x] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### Screenshot of Change

Screenshot 2023-10-16 at 8 02 09 am

### CODE REVIEW

**Comment by Siedlerchr** [comment]
so far it looks good, we just need to recheck if the preferences error happens again or can happen again.

**Comment by cmgoodall** [comment]
I've tried to recreate the issue however, have been unsuccessful. I think the issue might have stemmed from the fact I had JabRef preferences saved from the actual application and they might have been messing with it? I'm not 100% sure though. I've looked at all the files you've recommended and cannot see anything that is causing the error.

**Comment by Siedlerchr** [comment]
I also tested it locally back and forth with an older version of JabRef and could not reproduce the issue, so I think it's fine

**Review by Siedlerchr — APPROVED** [review]

**Review by Siedlerchr — APPROVED** [review]

**Comment by Siedlerchr** [comment]
No further actions necessary, the build will be automatically merged now.

**Comment by koppor** [comment]
@cmgoodall I don't see an issue at the user-documentation. Can you provide the link? https://github.com/JabRef/user-documentation/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

**Comment by cmgoodall** [comment]
Hi @koppor. Apologies, I didn't realise I was required to do this. I have just raised an issue

https://github.com/JabRef/user-documentation/issues/472

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
@cmgoodall I think @koppor is referring to 

> - [x] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
> - [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at [JabRef/user-documentation/issues](https://github.com/JabRef/user-documentation/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) or, even better, I submitted a pull request to the documentation repository.

that is, are there any parts of the user documentation that should be updated due to this PR, and if so, which parts?
From a generic open-source point of view, https://github.com/JabRef/user-documentation/issues/472 is not easily actionable for someone not familiar with this issue and PR (i.e., me 😅) because they are unlikely to be familiar with the EntryType thesis. Is there more context you can add to the documentation issue, create a PR, or briefly argue why you don't believe it to be necessary/useful? When I quickly search for `phdthesis` in our documentation, I don't find anything I believe needs to be updated, barring perhaps [the field mapping](https://docs.jabref.org/advanced/knowledge/msofficebibfieldmapping#entry-type-mappings).

**Comment by koppor** [comment]
> When I quickly search for `phdthesis` in our documentation,

Some spontaneous ideas: Maybe a new screenshot of the entry editor? Maybe pointing the user to a place in the biblatex documentation where this feature is described?

**Pull request merged**
