### PR TITLE
Use GitVersion to increment build numbers

### PR DESCRIPTION
**Pull request by tobiasdiez**
Fixes https://github.com/JabRef/jabref/issues/5399 and fixes https://github.com/JabRef/jabref/issues/5657.
The following version information is automatically determined by GitVersion based on the current tags.

|  Context      | Build version |  Build information |
|---------------|---------------|--------------------|
| PR            | 5.0.X         | 5.0-branch.Y       |
| Master        | 5.0.X         |  5.0               |
| After tag 5.1 | 5.1.X         |  5.1               |

Here, `X` is the number of commits since the last tag; and `Y is the number of commits on this branch; and `branch` is the branch name. Build version is the version used in gradle, i.e. the one used to generate the installer. Build information is what is displayed in the about dialog.
(Not sure if it really works on the master as it should; couldn't test it so far).

It should also work with tags of the form `5.0-beta` (which have `build version = 5.0.X` and `build information = 5.0-beta`). Thus, this PR hopefully also solves the problems of  https://github.com/JabRef/jabref/pull/5684.

- [ ] Change in CHANGELOG.md described (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for bigger UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not: Issue created at <https://github.com/JabRef/user-documentation/issues>.

### CODE REVIEW

**Comment by tobiasdiez** [comment]
Another note to myself: The about dialog current shows `5.0.0`. As we need to increase the last `patch` digit along versions to make the windows installer work, the display should be restricted to `5.0`.

**Comment by tobiasdiez** [comment]
It's a problem with our github workflow, which expects a proper git ref to determine the branch name. The build works after you commit something else. Nonetheless, it seems like the beta part is not picked up properly. Easiest workaround: work on branch with name beta.

**Comment by tobiasdiez** [comment]
Update: this seems to be by design, as the branch name overwrites every other pre release label. https://gitversion.readthedocs.io/en/latest/configuration/#tag

Thus, it only works on master. In the worst case, we have to add
```
release:
    regex: ^releases?[/-]
    mode: ContinuousDelivery
    tag: beta
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    tracks-release-branches: false
    is-release-branch: true
```
to the GitVersion config, and always deploy from the `release` branch (which might actually be a good idea regardless).

**Comment by tobiasdiez** [comment]
@LinusDietz building on a tag should now also work, if you still have problems with this on master.

**Comment by koppor** [comment]
We should disable the auto update check for version `0.0.1`:

grafik

**Comment by tobiasdiez** [comment]
@koppor good point. I've now set the default version to 100.0.0, so we should never reach this.

For the sake of moving forward, I'll merge now. Let's see how it works on master.

**Pull request merged**
