### PR TITLE
Fix failing fetcher tests

### PR DESCRIPTION
**Pull request by k3KAW8Pnf7mkmdSMPHz27**
### Mandatory checks

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by Siedlerchr** [comment]
Thanks! 
I wonder why CollectionOfComputerScience Tests are not disabled, the website is offline since a while. So maybe we need to add a Disabled to the tests as well

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
Ah, I was wondering the same thing while going through the Git blame X)

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
@Siedlerchr imho deprecate/remove the class?

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
https://github.com/JabRef/jabref/blob/dc2b649e02ed2a577ad884c0cad93bab84038fe4/src/main/java/org/jabref/logic/importer/fetcher/CollectionOfComputerScienceBibliographiesFetcher.java#L29

**Comment by Siedlerchr** [comment]
I would just add a @Disabled annotation,  For more information about CCSB see melting pot https://github.com/JabRef/jabref-issue-melting-pot/issues/259

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
Is there anything to do about the GROBID tests, or does the server need a kick?

**Comment by Siedlerchr** [comment]
Grobid is running on Azure now, will auto-restart. I saw some things in the logs, but not sure. I restarted the container now.

**Comment by Siedlerchr** [comment]
Can you check the UrlDownloadTest as well? seems like the is something wrong with the url

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
I'll be heading to sleep, but the 404 should be fixed, good catch!

When I am tired, I blame Grobid for everything 😳

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
GAH, too tired, sec.

**Review by Siedlerchr — APPROVED** [review]

**Pull request merged**
