### PR TITLE
bump checkstyle version to 9.0

### PR DESCRIPTION
**Pull request by nmancus1**
In reference to https://github.com/checkstyle/checkstyle/issues/10792, I would like to test this change against jabref's github CI before proceeding with investigation on Checkstyle's side.

Edit: checkstyle gradle build has passed, @Siedlerchr please take a look 

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by Siedlerchr** [comment]
You have modified the gradle properties. If you remove the change you will get the out of memory

**Comment by nmancus1** [comment]
> You have modified the gradle properties. If you remove the change you will get the out of memory

Yes - from your changes at 406f38bba11833dddd70f8a7667c548088a4a208 and bc9d1832247f07ab278b51a22d6165c3a45a1f5f, I thought that you were ok to increase heap size for your gradle build in response to Checkstyle using more memory.

**Comment by Siedlerchr** [comment]
It was an attempt to test if this helps

**Comment by nmancus1** [comment]
> I just wonder why Gradle does not pick up the env variables memory config

I am much more familiar with maven, but I know that JVM args for heap size can be very touchy, and I have a feeling that the JVM did not like `4g` as opposed to `4096M`.

**Pull request merged**
