### PR TITLE
Groups: Searching for keywords field mandatory value not checked

### LINKED ISSUE #6066: Add a subgroup: a warning should not close the window
JabRef 5.0-beta.532--2020-03-04--8111707
Linux 4.9.0-12-amd64 amd64 
Java 13.0.2

- [x ] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

While adding a subgroup, if a warning is displayed, the "add subgroup" window is closed.

1. In the group interface, right click and select "Add subgroup". This opens a window entitled "Add subgroup"
2. In this window, add a text in the description field. And DO NOT enter a group name.
3. Click on OK

==> An error window appears, stating (rightfully) that "Please enter a name for the group". Click on OK (no other choice). This causes the window "Add subgroup" to disappear.
Expected behavior: leave open the window "Add subgroup", so that I can enter the name of the group.

### LINKED ISSUE #6108: Empty field not checked in dialog for creation of keyword-search groups
JabRef 5.1--2020-03-12--23034ce
Linux 5.4.19-050419-generic amd64 
Java 13.0.2

- [X] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Create a group of type `searching for keywords`
2. Leave `Field`empty and add some keyword to `Keyword` 
3. When adding an entry to the group by drag-n-drop, JabRef generates a key-value pair with an empty key without any notification.

My expectations would have been, e.g. to (i) let the user know that `field` needs to be assigned some content, such as `keywords` or `group`, (ii) to make this field a drop-down textfield with a default value, (iii) or at least checking for `!key.isEmpty()` when generating the BibTeX entry. BibTeX will produce errors when running into malformed key-value pairs.

### PR DESCRIPTION
**Pull request by stefan-kolb**
Closes #6108 
Closes #6066 

- [x] Alert dialog triggered
image

- [x] Active Info icons:
image

- [x] Inactive info icons
image

- [x] Dialog should not close when error dialog is discarded!
@calixtus Not sure if we have this problem in more dialogs. The `setResultConverter` method will always close the dialog. We want to go abck to the dialog if errors are displayed as alert dialogs , however. We need to use `addEventFilter` for this I guess (am no expert in JavaFX @tobiasdiez) See Dialog validation section at https://docs.oracle.com/javase/8/javafx/api/javafx/scene/control/Dialog.html

### CODE REVIEW

**Comment by Siedlerchr** [comment]
In other dialogs we don't show any error message, instead we disable the ok buton until all required fields are set
 The dialog is duplicate. See for example the SharedDatabaseLogin Dialog

**Comment by koppor** [comment]
@Siedlerchr I really like that metaphor. Think, it's also in place in Angular apps ^^. Refs https://github.com/koppor/jabref/issues/410 (which states that we should document it).

**Comment by stefan-kolb** [comment]
I agree. But that's not what I fixed and what the PR is about ;-)

**Comment by tobiasdiez** [comment]
I agree that the OK-button should be disabled in case there are validation errors. The code for this seems to be in place as well, so I guess there is a bug somewhere. @Siedlerchr @calixtus do you have an idea where?

**Comment by calixtus** [comment]
I did take a look at the code and tried a little bit around, but I must confess, I don't ever reach the alert dialog. The button disableProperty is "bound" to the validation status and I'm unable to click the button. So... huh?
Also I agree to the button-disabled-metaphor.

**Comment by Siedlerchr** [comment]
So simply remove the dialog and all is done.

**Comment by stefan-kolb** [comment]
Disabled button should work, except for when the dialog is opened at first. The checks only come into place when one has entered data in the mandatory fields. We need to trigger the validation after initialization to change this.

**Comment by stefan-kolb** [comment]
Can we track the additional changes in a follow up issue? I'd rather limit this PR to the fixes  if possible.

**Pull request merged**
