### PR TITLE
NPE when exporting the database to an .sql file

### PR DESCRIPTION
**Pull request by jensdoecke**
Couldn't resolve the root cause, because of a mixup between Connection and Filehandling (disregards SoC)

### CODE REVIEW

**Comment by oscargus** [comment]
Thanks for the contribution. Makes sense!

Next time, please create a branch for your PR. I think that there may be some problems merging from your master branch so I let someone more knowledgeable do it.

**Comment by simonharrer** [comment]
Could you add a CHANGELOG entry, please?

For us, it is not soo much an issue if this is on the master branch. So when a CHANGELOG entry is added, we can merge this in. 

But maybe we should refactor the code to avoid these if statements whether we have a database connection or a file handle.

**Comment by jensdoecke** [comment]
I added the Fix to the CHANGELOG. 
These are my first steps in open source contribution so please forgive me the beginnner faults. ;-)

**Comment by tobiasdiez** [comment]
Thanks @jensdoecke. 
Can you please shortly explain why you tested that `out` is a connection and not that `val` is not null?

**Comment by jensdoecke** [comment]
In my opinion is the code more readable.

I prefer something like this:
When the object is a connection, I want to check if it is a MySql DB.

Instead of the assumption:
When the object is null, it must be a FileOutputStream and no Connection, so I don't check the dbParams.

**Comment by tobiasdiez** [comment]
Ok thanks for this clarification and your pullrequest. In my opinion, this can be merged in. :+1:

**Comment by stefan-kolb** [comment]
Thanks for the PR :+1:

**Pull request merged**
