### PR TITLE
Rating in main table

### LINKED ISSUE #5842: Improve Ranking column feature in main table
Unranked papers can currently only be ranked through the context menu, unlike read status, relevance, priority, and quality which can be directly toggled. However, after the first ranking, the star bar is shown in the entry list and can be toggled as usual. Although I realise that "empty star bar" = 0 stars and "unranked" are two different states. Following the logic of the other classification attributes, one could just treat these two states as equal, btw tools such as Rythmbox (a GTK-based media player) also handle it like this.

Otherwise, I consider this issue as closable.

_Originally posted by @ytzemih in https://github.com/JabRef/jabref/issues/5834#issuecomment-575527597_

### PR DESCRIPTION
**Pull request by calixtus**
Fixes #5842

Improves rating column to show even when no rating is presented.
Changes symbol from colorful standard controlsfx star to more serious monochrome one.

grafik 

grafik

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Review by btut — APPROVED** [review]
Did not try this out, but code and screenshots look good!

**Comment by Siedlerchr** [comment]
grafik

Can you take a look at the contex menu as well?

**Comment by calixtus** [comment]
About context menu: seems the right click to select the table row is not passed through the rating control, but for the context menu it is. Very strange.

**Comment by calixtus** [comment]
Fixed it.

**Comment by Siedlerchr** [comment]
Looks like this now, didn't we have the number of stars in front of it back then? 
grafik

**Comment by calixtus** [comment]
Not that I know of

Christoph ***@***.***> schrieb am Do., 4. Aug. 2022, 18:04:

**Review by koppor — APPROVED** [review]

**Pull request merged**
