### PR TITLE
Add some special fields as default columns

### PR DESCRIPTION
**Pull request by tobiasdiez**
So that users find these features more easily.

- [ ] Change in CHANGELOG.md described (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

**Review by koppor — COMMENTED** [review]
I would not remove the `citationkey` as I am used to have the table sorted by the key and search using the key (or am I not any more?)

Why is `linked_id` removed? Isn't that the URL and DOI thingy?

**Comment by tobiasdiez** [comment]
The citation key is removed as it contains mostly redundant information that is already displayed (in the default configuration it is author + year). The linked doi column is removed since this has only limited use cases in my opinion. Jabref is usually able to get bibliographic infos and the fulltext automatically, so there is no need to go to the journal website. Of course both columns have their uses and some users will readd them, but I don't think they need to be shown by default.

**Comment by koppor** [comment]
I think, my thoughts were that in `.tex` documents, entries are linked using the `key`. This key is different from the label put in the bibliography printed at `\printbibliography`. Students do not know that easily. Thus, my idea was to show the key prominent somehow so that they are reminded of that fact. - I think, I can live without the citation key column as default.

In the context of Cloud computing, more and more references are Web pages. This research field is still an important one. - If I recall correctly: With that icon, it was easy to jump to the web site. Just a single click. This was possible, because we merged DOI and URL into a single field. We did not merge URL and file into a single column, because we wanted to distinguish between local files and remote resources. I wonder why we prefer local resources over remote ones with this PR. I would not remove the file column even though one could also see in the tabs that a file is linked.

**Comment by koppor** [comment]
Maybe, we could merge the internal and external links into one "smart" link column. I just checked my personal library.

I have links only if I don't have a local copy. Thus, my preference would be:

- display file link
- display DOI link
- display web link

grafik

**Comment by tobiasdiez** [comment]
Yeah, I guess it strongly depends on your subject. In physics and mathematics, it's still pdf-first. I think, the last survey showed that this is our largest target group. But yeah, we sadly don't have good data for how many people click on the linked files / urls. So it's somewhat of a guessing game, partly based on our own experience.

**Comment by Siedlerchr** [comment]
As I said earlier, just add the new fields and keep the original fields

**Comment by koppor** [comment]
I think, this depends on https://github.com/JabRef/jabref/issues/6601 to have easy configurable columns.

**Comment by koppor** [comment]
Discussion with @stefan-kolb:

CitationKey

Against removal: We are still a BibTeX management tool. The most important thing of a BibTeX entry is the bibtex key. When we remove that, we might seem not a BibTeX tool any more

Pro removal: With the default BibTeX key generator, the author and year is

---

Discussion on special fields:

- Star rating is very useful, because after reading a paper, one can certainly assign a star rating
- Do we really need "printed" in the year 2021? Are the "modern" researchers not more screen-reader ones?
- I as user should remember whether I read a paper or not (read status).
- Priority is a very special case and certainly not the main use case.

Special fields may pollute the interface - not a "clean interface".

It is questionable whether all features fit the table. Maybe, therefore the proposal was to remove the BibTeX key.

---

URL column:

- For quality assurance, the functionality to go to the web site is ofen used.
- The field width is small.
- `@Misc` often used the URL. For instance, for a facebook thing.
- Searching in the current entry editor for the URL field is cumbersome
- Should NOT be merged with the file column, because files are something different than external URLs

---

Discussion on other fields:

- Most users will need
  - PDF
  - Author/Editor
  - Title
  - Year
- Not absolutely necessary
  - Journal/Booktitle

## Summary

- Remove citation key column
- Keep URL column
- Add star rating

**Comment by koppor** [comment]
BTW: This reminds me of the Eclipse perspective feature: https://www.tutorialspoint.com/eclipse/eclipse_perspectives.htm

We are discussing there different persepectives

- new noob user (e.g., BSc student)
- user writing a paper (refs https://github.com/JabRef/jabref/issues/160)
- user doing a systematic literature study
- (maybe?) users moving from Zotero

Our aim seems to be to bind interested JabRef users on JabRef. We mostly assume that users longer using JabRef are curious about new features (which I did not persieve).

Each of them requires a dedicated perspective to be productive. Currently, we do not have these perspective explicit, but argue about a perfect one fitting for all

**Comment by tobiasdiez** [comment]
Thanks for the discussion @koppor and @stefan-kolb! I've now implemented your suggestions. The only things were I disagree are
> I as user should remember whether I read a paper or not (read status).

You should also remember what is contained in the paper, and we still have a comment tab where people can put their summary into. Fact is, people forget stuff and it can be handy to keep track of what paper you already read / still need to read.

> Priority is a very special case and certainly not the main use case.

Given that there are so many things to read, I would say prioritization is one of the most important features to manage reading lists.


For these reasons, I added these two columns. They should be useful for all "perspectives" (but of course depend on the user's workflow). Can you agree with adding these two columns as well?

**Review by koppor — APPROVED** [review]

**Pull request merged**
