### PR TITLE
Ignore non-displayable fields for indent during writing

### LINKED ISSUE #834: Writeable fields should not cause rewriting of the whole entry
When an entry is unmarked, the field `__markedentry` is removed. If all other fields are shorter, the complete entry changes as the alignment changes. I am aware that we decided that at #116. We have, however, not thought about such exceptional cases.

Example:
grabbed_20160219-201705
(I know that a little bit more changed here. My database is written as BibLaTeX database).

Suggestion: Do not include non-displayable fields in the calculation of the amount of spaces to write.

Refs #574

### PR DESCRIPTION
**Pull request by koppor**
Fixes #834

### CODE REVIEW

**Comment by simonharrer** [comment]
Long term fix would be to not indent at all, and just write `key = value`.

**Comment by koppor** [comment]
The indent has been agreed upon during the discussion at #116 and it seems to be liked by users [as there was a question regarding it on tex.stackexchange](http://tex.stackexchange.com/q/294906/9075).

No indent would us bring closer to original bibtex format, but away from the biblatex format.

Example from page 32 of biblatex's manual:

grabbed_20160228-152131

**Comment by koppor** [comment]
Decision: Do not merge. Do the long term fix described at https://github.com/JabRef/jabref/issues/574#issuecomment-193718235.

**Comment by koppor** [comment]
Refs #1043

**Pull request closed without merging**
