### PR TITLE
Add HTTP server for MS Office Word integration

### PR DESCRIPTION
**Pull request by tobiasdiez**
Adds HTTP server for Office integration. At the moment, it's only a prototype showing that we do have enough space in our module list to include the jdk.httpserver (which is unfortunatly not as dev-friendly as other solutions, but works fine).

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by Siedlerchr** [comment]
See my otherPR https://github.com/koppor/jabref/pull/628 for setting up a nice REST API

**Comment by tobiasdiez** [comment]
@Siedlerchr the point here is that jdk.httpserver is small enough to be included while jetty/tomcat and (probably undertow) are too large. Thus, in the short term this seems to be our only option.

**Comment by koppor** [comment]
Sacrificing code maintainability because of a bug in the language environment 🙈

**Comment by tobiasdiez** [comment]
It's not that terrible, just a bit more low-level and can be abstracted away. But yes, if that's what it takes to play around the annoying jdk bug but have a nice user experience, then I'm fine with it.

**Comment by Siedlerchr** [comment]
We need to have SSL support enabled for the office addin

**Comment by koppor** [comment]
Superseeded by https://github.com/JabRef/jabref/pull/9748

**Pull request closed without merging**
