### PR TITLE
Improve code of BibDataBaseDiff

### PR DESCRIPTION
**Pull request by koppor**
Made during thinking of https://github.com/JabRef/jabref/issues/4877 (but did not work)

### Mandatory checks

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by Siedlerchr** [comment]
I could stil reproduce it sometimes with the file field, it seems the formatting differs, I have autosve enabled and reformat is disabled. I stored the bib file in nextcloud synced folder. (tested on mac)

 see the entries:
[test2entries.zip](https://github.com/user-attachments/files/15749349/test2entries.zip)

If you quickly type into the comemnt field some gibberish text and wait it will also trigger the dialog.

**Comment by koppor** [comment]
I would take a different approach to disable the changes if the file in disk is the saved file.

Reason: Save actions modify the file. That should happen silently...

**Comment by Siedlerchr** [comment]
Yes, that seems like a good idea, but isn't the change scanner basically doing this? Except that we compare it with the in memory library

**Comment by koppor** [comment]
> Yes, that seems like a good idea, but isn't the change scanner basically doing this? Except that we compare it with the in memory library

Memory is not equal to disk because of white space removal. File field could be different thing. I don't know yet.

Memory and disk is same for applied save actions, because these propagate back to the memory - but lead to cursor jumping.

**Comment by Siedlerchr** [comment]
> Memory is not equal to disk because of white space removal. File field could be different thing. I don't know yet.

Another thing related to autosave: Should autosave trigger only when leaving the field?

File field is treated as mulitline field at least in FieldContentFormatter
For file we have FileFieldwriter . however that is directly applied after setting the field

**Review by Siedlerchr — APPROVED** [review]

**Pull request merged**
