### PR TITLE
ISBN2Bibtex warning is now more clear when no entry is found 

### PR DESCRIPTION
**Pull request by Siedlerchr**
Finished the full Request, hope now all is correct.   #684

### CODE REVIEW

**Comment by koppor** [comment]
Yeah, keep them. Just do

- git gui
- [x] amend last commit
- unstage the change of JabRef_en.properties
- commit
- push with [x] force overwrite.

Then, this PR should be updated correctly.

**Comment by Siedlerchr** [comment]
@koppor Thanks for the instructions. Worked.

**Comment by koppor** [comment]
I have no clue, why the tests fail. Could merge the master branch and rebase? I tried to describe the steps at https://github.com/JabRef/jabref/pull/689#issuecomment-173824448

**Comment by tobiasdiez** [comment]
@koppor I think the failing test has nothing to do with this PR since the same test also fails locally for me with the current master. 

The PR looks good to me & can be merged in.

**Comment by Siedlerchr** [comment]
I just noticed that on the FAQ Section in the Website, the wrong Pull Request is linked in the Section "Q: I have an ISBN"  At the moment #791  is linked and not #761

**Comment by oscargus** [comment]
I corrected it. Thanks for pointing it out.

**Pull request merged**
