### PR TITLE
Delete link after download

### LINKED ISSUE #6588: Delete online link after download
**Is your suggestion for improvement related to a problem? Please describe.**
When downloading an linked online file, the online link is kept.

**Describe the solution you'd like**
Automatically delete online link. Since some people might prefer to keep the link, a new preference option would be good I guess.

### PR DESCRIPTION
**Pull request by tobiasdiez**
Fixes #6588.

- [ ] Change in CHANGELOG.md described (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by koppor** [comment]
Replaced `Optional<Integer>` by `int` as we directly operate on the list and do not use the full power of `Optiona.`.

**Comment by tobiasdiez** [comment]
I don't really think that the new version is much more readable, but ok...

**Comment by koppor** [comment]
@koppor Please test 

1. Pre-condition: Entry with link (in the file field)
2. Right-click: download
3. Link should be replaced

**Comment by koppor** [comment]
Tried it out locally. Works.

grafik

**Pull request merged**
