### PR TITLE
Remove preferences and globals from tests

### PR DESCRIPTION
**Pull request by tobiasdiez**
This PR aims to make @lenhard happy again by introducing huge architectural constraints on our tests: they are not allowed to work with the preferences class anymore. As a positive side-effect also @koppor will be happy about this as tests now can no longer accidentally change or reset your preferences.  

Changes in detail:
- Remove `JabRefPreferences.getInstance` or `Globals.prefs` by mocking away all preferences class (like `LayoutFormatterPreferences`)
- Refactor `KeyBindinings` and `JournalAbbreviations` so that these classes don't operate on the `JabRefPreferences` class anymore. This required to hide some methods of the preferences in a new interface 
`PreferencesService`.
- Create architectural tests for the tests

-----

- [ ] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [ ] Screenshots added (for bigger UI changes)
- [ ] Manually tested changed features in running JabRef
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)
- [ ] If you changed the localization: Did you run `gradle localizationUpdate`?

### CODE REVIEW

**Comment by Siedlerchr** [comment]
In general LGTM but please have a look at the fetcher test, there seems to be some NPEs occuring wich maybe related to this PR/the mocking

**Comment by tobiasdiez** [comment]
Ups, I forgot to fix the fetcher tests. This is done now, except that the ISBN Chimbori fetcher seems to be totally broken (@koppor this is your baby, right?)

**Comment by Siedlerchr** [comment]
I merge this now. Please open a new issue for the ISBN fetcher.

**Comment by koppor** [comment]
This refs https://github.com/JabRef/jabref/issues/110#issuecomment-134308159.

**Pull request merged**
