### PR TITLE
Improve change scanner

### LINKED ISSUE #5257: Jabref reports inexistent changes
JabRef version 5.0-dev

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

Jabref frequently reports external changes although there have been none (I could find the corresponding bug report). Now, it also reports changed fields. However, both values are identical, e.g.
```
Modification of field: DATE
Value set externally: 1987
Current value: 1987
Modification of field: LOCATION
Value set externally: Stroudsburg, PA, USA
Current value: Stroudsburg, PA, USA
```

### PR DESCRIPTION
**Pull request by tobiasdiez**
If a file is changed externally, JabRef is doing a 3-way merge between the last saved value vs current value in JabRef vs new value in file.
The way this is done is by first comparing the last saved file with the current (changed) file, and then trying to find additional/other changes in the currently open database. This is really complex and I believe there is some subtle bug in the logic leading to #5257.

With this PR, the change scanner is changed to a to simple 2-way merge between the current value in JabRef vs new value in file. This is way simpler and I hope this PR fixes #5257.
In a few edge cases, the 2-way merge has a small disadvantage. For example, consider the following steps:
- User A opens file
- User A changes field `Author` to `User A` and adds field `Title` with value `new`
- User B opens file
- User B changes field `Author` to `User B`
- User B saves file

At this point, User A gets a message that the file changed with the following changes:
- field `Author` changed from `User A` to `User B`
- field `Title` was removed

The 3-way merge could detect that `Title` was newly added, and thus could automatically reapply this change.  This is no longer possible with the simple 2-way merge.

- [ ] Change in CHANGELOG.md described (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for bigger UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not: Issue created at <https://github.com/JabRef/user-documentation/issues>.

### CODE REVIEW

**Comment by Siedlerchr** [comment]
We have to be careful how this works together with a shared database

**Comment by tobiasdiez** [comment]
The shared databases have their own update/sync mechanism. But I do agree that this should be made consistent at some point.

**Comment by koppor** [comment]
I am making it consistent in my local dev branch. That one will use the merge entries dialog as it is the case in the shared database dialog. Does also cover the edge case by @tobiasdiez

**Comment by koppor** [comment]
Is the reference file updated after the conflicts are reported? (Is it necessary? I would guess: yes, because changes reported should not be reported again - and the reference file is not the bib file on disk)

Is it possible to add some test cases?

**Comment by tobiasdiez** [comment]
I removed the reference file completely...

**Comment by koppor** [comment]
How hard is it to embed the [merge entries dialog](https://docs.jabref.org/finding-sorting-and-cleaning-entries/mergeentries) at the yellow place below?

grafik

**Comment by Siedlerchr** [comment]
@koppor The merge entries dialog is already consisting of a BorderPane called `MergeEntries` which can be embedded easily. See the `MergeEntriesDialog`

**Comment by koppor** [comment]
Minor wish: <kbd>Esc</kbd> should be enabled for closing the dialog.

(Refs https://github.com/JabRef/jabref/issues/2949)

**Comment by koppor** [comment]
@siedlerchr great! May I ask whether you could do it?

**Comment by Siedlerchr** [comment]
I if can wait until this evening or afternoon I can try to add it.

**Comment by tobiasdiez** [comment]
Improved the PR based on the comments. So, we are going ahead with this PR and further work on https://github.com/JabRef/jabref/pull/5669 after the release of 5.0?

**Comment by koppor** [comment]
This PR has the advantage that it's finished and seems to work 🎉 

Maybe we will offer both possibilities:

- transparent merge of changes (#5669)
- explicit merge of changes (this PR)

@Siedlerchr Can you do the integration of the merge entries dialog in a separate PR? - This evening is still long and I am really looking forward to it. Meanwhile, I'll work on the other PR.

**Pull request merged**
