### PR TITLE
Increase size of file and keywords editors

### PR DESCRIPTION
**Pull request by lenhard**
In the new EntryEditor, we have the problem that sometimes text in the TextAreas is hard to read, because the areas are very narrow. The reason for this is that Java tries to fit them in the available display space. Examples: #3130 #3117 #2941

This PR sets a minimum size for all TextAreas in the EntryEditor. The value of 70px is rather arbitrary and I'll be happy to get some thoughts if this is good or if more or less is desirable. With this minimum size all TextAreas are nicer to read, even in the cramped up General tab. The only "problem" is that you now need to scroll in the General tab most of the time. 

All in all I think this should definitly go into 4.0!

- [X] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [ ] Screenshots added (for bigger UI changes)
- [x] Manually tested changed features in running JabRef
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)
- [ ] If you changed the localization: Did you run `gradle localizationUpdate`?

### CODE REVIEW

**Comment by tobiasdiez** [comment]
To be honest, I'm not a big fan of the increased size. I prefer to have as much information on the screen as possible and not to have to scroll. On the other hand, I acknowledge that the current layout is also suboptimal as the text fields are not expanding on their own when they contain much information. Maybe it is already enough to increase the `prefered` height (instead of minimum)?

**Comment by lenhard** [comment]
@tobiasdiez Ok, you have the same opinion as @koppor I guess.

Increasing the preferred height didn't help unfortunately. We can leave most field editors as they are, but we have to increase the size of the file and the the keywords editor. Those are the two editors in the cramped general tab where users could enter information with more than a single line. That doesn't look good at all and really does annoy users.

I've tried to change just these two editors in code, but failed. Whenever I call `setMinWidth` in https://github.com/JabRef/jabref/blob/master/src/main/java/org/jabref/gui/fieldeditors/LinkedFilesEditor.java or change the `minHeight` in the related fxml file, the min height of all field editors in the tab increase. Any hint?

**Comment by tobiasdiez** [comment]
The problem is probably https://github.com/JabRef/jabref/blob/master/src/main/java/org/jabref/gui/entryeditor/FieldsEditorTab.java#L166, where the rows are set to have the same height.

**Comment by matthiasgeiger** [comment]
Quick idea: If the row constraints are the problem, it might be an option to use two rows for the File/Keyword editors

**Comment by lenhard** [comment]
@matthiasgeiger Not sure if that's easily possible. The best solution is probably to write new subclass of EntryEditorTab.

**Comment by tobiasdiez** [comment]
Or extend the `FXFieldEditor` by a `getWeight` method, which you can use in https://github.com/JabRef/jabref/blob/master/src/main/java/org/jabref/gui/entryeditor/FieldsEditorTab.java#L114.

**Comment by lenhard** [comment]
Ok, I've implemented a hack that assigns twice the space of normal rows to the keyword and file field editors.

As I said, this is a hack. But before I turn this into something more acceptable (along your suggestion @tobiasdiez ), I would like to get confirmation from the team that this is a solution that we can live with visually in the JabRef UI. If not, than I am just wasting my time with GUI hacking.

**Comment by lenhard** [comment]
And now I refactored it anyway... JabRef continues to ruin my lunch time.

**Comment by koppor** [comment]
I tried out the new solution locally and it looks good enough. On two-column tabs, the things shrink too much, but we discussed in the devcall that it is difficult to determine the right "min-height". (screen resolution etc).

So, good to merge.

**Comment by lenhard** [comment]
As discussed in the dev call, I am merging this now.

**Pull request merged**
