### PR TITLE
[WIP] First attempt at using TextAnalyzer

### PR DESCRIPTION
**Pull request by oscargus**
I thought I'd give the TextAnalyzer a go and it turns out that it can find year and pages numbers from my limited experiments. However, although volume and journal theoretically could be found I haven't figured out which format it succeeds in. 

To test it select "New entry from plain text", paste a reference in some format and press the wand.

The reverse marking is not fully working, I know. Not sure if I will progress on this one, it seems to be quite a bit of work to improve TextAnalyzer, but as a reference and starting point.

### CODE REVIEW

**Comment by oscargus** [comment]
Ready-built versions available at http://builds.jabref.org/usetextanalyzer/

**Comment by koppor** [comment]
The idea is great. I'd love to have the result of "Parse with Freecite" integrated the same way.

However, could you provide us with an example entry? When I tried the following entry, only "12" is highlighted.

    Binz, Tobias; Breiter, Gerd; Leymann, Frank; Spatzier, Thomas: Portable Cloud Services Using TOSCA. In: IEEE Internet Computing. Vol. 16(03), Los Alamitos, CA, USA: IEEE Computer Society, 2012.

grabbed_20151221-114440

**Comment by oscargus** [comment]
Yes, that is indeed one of the problems. The year is found and later on processed in several steps before the actual position is stored. This is still slightly better than the original version of TextAnalyzer. I couldn't really bother to work more on it yesterday as there were so many other issues. However, this particular one should be rather manageable. 

If you add page numbers those will be correctly extracted (but incorrectly highlighted) as well.

**Comment by simonharrer** [comment]
What about this PR? Any idea how to progress there? Is it good enough already to be merged? Does it already create value or improves the code quality of JabRef?

**Comment by oscargus** [comment]
The problem is that TextAnalyzer only can guess very few fields (year, pages, volume, journal) and not really consistently. The GUI issues can be fixed quite quickly, but I do not think it is worthwhile as long as TextAnalyzer is not more mature.

It is worthwhile merging from the perspective that if anyone gives it a go, TextAnalyzer is slightly better now. However, the GUI part should probably be removed for now, commenting out lines 232-233 in TextInputDialog for easy restoring.

But I strongly believe that no one will improve TextAnalyzer enough, so it may be better to remove it completely.

**Comment by simonharrer** [comment]
We decided at JabCon that we remove this feature.

**Pull request closed without merging**
