### PR TITLE
String to int conversion

### PR DESCRIPTION
**Pull request by oscargus**
Replaced the Integer.parseInt() and Integer.valueOf() calls with Util.intValueOf(), which is a faster implementation.

Most of the time this won't matter, but since the method is there... (See #269)

### CODE REVIEW

**Comment by stefan-kolb** [comment]
I'm not a fan of using custom methods for JDK defaults if it isn't necessary from a performance standpoint.

**Comment by koppor** [comment]
I don't have a strong opinion on that. One the hand hand consistency, on the other hand least surprise. I lean towards the concept of least surprise.

**Comment by matthiasgeiger** [comment]
Same here. If it is not **really** necessary due to performance issues, use the "standard" API methods.

**Comment by simonharrer** [comment]
I think a consensus is reached here that this PR is to be closed without merging.

**Pull request closed without merging**
