### PR TITLE
Rename Groups interface into Groups

### LINKED ISSUE #8447: Menu: Rename "Groups interface" into "Groups"
Here is the View menu:
ksnip_20220119-101236

**Is your suggestion for improvement related to a problem? Please describe.**
The Web search interface is named `Web search`.
The OpenOffice/LibreOffice interface is named `OpenOffice/LibreOffice`.

Why to name the Groups interface `Groups interface`?

**Describe the solution you'd like**
Naming it `Groups` should be enough.

### PR DESCRIPTION
**Pull request by mlep**
Fixes #8447.
So easy?!?

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by Siedlerchr** [comment]
You need to edit it here as well https://github.com/JabRef/jabref/blob/main/src/main/resources/l10n/JabRef_en.properties

**Comment by calixtus** [comment]
Why is the l10n test not failing?

**Comment by calixtus** [comment]
Bug triangulation:
- The consistency test should fail if the l10n-key is removed in the code but not in the language resource file.
- "Groups interface" is included in JabRef_en.properties but in IntelliJ the key in the resourcefile is not recognized as used.
- The language key is used in an enum ub StabdardActions

**Comment by Siedlerchr** [comment]
@calixtus  It is failng:
LocalizationConsistencyTest > findObsoleteLocalizationKeys() FAILED
    org.opentest4j.AssertionFailedError: Obsolete keys found in language properties file: 

    Groups interface

    1. CHECK IF THE KEY IS REALLY NOT USED ANYMORE
    2. REMOVE THESE FROM THE ENGLISH LANGUAGE FILE
     ==> expected: <[]> but was: <[Groups interface]>

**Comment by mlep** [comment]
So, yeah, not so easy... :cry:

**Review by Siedlerchr — APPROVED** [review]

**Review by calixtus — APPROVED** [review]

**Comment by calixtus** [comment]
Must have overlooked it...
Thanks for the contribution, merging now!

**Comment by calixtus** [comment]
Why messy? It was perfectly fine!

**Comment by mlep** [comment]
Thanks. When I saw it was failing and led to discussion, I thought it was a dumb action from me.
Considering it was a success, I may try again. :wink:

**Comment by calixtus** [comment]
You should absolutley! 👍

**Pull request merged**
