### PR TITLE
Move CSL to buildres/csl to speedup "processResources" during development

### PR DESCRIPTION
**Pull request by koppor**
`processResources` takes approx. 2 minutes at a fresh run on my [Samsung 980 Pro](https://www.pcgameshardware.de/SSD-Hardware-255552/Tests/Samsung-SSD-980-Pro-Test-1358542/). I think, the reason is the 10.000 CSL files and a slow NTFS file system when it comes to small files.

```
$ gradlew processResources

> Configure project :
Project : => 'org.jabref' Java module

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.5/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 1m 59s
1 actionable task: 1 executed
```

With this patch, it takes 7 seconds.

```
$ gradlew processResources

> Configure project :
Project : => 'org.jabref' Java module

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.5/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 7s
1 actionable task: 1 executed
```

I left some CSL files in the normal resources to ensure that testing is still possible.

When a release is build, all CSL files are still copied.

- [ ] Change in CHANGELOG.md described (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by koppor** [comment]
Tested locally at six-eyes-principle. works.

**Review by DominikVoigt — APPROVED** [review]
Looks good to me!

**Comment by calixtus** [comment]
Looks (literally) good (g...) to me

**Review by calixtus — APPROVED** [review]

**Comment by koppor** [comment]
Side note: When copying the `csl-locales` locally using the Windows Explorer, it also took me more than 10 seconds.

**Comment by Siedlerchr** [comment]
Gradlew run now results in error when opening preferences: 
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:208)
	at org.jabref@100.0.0/org.jabref.logic.citationstyle.CitationStyle.discoverCitationStyles(CitationStyle.java:138)
	at org.jabref@100.0.0/org.jabref.gui.util.BackgroundTask$1.call(BackgroundTask.java:59)
	at org.jabref@100.0.0/org.jabref.gui.util.DefaultTaskExecutor$1.call(DefaultTaskExecutor.java:160)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

**Comment by koppor** [comment]
Fixed at https://github.com/JabRef/jabref/commit/8c49600df0e714f4806e4a4d2cf3702994d8ec3b. Tested the end-user distribution only back then...

**Pull request merged**
