### PR TITLE
Try to debug new oracle action version

### PR DESCRIPTION
**Pull request by koppor**
Try to debug new oracle setup-java action.

It runs on Java 21 - https://github.com/oracle-actions/setup-java/releases/tag/v1.3.4

### Mandatory checks

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by koppor** [comment]
This downgrades the action to the last one without requirement to JDK21 (which is unavailable on BuildJet)

**Comment by koppor** [comment]
Alternatively, we could set `JAVA_HOME_21_arm64` in the workflow to the JDK17.

**Comment by koppor** [comment]
Security: For higher security, we could pin the versions to SHA https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions. - Not sure, how this works with dependabot.

**Comment by koppor** [comment]
Drawack: We cannot run on ARM64 with that - https://github.com/oracle-actions/setup-java/pull/73

**Review by Siedlerchr — APPROVED** [review]

**Pull request merged**
