### PR TITLE
Merge identical group colors

### LINKED ISSUE #6175: Group color, only display identical colors once
Suppose i have the following Categories and Subcategories
Category: Food: Subcategory: Nuts
Category: Trees: Subcategory: Nut trees

Now it is possible (and makes sense) to assign a single colour to both subcategory Nuts and Nut trees.  Some papers however, will naturally be categorized in both groups. In such instances, Jabref currently displays twice the colour in the main table (in the column group color). Would it be possible to only display the unique colours?

I hope this (rather contrived) example is clear.  Please let me know if not!

### PR DESCRIPTION
**Pull request by WangAooa**
Fixes #6175
Hi, I made some mistake that close the PR. This is a new PR about #6175 issue.

- [x] Change in CHANGELOG.md described (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by calixtus** [comment]
Hi @WangAooa , thanks for reintroducing this PR. However, @tobiasdiez asked for some changes in the other PR. Please fix the checkstyle issues and consider the changes he asked for.

**Comment by calixtus** [comment]
https://github.com/JabRef/jabref/pull/6491#pullrequestreview-416035892

**Comment by koppor** [comment]
This is a good start. Since there was no activity since a few weeks, we would like to ask whether there is some interest in continuing in this.

**Comment by calixtus** [comment]
Hi @WangAooa , since there was no progress here and we like the idea, we gonna take this over and finish it soon. Thanks for your work.

**Pull request closed without merging**
