### PR TITLE
Fix icon color in dark mode

### LINKED ISSUE #7853: Icons in Entry Edit Window not visible in Dark Mode
JabRef version 5.3--2021-06-27--aa60dd6 on Windows 10

I have tested the latest development version from http://builds.jabref.org/main and the problem persists

The icons in the entry edit window are frequently too dark to be visible in dark mode. A bright color would be better suited

1. change to dark mode
2. edit an entry
3. view icons

Screenshot 2021-06-28 132651

### PR DESCRIPTION
**Pull request by Joe11028**
A new PR to #7917, fixes #7853
QQ截图20210802082831
by adding this at the end of PreferencesDialog.css and it works. Here's comparison.
**BEFORE**
QQ截图20210718171836
QQ截图20210718171728
QQ截图20210718171802
QQ截图20210718171824
**AFTER**
QQ截图20210802081841
QQ截图20210802081849
QQ截图20210802081709
QQ截图20210802081729

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by calixtus** [comment]
I'm pretty sure we use Ikonli-icons not just in the preferences dialog. So i guess it would be better, to put that into the base.css?

**Comment by calixtus** [comment]
Btw, keeping the checkboxes in the PR description and checking them, if apllicable is **mandatory**!

**Comment by calixtus** [comment]
Why did you open a new PR instead of pushing your commit onto the old branch?

**Comment by Joe11028** [comment]
@calixtus I've tried put it in base.css, but it also changes something else, which makes it weird.
QQ截图20210802080608
I think it should look like the following pic.
QQ截图20210802081709
So I just add it on perferencesDialog

**Review by Joe11028 — COMMENTED** [review]
A discription to the work i've done.

**Comment by Siedlerchr** [comment]
You only need to add it to Dark.css so that it only is applied when you select the Dark theme

**Comment by Joe11028** [comment]
@Siedlerchr I know, but in the figures following:
InkedQQ截图20210802080608_LI
InkedQQ截图20210802081709_LI
In this dialog, these icons' color will change, so I think put this code in PreferencesDialog.css would be better.

**Comment by Siedlerchr** [comment]
try the following (in Base.css)

to .glyph icon add     -fx-icon-color: -jr-theme-text; 
and before add the ikonli font icon

```
.ikonli-font-icon {
	-fx-icon-color: red;
}
.glyph-icon {
    /* This adjusts text alignment within the bounds of text nodes so that
       the text is always vertically centered within the bounds. Based on
       the cap height of the text. */
    -fx-bounds-type: logical_vertical_center;

    /* The base color of icons should always be the same as the text. */
    -fx-fill: -fx-text-base-color;
    -fx-icon-color: -jr-theme-text;
}
```

**Comment by Joe11028** [comment]
@Siedlerchr In this way, it works but still have problems. In the figure, you can see this icon is colored by the theme-color while it should be the text base color.
QQ截图20210802151804

**Comment by Siedlerchr** [comment]
If you look into IconTheme, you see that there is a method asButton which adds another css class and makes it an icon-button. Seems like you need to add an extra rule for that

**Pull request closed without merging**
