### PR TITLE
Fix import entry by id does not generate citation key

### LINKED ISSUE #8406: When pasting an entry into jabref, check whether key already exists
**Is your suggestion for improvement related to a problem? Please describe.**
When I paste an entry into JabRef, I occasionally mess up my library because an entry with that citation key already exists.

**Describe the solution you'd like**
JabRef should notify me when I paste an entry and an entry with the same key already exists. I think this already happens as part of the import function, but not when an entry is pasted.

### PR DESCRIPTION
**Pull request by Siedlerchr**
Fixes https://github.com/koppor/jabref/issues/553
Fixes  #8406

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by ThiloteE** [comment]
Would also fix #8354

**Comment by tobiasdiez** [comment]
Can we reuse the import handler here so that other features (like automatically generating timestamps etc) are also working as expected?

**Comment by Siedlerchr** [comment]
Good idea, but the import handler does not check for duplicates.  That only happens in the New Entry dialog

**Comment by tobiasdiez** [comment]
I guess it make sense to extract the duplication check also to the import handler. Then one would get also a duplication warning if one say uses copy&paste of an id to create an entry. That's a nice enhancement in my opinion. (The only situation where you don't need this check is after the import dialog, which already handles this.)

**Comment by ThiloteE** [comment]
Related: #8406

**Comment by Siedlerchr** [comment]
When an entry is pasted or imported by id and already exists, the duplicate resolver dialogs opens. And also the keys are generated
Works also for pasting DOI.
@ThiloteE  you can test here 
https://builds.jabref.org/pull/8361/merge/

**Comment by ThiloteE** [comment]
Found a bug:

1. have entry1 in libraryA
2. have entry2 to libraryB
3. Both have similar entry data, except citationkey.
4. Copy and paste entry2 to libraryA.
5. The entry merge dialogue will emerge
6. Click on "Do not import entry" OR click on the X in the top right corner of the entry merge dialogue (to close the dialogue).

- The entry2 WILL get imported.
- (This entry2 will get assigned a new citation key that follows my citation key patterns I declared in my preferences, It will be two different citationkeys, because duplicate prevention adds a letter at the end.)

Expected outcome:

This entry2 SHOULD NOT get imported.

Expected outcome: The entry should NOT get imported.

**Comment by ThiloteE** [comment]
Bug 2:

0.1 Have "overwrite existing keys" in Keygen preferences DISABLED.
0.2 Have a key pattern in keygenerator
1. Have entry3 with DOI in LibraryC
2. Copy DOI.
3. Paste DOI in LibraryC
4. Entry Editor emerges
   image
5. Choose "import and keep old entry"

**What happens:**

- Old entry is kept (good!)
- A new entry is imported, but old citationkey is overwritten by citationkey pattern that was specified under preferences.

Expected Outcome:

- The new entry is imported with original citationkey from internet (grobid maybe?). 
- The citationkey should NOT be overwritten.

**Comment by ThiloteE** [comment]
Sorry. 😅

**Comment by Siedlerchr** [comment]
Thanks for testing, will check this again  wth the right/left thing

**Comment by Siedlerchr** [comment]
@ThiloteE  I fixed the cancellation and the order in the dialog. Can you please test again?
https://builds.jabref.org/pull/8361/merge/

**Comment by ThiloteE** [comment]
Looking quite good! Solved 2 issues. 1 new issue pops up 😂 Hopefully the last one.

Bug3:

1. Have  `options>preferenes>import and export>generate a new key for imported entries (overwriting their default)` enabled.
2. Have a customized key-pattern for the citation-key generator set in preferences.
3. Have this preference set under citation-key generator preferences:
   image
3. Import entry by ID into library5 **OR** paste entry5 by ID into library5. Let's call this one entry5.
4. Import entry by ID into library5 **OR** paste entry5 by ID into library5 AGAIN. Let's call this one entry5².
   - Duplicate Merge Editor will emerge. So far so good.
5. Click `keep merged entry only`

Result:

- 
- entry5² will get assigned `citationkey-according-to-my-pattern`+`a`

Expected result:
- entry5² will get assigned `citationkey-according-to-my-pattern`


**Additional info:**

This becomes really weird when entry5 and entry5² are not exactly identical. E.g. 
- entry5: date = {2016}
- entry5²: date = {2016-10-02}

My key pattern includes the date into the citation-key. Therefore,

key before merge: `2016`
key after merge: `2016-10-02a`, EVEN THOUGH 2016-10-02 would be unique in my library.





I think all the others work

**Comment by Siedlerchr** [comment]
I reverted the changes to the citation key method as this would break more tests and is an unusual edge case.

**Comment by koppor** [comment]
I can confirm it fixes https://github.com/koppor/jabref/issues/553.

It does NOT fix https://github.com/JabRef/jabref/issues/8406. See https://www.loom.com/share/0c29cb50e91c431488a54c3c5266379d.

**Review by calixtus — APPROVED** [review]

**Comment by Siedlerchr** [comment]
@koppor This is odd. I tested it with copy and paste and @ThiloteE  as well. Maybe you have some of your citation key generator settings modifeid?

**Pull request merged**
