### PR TITLE
Add gtk3 support

### PR DESCRIPTION
**Pull request by LyzardKing**
This is a WIP to solve #5298 

----

- [ ] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [ ] Manually tested changed features in running JabRef
- [ ] Screenshots added in PR description (for bigger UI changes)
- [ ] Ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)

### CODE REVIEW

**Comment by LyzardKing** [comment]
@Siedlerchr Do I have to change something in the build system?

**Comment by Siedlerchr** [comment]
Well, gradle is still used for compiling and building. I am unfortunately not sure how and if this jlink stuff is needed for running

**Comment by LyzardKing** [comment]
Could we loop @tobiasdiez in this work?
Is there any difference in the build/run of the linux builds?

**Comment by Siedlerchr** [comment]
```
Failed to generate snap metadata: The specified command 'desktop-launch' defined in the app 'jabref' does not exist or is not executable.
Ensure that 'desktop-launch' is installed with the correct path.

```
https://build.snapcraft.io/user/JabRef/jabref/670638

**Comment by LyzardKing** [comment]
I'll try and run the exact build (in lxd) like the server did.

**Comment by tobiasdiez** [comment]
I have no experience, with snapcraft so I cannot say much about that. For the build, it should look as follows:
- Run `gradle jlink`. This gives you a `build/image` folder containing a working runtime image (JabRef + all dependencies including the necessary java libraries). 
- In `image/bin`, you find some (platform-dependent) luncher scripts (on Windows: `JabRef.bat`).

So the snapcraft build should bundle the `image` folder together (or directly use the zip created by `gradle jlinkzip`) and invoke the correct lunch script (or replicate what they contain).

**Comment by LyzardKing** [comment]
Thanks! I'll try a few changes now...

**Pull request merged**
