### PR TITLE
Add SonarCloud Trigger

### PR DESCRIPTION
**Pull request by koppor**
SonarCloud offers great code quality analysis. This PR enables it.

Refs https://github.com/JabRef/jabref/pull/5991

### CODE REVIEW

**Comment by tobiasdiez** [comment]
I still have to see valuable recommendations from these static code analyzers, but well let's try another one ;-)

Why is this PR needed? It appears that sonarcloud is already posting to PRs (which is a bit annoying to be honest, would have preferred a github action)

**Comment by Siedlerchr** [comment]
I'm also against using them. They have more false positives than valuable recommendations. Annoying

**Comment by koppor** [comment]
I agree that the comments are annoying. We are trying to turn them off.

Nevertheless having all tools running enables JabRef being part of teaching Software Engineering. For instance, statement such as "more false positives than valuable recommendations" can be quantified when a) the analysis results are available and b) results of other products are available. Otherwise, that statement makes an impression to me made out of the blue based on other experiences, but not with the current code at hand.

**Comment by koppor** [comment]
Because of https://community.sonarsource.com/t/disable-github-merge-request-comments/18520/19, I will not go forward. (PR commenting cannot be disabled)

Ticket https://jira.sonarsource.com/browse/SCCOMM-19 - please vote for it 🎉

**Pull request closed without merging**
