### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by Siedlerchr**
Enjoy!

### CODE REVIEW

**Comment by Siedlerchr** [comment]
do not merge

**Comment by Siedlerchr** [comment]
Note for future new languages: Upload the file in crowdin, Changes on github are not synced back

**Comment by calixtus** [comment]
There seems to be something wrong with this PR. The changes to JabRef_de.properties are

Filter=Filtro
Icon=Ícone
Link=Linkar
Name=Nome
OK=Ok

This is not german... 😃

**Comment by Siedlerchr** [comment]
Thanks for spotting! Yeah, there was a problem with crowdin 🙄 . There was a confusion with the portguse import of the files, I was overwriting the German files with portguese. Replaced it again with German afterwards, but seemed like some were not replaced. Should be fixed in the next sync

**Pull request merged**
