### PR TITLE
Error setting field freeze

### PR DESCRIPTION
**Pull request by grimes2**
- [x] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [ ] Screenshots added (for bigger UI changes)
- [x] Manually tested changed features in running JabRef
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)

### CODE REVIEW

**Comment by lenhard** [comment]
Refs #1757

It is always nice to see a new contributor! :) You took a rather challenging task for your first contribution.

When you consider your PR ready, please indicate this to us by setting the label "ready-for-review" at the right hand side. Then, we will have a look at your code, comment on things to improve, and try to verify and test that your solution works as desired. 

Probably @oscargus should have a look at this.

**Comment by grimes2** [comment]
My pull request is ready. Please set the label "ready-for-review".

**Comment by oscargus** [comment]
Thanks! It clearly solves the problem! However, it also removes the warning when changing field, but I am not sure if this is an improvement or an issue. ;-) A maybe more serious issue is that when selecting another entry, no warning is shown either and the edit is dropped. However, the dropping appears without the fix as well, so again, the question is what is the worst.

One thing is clear, that even though this fix solves the crash problem, which is clearly significant, we really need to look into this automatic field storage/warning mechanism... Also, the red color only flashes by in some situations, although the dialog shows up, so many events happening more or less at the same time. I guess I'm not missing many brackets as I haven't really notices this earlier...

@JabRef/developers : crash on rare occasions or missing warnings slightly more often? I'd say missing warnings.
@grimes2 : feel free to add a change log entry, if not, I'll do it later.

**Comment by grimes2** [comment]
I can add a else branch with the red background color only, for the EDT Events. A error message is impossible, because JOptionPane is not thread-safe.

**Comment by oscargus** [comment]
Yes, either that or set the background outside of the if. Another good thing with the fix is that only one dialog is shown for the save toolbar button. :+1:

**Comment by lenhard** [comment]
@oscargus Missed warnings are certainly preferable to application crashes. Moreover, I can confirm the change losses when selecting a new entry. I will open a new issue for that.

I have tested this PR locally and can confirm that it fixes #1757. The coloring also seems to be consistent after the last commit.

All that is missing for merging is the Changelog entry. This is a little complicated since we had the intermediate release of 3.6. @grimes2: It would be best if you merge master into your branch before editing the Changelog. This should carry over the release data.

**Comment by grimes2** [comment]
I don't know, how to merge master into branch.

**Comment by Siedlerchr** [comment]
If you have setup your local git repository  (look here for details on how to https://help.github.com/articles/fork-a-repo/)
git fetch upstream 
git merge upstream/master
Resolve any conflicts
git push (best done over the git gui)

https://github.com/JabRef/jabref/wiki/Guidelines-for-setting-up-a-local-workspace

**Comment by oscargus** [comment]
Great, thanks! I merge this in.

**Comment by oscargus** [comment]
@grimes Feel free to open a PR with your name added in https://github.com/JabRef/jabref/blob/master/AUTHORS 

We forgot about that. Not so used with new contributors... :+1:

**Comment by stefan-kolb** [comment]
This is autogenerated from the git history @oscargus

**Comment by oscargus** [comment]
Ah, OK! Thanks @stefan-kolb .

**Pull request merged**
