### PR TITLE
Add support for Microsoft Edge browser in Windows and Linux builds

### PR DESCRIPTION
**Pull request by LyzardKing**
Fixes https://github.com/JabRef/JabRef-Browser-Extension/issues/238
This PR adds the support for the Edge browser on Windows and Linux.
It still needs testing, especially the Windows support.

I will update the relevant documentation and changelog when the support has been tested.

- [x] Change in CHANGELOG.md described (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

**Review by tobiasdiez — APPROVED** [review]
Thanks a lot! Codewise this looks good to me.

For the renaming of the firefox json, it should be checked that it still works if you upgrade an older installation. I'm not sure if the uninstall actually cleans the registry/folder, so there might still be the old reference to `jabref.json`. If an upgrade-install works, this is good to go from my side.

**Comment by LyzardKing** [comment]
I didn't think about upgrades.. I can revert it back to the old name.
I can't run the test myself since the windows vm I use started crawling to a halt.

**Comment by tobiasdiez** [comment]
I'll see if I find the time the next days. If not, I propose, we are going to be brave, merge and let our alpha users test it ;-).

Can you please add a changelog, and open a PR for changes to https://github.com/JabRef/user-documentation/blob/master/en/collect/jabref-browser-extension.md which we can merge directly before the next release. Thanks.

**Comment by LyzardKing** [comment]
I'm working now on the documentation and changelog ;)

**Comment by LyzardKing** [comment]
Added the changelog and documentation updates.
I personally tested the Linux integration (deb+snap)

**Comment by Siedlerchr** [comment]
I can test Windows (Monday or Tuesday)

**Comment by Siedlerchr** [comment]
On windows 10 I can't find the extension in Edge, although the registry entry is set correctly. I will try again later with a restart of my computer. I had to upgrade the Edge installation first. Maybe that's the proble..
https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/native-messaging?tabs=windows

**Comment by Siedlerchr** [comment]
I tested it again I tested again, but I don't see the extension, neither in Firefox. nor in Edge.  Maybe it has something to do with the renaming?

**Comment by LyzardKing** [comment]
@Siedlerchr Have you installed the extension from the edge store?
It might be different if you install the chrome extension in edge..

**Comment by Siedlerchr** [comment]
Ah thanks for the hint. Works now. I didn'tknow I had to isntall it from the Edge store first

**Comment by LyzardKing** [comment]
It's a bit confusing, since you can technically install two parallel versions of the extension, from the edge store and the chrome store.
They have a different id, but apart from that they are the same..

**Pull request merged**
