### PR TITLE
Typos in teaching.md

### PR DESCRIPTION
**Pull request by Redevectored**
Removed a link leading to nothing, a comma and replaced "wirking" through "working".

- [ ] Change in CHANGELOG.md described (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by Redevectored** [comment]
Hello, 
I am new to this, apologies. The tests failed, and then I was confused, and then I tried to change the commit, 
-> the link was re-added. I'm not sure if I need to properly test it first.

**Comment by Siedlerchr** [comment]
The link should have led to an anchor (the # sign is used to identify text anchors .e.g headings)

**Comment by Redevectored** [comment]
Hello again, and thank you for your quick replies.

I think I broke that link, or it was already broken. After the sentence there is a sudden 1, and it doesn't lead me to any other header. 

Here the link to the docs where it is for convenience: 
https://devdocs.jabref.org/teaching#Ayaankazerouni

Apologies for the inconvenience. 
Greetings.

**Comment by Siedlerchr** [comment]
Ah now I understand it. It's supposed to be  a footnote link. If you scroll down to the References section. You see the 1 again.

The problem seems to be that gitbook doesn't support them https://gitbook.canny.io/feature-requests/p/footnotes
So it seems like the 1 should refer to the 1 at the bottom.

**Pull request merged**
