### PR TITLE
Deleted code related to the pdf and ps fields

### PR DESCRIPTION
**Pull request by oscargus**
Dropping the support for ps and pdf fields (which seems dropped already as hardcoding a pdf-field in a .bib-file doesn't even show up in the entry editor) seemed to remove quite a bit of code.

### CODE REVIEW

**Comment by simonharrer** [comment]
I am suprised that so much code is unused. But I do like it that we can throw so much unused code away! :)

**Comment by ajbelle** [comment]
I suspect that in all that code JabRef was providing the multiple root directory access functionality discussed in https://github.com/JabRef/jabref/issues/496 :-)

**Comment by oscargus** [comment]
Could be like that, yes. Doesn't it work for you anymore?

**Comment by ajbelle** [comment]
Sorry, so near end of my PhD I don't dare update, for fear of loosing access to thousands of references. My understanding is that the functionality I am using was 'never there' (none on the team understood what I was on about, and hence the lengthy  [#496](https://github.com/JabRef/jabref/issues/496)). I  thought you may have seen something that may have been enabling it, and was forewarning.

**Comment by ajbelle** [comment]
@oscargus Over Easter I updated to ver3.2 to try fix a Search issue. My install still finds the files I have residing in the old legacy pdf file structure that is not in the same tree as the JabRef files! No symbolic or hardlinks present, so I believe in magic! :-)  It must be coded elsewhere. happy Easter.

**Comment by oscargus** [comment]
@ajbelle this PR is not in 3.2 so maybe a bit too early to be fully relieved. ;-) However, I know of some code which currently supports different directories for different file types and I won't remove that. Not sure if that code is enough, but it might in fact be.

**Comment by oscargus** [comment]
This code was primarily related to the UI side, so any buttons magically showing up next to the PDF-field etc.

**Pull request merged**
