### PR TITLE
Show author/editor and journal/publisher in the main table by default

### PR DESCRIPTION
**Pull request by tobiasdiez**
Implements #470.

### CODE REVIEW

**Comment by koppor** [comment]
Looks like follows:

grabbed_20151205-225839

"Author/Editor" is OK.

Unsure if "Journal/Publisher" is confusing. I think, "booktitle/journal" would be the right correspondence. We should replace the default "journal" column by "booktitle/journal".

How often is `InBook` used? Consequently, `title` should become `chapter/title`, but that heading is confusing.

**Comment by oscargus** [comment]
I'd also vote for journal/booktitle (as that is what I use, dealing primarily with journal and conference papers). On the other hand, a good thing with this PR is that it indicates that these things are possible and how to do it.

**Comment by tobiasdiez** [comment]
The journal says where an article is published. Similarly, the publisher is...well... the publisher of the book. So I would advocate the proposed `journal/publisher`. Booktitle would probably only make sense for articles in conference proceedings. I think articles and books are the most common types, so we should focus on them.

@koppor: `InBook`s also have an author and title, so there shouldn't be a problem.

**Comment by oscargus** [comment]
Guess it depends on scientific area. I would possibly argue that in general, a publisher doesn't really add any important information, even for books, while in the case of conference papers, the booktitle is crucial. (I know that the publisher is important to create a valid reference, but it doesn't really add any information when browsing a database.)

**Comment by koppor** [comment]
In my discipline (computer science), I'd see the correspondence as follows (bibtex fields)

inproceedings | journal
------- | -------
title | title
author | author
booktitle | journal
publisher | publisher
year | year

For instance, take an Elsevier article (http://www.sciencedirect.com/science/article/pii/S0268401215000808). The publisher is Elsevier, but the Journal is "International Journal of Information Management". Elsevier publishes more than one journal.

I read "where something is published" as the conference and the concrete journal. The conference is stored in "booktitle", whereas the concrete journal is stored in "journal". Both kinds of works are published by a publisher.

Is it different in your discipline @tobiasdiez?

**Comment by oscargus** [comment]
I do not think @tobiasdiez disagrees with that analysis, but I got the
impression that he cites more books than conference papers. In that case I
can probably agree that publisher is the "next" field to add (mainly
because of lack of others).

Journal/booktitle/publisher? (Except for the very long heading...)

**Comment by tobiasdiez** [comment]
Ok apparently the majority is for booktitle. Hence I changed it accordingly. 

My reasoning was indeed based on `book`s for which the publisher is the equivalent of a journal. Since books occur more often in my database, I thought this addition was more valuable. For `InProceedings` the booktitle indeed makes more sense.

**Comment by koppor** [comment]
I suppose, `journal/booktitle/publisher` is too confusing? I really agree that the column `journal/booktitle` is empty too often if many books are in the database.

I'll merge it and let's see what others say. :sunflower:

**Pull request merged**
