### PR TITLE
Integrated CustomizeExternalFileTypesDialog into Preferences

### PR DESCRIPTION
**Pull request by calixtus**
grafik

Instead of opening the dialog with a button inside the External programs tab in the preferences nested inside the Push to applications preferences, this dialog has now it's own tab in the preferences.

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by Siedlerchr** [comment]
Might check if this als fixes 5902

**Comment by calixtus** [comment]
Probably not, as i only integrated the dialog in the preferences dialog, but i did not change anything on the table.

**Comment by calixtus** [comment]
But this rather seems to be a javafx bug.

**Review by Siedlerchr — APPROVED** [review]

**Comment by Siedlerchr** [comment]
Merge after 5.4 release due to l10n change

**Pull request merged**
