### PR TITLE
Removed a duplicate name (closes #5476)

### LINKED ISSUE #5476: possible duplicate name in AUTHORS file
See https://github.com/JabRef/jabref/blob/master/AUTHORS#L59-L60

When I disregard unicode, the names are identical. When I look at this commit, that too suggests it's really the same person: https://github.com/JabRef/jabref/commit/61df0d7de74469941ec1f57989f36132fedc9fe1

### PR DESCRIPTION
**Pull request by egonw**

### CODE REVIEW

**Comment by Siedlerchr** [comment]
Thanks a lot for your contribution!
And thanks for hosting the session!

**Comment by egonw** [comment]
PS, I looked up matches, you can find them with `git log --author=egonw`

**Comment by Siedlerchr** [comment]
PPS: regarding the CSL discussion, you can drop us a mail at developers@jabref.org

**Comment by koppor** [comment]
I wonder why this happens. In https://github.com/JabRef/jabref/blob/master/scripts/generate-authors.sh, there is `| LC_ALL=C.UTF-8 sort --unique --ignore-case`. Maybe Erdem configures his username with a space? I found the name in our `.mailmap`: https://github.com/JabRef/jabref/blob/aaa081dc6b7a356a4f6c15932711a78392d812f0/.mailmap#L135

**Pull request merged**
