### PR TITLE
New Iconset

### PR DESCRIPTION
**Pull request by stefan-kolb**
Also see #130 

- [x] Unlike expected, PNG files do not look sharper than the font version for me
- [x] Anyhow, we should go up to 24px as 16px seems way to small
- [x] ~~Strangely, some icons are missing in the materialize Github repository, e.g. `settings`~~ not relevant
- [x] We still have duplicated and unused icons in the properties file
- [x] Open file icon should be either `file-pdf` or `file-document` (or `attachment`) depending on actual file type.
- [x] How are icons for external file types handled? users cannot set this anymore, they have to use the default icons instead. 
- [x] squash commits so that temporary binary files are not in the history
- [x] separator are not removed when the icons are hidden (see special fields like rank)
- [x] add information about used font into `external-libraries.txt` and update "About" content

### CODE REVIEW

**Comment by koppor** [comment]
When checking for the size of the icons, please also check high resolutions settings:

 * [840x2160 pixels under Gnome 3; HiDPI](http://sourceforge.net/p/jabref/mailman/jabref-users/thread/CAPMKG4CoXgAPXTKtnSwxWvXAKrCHQy8oXk0NetXVYiZVZS46Ag@mail.gmail.com/#msg34472086)
 * [2160x1440 and 2560x1440](http://sourceforge.net/p/jabref/bugs/1255/)

Refs #113

**Comment by matthiasgeiger** [comment]
So we should use the Font as this enables simple resizing.
I will investigate whether it is possible to make the icons sharper somehow...

**Comment by kubovy** [comment]
What about some icon dpi scheme ala android: mdpi, hdpi, xhdpi, ...? Since resolution are growing.  If you want to use vector format what about SVG?

**Comment by simonharrer** [comment]
We wanted to use an icon font. This should scale for all resolutions..

**Comment by simonharrer** [comment]
What needs to be investigated

- [ ] the menu item gets bigger when we use the 24px icon. This looks strange when we have normal menu items with no icons and menu items with the 24px icons in a single menu. 
- [ ] disabled icons look strange

# ideas
- the selection of the color to mark an entry should be done in the tool bar as well right next the marker symbol - or we change the color symbol in the toolbar depending on the current color selection.

**Comment by simonharrer** [comment]
:+1: for linking to the donations page as it also explains how the money is spent.

**Comment by matthiasgeiger** [comment]
Okay... I think we are coming down the stretch...

@koppor @lenhard (and all interested others): Do you have some feedback to be integrated before we merge into master?

**Comment by simonharrer** [comment]
Squashed the commits so that temporary png files and fonts are pruned from the history. And removed the ability to change the icon of an external file type entry. Hence, only a single item in this PR is remaining.

**Comment by koppor** [comment]
The last issue was partially adressed by e57fb49. If #257 goes through, this PR can be merged as is.

**Pull request merged**
