### PR TITLE
Rename menus citation style in preview style

### PR DESCRIPTION
**Pull request by mlep**
In JabRef 5.2, an entry preview is displayed in the entry editor.
The preview style can be configured in **Options -> Preference -> Entry preview**.

The menu to switch between preview styles are **View -> Next citation style** and **View -> Previous citation style**.
When a menu is activated, it display an information message mentioning "Preview".

The issue is that the name of these two menus are confusing, because in fact, they are not about _citation style_ but about _preview style_.

This PR renames the menus by changing the word _citation_ into _preview_:
- **View -> Next citation style** --> **View -> Next preview style**
- **View -> Previous citation style** --> **View -> Previous preview style**

.

- [X] Change in CHANGELOG.md described (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by mlep** [comment]
Sure!

**Comment by koppor** [comment]
DevCall:

1. Renaming OK
2. "build-in style" (not "JabRef style", because people can customize it) --> "customized preview style"

grafik

grafik

**Comment by mlep** [comment]
@koppor  Sorry, but I do not understand you point 2.

**Comment by koppor** [comment]
I rewrote the second point now:

> Rename "Preview" to "customized preview style"

Now, the text should also match the screenshots, doesn't it?

**Comment by mlep** [comment]
Got it. 
Note: I do not have the skills to do it (I do not know how find the right place in the code).

**Review by koppor — APPROVED** [review]

**Review by stefan-kolb — APPROVED** [review]

**Comment by mlep** [comment]
@calixtus Thank you for finishing the work (I was not able to do it by myself)

**Pull request merged**
