### PR TITLE
Improve LocalizionConsistencyTest to include JavaFX files

### PR DESCRIPTION
**Pull request by tobiasdiez**
The FXML files may contain localized strings in the form `<label text = "%localized description">` (and not `Localization.lang("localized description"`)). I adapted the LocalizationParser to also look for these kind of strings. Together with #1753, the JavaFX branch should now build without errors.

For some reason the ManageJournalAbbreviationsView has some problems with localized strings, although the same code works for the other dialogs. This needs further investigations (not part of this PR).

- [ ] Change in CHANGELOG.md described
- [x] Tests created for changes
- [ ] Screenshots added (for bigger UI changes)
- [ ] Manually tested changed features in running JabRef
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)

### CODE REVIEW

**Comment by boceckts** [comment]
For me there are quite some errors in the localization test files, are they intended?

**Comment by tobiasdiez** [comment]
What do you mean by errors? Some of the localization tests still fail, but I suspect all of them pass with the fixes of #1753.

**Comment by boceckts** [comment]
No I mean, there is an error in LocalizationParserTest that it can't find the `LocalizationParser.JavaLocalizationEntryParser` due to its visibility. Setting it to public gives an error in the LocalizationBundle class.
> The type LocalizationBundle is already defined

**Comment by tobiasdiez** [comment]
Thanks, fixed the visibility issue.

**Comment by boceckts** [comment]
Now I get the following error
> The type LocalizationBundle is already defined

in the class `LocalizationBundle.java` in src/test/java/ in package net.sf.jabref.logic.l10n

**Pull request merged**
