### PR TITLE
Added JabRef logo as tiff for Mac OS installer (retina support) #5759

### LINKED ISSUE #5759: Add JabRef logo as tiff for Mac OS installer (retina support)
The jpackage tool has now the option to provide a tiff with high resolution for Mac OS retina 
displays. JabRef should also provide a high resolution image.

Refs: https://bugs.openjdk.java.net/browse/JDK-8234284

Some tutorials. It seems to be someone with a mac is required.

https://computers.tutsplus.com/tutorials/how-to-create-a-retina-ready-dmg-based-app-installer--cms-21653

https://developer.apple.com/library/archive/documentation/GraphicsAnimation/Conceptual/HighResolutionOSX/Optimizing/Optimizing.html

### PR DESCRIPTION
**Pull request by Gena928**
Fixes #5759 
Created JabRef logo as tiff for Mac OS installer (retina support). Tiff file for installer and it's png images:
[masOS install images.zip](https://github.com/JabRef/jabref/files/4494556/masOS.install.images.zip)

Settings for icons in Mac dmg install package:
- JabRef & Applications icons are of 84 size (dmg file properties);
- font size of JabRef icon & Applications icon - 12 px;

Comments
- [X] Change in CHANGELOG.md described (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by tobiasdiez** [comment]
Thanks. I think the file needs to be named `background_dmg.tiff` and be placed in https://github.com/JabRef/jabref/tree/master/buildres/mac

**Comment by tobiasdiez** [comment]
Thanks!

We run into a strange bug from gitversion which is why the build currently fails. I'll merge now and hope the master branch builds without problem. Can you please check the build from builds.jabref.org/master/ in about 30 min.

**Comment by Gena928** [comment]
Good day,
I downloaded pkg and dmg files from your link and starter JabRef. Works fine, it doesn't crashes.

**Comment by tobiasdiez** [comment]
Perfect. I assume this also means that the dmg installer is shown correctly, right?

**Comment by Gena928** [comment]
Sorry, but it's still the same.
Screenshot 2020-04-18 at 13 40 32

**Comment by tobiasdiez** [comment]
There was a problem in the build chain and the build wasn't updated. Can you please retry in 30 min. Thanks

**Comment by Siedlerchr** [comment]
Probably the same reason why the plist file doesn't get copied. Do we need to specify the resource folder somewhere?

**Comment by Gena928** [comment]
Hello again,
dmg file is the same. I.e. old design.

**Comment by tobiasdiez** [comment]
It's only now uploading...you can verify that you are testing the new file by looking at the "Last modified" date on https://builds.jabref.org/master/ (which is currently 2020-04-14)

**Comment by Siedlerchr** [comment]
Refs #5986 I just also pushed the --resource dir for mac switch

**Comment by Siedlerchr** [comment]
Let's wait the current build. If it works it's fine, otherwise I found this helpful guide:
https://docs.oracle.com/en/java/javase/14/jpackage/override-jpackage-resources.html#GUID-1B718F8B-B68D-4D46-B1DB-003D7729AAB6

**Comment by Gena928** [comment]
dmg file as of "2020-04-18 15:25" looks the same. I.e. black background color.
If I press Command + Shift + . I can see the content of package, and looks like our new image is not there. 
Screenshot 2020-04-18 at 15 31 54

The program works fine.

**Comment by Siedlerchr** [comment]
I just renamed the file according to the docs. Waiting for the new build.

**Comment by Gena928** [comment]
`2020-04-18 15:58`
The same dmg file. I.e. just black background without image.

**Comment by Siedlerchr** [comment]
I have created an issue at the jlink/jpackage gradle plugin repo:
https://github.com/beryx/badass-jlink-plugin/issues/132

**Comment by tobiasdiez** [comment]
I think it should be lower case `jabref`, at least if I read https://github.com/openjdk/jdk/blob/4d487927adb6fa5c206198ed8ee46aa3ab2a526f/src/jdk.incubator.jpackage/macosx/classes/jdk/incubator/jpackage/internal/MacDmgBundler.java#L133-L137 correctly.

**Comment by Gena928** [comment]
dmg file as of "2020-04-18 22:09".
Looks the same. But when I show hidden files (Command + Shift + .) I see our background image in one of the folders.
Screenshot 2020-04-18 at 22 19 54

A progress )). 
Sorry, but I'm afraid I must ask a few questions. Let's say we solved the problem with background. But then:
- how we are going to add "Applications" icon to dmg file? 
- how we are going to position JabRef icon & Applications icon?
Those icons should be carefully positioned on a both sides of the arrow.
- how we are going to increase the size of JabRef icon and Applications icon?
84 size is required. Otherwise it looks ugly.

I can do it manually, using Mac "Disk Utility", but is it possible to do it automatically?
I'm sorry, if I'm asking those questions too late. I've never done it before.

**Comment by tobiasdiez** [comment]
The position of the icon is hard-coded here:
https://github.com/openjdk/jdk/blob/master/src/jdk.incubator.jpackage/macosx/classes/jdk/incubator/jpackage/internal/resources/DMGsetup.scpt
So I guess the background needs to be designed around this (unfortunately)

**Comment by Siedlerchr** [comment]
@Gena928  No problem, this is new for us all. The jpackage tool is relatively new. The idea is relative simple, you provide the icons in the resource folders for the system like background and in the gradle file the locations are specified for each os:
You already have the svg file, so it should be possible to create  a 84x84 icns version,

@tobiasdiez  We can also modfiy the DMGgsetup script:
`Using default package resource DMGsetup.scpt [DMG setup script] (add JabRef-dmg-setup.scpt to the resource-dir to customize).`

From the log I saw that we also need images for the pgk build:
```
 Building PKG package for JabRef.
Using default package resource background_pkg.png [pkg background image] (add JabRef-background.png to the resource-dir to customize).
Using default package resource background_pkg.png [pkg background image] (add JabRef-background-darkAqua.png to the resource-dir to customize).

Using default package resource java.icns [volume icon] (add JabRef-volume.icns to the resource-dir to customize).
```
https://github.com/JabRef/jabref/blob/38e3aa7f777ee9ae547a62070d32d2db03b76386/build.gradle#L641-L693

**Pull request merged**
