### PR TITLE
Make Identifier paste work with Unicode REPLACEMENT CHARACTER

### PR DESCRIPTION
**Pull request by MadDingzhen**
Slightly change to DOI method so it can now replace all `�` so it won't bothering when import doi with `�`
Also added some data in `org.jabref.model.entry.identifier.DOITest#testData`

Closes https://github.com/JabRef/jabref/issues/11986
### Mandatory checks

- [x] I own the copyright of the code submitted and I licence it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [x] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by koppor** [comment]
Please fix checkstyle. See box of GitHub at pull request - or run checkstyle in your IDE

**Comment by koppor** [comment]
Please learn about

git fetch upstream 
git merge upstream/main

for the next pull request; this gets updates in. No need for a strange commit ...

**Comment by MadDingzhen** [comment]
Sorry about that,
thank you very much for your help and suggestion, I really appreciate it!

Oliver Kopp ***@***.***> 于2024年10月25日周五 18:35写道：

**Comment by calixtus** [comment]
Please change the title of this pr. Nobody knows without clicking around what issue no 11986 is. Every other pr has a reasonable name.

**Comment by MadDingzhen** [comment]
> Please change the title of this pr. Nobody knows without clicking around what issue no 11986 is. Every other pr has a reasonable name.

Nailed it.

**Review by koppor — CHANGES_REQUESTED** [review]
Tried out. Works.

Please add a `CHANGELOG.md` entry and then this is good to go!

**Comment by MadDingzhen** [comment]
> Tried out. Works.
> 
> Please add a `CHANGELOG.md` entry and then this is good to go!

Done it😊

**Review by koppor — APPROVED** [review]
Since test works: Nic

**Pull request merged**
