### PR TITLE
Cleanups, warning removals, move and test.

### PR DESCRIPTION
**Pull request by oscargus**
Some cleanups and warning removals. Should get rid of six high impact Coverity issues (I hope).

### CODE REVIEW

**Comment by simonharrer** [comment]
:+1: looks good to me. The stupro PRs may have to rebase after this is merged.

**Comment by oscargus** [comment]
Maybe, but I do not think so. However, it may be that the IsiImporterTest is not longer needed once the StuPro tests are merged. Either way, we can wait with merging this if it is a potential problem (or I remove the final commit which is the one potentially causing problems, I guess.)

**Comment by simonharrer** [comment]
It would be best if you would remove the final commit, then I can merge your changes immediately.

**Comment by oscargus** [comment]
OK! I've done that and hopefully stored the removed commit in such a way that it can be recreated. :-)

**Pull request merged**
