### PR TITLE
Fix for issue #417

### PR DESCRIPTION
**Pull request by nivieru**
Removed checks that prevented the table from being updated when switching between groups.

### CODE REVIEW

**Comment by simonharrer** [comment]
Thank you for the contribution. Can you please indent the lines correctly which were in the then-block of the removed if-condition? Apart from that, this can be merged in from my point of view.

**Comment by simonharrer** [comment]
Hm, would like to merge it, but github says it has conflicts. Can you have a look into this, please?

**Comment by oscargus** [comment]
Probably ChangeLog-conflicts...

**Comment by oscargus** [comment]
By the way, when merging the ChangeLog (if that is the one with the conflict), note that the entry starting `Fixed #608` is actually the correct format. My bad for starting the new version with a made up format (but I'll take care of it eventually, a PR fixing most of it is in #602).

**Comment by nivieru** [comment]
Ok, I think it should be fine now

**Comment by oscargus** [comment]
I thought I'd give it a try to see how merging works. :-) Hope I didn't break anything...

**Comment by simonharrer** [comment]
:+1:

**Pull request merged**
