### PR TITLE
Add integrity check detecting booktitles ending with "conference on" …

### PR DESCRIPTION
**Pull request by simonharrer**
- Add integrity check detecting booktitles ending with "conference on"

### CODE REVIEW

**Comment by oscargus** [comment]
Maybe it is enough with ' on' to cover workshop etc? Good idea though!

**Comment by tobiasdiez** [comment]
The code looks good, but I'm not sure what the use case for such a checker is.
(By the way, if I remember correctly your words were that all the checkers should be extracted to separate classes as soon as a new checker is added :smile_cat: )

**Comment by simonharrer** [comment]
Good idea just to check whether it ends with ' on'. Should produce even better results. 

The checker should detect typical errors made by newcomers and experts with large databases, i.e., encoding the best practices we have all learned over time.

**Comment by tobiasdiez** [comment]
So "let's turn the music on" is not a valid booktitle? I still don't see why I would have a booktitle ending on "conference on". But probably that's just because I'm to inexperienced with citing conference proceedings. 

The biblatex manual says 
> Things like “Proceedings of the Fifth XYZ Conference” go into the titleaddon or booktitleaddon
field, respectively.

and provides the example 
````
@inproceedings{salam,
  author       = {Salam, Abdus},
  editor       = {Svartholm, Nils},
  title        = {Weak and Electromagnetic Interactions},
  date         = 1968,
  booktitle    = {Elementary particle theory},
  booksubtitle = {Relativistic groups and analyticity},
  booktitleaddon= {Proceedings of the Eighth Nobel Symposium},
  eventdate    = {1968-05-19/1968-05-25},
  venue        = {Aspen{\"a}sgarden, Lerum},
  publisher    = {Almquist \& Wiksell},
  location     = {Stockholm},
  pages        = {367-377},
}
````

**Comment by simonharrer** [comment]
Hm, I only use bibtex, so I cannot say something about the usage in biblatex. In bibtex, all is put into the booktitle, as shown in the tests. 

The rule can have some false positives, similar to the Pages check as some journals have page numbers like this `4:1--4:56` but I think it is useful in a lot of cases (and has been in my own file).

**Comment by oscargus** [comment]
Context: at least IEEE has been hopeless in writing conference titles
like Electronics,
Circuits and Systems, 2002. 9th International Conference on
<http://ieeexplore.ieee.org/xpl/mostRecentIssue.jsp?punumber=8101> and I
regularly see those incorrect booktitles in papers I read. There's even
code in JabRef to sort it out upon import, but if you download directly you
get entries like:

```
@INPROCEEDINGS{1046205,
author={O. Gustafsson and L. Wanhammar},
booktitle={Electronics, Circuits and Systems, 2002. 9th International
Conference on},
title={Bit-level pipelinable general and fixed coefficient
digit-serial/parallel multipliers based on shift-accumulation},
year={2002},
volume={2},
pages={493-496 vol.2},
keywords={adders;distributed arithmetic;logic design;pipeline
arithmetic;shift registers;bit-level pipelinable general/fixed coefficient
multipliers;bit-level pipelined multipliers;digit-serial/parallel
multiplication;digit-serial/parallel multipliers;distributed arithmetic;low
hardware complexity design;maximal cascaded full-adder number;pipeline
arithmetic;shift-accumulation;shift-accumulators;Adders;Arithmetic;Circuits;Clocks;Energy
consumption;Hardware;Pipeline processing;Process design},
doi={10.1109/ICECS.2002.1046205},
month={},}
```

They had similiar issues for journals, but that seems to be correct in IEEE
Xplore now, although there are probably millions of downloaded entries out
there...

**Comment by tobiasdiez** [comment]
Ok, then it makes sense to add such a checker. Would merge, but the build is failing for some reason.

**Comment by simonharrer** [comment]
I keep it to 'conference on' for now just because this is the most problematic thing.

**Comment by tobiasdiez** [comment]
LGTM :+1: for merge now that I understood the purpose of this checker...

**Pull request merged**
