### PR TITLE
Paging support for fetchers #5507

### LINKED ISSUE #5507: Paging support for fetchers
So far only a predetermined number of search results are shown. I would like support for pagination. 
For this we have to do the following: 
* The GUI has to be adapted 
* Introduce an interface for paginated fetchers
* Migrating the implementation of fetchers (also possible step-by-step)

If there were no concerns, I would take a look.

### PR DESCRIPTION
**Pull request by Ajitaganguly3**
### **Description**

Fixes #5507
This pull request adds a next button, a previous button and pagination for the Fetchers.

### **Changes Made**

- Added  new classes `WebImportEntriesDialog`, and, `WebImportViewModel` that adds the previous button, next button and pagination.
- Added the disable feature to the `Previous` button. The previous button will be disabled at first.
-  Implemented the logic so that the Fetcher only shows 20 data per page
- Added `WebImportEntriesDialog.FXML` file which shows the buttons and the pagination

### CODE REVIEW

**Comment by koppor** [comment]
I tried it out with "ArXiv". The "Next" button does not work:

image

Expected: When clicking on "Next", items 21..40 are fetched.

When searching in the web for "test", there are more than 160.000 entries.

https://arxiv.org/search/?query=test&searchtype=all&source=header

image

**Comment by Ajitaganguly3** [comment]
Thank you @koppor for providing insight on this. I'll try to make the necessary modifications on the code so that it works fine with all the Fetchers.

**Comment by koppor** [comment]
Take this as exercise for agile development with feedback loops. Typically, customers don't know what they exactly want at the beginning. It will come to light while presenting intermediate results.

BTW: I like the idea that Next also works with non-paged fetchers. Maybe the dialogs can be unified again so that the same dialog can be used for page based and non-page based fetchers.

**Comment by koppor** [comment]
Closing this issue due to inactivity :zzz: 

Please ping us if you intend to resume work on this one.

**Pull request closed without merging**
