### PR TITLE
Add mappings on ModsImporter.java

### LINKED ISSUE #9185: Mods importer should be able to import conference papers with the correct entry type
**Is your suggestion for improvement related to a problem? Please describe.**
I recently had to import a reference from the ISCRAM conference. However, they only offer MODS export format and I noticed that my entry got imported as misc.

**Describe the solution you'd like**
I would like to have conference publications imported as proceedings.

**Additional context**
Here is a list of mappings for the field genre:
https://www.loc.gov/standards/valuelist/marcgt.html

The code needs to be adpated at this place :
https://github.com/JabRef/jabref/blob/d3e0f86a6be977aa16204fd611023e2358a556a7/src/main/java/org/jabref/logic/importer/fileformat/ModsImporter.java#L170

### PR DESCRIPTION
**Pull request by berry120**
Fixes #9185

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by Siedlerchr** [comment]
Thank you for your contribution. Looks good already. Can you please add a test for this as well?
Have a look at the mods importer test files

**Comment by berry120** [comment]
@Siedlerchr Absolutely, that's now added 👍

**Review by Siedlerchr — APPROVED** [review]

**Comment by Siedlerchr** [comment]
Thanks! Please add a changelog entry, then it's ready!

**Comment by berry120** [comment]
@Siedlerchr Thanks, done!

**Review by calixtus — APPROVED** [review]

**Comment by calixtus** [comment]
Don't know if this will be accepted to hactoberfest, since the PR was created on 9/30 and they say that they only accepted PRs created between 1 and 31 of october. But we can try anyway.

**Pull request merged**
