### PR TITLE
Reduce memory footprint

### PR DESCRIPTION
**Pull request by tobiasdiez**
by removing some caching of ids and keys in databases.
image
Realized to late that the numbers are actually quite small. So this doesn't give much of a boost, but anyway it also doesn't hurt. Moreover, in my opinion,  the code is more readable now.

- [ ] Change in CHANGELOG.md described (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by Siedlerchr** [comment]
You seem to have committed on top of an old branch. I had a déjà vu seeing some changes

**Comment by tobiasdiez** [comment]
Yep, now it should be fine. Sorry

**Comment by Siedlerchr** [comment]
Could you please check the performance of import? The duplication checker is heavily used on import

**Comment by tobiasdiez** [comment]
I didn't experience any performance problems with it. Adding a new entry is now slightly slower because we have to traverse a ArrayList instead of looking up a key in a hashmap. But I guess the difference should be negligible to average size databases of <= 10k entries.

@koppor not sure what you mean with model vs logic. All my changes concern only the model package.

**Pull request merged**
