### PR TITLE
Remove customjfx

### PR DESCRIPTION
**Pull request by Siedlerchr**
This removes the custom JfXPanel hack we introduced for  #3028  @koppor 
As now the main frame is javafx and no longer swing this hack is no longer needed and can be removed.

I did not completely remove the class, because some dialogs still require a jfxpanel with a scene

----

- [ ] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [x] Manually tested changed features in running JabRef
- [ ] Screenshots added in PR description (for bigger UI changes)
- [x] Ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)

### CODE REVIEW

**Comment by Siedlerchr** [comment]
Hm, good question. I will take a look at that.

**Comment by Siedlerchr** [comment]
As far as I see the panel is only used to add the PreviewPanel which does not provide a way to input content. So we can safely remove that.

**Comment by tobiasdiez** [comment]
Ok, but we may still need it in the future for example when the preferences are migrated pane by pane. If the library makes problems with Java 9, then I'm OK with merge. Otherwise I would keep it for the moment until the majority of the dialogs is also converted.

**Comment by tobiasdiez** [comment]
So, is our custom fx hack a problem for java 9 or not? In the latter case I would vote for closing this PR; otherwise just merge it.

**Comment by Siedlerchr** [comment]
I want to get rid of the class completely, it can be safely removed as JavaFX is our first class citizen.
For swing content we need to embed we can now use Swing Node 

I will update the PR to convert the remaining usage to fx

**Comment by Siedlerchr** [comment]
I now converted the Preamble Editor to javafx. This was the only critical thing which remained and had a TextArea as input field.
All other cases where Customjfxpanel is used is uncrictical and only the previewpanel in the External Changes Dialog.

**Comment by Siedlerchr** [comment]
@tobiasdiez Well, we can simply do it the other way round then. We wrap it in javafx by using a SwingNode. 
I did this with the cleanup operations already

**Pull request merged**
