### PR TITLE
Rename "Remote" to "Tele"

### PR DESCRIPTION
**Pull request by tobiasdiez**
The socket server that is run so that other instances of JabRef can detect the running instance were called "Remote". I found this a bit confusing since everything is actually local, so I've renamed it to "Tele".

Besides this rename, I cleaned the code and added a log statement here and there. Only functional change is that the tele server is now only started as part of the other background tasks, i.e. after/during the initial rendering of the main window. Previously, it happened during the CLI, so that even `jabref --help` started the tele server - and in fact never closed it.

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by koppor** [comment]
DevCall: Please stick with `Remote`. We don't know the term `Tele`. We remember [Teletext](https://de.wikipedia.org/wiki/Teletext), [Telecommunications](https://en.wikipedia.org/wiki/Telecommunications). In French, the association is with [Television](https://fr.wikipedia.org/wiki/T%C3%A9l%C3%A9vision). - No one of the developers on the call associated it with "server".

Some know [telnet](https://fr.wikipedia.org/wiki/Telnet), however, there is an `e` missing - and it's `terminal`.

**Comment by koppor** [comment]
Seems NOT to fix https://github.com/JabRef/jabref/issues/9196, does it?

**Comment by tobiasdiez** [comment]
> Seems NOT to fix #9196, does it?

Was my hope that I find the reason for this issue by going through the code.

**Comment by tobiasdiez** [comment]
> DevCall: Please stick with `Remote`. We don't know the term `Tele`. We remember [Teletext](https://de.wikipedia.org/wiki/Teletext), [Telecommunications](https://en.wikipedia.org/wiki/Telecommunications). In French, the association is with [Television](https://fr.wikipedia.org/wiki/T%C3%A9l%C3%A9vision). 

"Tele" is the greek prefix for "far" or "from far away", e.g. telecommunication = communication over a distance. And in the context of this PR, it would mean "control JabRef from somewhere else", which is pretty much was this code is doing.

> No one of the developers on the call associated it with "server". 

That was my point. There should be no association to "server". That we use sockets is an implementation detail. We could also write the commands to a file that is watched by another instance, or implement a full http server or write to the registry or whatever. But I think we all agree that "FileWatcher", "ServerWatcher" or "RegistryWatcher" are bad names for this would-be implementation. "Tele" would cover all these implementations as well.

For the same reasons, I find it as a user highly confusing why this feature is under "Network". I would never look there if I want to have only one instance of JabRef. For the sake of limiting the scope of this PR, I didn't touch this though.

I'm very much open to other suggestions, "Tele" was the best I came up with but I'm open to other words as well.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
I don't think I understand this, can't we send command line arguments through the client/listener? I was assuming remote ~ remote control. Otherwise, the rest of the network settings wouldn't make sense.

External application access?

**Comment by koppor** [comment]
> > DevCall: Please stick with `Remote`. We don't know the term `Tele`. We remember [Teletext](https://de.wikipedia.org/wiki/Teletext), [Telecommunications](https://en.wikipedia.org/wiki/Telecommunications). In French, the association is with [Television](https://fr.wikipedia.org/wiki/T%C3%A9l%C3%A9vision).
> 
> "Tele" is the greek prefix for "far" or "from far away", e.g. telecommunication = communication over a distance. And in the context of this PR, it would mean "control JabRef from somewhere else", which is pretty much was this code is doing.

Based on our IT experience, "tele" is not known and might confuse other developers. We should stay in line with common terms.

For now, I would stick for "remote", because this also offers to open the port on the firewall and let having JabRef controlled remotely. (Doesn't it? I think, we just open the port with no restrictions on the incoming source IP address?)

> For the same reasons, I find it as a user highly confusing why this feature is under "Network". I would never look there if I want to have only one instance of JabRef. For the sake of limiting the scope of this PR, I didn't touch this though.

The left menu should not grow more, thus, I currently don't come up with another idea.

**Comment by tobiasdiez** [comment]
> I don't think I understand this, can't we send command line arguments through the client/listener? I was assuming remote ~ remote control. Otherwise, the rest of the network settings wouldn't make sense.

Yes, "remote control" is a good word for it. "Teleoperation" is a synonymy (https://en.wikipedia.org/wiki/Teleoperation and https://en.wikipedia.org/wiki/Telecommand) that I liked since its less overloaded. At least for me "Remote" in an IT context has a server/client connotation, e.g. remote desktops are usually run on a server and the graphical display is shown at the user. This possible source of confusion is also nicely demonstrated by @ThiloteE tagging this PR with "shared database", which is actually a completed different feature but also something I would intuitively think of when I hear "remote" in the context of JabRef.


> We should stay in line with common terms.

From https://en.wikipedia.org/wiki/Teleoperation: "[Teleoperation] is similar in meaning to the phrase "remote control" but is usually encountered in research, academia and technology." Seems to be our area, or not?

**Comment by ThiloteE** [comment]
Mhm, so if I understand it right, this is code about controlling JabRef from afar? Would it not be possible for multiple users to control the same (remote/tele) JabRef instance at the same time? That is why I thought "shared" database might be a fit, but maybe I am wrong.

**Comment by tobiasdiez** [comment]
It's about ensuring that only one instance of JabRef is running. Part of the feature is that if you have one Jabref window open, and start another one with some command line arguments (e.g. "open this and that library"), these commands are instead sent to the already running instance. But it's not like that you really have a JabRef server instance that you remote control from another PC or something like that.

**Comment by ThiloteE** [comment]
Ah, ok got it. Thanks for the explanation.

**Comment by Siedlerchr** [comment]
Renamed Tele back to Remote , otherwise I think the changes look good now

**Pull request merged**
