### PR TITLE
Remove PDF preview functionality

### PR DESCRIPTION
**Pull request by stefan-kolb**
I suggest to remove the PDF preview functionality in the preview panel

Why?
- The preview is not working all the time
- the preview is too small to provide valuable information
- opening the linked PDF via a simple click on the PDF icon is way faster and more convenient

@JabRef/developers WDYT?

### CODE REVIEW

**Comment by simonharrer** [comment]
:+1: makes sense.

**Comment by oscargus** [comment]
Would probably be better to integrate a proper PDF viewer in that case.

I must say though that on my 2560x1440 screen, the preview is sort of OK sized.

**Comment by oscargus** [comment]
What about adding a ChangeLog entry?

**Comment by matthiasgeiger** [comment]
@stefan-kolb @oscargus is right: Should be added to the CHANGELOG

**Comment by stefan-kolb** [comment]
Is already done https://github.com/JabRef/jabref/blob/master/CHANGELOG.md

**Comment by matthiasgeiger** [comment]
Oh... :astonished:

**Pull request merged**
