### PR TITLE
Change WM_CLASS to jabref

### LINKED ISSUE #7848: change `WM_CLASS` from `org.jabref.gui.JabRefMain` to `jabref`
**Is your suggestion for improvement related to a problem?**
If you filename your `*.desktop`-file (on linux) different than the `WM_CLASS` then you have two problems
- first you can't add them to favourites via right-click
- secondly jabref is twice in the menu, one pinned one, and one for the opened instances

Screenshot from 2021-06-24 18-19-10

**Describe the solution you'd like**
change the `WM_CLASS` of the linux-application to `jabref`

the current WM_CLASS is `org.jabref.gui.JabRefMain` and can be checked with `xprop`

so you have to name the *.desktop-file as `org.jabref.gui.JabRefMain.desktop` which is very unconvetional/inconvenient (and maybe problematic because it contains dots `.` the _typos_ in the filename could be easily be overseen) .

**Additional context**
Illustration of the problem: https://askubuntu.com/a/1155956/676490
Infos about `WM_CLASS`: https://unix.stackexchange.com/a/225409/241592

### PR DESCRIPTION
**Pull request by Siedlerchr**
Fixes  #7848

- [] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [] Tests created for changes (if applicable)
- [] Manually tested changed features in running JabRef (always required)
- [] Screenshots added in PR description (for UI changes)
- [] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by Siedlerchr** [comment]
Can someone on linux test this branch=? https://builds.jabref.org/pull/7858/merge/

**Comment by koppor** [comment]
@JoKalliauer Could you download and try https://builds.jabref.org/pull/7858/merge/?

**Comment by calixtus** [comment]
Tested with ARCH Linux with KDE 5.22 and it seems to work and to collect all instances in one symbol.

**Review by calixtus — APPROVED** [review]

**Comment by JoKalliauer** [comment]
> @JoKalliauer Could you download and try https://builds.jabref.org/pull/7858/merge/?

The `WM_Class` is still "org.jabref.gui.JabRefMain"

Screenshot from 2021-07-02 10-53-51

**Pull request merged**
