### PR TITLE
fix: fix content selector for custom fields

### LINKED ISSUE #6819: Content selector does not seem to work for custom fields
JabRef version JabRef 5.1--2020-08-30--e023aa0 Linux 4.15.0-112-generic amd64  Java 14.0.2

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

The content sectors just do not show up when entering text in the input fields that are connected with content selectors.

### PR DESCRIPTION
**Pull request by yinpeiqi**
We Fix the issue that Content selector does not seem to work for custom fields. This issue actually do not affect the correctness of running and just show a ugly output in the frontend. So I simply change the 'toString()' method in UnkownField class. This method do not make any effect to other functions but the user interface shown in the issue.

fixes #6819 

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

image

### CODE REVIEW

**Comment by tobiasdiez** [comment]
Thanks for your contribution! Very much appreciated.

You are already on the right track. However, instead of changing `toString`, which should be exclusively used for debugging, the dialog should use
https://github.com/JabRef/jabref/blob/9aad6fcf5f27e644f0fa079c118dc8a46ca89b42/src/main/java/org/jabref/model/entry/field/Field.java#L19
to display the field name. This would also improve the display of standard fields, e.g. `Keyword` instead of `KEYWORD`.

**Comment by yinpeiqi** [comment]
@tobiasdiez Thanks for your reviewing. Currently I get no idea on how to use getDisplayName() without any changes on toString(). Is there any other method to approach it? Thanks!

**Comment by yinpeiqi** [comment]
Thanks for your guidance!

**Comment by yinpeiqi** [comment]
I finished the behavior you mentioned above. Now the program can show display name without faults occurring in debug.

**Review by tobiasdiez — APPROVED** [review]
Looks good to me. Again, thanks a lot for your contribution!

**Comment by yinpeiqi** [comment]
You are welcome!

**Review by Siedlerchr — APPROVED** [review]

**Comment by Siedlerchr** [comment]
Thanks a lot for your contribution!

**Pull request merged**
