### PR TITLE
Fix pasting on mac and linux

### LINKED ISSUE #4699: Mac OS X: Pasting bibtex entry creates duplicate entries
JabRef version: 5.0-dev

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

When copying and pasting a bibtex entry into jabref, it creates duplicate entries for the citation. This occurs regardless of if I have All Entries open, or am just viewing a group or subgroup.

<details>
  <summary>Log File</summary>
Opening: /Users/adamg/Dropbox/adam.bib
Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
Can only load style files: Preview
Opening: /var/folders/8w/wfth0jx51l960l8mgcjlxn580000gn/T/jabref7386437712883599037.bib
Opening: /Users/adamg/Dropbox/adam.bib
Opening: /var/folders/8w/wfth0jx51l960l8mgcjlxn580000gn/T/jabref7386437712883599037.bib
Opening: /Users/adamg/Dropbox/adam.bib
Opening: /var/folders/8w/wfth0jx51l960l8mgcjlxn580000gn/T/jabref7386437712883599037.bib
Opening: /Users/adamg/Dropbox/adam.bib
Opening: /var/folders/8w/wfth0jx51l960l8mgcjlxn580000gn/T/jabref7386437712883599037.bib
Opening: /Users/adamg/Dropbox/adam.bib
Can only load style files: Preview  
</details>

### PR DESCRIPTION
**Pull request by LinusDietz**
PR #6313 caused the double pasting issue on MacOS (see #4699)

After the first paste,  the Edit Action focusOwner did somehow trigger on Mac and this resulted in executing paste twice.

Fixes #4699.

### CODE REVIEW

**Comment by calixtus** [comment]
I really don't get where the bug is. Reverting this reopens issue #6293

**Comment by LinusDietz** [comment]
@calixtus Whoops, I overlooked the original issue (#6293) for your PR (#6313).

So, we are in some kind of situation, where we have contradicting behavior in two operating systems. That kinda sucks, since we need to differentiate between those now. :/

**Comment by calixtus** [comment]
I have been thinking this through since the hint of @Siedlerchr. The thing is, the insert command should stand here. Is there another issue with macos, some method fired by macos we did not see yet?

**Comment by Siedlerchr** [comment]
If we don't find out the root cause in mac, we could add an ugly os check for Linux/mac

**Comment by calixtus** [comment]
I already stumbled upon another method (`JabRefFramein::openAction`) especially for macOS. Did I mention that I don't like apple? 😉

**Comment by tobiasdiez** [comment]
I agree with @calixtus, the command there makes sense. @LinusDietz can you debug and report which other code triggers the `paste` command on MacOS?

**Comment by Gena928** [comment]
OS: macOS Catalina 10.15.4 (19E287)

Hello everyone,
I'm currently trying to reproduce the error of non working menu items, or duplicating objects during "paste" command (from Google Scholar and between two .bib libraries) but I can't.

I use IntelliJ Idea to start JabRef.
Are there any issues with copy/paste?

**Comment by koppor** [comment]
@Gena928 Just to double check: You are on latest `master` (https://github.com/JabRef/jabref)? @LinusDietz Maybe you can add a screencast using [Loom](https://www.loom.com/)?

**Comment by Gena928** [comment]
@koppor  yes, I'm on latest master.
I downloaded last build and pulled changes from github. Both (last build and source code in IntelliJ) show no error. I.e. record inserts without duplicates.

**Comment by Gena928** [comment]
Looks like I see an error.
It's very phantom, i.e. I still can not understand what should I do to repeat it. Sometimes I have 2 entries inserted, sometimes only one. I'll continue testing and try to do something about it.

**Comment by Gena928** [comment]
OK, I need some help )). Looks like `paste()` command of `MainTable.java` executed twice:
1) In `EditAction.java`, and this was deleted by current pull request. Now it's back again? 
Line 78:
`frame.getCurrentBasePanel().paste();`
2) In `MainTable.java` method `setupKeyBindings`;

I tracked first case, and it turns out that `EditAction.execute()` called by `JabRefFrame.java`, line 740 (`createMenu()` method). When I commented that line, JabRef inserts only one item per each Ctrl+V command.

So in general, paste command is called:
- first time because we have `MainTable.setupKeyBindings`, and it triggered by Ctrl+V;
- second time because Ctrl+V command triggers main menu command (Edit=>Paste);

**Comment by calixtus** [comment]
Sorry for our late reply.
The deletion of `frame.getCurrentBasePanel().paste();` was the unsuccessful attempt to fix the issue in this PR.

Would you like to create a fix for this issue following your investigations and to open a new PR, so we can probably close this one and merge your's with the master branch?

**Comment by Gena928** [comment]
@calixtus 
I hoped to get some Ideas about solving this issue... OK, if there are no any ideas, I will continue to investigate myself. 
We have to disable main menu from listening "Ctrl+V" and keep it listening in `MainTable.java`.

I'll be back with ideas.

**Comment by calixtus** [comment]
Does Ctrl + C or Ctrl + X also call an edit action? Maybe there is some design flaw in a hotkey, that is defined twice by setupkeybindings and the the menu command...

**Comment by Gena928** [comment]
Ctrl+X works in the same way
1) When I press "Command + X" the program deletes 2 (two) entries from current lib;
2) Then I move the cursor to another lib and press "Command + V";
3) JabRef inserts last entry to the new library. I.e. one entry just disappears.

It looks like JabRef cut entries twice...
Checked from IntelliJ and using last stable version from JabRef.org.

**Comment by Gena928** [comment]
Why do we need `SetupKeyBindings` method in `MainTable.java`? 
When I delete COPY/PASTE/CUT commands from it, the program works fine.
this lines:
```
                    case PASTE:
                        paste();
                        event.consume();
                        break;
                    case COPY:
                        copy();
                        event.consume();
                        break;
                    case CUT:
                        cut();
                        event.consume();
```
So, why do we need those commands in `MainTable.java`?

**Comment by Siedlerchr** [comment]
The reason is that you can define custom keybindings (options? manage keybindings) for all commands and so people can use their emacs/vim whatever paste command style.
For mac we use all default keybindings and simply replace ctrl with meta in the KeybindingRepository

```
   public KeyCombination getKeyCombination(KeyBinding bindName) {
        String binding = get(bindName.getConstant());
        if (OS.OS_X) {
            binding = binding.replace("ctrl", "meta");
        }

        return KeyCombination.valueOf(binding);
    }
```

**Comment by Gena928** [comment]
@Siedlerchr 
if I remove this line of code.  `binding = binding.replace("ctrl", "meta");` I just have to use "Command" button on Mac, instead of "Control". A bit more natural for IOS.
The problem persists.

What about main menu? 
I mean, if you wanna change key combinations, and we remove that lines from `MainTable.java`. Does main menu works with new key combinations for COPY/PASE/CUT?

**Comment by Siedlerchr** [comment]
I will test this on Windows : Options -> Customize Keybindings:
grafik
I changed copy/paste to the following (Alt Gr+O and Alt GR+P) 
I can copy and paste using those shortcuts. 
CTRL+C and CTRL+V then don't work.

I also tested uncommenting the `setupKeyBindings `in MainTable.
No difference, no duplicates.

So, now we would need someone on Linux who can test this.

**Comment by Gena928** [comment]
Linux user wanted! :-)

**Comment by Siedlerchr** [comment]
@LyzardKing  Could you assist in testing this on linux? AssiGg some other shortcuts to copy/paste
test if it works
And then do a test with commenting out the method setupKeyBindings  in MainTable

**Comment by LyzardKing** [comment]
Sure, I can test both stable and the version from builds.jabref.org
It's not clear to me what I should be doing..
I've never had duplicates in pasting... if that's the issue here.

**Comment by calixtus** [comment]
Issue #6293 was about merging in pasting in linux and windows. Lets follow the mac related stuff here.

**Comment by Siedlerchr** [comment]
Will look into this as I have now a mac at hand

**Comment by Siedlerchr** [comment]
I fixed the issue for mac and believe it shoudl also work now on linux:
https://builds.jabref.org/pull/6419/merge/

**Comment by Siedlerchr** [comment]
Nope, didnt fix it. But I think I found the real reason now

**Comment by LyzardKing** [comment]
Doesn't work on linux.
I hadn't noticed this issue before.

**Comment by LyzardKing** [comment]
In the .deb it now doesn't work even if I press Ctrl+V

**Comment by Siedlerchr** [comment]
I think I have found the root cause now. Pasting to a new library should work now as well. Please try again when the new build is ready.

**Comment by Siedlerchr** [comment]
new build is ready , please try pasting an entry from a library to a new empty library
https://builds.jabref.org/pull/6419/merge/

**Comment by LyzardKing** [comment]
It works, but I have top copy Ctrl-V multiple times to get it to work if the library is empty.
The copy/paste buttons are not active on an empty library
On a not empty library it works normally.

**Comment by Siedlerchr** [comment]
Works fine on Windows as well. The menu buttons are disabled on Windows as well. I think they are only activated if you have at least one entry selected. But this is a minor issue.
Therefore I would merge this.

**Comment by koppor** [comment]
Regarding the disabled/enabled menu items, we track the issues at https://github.com/koppor/jabref/issues/419.

**Comment by Siedlerchr** [comment]
The problem turns out to be a bit complex. We need to find a way to differ if an action was triggered by key or not or to move the keybinding from the maintable to the edit action.
Therefore I would prefer to have this PR in as it enables copy pasting vai keyboard commands and we can reopen the other issue regarding the menu commands

**Pull request merged**
