### PR TITLE
[WIP] Translating some entries to pt_BR

### PR DESCRIPTION
**Pull request by mairieli**
- [ ] Change in CHANGELOG.md described?
- [ ] Changes in pull request outlined? (What, why, ...)
- [ ] Tests created for changes?
- [ ] Tests green?

### CODE REVIEW

**Comment by matthiasgeiger** [comment]
Thanks for your contribution!

Are you planning to submit some more entries? 
If so, I would wait with merging this in.

**Comment by mairieli** [comment]
I'm planning to submit more entries. @matthiasgeiger

**Comment by matthiasgeiger** [comment]
Great! 

You can simply make more commits in your fork, which will end up in this Pull Request.

Just tell us, when you are done and we will merge your commits in the master branch.

**Comment by oscargus** [comment]
Just a small note: there are about 150* obsolete strings in the translation file. My guess is that you translate strings you see in JabRef and at the moment that is good practice. Once #869 is merged there will be stricter checks for obsolete keys.

* Many of them are older, so there are hardly 150 obsolete strings without translations. Still, it would be a waste of your time to translate those obsolete ones.

**Comment by mairieli** [comment]
It's done! @matthiasgeiger

**Comment by tobiasdiez** [comment]
Thank you very much for you contribution. I`ll merge this now in. If you have further translations, feel free to open a new Pull Request.

**Pull request merged**
