### PR TITLE
try fixing rpm uninstall error

### LINKED ISSUE #12213: packaging? rpm remove does not work
### JabRef version

Other (please describe below)

### Operating system

GNU / Linux

### Details on version and operating system

JabRef 6.0--2024-11-17--572c823 Linux 6.11.7-300.fc41.x86_64 amd64 Java 23.0.1 JavaFX 23.0.1+4

### Checked with the latest development build (copy version output from About dialog)

- [x] I made a backup of my libraries before testing the latest development version.
- [x] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. on Fedora use dnf to remove the rpm.

this does not work anymore.

### Appendix

...
<details>

<summary>shell report</summary>

```
root@PC:~# dnf remove jabref
Package                                                           Arch            Version                                                            Repository                                Size
Removing:
 jabref                                                           x86_64          6.0.6580-1                                                         @commandline                         350.4 MiB
 jabref                                                           x86_64          6.0.6588-1                                                         <unknown>                            356.4 MiB

Transaction Summary:
 Removing:           2 packages

Is this ok [y/N]: y
Running transaction
[1/3] Prepare transaction                                                                                                                                  100% |   2.0   B/s |   2.0   B |  00m01s
>>> Running pre-uninstall scriptlet: jabref-0:6.0.6588-1.x86_64
>>> Error in pre-uninstall scriptlet: jabref-0:6.0.6588-1.x86_64
>>> Scriptlet output:
>>> /var/tmp/rpm-tmp.LOQnhY: line 116: do_if_file_belongs_to_single_package: command not found
>>> /var/tmp/rpm-tmp.LOQnhY: line 117: do_if_file_belongs_to_single_package: command not found
>>> /var/tmp/rpm-tmp.LOQnhY: line 118: do_if_file_belongs_to_single_package: command not found
>>> 
>>> [RPM] %preun(jabref-6.0.6588-1.x86_64) scriptlet failed, exit status 127
>>> Running pre-uninstall scriptlet: jabref-0:6.0.6580-1.x86_64
>>> Error in pre-uninstall scriptlet: jabref-0:6.0.6580-1.x86_64
>>> Scriptlet output:
>>> /var/tmp/rpm-tmp.w4SfXT: line 116: do_if_file_belongs_to_single_package: command not found
>>> /var/tmp/rpm-tmp.w4SfXT: line 117: do_if_file_belongs_to_single_package: command not found
>>> /var/tmp/rpm-tmp.w4SfXT: line 118: do_if_file_belongs_to_single_package: command not found
>>> 
>>> [RPM] jabref-6.0.6588-1.x86_64: erase failed
>>> [RPM] %preun(jabref-6.0.6580-1.x86_64) scriptlet failed, exit status 127
Transaction failed: Rpm transaction failed.

```

</details>

### PR DESCRIPTION
**Pull request by Siedlerchr**
add COMMON_SCRIPTS

refs https://github.com/openjdk/jdk/commit/7848ed779b8c292fe78b5e4c90a7504e034e1bf0

Fixes #12213 

### Mandatory checks

- [x] I own the copyright of the code submitted and I licence it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if change is visible to the user)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by Siedlerchr** [comment]
I tried more stuff based on https://github.com/openjdk/jdk/blob/jdk-23%2B37/src/jdk.jpackage/linux/classes/jdk/jpackage/internal/resources/template.spec

**Comment by koppor** [comment]
Current state: Still not working: https://github.com/JabRef/jabref/issues/12213#issuecomment-2504408234

Should we work on a `Dockerfile` to ease development?

**Comment by Siedlerchr** [comment]
The thing is, I looked into the generated rpm file and the script `do_if_file_belongs_to_single_package` is there - but now multiple times.... 

grafik

**Comment by Siedlerchr** [comment]
wil try to setup javafx reproducer

**Comment by Siedlerchr** [comment]
Trying with no custom spec file so defautl should be used

**Review by HoussemNasri — APPROVED** [review]

**Pull request merged**
