### PR TITLE
Fixing unwanted tree group node expansion selection bug

### PR DESCRIPTION
**Pull request by credmond**
Fixing bug introduced in https://github.com/JabRef/jabref/pull/9728 which undid/broke this improvement: https://github.com/JabRef/jabref/pull/8785, which prevented the group node from being selected when the user is just attempting to expand or shrink the tree node. Now, once again, the mouse click is handled and consumed at the capture stage if the expansion pane is clicked, therefore preventing the node from being selected.

### Mandatory checks
- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Review by Siedlerchr — DISMISSED** [review]

**Comment by credmond** [comment]
@Siedlerchr: had two fix two comment typos (apologies, was a rushed PR) -- can you re-approve please?

**Review by Siedlerchr — DISMISSED** [review]

**Comment by calixtus** [comment]
Thanks for investigating the issue underneath and for your PR.

However, I'm not that happy with the implementation yet, as this modifies a common utility class to fix a very specific bug and also it is not clear, what the boolean flag means from the viewpoint of the user. I will try to look into it in the next days and would ask the other reviewers not yet to merge this PR.

**Comment by credmond** [comment]
Currently ViewModelTreeTableRowFactory is used only in one class (GroupTreeView) and was introduced only in March for unspecified reasons (which introduced the bug).

I don't like the fix either (I didn't actually want to raise a PR, my time is limited), but I also don't like the constraints a utility class such as ViewModelTreeTableRowFactory enforces (and the many variations of it I've noticed). E.g., you cannot control where you listen: capture or bubbling phase. Would be good to have a common pattern or approach of allowing you to specify whether what you need is a listener vs. handler.

**Comment by calixtus** [comment]
I introduced this utility class back then, because we already have a pattern of similar utility classes and I wanted to clean up the GroupTreeView class, which was a mess back then.
About the issue itself, i was wondering why the already defined checks in GroupTreeView for the style class and the event.close method is not working (https://github.com/JabRef/jabref/blob/5e4cb4e8afb0dcb33629cfc2034f96b7d4ead053/src/main/java/org/jabref/gui/groups/GroupTreeView.java#L227-L233), but was interrupted today when I wanted to debug to understand the issue better. maybe I can look deeper  the next days

**Comment by credmond** [comment]
I explained this a little bit in the comment here: https://github.com/JabRef/jabref/pull/8785

The event.consume() is working in main, it's just too late (bubbling phase) -- the node has already selected itself during the capture phase.

It worked before your refactor in March because it was using an event **filter**, which is called during the **capture** stage, and consumed before the node could select itself. But your March change, unknowingly, changed it to use an event handler, which is called during the bubbling stage; that is too late as the node is already selected.

Filters = capture phase
Handlers = bubbling phase

My PR changes it back to using an event filter, and it works again.

E.g.: the arrow gets clicked, the following happens:

**Event created.**
Capture chain = row -> child -> child's children, etc...
Bubble phase is **after** that, in reverse: child's children -> child -> row

The main branch with the bug is this:
Capture chain = row -> child **(unwanted select of group here)** -> another child -> child's children, etc...
Bubble phase is **after** that, in reverse: child's children -> another child (**event.consume() here, for example; but it's too late)** -> child -> row

My PR (and pre-March) is this:
Capture chain = row **(consume event here to stops it)** -> child -> another child -> child's children, etc...
Bubble phase is **after** that, in reverse: child's children -> another child -> child -> row

**Review by koppor — APPROVED** [review]

**Review by Siedlerchr — APPROVED** [review]

**Comment by calixtus** [comment]
Thanks for your effort debugging this issue and providing the solution rationale.

**Comment by credmond** [comment]
> I worked a little bit on your PR and modified the utility class to also forward event filters. Tested it, the bug is still fixed, but we can avoid the boolean and and the a misunderstandable withOnMouseClicked method by providing a more generic utility class.

Looks good!

**Pull request merged**
