### PR TITLE
Group pane automatically takes up remaning space in side pane

### PR DESCRIPTION
**Pull request by tobiasdiez**
Implements https://github.com/JabRef/jabref/issues/1233. Also the buttons at the bottom to expand or shrink the group pane are now superfluous, so I removed them.

- [x] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [ ] Screenshots added (for bigger UI changes)

### CODE REVIEW

**Comment by simonharrer** [comment]
Can you provide a screenshot? Are there any issues with the other side pane elements, e.g., Fetchers?

**Comment by tobiasdiez** [comment]
Yes and no :smile: 
untitled

**Comment by matthiasgeiger** [comment]
This looks rather strange at the bottom over the status bar... Is there some overlap?

**Comment by simonharrer** [comment]
Hm, what I see: it could happen that the window size render the group function unusable. 

1. Shrink window so that there is only space for the fetcher
2. Groups pane shrinks as well, showing basically no entry anymore

Is this the case?

**Comment by tobiasdiez** [comment]
@matthiasgeiger Yes, the status bar has no border and thus there is no separation to the side pane.
@simonharrer No, the groups pane does not shrink below a certain size (two groups displayed). If not enough space remains to show all groups, then a scrollbar is displayed.

**Comment by simonharrer** [comment]
LGTM

**Pull request merged**
