### PR TITLE
Extract all Integrity checker classes to it's own file

### PR DESCRIPTION
**Pull request by grimes2**
Issue #1922

- [ ] Change in CHANGELOG.md described
- [x] Manually tested changed features in running JabRef

### CODE REVIEW

**Comment by Siedlerchr** [comment]
You have still some checkstyle erorr with your imports. If you run eclipse and have the JabRef profile inlcuded, then you can just do Strg+Shift+o for oganizing imports and your checkstyle error will go away ;)
PS: you should also run ./gradlew check before a commit to see if all is right

**Comment by grimes2** [comment]
Ahh. :laughing:  Thanks. Please set label "ready-for review"

**Comment by lenhard** [comment]
Looks fine code-wise, solid work! Can be merged, in my point of view.

**Comment by Siedlerchr** [comment]
Yes, LGTM, too!

**Pull request merged**
