### PR TITLE
Introduce OpenLibraryFetcher (and remove OttoBibFetcher)

### LINKED ISSUE #8652: Change order of ISBN fetchers to improve fetching most complete information
See discussion and report of the problem in the forum: https://discourse.jabref.org/t/ebook-de-incomplete-isbn-information/3313

> When using the Import by ID feature using ISBN, the first search engine is ebook(dot)de, as explained in the jabref documentation. It seems that ebook(dot)de only provides one author in the author field (this has happened multiple times, I don’t know if it’s a general feature of ebook(dot)de). For example, for ISBN 0521099064, the [ebook.de output 1](https://www.ebook.de/de/product/3238810/stephen_hawking_the_large_scale_structure_of_space_time.html) shows Stephen Hawking as author, while the [ottobib.com output 1](https://www.ottobib.com/works-cited/e61a41660b) correctly shows S. Hawking and G. Ellis as authors. Shouldn’t the first search tool provide the most complete information?

> Can reproduce with ISBN: 9780203854693

> I think it makes sense to switch the order. Ottobib apparently uses WorldCat as source

### PR DESCRIPTION
**Pull request by koppor**
Fixes #8652 

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [x] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Review by calixtus — APPROVED** [review]

**Comment by koppor** [comment]
Test case `PdfMergeMetadataImporterTest > importWorksAsExpected() FAILED`. Seems to be related to switch of the ISBN fetcher.

**Comment by a1819644** [comment]
@koppor. Can my team have a look into this issue too?  We are the student from Adelaide university.

**Comment by calixtus** [comment]
I'm afraid this is not a real issue, but already an almost done pull request with some minor tweaks needed. You can of course take a look into, but expect this to be finished soon. So don't waste your efforts.

**Comment by a1819644** [comment]
> I'm afraid this is not a real issue, but already an almost done pull request with some minor tweaks needed. You can of course take a look into, but expect this to be finished soon. So don't waste your efforts.

Ohk i see. Thanks for the quick response

**Comment by calixtus** [comment]
Maybe you would like to take a look at our list of good first issues: https://github.com/JabRef/jabref/labels/good%20first%20issue

**Pull request merged**
