### PR TITLE
Update to gradle 7.4.2 and jdk18

### PR DESCRIPTION
**Pull request by calixtus**
- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by koppor** [comment]
News of Java 18: https://www.infoworld.com/article/3630510/jdk-18-the-new-features-in-java-18.html - especially UTF-8 as default - yeah 🎉

**Comment by koppor** [comment]
IntelliJ doesn't seem to support Java 18 (yet): https://www.jetbrains.com/help/idea/supported-java-versions.html#2021 - maybe, we should wait until there is an IntelliJ update?

**Comment by calixtus** [comment]
I agree. There is no hurry.

**Comment by koppor** [comment]
https://whichjdk.com/ --> UTF-8 as default

grafik

Nevertheless, as soon as Eclipse supports JDK18, we should update

**Comment by koppor** [comment]
Fetcher tests failing is mostly IEEE:

    java.io.IOException: Server returned HTTP response code: 503 for URL: https://ieeexplore.ieee.org/document/7421926/

**Pull request merged**
