### PR TITLE
Update JabRef.desktop

### LINKED ISSUE #10407: JabRef icon on Ubuntu dock
When you add JabRef to favorite apps then its icon appears on the Ubuntu dock. However, when you click on the dock icon to start JabRef, it adds another icon to the dock which is not the desired behavior. It should only show *one* icon with a red dot below it to indicate that an instance of JabRef is running. Generally, there should always exist one icon and the number of red dots below the icon indicates that how many instances of that program are running currently. See the following picture.

Screenshot from 2023-09-21 20-16-57

### PR DESCRIPTION
**Pull request by teertinker**
Change is neccessary that the program instance and launcher are connected properly . 

See: https://github.com/JabRef/jabref/issues/10407#issuecomment-1985207637
- closes #10407

### CODE REVIEW

**Comment by Siedlerchr** [comment]
I think this is now launcher @calixtus?
 https://github.com/JabRef/jabref/blob/main/src/main/java/org/jabref/Launcher.java

**Comment by calixtus** [comment]
I believe it should be JabRefGui. All JavaFx Application stuff was moved there.

**Comment by koppor** [comment]
Let's just merge and see if it the fix works.

**Comment by teertinker** [comment]
I tested the updated dev version on ubuntu 22.04. It does work now. Thanks für merging.

**Pull request merged**
