### PR TITLE
[WIP] OpenOffice.org/LibreOffice improvements

### PR DESCRIPTION
**Pull request by oscargus**
Changed default file names suitable for OO.o 4 and LO 5 and added support for having both OpenOffice.org and LibreOffice installed (sort of)

### CODE REVIEW

**Comment by simonharrer** [comment]
What do you mean with (sort of)? Can you add a CHANGELOG entry, please? Why is OpenOffice now renamed to OpenOffice.org?

We have changed a lot of defaults from JabRef 2 to JabRef 3. Users upgrading will not get these new defaults. But I do not have an idea how to solve this with minimal effort.

**Comment by oscargus** [comment]
Yes, forgot about CHANGELOG.

Sort of: it should be able to find all versions installed. However, as JabRef and OO/LO must both run in the same JRE and that OO only (easily) supports 32-bit JREs, it will be that JabRef running in a 64-bit JRE will not connect to OO, while one may still select it. There are some things related to that which I have not figured out, such as how to figure out if JabRef is running in a 32-bit or 64-bit JRE or if the 32-bit or 64-bit version of LibreOffice is installed (on Windows one can make an educated guess based on the directory it is installed in).

I should erase my JabRef preferences for a bit more testing, so it may be a good idea to put this on hold for a while.

**Comment by oscargus** [comment]
Oh yeah, I was wrong about OpenOffice.org, that was the previous name. I guess OpenOffice works better than Apache OpenOffice.

Related: should we bother distinguishing between OO and LO or just use OO for both? Considering the 32-bit issue, it is easier to connect to LO at the moment (if you run a 64-bit JRE only).

**Comment by oscargus** [comment]
One more thing... I should look at it more carefully to be 100% sure, but using a manual connection will update using the new "default" paths (which are present both in the Preferences and in the connection code).

This will by the way probably break using earlier versions of OO/LO. Should one keep support for those as well? Seems like more people will upgrade to OO 4-series or LO 5-series anyway (and it works with some earlier versions, not just sure when the change was done).

**Comment by koppor** [comment]
I would also lean towards loosing support for old versions of OO. We don't have the man power to maintain backwards compatibility. :fire:

**Comment by stefan-kolb** [comment]
What is the status of this PR? Ready for 3.0 or to be postponed for 3.1?

**Comment by oscargus** [comment]
Apart from changing the OpenOffice.org naming, I think it is at least better than the current master version. Primarily since it looks for the correct paths. I will probably not have time until Thursday or Friday to sort these things out though, but I believe it makes sense to include it in 3.0.

**Comment by koppor** [comment]
@oscargus Could you add a CHANGELOG.md entry? Think, you can do it within seconds - hopefully.

Then, I'll let this through!

**Comment by simonharrer** [comment]
Plus can you rebase or merge so that the tests may run successfully on circleci?

**Comment by oscargus** [comment]
I've done the changes (including rebase), but lack of internet access right
now.

Will commit this evening.

**Comment by oscargus** [comment]
I've updated but the test fails on what looks like a totally unrelated issue.

**Comment by stefan-kolb** [comment]
@simonharrer Problem with the install4j task?!

**Comment by simonharrer** [comment]
Should be fixed in master now.

**Pull request merged**
