### PR TITLE
Update to JDK22 for building

### PR DESCRIPTION
**Pull request by koppor**
JDK22 is generally available (GA). Since we use the Gradle Toolchain feature, we can use it for building.

I did NOT update the JDK for gradle itself, gradle itself does not support JDK22 yet (https://github.com/gradle/gradle/issues/26162).

- [ ] Update documentation that JDK 22 should be used in IntelliJ

### Mandatory checks

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by Siedlerchr** [comment]
Do we use it for deployment/building? Because jdk21 is long term and 22 might not yet be available for all unix distributions pakaged etc, This will create issues with people building jabref themselves

**Comment by koppor** [comment]
Updated EA build to use 23 only:

image

**Comment by koppor** [comment]
> Do we use it for deployment/building? 

With this configuration: yes.

We do not yet use JDK 22 features. But we are ready now. The variable https://docs.gradle.org/current/kotlin-dsl/gradle/org.gradle.api/-java-version/-v-e-r-s-i-o-n_22/index.html exist.

New on JDK 22: https://www.infoworld.com/article/3708329/jdk-22-the-new-features-in-java-22.html

Maybe the "structured concurrency" is cool for our file indexer:

> With [structured concurrency](https://openjdk.org/jeps/462), from Project Loom, concurrent programming is simplified through an API that treats groups of related tasks running in different threads as a single unit of work,

And even cool String templates: https://openjdk.org/jeps/459

Oh, we finally do have `_` to ignore variables - https://openjdk.org/jeps/456

---

> Because jdk21 is long term and 22 might not yet be available for all unix distributions pakaged etc, This will create issues with people building jabref themselves

At least debian has JDK22 (https://packages.debian.org/sid/openjdk-22-jdk). 😅

**Comment by Siedlerchr** [comment]
Rather arch and other distributions...https://archlinux.org/packages/?sort=&q=openjdk&maintainer=&flagged=

**Comment by koppor** [comment]
I think, we have to wait until JDK22 appears somehow in the [Gradle Java compatibility matrix](https://docs.gradle.org/current/userguide/compatibility.html?_gl=1*12ab6bn*_ga*ODc5NzYyNzI1LjE2NzkzNTI1MjA.*_ga_7W7NC6YNPT*MTcxMDkyNzUxNS44MC4xLjE3MTA5MjkyNjkuNDkuMC4w&_ga=2.173122403.1989232517.1710927515-879762725.1679352520#java.)

---

This motivates me to try out [bld](https://rife2.com/bld) or [Bach](https://github.com/sormuras/bach/tree/main?tab=readme-ov-file#bach---java-shell-builder---builds-only-modules) :)

**Comment by koppor** [comment]
Gradle 8.7 will support compiling using JDK22: https://github.com/gradle/gradle/issues/26245

**Comment by koppor** [comment]
JDK22 compilation is enabled in https://github.com/JabRef/jabref/pull/11059 (for the EA builds only)

**Comment by koppor** [comment]
https://github.com/JabRef/jabref/pull/11430 might need unnamed variables -- thus reopening the PR. Should happen for JabRef 6.0

**Comment by koppor** [comment]
Oh, we also need to update the workflows themselves to enable jpackage. Otherwise:

    Caused by: java.lang.module.InvalidModuleDescriptorException: Unsupported major.minor version 66.0

**Comment by koppor** [comment]
Seeing that Java 25 is going to be an LTS again (see https://www.oracle.com/de/java/technologies/java-se-support-roadmap.html), we could wait 1 year for a Java update. Seeing the effort for updating (also at the local developer's machine), unless we really require a new feature, we should stick with LTS.

**Pull request closed without merging**
