### PR TITLE
Add config for codespaces

### PR DESCRIPTION
**Pull request by tobiasdiez**
Similar to the config for gitpod, we add a config for Github's codespaces. Compilation works. Moreover, one can run the compiled version (in the browser) buy following the steps at https://github.com/devcontainers/features/blob/main/src/desktop-lite/NOTES.md#connecting-to-the-desktop and then opening a terminal, and running jabref via `gradle run`.

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by Siedlerchr** [comment]
Please add a hint/howto section to the devdocs as well

**Comment by koppor** [comment]
GitPod was https://github.com/JabRef/jabref/pull/8921

**Comment by tobiasdiez** [comment]
That was always the case, but I'm starting the codespaces from my personal account which is (still) free.

**Comment by koppor** [comment]
Codespaces IMHO belong to the organization where the repository belongs to. Otherwise, I cannot explain the costs hitting us for Codespaces usage!

**Comment by tobiasdiez** [comment]
Are we talking about the 7 cents that are coming from the prebuild images that incure storage costs? https://github.com/organizations/JabRef/settings/billing

Otherwise codespaces for the org are disabled: https://github.com/organizations/JabRef/settings/codespaces

**Pull request merged**
