### PR TITLE
Push to external application config

### PR DESCRIPTION
**Pull request by Siedlerchr**
Fixes https://github.com/JabRef/jabref/issues/10133

grafik

Needs testing for emacs, vim and winEdt and textstudio etc

- [x] sublime text
- [ ] vim
- [ ] emacs 
- [ ] texstudio
- [ ] WinEdt

### Mandatory checks
- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by Siedlerchr** [comment]
@AdamWysokinski I implemented a first version and I tested it with sublime on mac.
Would be nice if you could test this as well:
https://builds.jabref.org/pull/10303/merge/ 

I used this pattern, as this works with multiple citations as well: 
grafik

**Comment by AdamWysokinski** [comment]
Tested with SublimeText on Linux. Works exactly as expected, THANK YOU!

**Comment by koppor** [comment]
TeXStudio:

grafik

grafik

**Comment by koppor** [comment]
```
[@key1;@key2]

[@
;@
]

\cite{key1,key2}
```

**Comment by Siedlerchr** [comment]
[@key1;@key2] is now the new syntax

**Comment by koppor** [comment]
Not working with TeXStudio:

grafik

**Review by koppor — APPROVED** [review]

**Pull request merged**
