### PR TITLE
Fix for unnecessary horizontal scroll bar in group panel

### LINKED ISSUE #8467: Scrollbar shows up needlessly in group panel, while decreasing the width.
### JabRef version

5.5 (latest release)

### Operating system

Windows

### Details on version and operating system

JabRef 5.6--2022-01-25--2c92eb0 Windows 10 10.0 amd64  Java 16.0.2  JavaFX 17.0.1+1

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Expand the width of the group panel.
2. Then decrease the width of the groups panel.

Result:

at certain widths, while decreasing the width, the row will show up.

Examples:

- Dark Mode:
   image
- Light Mode:
   image

### Appendix

_No response_

### PR DESCRIPTION
**Pull request by LIM0000**
## **Proposed solution: Hide the group panel scroll bar from user interface**
Fixes #8467
```
.tree-table-view .scroll-bar:horizontal {
    -fx-opacity: 0;
}
```

https://user-images.githubusercontent.com/49628911/166685392-36c501c4-a214-4179-920e-b3044789a94b.mp4

## **PR Checklist:**
- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by calixtus** [comment]
I'm not really happy about just making the scrollbar invisible. Instead I'd ask if you could look into if there is a root cause for displaying the scrollbar? Is there a child node too wide to fit? Are there insets that need to be removed?
If we just make the scrollbar invisble, we also hide it when it is maybe wanted or neccessary...

**Comment by calixtus** [comment]
Thanks for your interest in this issue and your proposal to fix it.

**Comment by LIM0000** [comment]
Thank you for your valuable comment @calixtus.
I agree that hiding the scroll bar is not the best way to fix this issue. There are some [discussions](https://bugs.openjdk.java.net/browse/JDK-8089280) about horizontal scrollbar appears in `TableView` years ago. One of the comment had named a workaround that could fix horizontal scroll bar from appearing and flickering.



## Solution
I have followed the workaround and glad that it actually fixes our issue by:
1. `mainColumn` that needs to be `setResizeable(true)` to truncate long group names
2. `numberColumn` and `expansionNodeColumn` need to be `setResizable(false)` as they only need to be in fix size to display their contents
3. set `setMaxWidth`, `setMinWidth` and `setPrefWidth` for `numberColumn` and `expansionNodeColumn` columns

There is a tricky part for the value of width of `numberColumn` and `expansionNodeColumn`. Both these columns need to be `40d` and `20d` respectively. This is because the contents in both the columns have padding in them under `GroupTree.css`. If a random width value is set to the column, the column will either be too wide or too narrow which causes the display of horizontal scrollbar.

`mainColumn.prefWidthProperty().bind(groupTree.widthProperty().subtract(60d).subtract(15));` needs to be added to prevent horizontal scrollbar in table from flickering when table shrinks.

Flickering example when table shrinks:

https://user-images.githubusercontent.com/49628911/167147501-e59b8bbe-2867-4648-be2d-0d708dcb1631.mp4

**Comment by calixtus** [comment]
Thanks for looking into this. I believe the solution you found now is the better one.

We have to think about relativity of column width depending on screen resolution and scaling in the future. But I think this should not be fixed in this patch, since scaling fails in other places too. This one looks already good to me and is good improvement.

**Comment by calixtus** [comment]
Is this ready for review now?

**Comment by LIM0000** [comment]
Yes, it is ready for review.

**Pull request merged**
