### PR TITLE
Fix Russian translation

### PR DESCRIPTION
**Pull request by burrbull**
Should fix this bug when select Russian translation
```
java.lang.IllegalStateException: It is not allowed that the toReplace string: '<tt>author=smith and title=electrical</tt>' does not exist in the original string
	at org.jabref.gui.util.TooltipTextUtil.splitReplace(TooltipTextUtil.java:92)
	at org.jabref.gui.util.TooltipTextUtil.formatToTexts(TooltipTextUtil.java:62)
	at org.jabref.gui.search.GlobalSearchBar.setHintTooltip(GlobalSearchBar.java:291)
...
```

----

- [ ] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [ ] Manually tested changed features in running JabRef
- [ ] Screenshots added in PR description (for bigger UI changes)
- [ ] Ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)

### CODE REVIEW

**Comment by Siedlerchr** [comment]
Thanks for your contribution! For further translations you can use crowdin, https://crowdin.com/project/jabref 
The translations are then automatically synced with the ones from github and you get suggestions from previous translations.

**Comment by burrbull** [comment]
What I should do with this PR? Shall I move changes to crowdin or you'll make it yourself?

**Comment by Siedlerchr** [comment]
I merge this PR now, then I will trigger the sync with crowding and then you can continue to do further updates there.

**Comment by Siedlerchr** [comment]
@burrbull  If you start translating on crowding then please tell me your account name there, so I can add you as proofreader (you can then accept your own translations)

**Comment by burrbull** [comment]
I've signed with github account: Zgarbul Andrey (@ burrbull)

**Comment by Siedlerchr** [comment]
@burrbull  http://translate.jabref.org/project/jabref/invite?d=05l68525c6e5v623b3d3d3n4r4

**Pull request merged**
