### PR TITLE
Typo: seperator --> separator

### PR DESCRIPTION
**Pull request by mlep**
Just correcting a typo.

- [ ] Change in CHANGELOG.md described (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by Siedlerchr** [comment]
You need to correct that in the englis localization file as file 
https://github.com/JabRef/jabref/tree/master/src/main/resources/l10n
(only in the english file, crowdin later does the sync across all other langs)

**Comment by calixtus** [comment]
Took the liberty to quickly fix it myself.

**Comment by calixtus** [comment]
Thanks for the fix.

**Comment by mlep** [comment]
@calixtus  Thanks for tidying up the other files!

**Pull request merged**
