### PR TITLE
Try to update GitVersion action from v0.3 to v0.9

### PR DESCRIPTION
**Pull request by koppor**
and GitVresion from 5.1.2 to 5.1.3 (https://github.com/GitTools/GitVersion/releases/tag/5.1.3)

### CODE REVIEW

**Comment by Siedlerchr** [comment]
git checkout action v2 doesn't support submodules atm

**Comment by Siedlerchr** [comment]
Maybe you could also separate the snapcraft build as own job. This would speedup the build process

**Comment by koppor** [comment]
In https://github.com/JabRef/jabref/pull/5810 we switched from git submodules to [git subtree](https://www.atlassian.com/git/tutorials/git-subtree). Thus, we do not rely on git submodules any more. (Somehow refs https://github.com/JabRef/jabref/pull/5393 for historical reasons.)

**Comment by koppor** [comment]
The snapcraft build is handled at https://github.com/JabRef/jabref/pull/6063, thus I am not touching it here.

**Comment by koppor** [comment]
About dialog looks as follows:

grafik

I merge it to go ahead with the release.

**Comment by koppor** [comment]
Think, I have to downgrade in `master` - the AssemblyVersion is wrong

grafik

**Comment by koppor** [comment]
Even the old version does not work:

grafik

**Comment by koppor** [comment]
No huge difference between old and new version. Thus I will re-enable it after the release.

For reference: Not working: 8660e290a9e36103d (thus reverted at 3d9eccce7e757ac56) before the release. Had to add code into `Version.java` to strip the `ci` suffix: 2978deea1f713055921ee047

## old version

grafik

## new version

grafik

**Comment by koppor** [comment]
Refs https://github.com/GitTools/GitVersion/issues/1994 - still having issues with our version; therefore, we stick to the `-ci` thing.

**Pull request merged**
