### PR TITLE
Add check for frozen CHANGELOG.md sections

### PR DESCRIPTION
**Pull request by koppor**
This uses [clparse](https://github.com/marcaddeo/clparse) to detect updates to sections of `CHANGELOG.md` of released versions. This happens if PRs are longer-lasting than releases.

It implements the suggestion of https://github.com/NiclasvanEyk/keepac/issues/20#issuecomment-1712944920

This PR cannot use [heylogs](https://github.com/nbbrd/heylogs), because https://github.com/nbbrd/heylogs/pull/146 is not merged (and thus the functionality is not available).

### Mandatory checks
- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by koppor** [comment]
Step does not fail

```
 /home/runner/work/_temp/8e83877a-ff3f-4b97-8901-01baba8a5f03.sh: line 4: clparse: command not found
/home/runner/work/_temp/8e83877a-ff3f-4b97-8901-01baba8a5f03.sh: line 4: clparse: command not found
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
```

**Comment by koppor** [comment]
Cannot handle our format:

    git show main:CHANGELOG.md | clparse --format=json -

```
   {                                                                                                     
     "version": null,                                                                                    
     "link": "https://github.com/JabRef/jabref/compare/v5.9...v5.10",                                    
     "date": null,                                                                                       
     "changes": [                                                                                        
       {                                                                                                 
         "added": "We added a field showing the BibTeX/biblatex source for added and deleted entries in t
e \"External Changes Resolver\" dialog. [#9509](https://github.com/JabRef/jabref/issues/9509)"           
       },                                                                                                
       {                                                                                                 
``´

**Comment by koppor** [comment]
Blocked by https://github.com/marcaddeo/clparse/issues/22

**Comment by koppor** [comment]
- I switched away from crparse because of https://github.com/colindean/keepachangelog-parser-java/issues/17
- I switched to heylogs, because of https://github.com/nbbrd/heylogs/pull/146.

**Comment by koppor** [comment]
WTF

I don't get it. Why is the commit id of the checkout branch differently than the commit id which kicked-off the workflow?

image

image

**Comment by koppor** [comment]
Output with failing CHANGELOG.md:

```
CHANGELOG.md
     1:1  error  Expecting consistent version-date separator \u002d, found [\u2013]  consistent-separator (ignored)
    24:1  error  Change in a released version                                        releasechangesfrozen
  1168:1  error  Missing ref link                                                    all-h2-contain-a-version (ignored)

  3 problems
```

Output with "correct" CHANGELOG.md:

```
 CHANGELOG.md
     1:1  error  Expecting consistent version-date separator \u002d, found [\u2013]  consistent-separator (ignored)
  1168:1  error  Missing ref link                                                    all-h2-contain-a-version (ignored)

  2 problems
```

**Comment by koppor** [comment]
Output of the bot in case of an error:

image

**Comment by koppor** [comment]
Localization at test output:

image

**Review by calixtus — APPROVED** [review]

**Pull request merged**
