### PR TITLE
[WIP] Rewrite mods exporter and add test

### PR DESCRIPTION
**Pull request by tschechlovdev**
Follow up of #1989 and regarding #2078.
Rewrites the mods exporter with a jaxb parser. 

In comparison to the last PR, I do not longer rely on the NamespacePrefixMapper. I added an annotation in the package-info.java which also does the namespace prefix mapping. Only problem is that this annotation cannot be automatically generated by a gradle or ant script, that's why added the package-info.java to src/main/java/net/...../mods.

- [x] Tests created for changes
- [x] Manually tested changed features in running JabRef

### CODE REVIEW

**Comment by Siedlerchr** [comment]
Okay, now all seems to be executed fine on travis and codecov is increased

**Comment by tschechlovdev** [comment]
Yeah codecov was increased but the class ``modsExportFormatTestFiles`` was still not run, so this issue still remains.

**Comment by Siedlerchr** [comment]
Codecov itself does not run any tests, it relies on the results from travis:
http://docs.codecov.io/docs/ci-service-relationship
Mabye it's a travis configuration thing. No idea. It would be nice if you could search for information about that

**Comment by tschechlovdev** [comment]
Yeah, I will try to find a solution for this.

**Pull request merged**
