### PR TITLE
More JavaFX editors

### PR DESCRIPTION
**Pull request by tobiasdiez**
A few more field editors are reimplemented in JavaFX.
I will fix the failing language test later.

- [ ] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [ ] Screenshots added (for bigger UI changes)
- [x] Manually tested changed features in running JabRef
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)
- [x] If you changed the localization: Did you run `gradle localizationUpdate`?

### CODE REVIEW

**Comment by Siedlerchr** [comment]
Looks okay to me. Would be nice if you could add some screenshots

**Comment by stefan-kolb** [comment]
@JabRef/developers Whereas I like the work that is done here, it is a step back from the current UI. Some functionality is missing other functionality is not as accessible as before. We should have discussed this at least shouldn't we?

**Comment by Siedlerchr** [comment]
@stefan-kolb  I think the buttons are now setup as icons here.

**Comment by lenhard** [comment]
I agree with Stefan. It seems that the crossref, file, and timestamp field editors are missing certain functions.

Also if the text on the buttons is gone, then we at least need the tool tips.

**Comment by tobiasdiez** [comment]
@stefan-kolb as outlined in the previous PR, I will convert each editor peu à peu and in the end the full functionality should be restored. For the text buttons vs icons, we should probably discuss this in the devcall.

**Pull request merged**
