### PR TITLE
delete bug fix

### LINKED ISSUE #7392: A bug about the attachment and the deletion
JabRef 5.3--2021-01-02--0b4be8a
Linux 4.18.0-240.1.1.el8_3.x86_64 amd64 
Java 15.0.1

Steps to reproduce:

1. Attach a file to a record.
2. Select another record and press the "delete" key to delete it.
3. The delete warning window shows information about the attached file not the record itself.

Screenshot from 2021-01-28 10-52-10

### PR DESCRIPTION
**Pull request by BenArou**
- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by Siedlerchr** [comment]
Can you please explain your changes and what you did and why?

**Comment by BenArou** [comment]
I was kind of overwhelmed at first so I went ahead and read the code and the places i was pointed towards. I found that the keybindings part of the code did not have a delete function in it. So going I added the delete function in the use case function and tested it out again manually and found that the bug was not repeated.

**Comment by Siedlerchr** [comment]
Please always at least refer to a concrete issue and add a small explanation.this helps us to understand the changes and their context

**Comment by koppor** [comment]
@BenArou Which OS are you using? Is your intention to change the key binding for delete?

**Comment by BenArou** [comment]
I'm using windows 10, my intention is to make the delete function consistent and not interfere with other functions

**Comment by Siedlerchr** [comment]
I think this could cause issues on mac, will need to test this

**Comment by Siedlerchr** [comment]
Okay, I test it on mac and seems to work. I still don't understand why you added them, does this fix a bug? If yes please describe? Is there a related issue? @BenArou

**Comment by koppor** [comment]
Can one configure a key binding for the delete functionality now?

**Comment by koppor** [comment]
Please provide a screenshot of the keybindings dialog, if possible.

**Comment by koppor** [comment]
Summary: The reconfiguration of the DELETE key was not applied to the main table.

We added a CHANGELOG entry: https://github.com/JabRef/jabref/commit/add694a25c1aea0436384cb39af04412b59bf627

**Pull request merged**
