### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by koppor**
Enjoy!

### CODE REVIEW

**Comment by stefan-kolb** [comment]
How often are the translations created? Once a week would be fine as well...

**Comment by koppor** [comment]
I configured auto sync. Otherwise, I have to manually trigger sync once a
week. We can do that if this PRs are disturbing...

Am 15.03.2018 18:32 schrieb "Stefan Kolb" <notifications@github.com>:

How often are the translations created? Once a week would be fine as well...

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/JabRef/jabref/pull/3853#issuecomment-373460004>, or mute
the thread

**Comment by stefan-kolb** [comment]
When is auto synch triggered?

**Comment by koppor** [comment]
As soon as translator submits something (IMHO)

Am 15.03.2018 18:34 schrieb "Stefan Kolb" <notifications@github.com>:

**Comment by tobiasdiez** [comment]
I also agree that these PRs are creating a bit to much noise right now. Isn't feasible to sync changes only before a release (and in the rare case somebody provides translations via github)?

**Comment by koppor** [comment]
OK, I paused the sync on crowdin. When new translations from GitHub come in, one has to delete the integration and recreate it. For new translations from Crowdin, the sync just has to be resumed.

grafik

**Pull request merged**
