### PR TITLE
Try to  make reproducible builds

### PR DESCRIPTION
**Pull request by Siedlerchr**
Refs https://discourse.jabref.org/t/cant-build-jabref-reproducibly/3427

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by koppor** [comment]
Just a side note: In other projects, the `gradle.lock` file was a PITA when updating dependencies. Hope, we don't run into issues with dependabot or when manually adding dependencies.

**Review by koppor — APPROVED** [review]

**Comment by Siedlerchr** [comment]
We need to regenerate the lock file or we just do it for the releases

**Comment by linsui** [comment]
Could you please add lockfile when you tag a release? Thanks!

**Comment by Siedlerchr** [comment]
Okay, we will try to add this

**Pull request merged**
