### PR TITLE
snap: disable tests build, add removable media and specify architectures

### PR DESCRIPTION
**Pull request by LyzardKing**
This picks up from the previous snap (#4615),
it adds the explicit build architectures, the removable-media plug (not autoconnected) and disables tests on gradlwe build

### CODE REVIEW

**Comment by LyzardKing** [comment]
The snap can now run on strict confinement.
The only remaining issue (it seems) is the File > Save As, that locks up the ui.

**Comment by LyzardKing** [comment]
No, it fails with the same errors. Just like the save as.
One question, does openjfx work with gtk3? or is it still gtk2?

**Comment by Siedlerchr** [comment]
Okay, then it's probably the FileSaveDialog which is causing the problems,
openjfx/javafx 8 is still gtk2. 
GTK3 support is only possible with openjfx11  (which JabRef does not yet support)
It could be some java bug which is already fixed in later versions.
Java 9 support is another big issue we are working on https://github.com/JabRef/jabref/pull/3421#issuecomment-389229101

**Comment by LyzardKing** [comment]
I'm trying a build with gtk2...I'll test it and let you know

**Comment by LyzardKing** [comment]
Ok, with gtk2 save/export works!

**Comment by LyzardKing** [comment]
The theme will not work.
Snapcraft supports only gtk3 themes atm.
But it works, that's the most important part..

**Comment by LyzardKing** [comment]
The websearch has a few issues, but I'm not sure they're snap related.
The google scholar search returns no result,
The others (ie arxiv and citeseerx) fail to show the citation:
```
16:51:46.594 [pool-3-thread-5] ERROR org.jabref.logic.citationstyle.CitationStyleGenerator - Could not generate BibEntry citation
java.io.FileNotFoundException: Could not find style in classpath: /.csl
```

Am I missing some java thing?

**Comment by Siedlerchr** [comment]
@LyzardKing  Thanks for the work and the report. 
The google scholar is from time to time blocking too much requests, nothing we can do about.
Regarding the citation styles.
We recently added them as git submodule, so you probably need to add this before the build:
```
git submodule sync
submodule update --init
```
From a quick googling I found this yaml file from the mumble project which does this kind of submodule init:
https://github.com/snapcrafters/mumble/blob/d23434c1a80952733e4a7102b27bb2455ec4d86d/snap/snapcraft.yaml#L39

**Comment by LyzardKing** [comment]
@Siedlerchr to enable submodules I just had to explicitly set the source-type to git
That works now

**Comment by LyzardKing** [comment]
@Siedlerchr Does the architecture part of the build work on build.snapcraft.io?

**Comment by Siedlerchr** [comment]
I am merging this and then checking it out.
https://build.snapcraft.io/user/JabRef/jabref

**Comment by Siedlerchr** [comment]
Thank you very much for your contribution 🥇 and making it work!
I triggered a manual build and it was only run on those two architectures:
grafik

As this works now relatively stable as you say, we could announce that in a blog post.

Maybe @koppor  can remove the other architectures.

**Comment by LyzardKing** [comment]
Great!! I downloaded it as soon as it was uploaded, and I'm glad to see it works!!
I just needed an up to date version of jabref, since I use it personally.
Mine was a simple contribution, but to a project I use and enjoy!

**Comment by Siedlerchr** [comment]
So now the dev version in the snap should always be consistent with the one under https://builds.jabref.org/master
We soon want to release an alpha/beta version of 5.0-dev once the conversion to javafx is nearly complete, so feel free to report any kind of issues you encounter.

**Comment by LyzardKing** [comment]
If the build.snapcraft.io could be automated, it would be easy to keep using --edge (that would be built on every commit to master on github).
Then on proper beta releases you could promote manually. And the same with stable releases

**Comment by Siedlerchr** [comment]
I will talk to @koppor  if he can set this up somehow.

Just a notice, that to work with Open/Libre Office you need to install the libs manually:
http://discourse.jabref.org/t/connecting-with-libreoffice-snap-under-ubuntu-16-04/980/9

Referencing the original PR/issue here for documentation purposes #3121

**Comment by LyzardKing** [comment]
I don't think the jabref snap can call files in the system root.
I have at the moment the jabref snap and non snap libreoffice and it doesn't work.
That's to be expected for now, since a strict snap (or devmode) can not look into root.

**Comment by LyzardKing** [comment]
and even if the libreoffice snap is installed, they are both confined, so jabref could not look in /snap/libreoffice/...
It could look in the /home/user/snap/libreoffice folder, so if jabref could install a plugin on libreoffice that might work.
This might be a good question for the snapcraft forum

**Comment by LyzardKing** [comment]
(same goes for the other integrations..

**Comment by Siedlerchr** [comment]
Yeah, I already thought that. It would somehow destroy the concept of isolation. The users can then still use the normal jar file, so that shouldn't be a problem.

**Comment by koppor** [comment]
This refs https://github.com/JabRef/jabref/issues/3121.

**Pull request merged**
