### PR TITLE
Groups button and context menu for adding groups

### PR DESCRIPTION
**Pull request by tobiasdiez**
Add a button (and context menu) for adding groups in the new interface. Some todo's are still open, because they are easier to implement as soon as the majority of the group stuff is converted to javafx.

- [ ] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [ ] Screenshots added (for bigger UI changes)
- [ ] Manually tested changed features in running JabRef
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)
- [ ] If you changed the localization: Did you run `gradle localizationUpdate`?

### CODE REVIEW

**Comment by lenhard** [comment]
I played around a little with the UI interface. The tree and the context menu are fine I think. However (not using groups that much), it took me quite some time to locate the button you talked about. 

The button was located at the bottom of the interface also in the old groups interface, right? I think the rewrite of the groups panel gives us an opportunity to try to improve a few things. Personally, I think it would be better if the button were moved to the top, right under the heading of the groups sidepane and above the "All Entries" group. What do you think?

Also, support for assigning entries to groups by drag and drop would be cool :-)

**Comment by tobiasdiez** [comment]
You are of course right; we should use the rewrite to improve the interface. Thats why I moved the "new group" button from the top to the bottom 😄. My reasoning was that in the majority of the cases you are interested in selecting a group in order to find a assigned entry. Once you have an established group tree, the "new group" functionality is used very rarely. Thus the groups tree is way more important than the add button and should thus be put more prominently, i.e., at the very top. On the other hand, I can see that the add button at the bottom looks a bit disconnected from the groups tree (especially if you have only a few groups). Not sure how to improve this through.

But in the end, I have not a very strong opinion about the location of the button and it is very easy to change. My proposal would be to leave the button at the bottom for the moment and revisit this question as soon as more buttons/functionality is added to the groups pane.

**Comment by lenhard** [comment]
I don't have a strong opinion either :-) @JabRef/developers What does the rest of you think?

**Comment by Siedlerchr** [comment]
It would be nice if you could provide a screenshot. Otherwise I don't really care where it it as long as it is there. This is what I wanted in  #2467

**Pull request merged**
