### PR TITLE
snap: Add custom gradle plugin

### PR DESCRIPTION
**Pull request by LyzardKing**
added a custom gradle plugin with the new build/run commands
added the gnome platform to use gtk3
added __pycache__ to .gitignore to avoid committing python cache to git repo
Built locally jabref installs and runs (with limited testing...)
I imported my local library, and opened pdfs for now..
Do not merge yet since I need to still test adding the themes (I get some errors in the terminal, but it should be an easy fix)

----

- [ ] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [ ] Manually tested changed features in running JabRef
- [ ] Screenshots added in PR description (for bigger UI changes)
- [ ] Ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)

### CODE REVIEW

**Comment by LyzardKing** [comment]
@Siedlerchr  @tobiasdiez 
I added the integration with system themes (for the open/save dialogs, the rest is javafx stuff)
Everything seems to work on my system...but it needs testers to find all the possible issues.. let's find out all possible bugs ;)

**Comment by Siedlerchr** [comment]
Thanks a lot, is this custom gradle plugin really necessary? From what I see you only added the base path?

**Comment by LyzardKing** [comment]
It is unfortunately, I had to remove the hardcoded "jar" argument for the gradle command.
I asked in the snapcraft forum if it's something that can be patched (without the custom plugin)
or if it'll be added (since java11 and modularity is a new thing...)
If this is changed then we can remove the custom plugin.

**Comment by LyzardKing** [comment]
@Siedlerchr I've opened a PR on snapcraft to add this functionality to the upstream plugin.
If for now you want to merge this it works (on my system...it whould work on the build system as well)
Then when I can get it merged upstream we can remove the custom version.

**Comment by Siedlerchr** [comment]
Okay I merged it, let's see if it works

**Pull request merged**
