### PR TITLE
Shared database synchronized by FocusChangedEvent

### PR DESCRIPTION
**Pull request by m-mauersberger**
This PR is related to #6663 and partly #4461.

Shared database synchronization event in `DBMSSynchronizer` is triggered by a `FocusChangedEvent`. This is added similar to `FieldChangedEvent` but has to be initiated from `EntryEditor` (?).

I have manually tested the new code - _and it does not work_. Maybe we can discuss changes through this pull request.

Thank you for your help.

### CODE REVIEW

**Comment by m-mauersberger** [comment]
Thank you for your help. Finally, I deleted all `FocusEventChanged`-related stuff and concentrated on `CoarseChangeFilter`.
There I introduced a `DelayTaskThrottler` for the `eventBus.post(event)`. Also I revised the conditionals while introducing three conditions:
- `isNewEdit`: Editing right after loading shared database.
- `isEditOnOtherField`: Editing other field = changes on previous field should be synchronized.
- `isMajorChange`: Some editing with much character input.

I found out that a throttled task will not interrupt any input. That means if a `FieldChangedEvent` is posted with delay, you can write further until database synchronization appears. In the worst case you lose some information because all characters typed in after the event are not synchronized. Furthermore, it appears that when the event is posted during delay JabRef hangs up...

Can you reproduce this problems? In general, it works as intended.

Another idea: What about throttling _all_ `FieldChangeEvent`s in order to not interrupt input process? Then we would have to ensure that all pending synchronization events would be ready before closing the database. We could add an indicator in the GUI for this purpose or add something on closing-database event.

**Comment by koppor** [comment]
Side note: We have an internal discussion ongoing, why not using JavaFX Observables everywhere - instead of the event bus. Not fully checked all aspects until now. Will (hopefully) be done at [JabCon](https://jabcon.jabref.org/). Do you have a "feeling" on that?

**Comment by m-mauersberger** [comment]
I have not much experience with JavaFX Observables but it seems like they are directly bound to GUI elements.
Thus, events maybe could only be fired less in accordance to the GUI... On the other hand it would be an advantage to use GUI events from everywhere with little effort.
I think the `CoarseChangeFilter` would become obsolete, wouldn't it?
So why not giving Observables a try...

**Comment by tobiasdiez** [comment]
Thanks a lot @m-mauersberger! I've fixed a few very minor things that I noticed and will merge now. Looking forward to your next PR.

**Pull request merged**
