### PR TITLE
Solve the bug '1248 Key bindings not modified'

### PR DESCRIPTION
**Pull request by alauber**
After checking the bug '1248 Key bindings not modified', it was Identified que the creation of the hashmap list 'defKeyBinds' that sets the standard keyboard shortcuts, the feature 'Open folder' was not included in the 'defineDefaultKeyBindings ( )' method in 'JabRefPreferences' class .
In the creation of the menu item in the 'JabRefFrame' class for the item 'Open folder', it was not possible to recover the value of the item in the list 'defKeyBinds', occurring error 'NullPointerException' in the 'String makeEscape (String s) 'method in 'JabRefPreferences' class, which shouldnt return the value of 'String' to fill out the menu item.
When the 'User' tried to change and save the list, the error 'NullPointerException' not allow the execution of the procedure.
To solve the bug , was included in the verification of the presence of null in 'keyBinds' list (copy of 'defKeyBinds'), the value 'Not associated' being passed to the 'String' return.
The warning that menu feature is created in the 'JabRefFrame' class without associated keyboard shortcut, was moved to the method mentioned before, as was duplicated.

### CODE REVIEW

**Comment by igorsteinmacher** [comment]
Thanks for the PR. Please add yourself to About.html as described in  [CONTRIBUTING.MD](https://github.com/JabRef/jabref/blob/master/CONTRIBUTING.md)

**Comment by koppor** [comment]
I would also prefer not to include the first two commits (8e46928 and 1e1ca6). Or are they interesting for guys working on the issue?

**Comment by igorsteinmacher** [comment]
Nope. It is ok to not include the first two commits Oliver

**Comment by koppor** [comment]
I cherry-picked the last commit which converted to commit 522d8e43

**Pull request closed without merging**
