### PR TITLE
Store all types in prefs to inlcude modififed

### LINKED ISSUE #9805: Preferences / entry types doesn't register changes
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

Linux Mint 21.1 with Cinnamon

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

JabRef 5.10--2023-04-24--b599690
Linux 5.15.0-71-generic amd64 
Java 20.0.1 
JavaFX 20+19

1. File / Preferences / Entry types
2.  Select, e.g., "book"
3.  Click "required" for "Address"; also add some required fields like DOI, eprint, etc.
4. Save.
5. Have a look, close open, check again.  The selections at step 3 is forgotten.

### Appendix

_No response_

### PR DESCRIPTION
**Pull request by Siedlerchr**
Fixes #9805

```[tasklist]
### Compulsory checks
- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.
```

### CODE REVIEW

**Comment by koppor** [comment]
I tried. Preferences saving works. Using the types does not work.

I have put "Comment" and "ISBN" required. (OK, "Comment" was not that good, nevertheless)

image

ISBN still optional:

image

The stored .bib file does not contain the customized entry type:

```
@Book{,
  author = {tesat},
}

@Comment{jabref-meta: databaseType:bibtex;}
```

**Comment by Siedlerchr** [comment]
If I recall correctly, custom entry types are only stored in the bib file if they are a) used and b) entirely new entry types  
e..g @Comment{jabref-entrytype: asdfasdf: req[annote] opt[]}
 
grafik

That is the same as the previous behavior.

**Comment by Siedlerchr** [comment]
After a restart of JabRef it works in the entry editor as well

**Review by calixtus — APPROVED** [review]

**Comment by calixtus** [comment]
🎉

**Pull request merged**
